// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class OldMars
{
    public static partial class AObjectModification
    {
        private static FormLink<IAObjectModificationGetter> Construct(uint id) => new FormLink<IAObjectModificationGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IAObjectModificationGetter> mod_AVM_Cutter_Cutter_Preorder => Construct(0x3);
        public static FormLink<IAObjectModificationGetter> mod_AVM_Spacesuit_Miner_Backpack_OldMars => Construct(0x7);
        public static FormLink<IAObjectModificationGetter> mod_AVM_Spacesuit_Miner_Helmet_OldMars => Construct(0x8);
    }
}
