// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class SFBGS006
{
    public static partial class FormList
    {
        private static FormLink<IFormListGetter> Construct(uint id) => new FormLink<IFormListGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IFormListGetter> SFBGS006AddToList_SMSSet_HabVariants_Deimos_2L1W1H => Construct(0x209);
        public static FormLink<IFormListGetter> SFBGS006AddToList_SMSSet_HabVariants_HopeTech_2L1W1H => Construct(0x332);
        public static FormLink<IFormListGetter> SFBGS006AddToList_SMSSet_HabVariants_HopeTech_2L2W1H => Construct(0x338);
        public static FormLink<IFormListGetter> SFBGS006AddToList_SMSSet_HabVariants_Deimos_2L2W1H => Construct(0x341);
        public static FormLink<IFormListGetter> SFBGS006AddToList_SMSSet_HabVariants_Deimos_2L3W1H => Construct(0x349);
        public static FormLink<IFormListGetter> SFBGS006AddToList_SMSSet_HabVariants_HopeTech_2L3W1H => Construct(0xf22);
        public static FormLink<IFormListGetter> SFBGS006AddToList_SMSSet_HabVariants_Deimos_3L1W1H => Construct(0xf24);
        public static FormLink<IFormListGetter> SFBGS006AddToList_SMSSet_HabVariants_Deimos_3L2W1H => Construct(0xf26);
        public static FormLink<IFormListGetter> SFBGS006AddToList_SMSSet_HabVariants_HopeTech_3L1W1H => Construct(0xf29);
        public static FormLink<IFormListGetter> SFBGS006AddToList_SMSSet_HabVariants_Deimos_3L3W1H => Construct(0xf2b);
        public static FormLink<IFormListGetter> SFBGS006AddToList_SMSSet_HabVariants_HopeTech_3L2W1H => Construct(0xf30);
        public static FormLink<IFormListGetter> SFBGS006AddToList_SMSSet_HabVariants_HopeTech_3L3W1H => Construct(0xf36);
        public static FormLink<IFormListGetter> SFBGS006AddToList_SMSSet_HabVariants_Nova_2L1W1H => Construct(0xf37);
        public static FormLink<IFormListGetter> SFBGS006AddToList_SMSSet_HabVariants_Nova_2L2W1H => Construct(0xf38);
        public static FormLink<IFormListGetter> SFBGS006AddToList_SMSSet_HabVariants_Nova_2L3W1H => Construct(0xf39);
        public static FormLink<IFormListGetter> SFBGS006AddToList_SMSSet_HabVariants_Nova_3L1W1H => Construct(0xf3a);
        public static FormLink<IFormListGetter> SFBGS006AddToList_SMSSet_HabVariants_Nova_3L2W1H => Construct(0xf3d);
        public static FormLink<IFormListGetter> SFBGS006AddToList_SMSSet_HabVariants_Nova_3L3W1H => Construct(0xf3e);
        public static FormLink<IFormListGetter> SFBGS006AddToList_SMSSet_HabVariants_Stroud_2L1W1H => Construct(0xf40);
        public static FormLink<IFormListGetter> SFBGS006AddToList_SMSSet_HabVariants_Stroud_2L2W1H => Construct(0xf41);
        public static FormLink<IFormListGetter> SFBGS006AddToList_SMSSet_HabVariants_Stroud_2L3W1H => Construct(0xf4e);
        public static FormLink<IFormListGetter> SFBGS006AddToList_SMSSet_HabVariants_Stroud_3L1W1H => Construct(0xf55);
        public static FormLink<IFormListGetter> SFBGS006AddToList_SMSSet_HabVariants_Stroud_3L2W1H => Construct(0xf59);
        public static FormLink<IFormListGetter> SFBGS006AddToList_SMSSet_HabVariants_Taiyo_2L1W1H_Btm_A => Construct(0x1441);
        public static FormLink<IFormListGetter> SFBGS006AddToList_SMSSet_HabVariants_Taiyo_2L1W1H_Btm_B => Construct(0x1442);
        public static FormLink<IFormListGetter> SFBGS006AddToList_SMSSet_HabVariants_Taiyo_2L1W1H_Mid => Construct(0x1443);
        public static FormLink<IFormListGetter> SFBGS006AddToList_SMSSet_HabVariants_Taiyo_2L1W1H_Top_A => Construct(0x1444);
        public static FormLink<IFormListGetter> SFBGS006AddToList_SMSSet_HabVariants_Taiyo_2L1W1H_Top_B => Construct(0x1446);
        public static FormLink<IFormListGetter> SFBGS006AddToList_SMSSet_HabVariants_Taiyo_2L2W1H_Btm_A => Construct(0x1447);
        public static FormLink<IFormListGetter> SFBGS006AddToList_SMSSet_HabVariants_Taiyo_2L2W1H_Btm_B => Construct(0x1448);
        public static FormLink<IFormListGetter> SFBGS006AddToList_SMSSet_HabVariants_Taiyo_2L2W1H_Mid => Construct(0x144a);
        public static FormLink<IFormListGetter> SFBGS006AddToList_SMSSet_HabVariants_Taiyo_2L2W1H_Top_A => Construct(0x144d);
        public static FormLink<IFormListGetter> SFBGS006AddToList_SMSSet_HabVariants_Taiyo_2L2W1H_Top_B => Construct(0x144e);
        public static FormLink<IFormListGetter> SFBGS006AddToList_SMSSet_HabVariants_Taiyo_2L3W1H_Top_A => Construct(0x144f);
        public static FormLink<IFormListGetter> SFBGS006AddToList_SMSSet_HabVariants_Taiyo_2L3W1H_Top_C => Construct(0x1450);
        public static FormLink<IFormListGetter> SFBGS006AddToList_SMSSet_HabVariants_Taiyo_3L1W1H_Btm_A => Construct(0x1453);
        public static FormLink<IFormListGetter> SFBGS006AddToList_SMSSet_HabVariants_Taiyo_3L1W1H_Btm_B => Construct(0x1455);
        public static FormLink<IFormListGetter> SFBGS006AddToList_SMSSet_HabVariants_Taiyo_3L1W1H_Mid => Construct(0x1456);
        public static FormLink<IFormListGetter> SFBGS006AddToList_SMSSet_HabVariants_Taiyo_3L1W1H_Top_A => Construct(0x1457);
        public static FormLink<IFormListGetter> SFBGS006AddToList_SMSSet_HabVariants_Taiyo_3L1W1H_Top_B => Construct(0x1458);
        public static FormLink<IFormListGetter> SFBGS006AddToList_SMSSet_HabVariants_Taiyo_3L2W1H_Btm_A => Construct(0x145c);
        public static FormLink<IFormListGetter> SFBGS006AddToList_SMSSet_HabVariants_Taiyo_3L2W1H_Btm_B => Construct(0x145f);
        public static FormLink<IFormListGetter> SFBGS006AddToList_SMSSet_HabVariants_Taiyo_3L2W1H_Mid => Construct(0x1460);
        public static FormLink<IFormListGetter> SFBGS006AddToList_SMSSet_HabVariants_Taiyo_3L2W1H_Top_A => Construct(0x1463);
        public static FormLink<IFormListGetter> SFBGS006AddToList_SMSSet_HabVariants_Taiyo_3L2W1H_Top_B => Construct(0x1489);
        public static FormLink<IFormListGetter> ShipBehavior_DoorCycleExclusions01 => Construct(0xcb5e);
        public static FormLink<IFormListGetter> OutpostFurnitureToiletList01 => Construct(0xe87a);
    }
}
