// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class SFBGS006
{
    public readonly static ModKey ModKey = ModKey.FromNameAndExtension("SFBGS006.esm");
}
