// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class SFBGS004
{
    public static partial class CurveTable
    {
        private static FormLink<ICurveTableGetter> Construct(uint id) => new FormLink<ICurveTableGetter>(ModKey.MakeFormKey(id));
        public static FormLink<ICurveTableGetter> VehicleThrottleStickInputCurve => Construct(0x2f);
    }
}
