// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class SFBGS004
{
    public static partial class DefaultObject
    {
        private static FormLink<IDefaultObjectGetter> Construct(uint id) => new FormLink<IDefaultObjectGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IDefaultObjectGetter> VehicleKeyword_DO => Construct(0x18);
        public static FormLink<IDefaultObjectGetter> VehicleDriverSeatKeyword_DO => Construct(0x1a);
        public static FormLink<IDefaultObjectGetter> VehicleVascoSeatKeyword_DO => Construct(0x1e);
        public static FormLink<IDefaultObjectGetter> VehicleCompanionSeatKeyword_DO => Construct(0x1f);
        public static FormLink<IDefaultObjectGetter> VehicleThrottleStickInputCurve_DO => Construct(0x30);
        public static FormLink<IDefaultObjectGetter> SpaceshipPartLinkedVehicleKeyword_DO => Construct(0x3a);
        public static FormLink<IDefaultObjectGetter> VehicleShipLinkedRefKeyword_DO => Construct(0x3c);
        public static FormLink<IDefaultObjectGetter> SpaceshipVehicleRecipeFilterKeywordDO => Construct(0x59);
        public static FormLink<IDefaultObjectGetter> VehicleCollisionLayer_DO => Construct(0x2a4);
        public static FormLink<IDefaultObjectGetter> VehicleDefaultPlayerVehicle_DO => Construct(0x315);
        public static FormLink<IDefaultObjectGetter> StackIMODAlcoholKeyword_DO => Construct(0x31f);
        public static FormLink<IDefaultObjectGetter> VehicleDriverPerk_DO => Construct(0x329);
        public static FormLink<IDefaultObjectGetter> VehicleDriverDamageReductionFactorAV_DO => Construct(0x32a);
    }
}
