// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class SFBGS004
{
    public static partial class EffectSequence
    {
        private static FormLink<IEffectSequenceGetter> Construct(uint id) => new FormLink<IEffectSequenceGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IEffectSequenceGetter> SFBGS004_HeadLightAnimation => Construct(0x3d);
        public static FormLink<IEffectSequenceGetter> SFBGS004_RoverBoost_FXSQ => Construct(0x28c);
        public static FormLink<IEffectSequenceGetter> SFBGS004_RoverWeaponImpactExplosion_Seq => Construct(0x300);
    }
}
