// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class SFBGS004
{
    public static partial class GameSetting
    {
        private static FormLink<IGameSettingGetter> Construct(uint id) => new FormLink<IGameSettingGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IGameSettingGetter> fVehicleSlideGain => Construct(0x34);
        public static FormLink<IGameSettingGetter> fVehicleSlideWheelFriction => Construct(0x35);
        public static FormLink<IGameSettingGetter> fVehicleSlideWheelViscosityFriction => Construct(0x36);
        public static FormLink<IGameSettingGetter> fVehicleSlideYawSpeedThreshold => Construct(0x37);
        public static FormLink<IGameSettingGetter> fVehicleSlideDecay => Construct(0x38);
        public static FormLink<IGameSettingGetter> fVehicleAimModeTimeScale => Construct(0x40);
        public static FormLink<IGameSettingGetter> fVehicleAutoHandbrakeSlope => Construct(0x2e1);
        public static FormLink<IGameSettingGetter> fVehicleGravityAt10PercentG => Construct(0x2e2);
        public static FormLink<IGameSettingGetter> fVehicleCameraPitchMax => Construct(0x30f);
        public static FormLink<IGameSettingGetter> fVehicleCollisionSoundHeavyThreshold => Construct(0x316);
        public static FormLink<IGameSettingGetter> fVehicleCameraFirstPersonAimingMaxAbsYaw => Construct(0x31a);
        public static FormLink<IGameSettingGetter> fVehiclePassengerDialogueCooldown_EngageBoost => Construct(0x33c);
        public static FormLink<IGameSettingGetter> fVehiclePassengerDialogueCooldown_NonMovingIdle => Construct(0x33d);
        public static FormLink<IGameSettingGetter> fVehiclePassengerDialogueCooldown_VerticalCollision => Construct(0x33e);
        public static FormLink<IGameSettingGetter> fVehiclePassengerDialogueCooldown_VerticalCollisionLowVelocity => Construct(0x33f);
        public static FormLink<IGameSettingGetter> fVehiclePassengerDialogueCooldown_AimMountedWeapon => Construct(0x340);
        public static FormLink<IGameSettingGetter> fVehiclePassengerDialogueCooldown_Any => Construct(0x341);
        public static FormLink<IGameSettingGetter> fVehiclePassengerDialogueCooldown_HorizontalCollision => Construct(0x342);
        public static FormLink<IGameSettingGetter> fVehiclePassengerDialogueCooldown_KillWithCollision => Construct(0x343);
        public static FormLink<IGameSettingGetter> fVehicleBoostGravityAdjustment => Construct(0x344);
        public static FormLink<IGameSettingGetter> fVehicleLongJumpDistance => Construct(0x346);
        public static FormLink<IGameSettingGetter> fVehicle_VelocityForKnockdown => Construct(0x347);
        public static FormLink<IGameSettingGetter> fVehicleAimSlowMoOxygenDrainPerSec => Construct(0x35c);
        public static FormLink<IGameSettingGetter> fVehicleModelViewerMaxZoomFactor => Construct(0x366);
        public static FormLink<IGameSettingGetter> fVehicleModelViewerMinZoomFactor => Construct(0x367);
        public static FormLink<IGameSettingGetter> fVehicleVerticalBoostGravityAdjustment => Construct(0x370);
        public static FormLink<IGameSettingGetter> fVehicleBoostCeiling => Construct(0x371);
        public static FormLink<IGameSettingGetter> sVehicleObstructedCannotExit => Construct(0x372);
        public static FormLink<IGameSettingGetter> sNoFastTravelWhileDriving => Construct(0x373);
        public static FormLink<IGameSettingGetter> sMiscStatLongVehicleJumps => Construct(0x374);
        public static FormLink<IGameSettingGetter> sTopicSubtypeTextMiscellaneousVehiclePassengerEnterVehicle => Construct(0x375);
        public static FormLink<IGameSettingGetter> sTopicSubtypeTextMiscellaneousVehiclePassengerEngageBoost => Construct(0x376);
        public static FormLink<IGameSettingGetter> sTopicSubtypeTextMiscellaneousVehiclePassengerVerticalCollision => Construct(0x377);
        public static FormLink<IGameSettingGetter> sTopicSubtypeTextMiscellaneousVehiclePassengerEnterWater => Construct(0x378);
        public static FormLink<IGameSettingGetter> sTopicSubtypeTextMiscellaneousVehiclePassengerNonMovingIdle => Construct(0x379);
        public static FormLink<IGameSettingGetter> sTopicSubtypeTextMiscellaneousVehiclePassengerTriggerMine => Construct(0x37a);
        public static FormLink<IGameSettingGetter> sTopicSubtypeTextMiscellaneousVehiclePassengerAimMountedWeapon => Construct(0x37b);
        public static FormLink<IGameSettingGetter> sTopicSubtypeTextMiscellaneousVehiclePassengerKillWithCollision => Construct(0x37c);
        public static FormLink<IGameSettingGetter> sTopicSubtypeTextMiscellaneousVehiclePassengerKillWithWeapon => Construct(0x37d);
        public static FormLink<IGameSettingGetter> sTopicSubtypeTextMiscellaneousVehiclePassengerVerticalCollisionLowVelocity => Construct(0x37e);
        public static FormLink<IGameSettingGetter> sTopicSubtypeTextMiscellaneousVehiclePassengerHorizontalCollision => Construct(0x37f);
        public static FormLink<IGameSettingGetter> sWorkshopBeaconPlacement_InVehicle => Construct(0x380);
        public static FormLink<IGameSettingGetter> sNotAllowedToUseAutoDoorsWhileInVehicle => Construct(0x381);
        public static FormLink<IGameSettingGetter> fVehicleSpawnPlayerAvoidRadiusScalar => Construct(0x382);
        public static FormLink<IGameSettingGetter> fVehicleSpawnRotationOffset => Construct(0x383);
        public static FormLink<IGameSettingGetter> fVehiclePassengerDialogueCooldown_KillWithWeapon => Construct(0x385);
        public static FormLink<IGameSettingGetter> fVehicleSpawnMaxRadius => Construct(0x386);
        public static FormLink<IGameSettingGetter> fVehicleSpawnPositionOffsetScalar => Construct(0x387);
        public static FormLink<IGameSettingGetter> fVehicleSpawnShipModuleAvoidRadiusScalar => Construct(0x388);
        public static FormLink<IGameSettingGetter> bVehicleAllowTopExits => Construct(0x389);
        public static FormLink<IGameSettingGetter> fVehicle_VelocityForNoDamageToActor => Construct(0x38a);
        public static FormLink<IGameSettingGetter> fVehicle_VelocityForMaxDamageToActor => Construct(0x38b);
    }
}
