// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class SFBGS004
{
    public static partial class GenericBaseForm
    {
        private static FormLink<IGenericBaseFormGetter> Construct(uint id) => new FormLink<IGenericBaseFormGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IGenericBaseFormGetter> SMS_Vehicle_Nova_REV8_Top => Construct(0x46);
    }
}
