// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class SFBGS004
{
    public static partial class IdleAnimation
    {
        private static FormLink<IIdleAnimationGetter> Construct(uint id) => new FormLink<IIdleAnimationGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IIdleAnimationGetter> SFBGS004_Rover_EnterFromStands => Construct(0x5a);
        public static FormLink<IIdleAnimationGetter> SFBGS004_Rover_EnterFromStand => Construct(0x5b);
        public static FormLink<IIdleAnimationGetter> SFBGS004_Rover_EnterFromLeft => Construct(0x5c);
        public static FormLink<IIdleAnimationGetter> SFBGS004_Rover_EnterFromRight => Construct(0x5d);
        public static FormLink<IIdleAnimationGetter> Human_Root_Death_Rover => Construct(0x2fd);
    }
}
