// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class SFBGS004
{
    public static partial class Impact
    {
        private static FormLink<IImpactGetter> Construct(uint id) => new FormLink<IImpactGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IImpactGetter> SFBGS004_RoverBoostDustKickup_Sand => Construct(0x28f);
        public static FormLink<IImpactGetter> SFBGS004_PHY_Creations_Rover_Impact_Generic => Construct(0x294);
        public static FormLink<IImpactGetter> SFBGS004_PHY_Creations_Rover_Impact_Ice => Construct(0x295);
        public static FormLink<IImpactGetter> SFBGS004_PHY_Creations_Rover_Impact_Metal => Construct(0x296);
        public static FormLink<IImpactGetter> SFBGS004_PHY_Creations_Rover_Impact_NPC_Floater => Construct(0x297);
        public static FormLink<IImpactGetter> SFBGS004_PHY_Creations_Rover_Impact_NPC_Flyer => Construct(0x298);
        public static FormLink<IImpactGetter> SFBGS004_PHY_Creations_Rover_Impact_NPC_Generic => Construct(0x299);
        public static FormLink<IImpactGetter> SFBGS004_PHY_Creations_Rover_Impact_NPC_Human => Construct(0x29a);
        public static FormLink<IImpactGetter> SFBGS004_PHY_Creations_Rover_Impact_NPC_Insect => Construct(0x29b);
        public static FormLink<IImpactGetter> SFBGS004_PHY_Creations_Rover_Impact_NPC_Manta => Construct(0x29c);
        public static FormLink<IImpactGetter> SFBGS004_PHY_Creations_Rover_Impact_NPC_Robot => Construct(0x29d);
        public static FormLink<IImpactGetter> SFBGS004_PHY_Creations_Rover_Impact_Rock => Construct(0x29e);
        public static FormLink<IImpactGetter> SFBGS004_PHY_Creations_Rover_Impact_Sand => Construct(0x29f);
        public static FormLink<IImpactGetter> SFBGS004_PHY_Creations_Rover_Impact_Snow => Construct(0x2a0);
        public static FormLink<IImpactGetter> SFBGS004_PHY_Creations_Rover_Impact_Water => Construct(0x2a1);
        public static FormLink<IImpactGetter> SFBGS004_PHY_Creations_Rover_Impact_Wood => Construct(0x2a2);
        public static FormLink<IImpactGetter> SFBGS004_RoverWeaponExplosionImpactGeneric => Construct(0x302);
        public static FormLink<IImpactGetter> SFBGS004_RoverWeapon_vs_GenericImpact => Construct(0x304);
        public static FormLink<IImpactGetter> SFBGS004_RoverWeapon_vs_MetalImpact => Construct(0x305);
        public static FormLink<IImpactGetter> SFBGS004_RoverBoostDustKickup_Snow => Construct(0x351);
        public static FormLink<IImpactGetter> SFBGS004_RoverBoostDustKickup_Dirt => Construct(0x352);
        public static FormLink<IImpactGetter> SFBGS004_RoverBoostDustKickup_Sand_Red => Construct(0x35d);
        public static FormLink<IImpactGetter> SFBGS004_RoverBoostDustKickup_Sand_Gray => Construct(0x35e);
        public static FormLink<IImpactGetter> SFBGS004_RoverBoostDustKickup_Sand_Green => Construct(0x35f);
        public static FormLink<IImpactGetter> SFBGS004_RoverBoostDustKickup_Sand_Purple => Construct(0x360);
        public static FormLink<IImpactGetter> SFBGS004_RoverBoostDustKickup_Sand_Blue => Construct(0x361);
        public static FormLink<IImpactGetter> SFBGS004_RoverBoostDustKickup_Sand_Black => Construct(0x362);
        public static FormLink<IImpactGetter> SFBGS004_RoverBoostDustKickup_Dirt_red => Construct(0x36f);
    }
}
