// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class SFBGS004
{
    public static partial class Light
    {
        private static FormLink<ILightGetter> Construct(uint id) => new FormLink<ILightGetter>(ModKey.MakeFormKey(id));
        public static FormLink<ILightGetter> LGT_Vehicle_Headlight => Construct(0x29);
        public static FormLink<ILightGetter> SFBGS004_FX_RoverBoosterLgt => Construct(0x28d);
        public static FormLink<ILightGetter> SFBGS004_FX_RoverWeaponImpactLight => Construct(0x301);
        public static FormLink<ILightGetter> SFBGS004_FX_RoverWeaponMuzzleLight => Construct(0x309);
    }
}
