// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class SFBGS004
{
    public static partial class LoadScreen
    {
        private static FormLink<ILoadScreenGetter> Construct(uint id) => new FormLink<ILoadScreenGetter>(ModKey.MakeFormKey(id));
        public static FormLink<ILoadScreenGetter> LS_Vehicle01 => Construct(0x368);
        public static FormLink<ILoadScreenGetter> LS_Vehicle02 => Construct(0x369);
        public static FormLink<ILoadScreenGetter> LS_Vehicle03 => Construct(0x36a);
        public static FormLink<ILoadScreenGetter> LS_Vehicle04 => Construct(0x36b);
        public static FormLink<ILoadScreenGetter> LS_Vehicle05 => Construct(0x36c);
        public static FormLink<ILoadScreenGetter> LS_Vehicle06 => Construct(0x36d);
        public static FormLink<ILoadScreenGetter> LS_Vehicle07 => Construct(0x36e);
    }
}
