// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class SFBGS004
{
    public static partial class MaterialPath
    {
        private static FormLink<IMaterialPathGetter> Construct(uint id) => new FormLink<IMaterialPathGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IMaterialPathGetter> SFBGS004_ImpactDecalRoverLaserScorch => Construct(0x307);
    }
}
