// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class SFBGS004
{
    public static partial class MoveableStatic
    {
        private static FormLink<IMoveableStaticGetter> Construct(uint id) => new FormLink<IMoveableStaticGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IMoveableStaticGetter> SMOD_Vehicle_Nova_REV8_Top => Construct(0x4a);
        public static FormLink<IMoveableStaticGetter> SFBGS004_RoverWheelDust_Sand => Construct(0x28a);
        public static FormLink<IMoveableStaticGetter> SFBGS004_RoverWheelDust_Dirt => Construct(0x2df);
        public static FormLink<IMoveableStaticGetter> SFBGS004_RoverWheelDust_Water => Construct(0x317);
        public static FormLink<IMoveableStaticGetter> SFBGS004_RoverWheelDust_Stone => Construct(0x332);
        public static FormLink<IMoveableStaticGetter> SFBGS004_RoverWheelDust_Snow => Construct(0x333);
        public static FormLink<IMoveableStaticGetter> SFBGS004_RoverWheelDust_Ice => Construct(0x334);
        public static FormLink<IMoveableStaticGetter> SFBGS004_RoverWheelDust_Concrete => Construct(0x339);
        public static FormLink<IMoveableStaticGetter> SFBGS004_RoverWheelDust_Lava => Construct(0x353);
        public static FormLink<IMoveableStaticGetter> SFBGS004_RoverWheelDust_Sand_Red => Construct(0x354);
        public static FormLink<IMoveableStaticGetter> SFBGS004_RoverWheelDust_Sand_Grey => Construct(0x355);
        public static FormLink<IMoveableStaticGetter> SFBGS004_RoverWheelDust_Sand_Purple => Construct(0x356);
        public static FormLink<IMoveableStaticGetter> SFBGS004_RoverWheelDust_Sand_Green => Construct(0x357);
        public static FormLink<IMoveableStaticGetter> SFBGS004_RoverWheelDust_Sand_Black => Construct(0x358);
        public static FormLink<IMoveableStaticGetter> SFBGS004_RoverWheelDust_Sand_Blue => Construct(0x359);
        public static FormLink<IMoveableStaticGetter> SFBGS004_RoverWheelDust_Mud => Construct(0x363);
        public static FormLink<IMoveableStaticGetter> SFBGS004_RoverWheelDust_Dirt_Red => Construct(0x364);
        public static FormLink<IMoveableStaticGetter> SFBGS004_RoverWheelDust_Dirt_Grey => Construct(0x365);
    }
}
