// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class SFBGS004
{
    public static partial class PackIn
    {
        private static FormLink<IPackInGetter> Construct(uint id) => new FormLink<IPackInGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IPackInGetter> ShipPI_SMOD_Vehicle_Nova_REV8_Top => Construct(0x4d);
    }
}
