// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class SFBGS004
{
    public static partial class ProjectedDecal
    {
        private static FormLink<IProjectedDecalGetter> Construct(uint id) => new FormLink<IProjectedDecalGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IProjectedDecalGetter> SFBGS004_proj_ImpactDecalRoverLaser => Construct(0x308);
    }
}
