// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class Constellation
{
    public static partial class AObjectModification
    {
        private static FormLink<IAObjectModificationGetter> Construct(uint id) => new FormLink<IAObjectModificationGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IAObjectModificationGetter> mod_AVM_Spacesuit_Constellation_Body_DigitalDeluxe => Construct(0x8);
        public static FormLink<IAObjectModificationGetter> mod_AVM_Spacesuit_Constellation_Helmet_DigitalDeluxe => Construct(0x9);
        public static FormLink<IAObjectModificationGetter> mod_AVM_Spacesuit_Constellation_Backpack_DigitalDeluxe => Construct(0xa);
        public static FormLink<IAObjectModificationGetter> mod_AVM_EquiNOX_Constellation => Construct(0x45);
    }
}
