// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class ShatteredSpace
{
    public static partial class AnimationSoundTagSet
    {
        private static FormLink<IAnimationSoundTagSetGetter> Construct(uint id) => new FormLink<IAnimationSoundTagSetGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IAnimationSoundTagSetGetter> SFBGS001_QST_MQ06_MourningDevice_PowerSwitch_ATS => Construct(0x1204);
        public static FormLink<IAnimationSoundTagSetGetter> SFBGS001_NPC_QuadrupedA_Groat_Vortex => Construct(0x3caa);
        public static FormLink<IAnimationSoundTagSetGetter> SFBGS001_NPC_QuadrupedA_GroatSmall_Vortex => Construct(0x3cab);
        public static FormLink<IAnimationSoundTagSetGetter> SFBGS001_NPC_QuadrupedA_Groat => Construct(0x50ace);
        public static FormLink<IAnimationSoundTagSetGetter> SFBGS001_NPC_HexapodA_VortexHorror => Construct(0x7c032);
        public static FormLink<IAnimationSoundTagSetGetter> SFBGS001_WPN_MicroGun_ParticleMachineGun => Construct(0x7c035);
        public static FormLink<IAnimationSoundTagSetGetter> SFBGS001_NPC_QuadrupedA_GroatSmall => Construct(0x7e0e2);
        public static FormLink<IAnimationSoundTagSetGetter> SFBGS001_NPC_Redeemed_CyberSuit => Construct(0x949ac);
        public static FormLink<IAnimationSoundTagSetGetter> SFBGS001_WPN_ParticleRocketLauncher_ATS => Construct(0xaafa6);
        public static FormLink<IAnimationSoundTagSetGetter> SFBGS001_NPC_VaruunKai_Prey02 => Construct(0x103505);
        public static FormLink<IAnimationSoundTagSetGetter> SFBGS001_NPC_VaruunKai_Predator01 => Construct(0x103506);
        public static FormLink<IAnimationSoundTagSetGetter> SFBGS001_NPC_DazraTurret => Construct(0x11d813);
    }
}
