// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class ShatteredSpace
{
    public static partial class ArmorAddon
    {
        private static FormLink<IArmorAddonGetter> Construct(uint id) => new FormLink<IArmorAddonGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IArmorAddonGetter> SFBGS001_AA_Spacesuit_Redeemed_Legs => Construct(0x14da1);
        public static FormLink<IArmorAddonGetter> SFBGS001_AA_Spacesuit_Redeemed_Arms => Construct(0x14da2);
        public static FormLink<IArmorAddonGetter> SFBGS001_AA_Spacesuit_Redeemed_Head => Construct(0x14da3);
        public static FormLink<IArmorAddonGetter> SFBGS001_AA_Spacesuit_Redeemed_Mask => Construct(0x14da4);
        public static FormLink<IArmorAddonGetter> SFBGS001_AA_ParasiteA_VortexSpawn => Construct(0x263e8);
        public static FormLink<IArmorAddonGetter> SFBGS001_AA_HexapodA_VortexHorror => Construct(0x2e267);
        public static FormLink<IArmorAddonGetter> SFBGS001_AA_HexapodA_VortexHorror_Small => Construct(0x39d94);
        public static FormLink<IArmorAddonGetter> SFBGS001_AA_QuadrupedA_Groat_Male => Construct(0x4026b);
        public static FormLink<IArmorAddonGetter> SFBGS001_AA_QuadrupedA_Groat_Female => Construct(0x4026c);
        public static FormLink<IArmorAddonGetter> SFBGS001_AA_QuadrupedA_Groat_Kid => Construct(0x4026d);
        public static FormLink<IArmorAddonGetter> SFBGS001_AA_QuadrupedA_Groat_Horn_01 => Construct(0x4026e);
        public static FormLink<IArmorAddonGetter> SFBGS001_AA_QuadrupedA_Groat_Horn_02 => Construct(0x4026f);
        public static FormLink<IArmorAddonGetter> SFBGS001_AA_QuadrupedA_Groat_Horn_03 => Construct(0x40270);
        public static FormLink<IArmorAddonGetter> SFBGS001_AA_QuadrupedA_Groat_Horn_04 => Construct(0x40271);
        public static FormLink<IArmorAddonGetter> SFBGS001_AA_QuadrupedA_Groat_Horn_05 => Construct(0x40272);
        public static FormLink<IArmorAddonGetter> SFBGS001_AA_Clothes_Varuun_Administrator_UpperBody => Construct(0x5740b);
        public static FormLink<IArmorAddonGetter> SFBGS001_AA_Clothes_Varuun_Administrator_Sleeves => Construct(0x5740c);
        public static FormLink<IArmorAddonGetter> SFBGS001_AA_Clothes_Varuun_Administrator_LowerBody => Construct(0x5740d);
        public static FormLink<IArmorAddonGetter> SFBGS001_AA_Clothes_Varuun_Administrator_Cape => Construct(0x5740e);
        public static FormLink<IArmorAddonGetter> SFBGS001_AA_Clothes_Varuun_Administrator_Banner => Construct(0x5740f);
        public static FormLink<IArmorAddonGetter> SFBGS001_AA_Spacesuit_Redeemed_Armor => Construct(0x5d69d);
        public static FormLink<IArmorAddonGetter> SFBGS001_AA_Spacesuit_Redeemed_Body => Construct(0x100312);
        public static FormLink<IArmorAddonGetter> SFBGS001_AA_Spacesuit_Redeemed_Backpack => Construct(0x100313);
        public static FormLink<IArmorAddonGetter> SFBGS001_AA_Spacesuit_Redeemed_Pistons => Construct(0x100314);
        public static FormLink<IArmorAddonGetter> SFBGS001_AA_Spacesuit_Redeemed_Blade => Construct(0x110890);
        public static FormLink<IArmorAddonGetter> SFBGS001_AA_Clothes_Varuun_Unique_2_ShoulderPad => Construct(0x13514d);
        public static FormLink<IArmorAddonGetter> SFBGS001_AA_Clothes_Varuun_Unique_2_Scarf => Construct(0x13514e);
        public static FormLink<IArmorAddonGetter> SFBGS001_AA_Clothes_Varuun_Unique_2_LowerBody => Construct(0x13514f);
        public static FormLink<IArmorAddonGetter> SFBGS001_AA_Clothes_Varuun_Unique_2_Sleeves => Construct(0x135150);
        public static FormLink<IArmorAddonGetter> SFBGS001_AA_Clothes_Varuun_Unique_2_UpperBody => Construct(0x135151);
        public static FormLink<IArmorAddonGetter> SFBGS001_AA_Clothes_Varuun_Unique_2_Pouches => Construct(0x135152);
        public static FormLink<IArmorAddonGetter> SFBGS001_AA_Spacesuit_Varuun_Backpack_02 => Construct(0x15f2f9);
        public static FormLink<IArmorAddonGetter> SFBGS001_AA_Spacesuit_Varuun_LowerBody_02 => Construct(0x15f2fa);
        public static FormLink<IArmorAddonGetter> SFBGS001_AA_Spacesuit_Varuun_Sleeves_02 => Construct(0x15f2fb);
        public static FormLink<IArmorAddonGetter> SFBGS001_AA_Spacesuit_Varuun_UpperBody_02 => Construct(0x15f2fc);
        public static FormLink<IArmorAddonGetter> SFBGS001_AA_Spacesuit_Varuun_UpperBody_Details_02 => Construct(0x15f2fd);
        public static FormLink<IArmorAddonGetter> SFBGS001_AA_Spacesuit_Varuun_Sleeves_Details_02 => Construct(0x15f2fe);
        public static FormLink<IArmorAddonGetter> SFBGS001_AA_Spacesuit_Varuun_UpperBody_Armor_02 => Construct(0x15f2ff);
        public static FormLink<IArmorAddonGetter> SFBGS001_AA_Spacesuit_Varuun_LowerBody_Armor_02 => Construct(0x15f300);
        public static FormLink<IArmorAddonGetter> SFBGS001_AA_Spacesuit_Varuun_Helmet_02 => Construct(0x15f301);
        public static FormLink<IArmorAddonGetter> SFBGS001_AA_Spacesuit_Varuun_Sleeves_Armor_02 => Construct(0x162dbb);
    }
}
