// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class ShatteredSpace
{
    public static partial class Armor
    {
        private static FormLink<IArmorGetter> Construct(uint id) => new FormLink<IArmorGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IArmorGetter> SFBGS001_SpaceSuit_Varuun_Helmet_02_Zealot => Construct(0x83e);
        public static FormLink<IArmorGetter> SFBGS001_Spacesuit_Varuun_02_Zealot_Armored => Construct(0x83f);
        public static FormLink<IArmorGetter> SFBGS001_SpaceSuit_Varuun_Backpack_02_Zealot => Construct(0x85c);
        public static FormLink<IArmorGetter> SFBGS001_Clothes_Varuun_Administrator_Zealots => Construct(0x1613);
        public static FormLink<IArmorGetter> SFBGS001_Clothes_Varuun_Administrator_Vethaal => Construct(0x1616);
        public static FormLink<IArmorGetter> SFBGS001_Clothes_Varuun_Administrator_Kadic => Construct(0x1618);
        public static FormLink<IArmorGetter> SFBGS001_Spacesuit_Varuun_02_Zealot => Construct(0x16829);
        public static FormLink<IArmorGetter> SFBGS001_Spacesuit_Varuun_01_Zealot => Construct(0x18180);
        public static FormLink<IArmorGetter> SFBGS001_Spacesuit_Varuun_Backpack_01_Zealot => Construct(0x18182);
        public static FormLink<IArmorGetter> SFBGS001_Spacesuit_Varuun_Helmet_01_Zealot => Construct(0x18183);
        public static FormLink<IArmorGetter> SFBGS001_Clothes_Varuun_Administrator_Vethaal_NoCape => Construct(0x1a6d5);
        public static FormLink<IArmorGetter> SFBGS001_Clothes_Varuun_Administrator_Dulkehf_NoCape => Construct(0x1a6d6);
        public static FormLink<IArmorGetter> SFBGS001_Clothes_Varuun_Administrator_Kadic_NoCape => Construct(0x1a6d7);
        public static FormLink<IArmorGetter> SFBGS001_Clothes_Varuun_Administrator_Zealots_NoCape => Construct(0x1a6d8);
        public static FormLink<IArmorGetter> SFBGS001_Clothes_Varuun_Unique_2_Zealots => Construct(0x1a6d9);
        public static FormLink<IArmorGetter> SFBGS001_Clothes_Varuun_Administrator_Variant_01 => Construct(0x1c2cb);
        public static FormLink<IArmorGetter> SFBGS001_Clothes_Varuun_Administrator_Variant_01_NoCape => Construct(0x1c2cd);
        public static FormLink<IArmorGetter> SFBGS001_Skin_ParasiteA_VortexHorror => Construct(0x263ea);
        public static FormLink<IArmorGetter> SFBGS001_Skin_HexapodA_VortexHorror => Construct(0x2e266);
        public static FormLink<IArmorGetter> SFBGS001_SpaceSuit_Varuun_Backpack_02 => Construct(0x300ce);
        public static FormLink<IArmorGetter> SFBGS001_SpaceSuit_Varuun_Helmet_02 => Construct(0x300d0);
        public static FormLink<IArmorGetter> SFBGS001_Spacesuit_Varuun_02 => Construct(0x300d2);
        public static FormLink<IArmorGetter> SFBGS001_Clothes_Varuun_Unique_1 => Construct(0x300d3);
        public static FormLink<IArmorGetter> SFBGS001_Clothes_Varuun_Unique_2 => Construct(0x300d4);
        public static FormLink<IArmorGetter> SFBGS001_Skin_HexapodA_VortexHorror_Small => Construct(0x39d95);
        public static FormLink<IArmorGetter> SFBGS001_Skin_QuadrupedA_Groat_Male => Construct(0x40273);
        public static FormLink<IArmorGetter> SFBGS001_Skin_QuadrupedA_Groat_Female => Construct(0x40274);
        public static FormLink<IArmorGetter> SFBGS001_Skin_QuadrupedA_Groat_Kid => Construct(0x40275);
        public static FormLink<IArmorGetter> SFBGS001_Clothes_Neon_Gang_Strikers_01_Varuun => Construct(0x44d9c);
        public static FormLink<IArmorGetter> SFBGS001_Clothes_Varuun_Administrator => Construct(0x5740a);
        public static FormLink<IArmorGetter> SFBGS001_Spacesuit_Redeemed_Armor => Construct(0x5d69c);
        public static FormLink<IArmorGetter> SFBGS001_Spacesuit_Redeemed_Dark => Construct(0x75187);
        public static FormLink<IArmorGetter> SFBGS001_Spacesuit_Redeemed_light => Construct(0x75188);
        public static FormLink<IArmorGetter> SFBGS001_Spacesuit_Redeemed_Pale => Construct(0x75189);
        public static FormLink<IArmorGetter> SFBGS001_Clothes_Scrubs_Varuun => Construct(0x7ed77);
        public static FormLink<IArmorGetter> SFBGS001_Clothes_Varuun_Ambassador => Construct(0x7ed79);
        public static FormLink<IArmorGetter> SFBGS001_Skin_BipedA_BladedBack_Varuunkai => Construct(0x805b8);
        public static FormLink<IArmorGetter> SFBGS001_Skin_BipedA_BladedBack_VaruunkaiDeCa => Construct(0x805b9);
        public static FormLink<IArmorGetter> SFBGS001_Skin_BipedA_BladedBack_VaruunkaiDeFr => Construct(0x805ba);
        public static FormLink<IArmorGetter> SFBGS001_Skin_FloaterA_Nautiloos_VaruunkaiCaDeFr => Construct(0x805bb);
        public static FormLink<IArmorGetter> SFBGS001_Skin_FloaterA_Nautiloos_VaruunkaiDe => Construct(0x805bc);
        public static FormLink<IArmorGetter> SFBGS001_Skin_FloaterA_Nautiloos_VaruunkaiFrCaDe => Construct(0x805bd);
        public static FormLink<IArmorGetter> SFBGS001_Skin_FlyerA_Nautilus_VaruunkaiCaDe => Construct(0x805be);
        public static FormLink<IArmorGetter> SFBGS001_Skin_FlyerA_Nautilus_VaruunkaiCa => Construct(0x805bf);
        public static FormLink<IArmorGetter> SFBGS001_Skin_FlyerA_Nautilus_VaruunkaiCaDeFr => Construct(0x805c0);
        public static FormLink<IArmorGetter> SFBGS001_Skin_LarvaA_Grub_VaruunkaiCa => Construct(0x805c1);
        public static FormLink<IArmorGetter> SFBGS001_Skin_LarvaA_Grub_VaruunkaiCaDeFr => Construct(0x805c2);
        public static FormLink<IArmorGetter> SFBGS001_Skin_LarvaA_Grub_VaruunkaiDe => Construct(0x805c3);
        public static FormLink<IArmorGetter> SFBGS001_Clothes_Neon_Gang_Strikers_NoHeadgear_01_Varuun => Construct(0x8295f);
        public static FormLink<IArmorGetter> SFBGS001_Clothes_HouseDulkehfLab => Construct(0x847ca);
        public static FormLink<IArmorGetter> SFBGS001_Clothes_HouseDulkehfLab_NoShield => Construct(0x847cb);
        public static FormLink<IArmorGetter> SFBGS001_Clothes_HouseVethaalLab => Construct(0x847cd);
        public static FormLink<IArmorGetter> SFBGS001_Clothes_HouseVethaalLab_NoShield => Construct(0x847ce);
        public static FormLink<IArmorGetter> SFBGS001_Clothes_HouseKadicLab => Construct(0x847d0);
        public static FormLink<IArmorGetter> SFBGS001_Clothes_HouseKadicLab_NoShield => Construct(0x847d1);
        public static FormLink<IArmorGetter> SFBGS001_Clothes_ZealotsLab => Construct(0x847d3);
        public static FormLink<IArmorGetter> SFBGS001_Clothes_ZealotsLab_NoShield => Construct(0x847d4);
        public static FormLink<IArmorGetter> SFBGS001_Elite_TaneSalavae => Construct(0x98ad8);
        public static FormLink<IArmorGetter> SFBGS001_LC06_SpaceSuit_Varuun_Helmet_ValrakBattleHelmet => Construct(0xac80f);
        public static FormLink<IArmorGetter> SFBGS001_Clothes_Varuun_Unique_2_Zealots_NoScarf => Construct(0xae58f);
        public static FormLink<IArmorGetter> SFBGS001_Clothes_Varuun_Unique_2_NoScarf => Construct(0xae590);
        public static FormLink<IArmorGetter> SFBGS001_Clothes_Varuun_Unique_2_Variant_01_NoScarf => Construct(0xae591);
        public static FormLink<IArmorGetter> SFBGS001_Clothes_Varuun_Unique_2_Variant_02_NoScarf => Construct(0xae592);
        public static FormLink<IArmorGetter> SFBGS001_Clothes_Varuun_Unique_2_Variant_03_NoScarf => Construct(0xae593);
        public static FormLink<IArmorGetter> SFBGS001_LC06_SpaceSuit_Varuun_Helmet_01_Memorial => Construct(0xb732b);
        public static FormLink<IArmorGetter> SFBGS001_Spacesuit_Miner_Varuun => Construct(0xc0ae9);
        public static FormLink<IArmorGetter> SFBGS001_Spacesuit_Miner_Backpack_Varuun => Construct(0xc0aea);
        public static FormLink<IArmorGetter> SFBGS001_Spacesuit_Miner_Helmet_Varuun => Construct(0xc0af1);
        public static FormLink<IArmorGetter> SFBGS001_Clothes_Security_Guard_Helmet_01_VaruunElite => Construct(0xc94ca);
        public static FormLink<IArmorGetter> SFBGS001_Clothes_Security_Guard_Helmet_01_Varuun => Construct(0xc94cb);
        public static FormLink<IArmorGetter> SFBGS001_Clothes_Security_Guard_01_Varuun => Construct(0xc94cc);
        public static FormLink<IArmorGetter> SFBGS001_Clothes_Child_JacketPants_Varuun_DLC001_NOTPLAYABLE => Construct(0xcd167);
        public static FormLink<IArmorGetter> SFBGS001_Clothes_Child_JacketPantsBoots_Varuun_DLC001_NOTPLAYABLE => Construct(0xcd168);
        public static FormLink<IArmorGetter> SFBGS001_Clothes_Child_Jumpsuit_Varuun_DLC001_NOTPLAYABLE => Construct(0xcd169);
        public static FormLink<IArmorGetter> SFBGS001_Clothes_Trucker_LongSleeve_DLC001 => Construct(0xdbf80);
        public static FormLink<IArmorGetter> SFBGS001_Clothes_Trucker_LongSleeve_Hat_DLC001 => Construct(0xdbf81);
        public static FormLink<IArmorGetter> SpaceSuit_Varuun_Backpack_01_PowerBoost => Construct(0xeadf0);
        public static FormLink<IArmorGetter> SFBGS001_Clothes_ScienceLabTec_NoShield => Construct(0xee4c3);
        public static FormLink<IArmorGetter> SFBGS001_Clothes_ScienceLabTec => Construct(0xee4c5);
        public static FormLink<IArmorGetter> SFBGS001_Spacesuit_Fang_Backpack_Varuun => Construct(0x11bb99);
        public static FormLink<IArmorGetter> SFBGS001_Spacesuit_Fang => Construct(0x11bb9a);
        public static FormLink<IArmorGetter> SFBGS001_Spacesuit_Fang_Helmet => Construct(0x11c6df);
        public static FormLink<IArmorGetter> SFBGS001_Clothes_Varuun_Unique_2_Variant_01 => Construct(0x148604);
        public static FormLink<IArmorGetter> SFBGS001_Clothes_Varuun_Unique_2_Variant_02 => Construct(0x148605);
        public static FormLink<IArmorGetter> SFBGS001_Clothes_Varuun_Unique_2_Variant_03 => Construct(0x148606);
        public static FormLink<IArmorGetter> SFBGS001_Spacesuit_Varuun_02_Armored => Construct(0x15f302);
        public static FormLink<IArmorGetter> SFBGS001_Clothes_Varuun_Administrator_Dulkehf => Construct(0x160d54);
    }
}
