// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class ShatteredSpace
{
    public static partial class ArtObject
    {
        private static FormLink<IArtObjectGetter> Construct(uint id) => new FormLink<IArtObjectGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IArtObjectGetter> SFBGS001_Shrine_Devotion_Casting_FX => Construct(0x26569);
        public static FormLink<IArtObjectGetter> SFBGS001_Shrine_Obedience_Casting_FX => Construct(0x2656a);
        public static FormLink<IArtObjectGetter> SFBGS001_Shrine_Perseverance_Casting_FX => Construct(0x2656b);
        public static FormLink<IArtObjectGetter> SFBGS001_Shrine_Redemption_Casting_FX => Construct(0x26570);
        public static FormLink<IArtObjectGetter> SFBGS001_Shrine_Strength_Casting_FX => Construct(0x26581);
        public static FormLink<IArtObjectGetter> DLC001_NorthernLights_01_AO => Construct(0x39bc7);
        public static FormLink<IArtObjectGetter> SFBGS001_VortexPhantomFX_Hostile_AO => Construct(0x3e1c5);
        public static FormLink<IArtObjectGetter> SFBGS001_VortexHorrorFXAO => Construct(0x47099);
        public static FormLink<IArtObjectGetter> SFBGS001_VortexTeleportPortal01 => Construct(0x4709a);
        public static FormLink<IArtObjectGetter> SFBGS001_SummonVortexSpawn_AO => Construct(0x4d187);
        public static FormLink<IArtObjectGetter> SFBGS001_Redeemed_Armor_FX => Construct(0x5d69e);
        public static FormLink<IArtObjectGetter> SFBGS001_VortexPhantomFXAO => Construct(0x6e324);
        public static FormLink<IArtObjectGetter> SFBGS001_ParticleOuterCore => Construct(0x80d2c);
        public static FormLink<IArtObjectGetter> SFBGS001_VortexPhantomFX_Friendly_AO => Construct(0x8477e);
        public static FormLink<IArtObjectGetter> SFBGS001_VortexPhantomFX_PlayerTeleport_AO => Construct(0xc6b1d);
        public static FormLink<IArtObjectGetter> SFBGS001_StationGravJumpVFX => Construct(0xd9e5d);
        public static FormLink<IArtObjectGetter> DLC001_NorthernLights_00_AO => Construct(0xf8f63);
        public static FormLink<IArtObjectGetter> SFBGS_MourningBeamFX => Construct(0x101c68);
        public static FormLink<IArtObjectGetter> DLC001_NorthernLights_02_AO => Construct(0x10d6f1);
        public static FormLink<IArtObjectGetter> DLC001_NorthernLights_03_AO => Construct(0x10d6f5);
        public static FormLink<IArtObjectGetter> DLC001_NorthernLights_04_AO => Construct(0x11216b);
        public static FormLink<IArtObjectGetter> SFBGS001_Weather_Precipitation_EnergyStorm => Construct(0x1175a0);
        public static FormLink<IArtObjectGetter> SFBGS001_VortexPhantomGlow_ao => Construct(0x15eec6);
        public static FormLink<IArtObjectGetter> SFBGS001_BoostPackFX_Varuun_02 => Construct(0x162dbc);
    }
}
