// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class ShatteredSpace
{
    public static partial class AStoryManagerNode
    {
        private static FormLink<IAStoryManagerNodeGetter> Construct(uint id) => new FormLink<IAStoryManagerNodeGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IAStoryManagerNodeGetter> ShatteredSpace_DazraLocationNode => Construct(0xc702);
        public static FormLink<IAStoryManagerNodeGetter> SFBGS001_VaruunRandomConvos => Construct(0x88694);
        public static FormLink<IAStoryManagerNodeGetter> SFBGS001_MissionBranch_HV => Construct(0xd2522);
        public static FormLink<IAStoryManagerNodeGetter> OE_ShatteredSpaceNode => Construct(0xe0dc6);
        public static FormLink<IAStoryManagerNodeGetter> SFBGS001_HV_DazraCity => Construct(0xfbae0);
        public static FormLink<IAStoryManagerNodeGetter> OE_DazraLandmass => Construct(0x10a094);
        public static FormLink<IAStoryManagerNodeGetter> OE_OutsideOfDazraLM_BranchNode => Construct(0x10a095);
        public static FormLink<IAStoryManagerNodeGetter> SFBGS001_HV_DazraCity_Enter => Construct(0x11931f);
        public static FormLink<IAStoryManagerNodeGetter> DazraWanderingNPCs_SpawnManager => Construct(0xc703);
        public static FormLink<IAStoryManagerNodeGetter> DLC001LC010_EavesdropScene_BridgeDUPLICATE000 => Construct(0xe1fb);
        public static FormLink<IAStoryManagerNodeGetter> DLC001LC010_EavesdropScene_CaveWallDUPLICATE000 => Construct(0xe1fc);
        public static FormLink<IAStoryManagerNodeGetter> DLC001LC08_EavesdroppingScene_CaveEntrance => Construct(0xed9a);
        public static FormLink<IAStoryManagerNodeGetter> DLC001LC08_EavesdroppingScene_CaveEntrance_02 => Construct(0xf459);
        public static FormLink<IAStoryManagerNodeGetter> SFBGS001_LC13_RandomConvos => Construct(0x1512d);
        public static FormLink<IAStoryManagerNodeGetter> SFBGS001_MQ04_PostQuestNode => Construct(0x1af6e);
        public static FormLink<IAStoryManagerNodeGetter> SFBGS001_DazraCity_RC_HouseKadic => Construct(0x1c2ef);
        public static FormLink<IAStoryManagerNodeGetter> SFBGS001_DazraCity_TheKeepWardens => Construct(0x1c2f3);
        public static FormLink<IAStoryManagerNodeGetter> SFBGS001_DazraCity_RC_MourningDevice => Construct(0x1c720);
        public static FormLink<IAStoryManagerNodeGetter> SFBGS001_MQ01_QuestNode => Construct(0x26980);
        public static FormLink<IAStoryManagerNodeGetter> DLC001LC07_EavesdroppingSceneNode => Construct(0x2b97e);
        public static FormLink<IAStoryManagerNodeGetter> SFBGS001_SQ_Crew_SpawnManagerQuestNode => Construct(0x3bbc2);
        public static FormLink<IAStoryManagerNodeGetter> SFBGS001_SE_Player_PostQuestNode => Construct(0x3e1c1);
        public static FormLink<IAStoryManagerNodeGetter> SFBGS001_SE_POI_PostQuestNode => Construct(0x3fa6f);
        public static FormLink<IAStoryManagerNodeGetter> OE_Debug_JG => Construct(0x90e2b);
        public static FormLink<IAStoryManagerNodeGetter> SFBGS001_MQPostQuestChangeLocNode => Construct(0x94973);
        public static FormLink<IAStoryManagerNodeGetter> SFBGS001_MQPostQuestLocLoadedNode => Construct(0x94974);
        public static FormLink<IAStoryManagerNodeGetter> SFBGS001_DazraCity_RC_GoodsExchange => Construct(0x9660c);
        public static FormLink<IAStoryManagerNodeGetter> SFBGS001_MB_QuestNode => Construct(0xa2ec3);
        public static FormLink<IAStoryManagerNodeGetter> SFBGS001LC07_RumbleNode => Construct(0xcfb0b);
        public static FormLink<IAStoryManagerNodeGetter> SFBGS001_MB_HuntQuest => Construct(0xd2524);
        public static FormLink<IAStoryManagerNodeGetter> SFBGS001_MB_BountyQuests => Construct(0xd2540);
        public static FormLink<IAStoryManagerNodeGetter> OE_DazraLM_Rare => Construct(0xe0dc7);
        public static FormLink<IAStoryManagerNodeGetter> SFBGS001_BEDockingSpecificShipNode => Construct(0xe58cc);
        public static FormLink<IAStoryManagerNodeGetter> SFBGS001_MB_RescueQuests => Construct(0xe6c25);
        public static FormLink<IAStoryManagerNodeGetter> SFBGS001_MB_SmugglerQuests => Construct(0xe6c27);
        public static FormLink<IAStoryManagerNodeGetter> SFBGS001_MB_BountySpaceQuests => Construct(0xe6c3d);
        public static FormLink<IAStoryManagerNodeGetter> SFBGS001_HV_DazraCity_CityLife => Construct(0xfbae1);
        public static FormLink<IAStoryManagerNodeGetter> SFBGS001_DazraCity_RC_CommonerNeighborhood => Construct(0x102471);
        public static FormLink<IAStoryManagerNodeGetter> SFBGS001_DazraCity_PostQuestConvos => Construct(0x104837);
        public static FormLink<IAStoryManagerNodeGetter> OE_DazraLM_Unique => Construct(0x10a096);
        public static FormLink<IAStoryManagerNodeGetter> OE_DazraLM_Uncommon => Construct(0x10a097);
        public static FormLink<IAStoryManagerNodeGetter> OE_DazraLM_Common => Construct(0x10a098);
        public static FormLink<IAStoryManagerNodeGetter> OE_OutsideOfDazraLM_Unique => Construct(0x10a099);
        public static FormLink<IAStoryManagerNodeGetter> OE_OutsideOfDazraLM_Rare => Construct(0x10a09a);
        public static FormLink<IAStoryManagerNodeGetter> OE_OutsideOfDazraLM_Uncommon => Construct(0x10a09b);
        public static FormLink<IAStoryManagerNodeGetter> OE_OutsideOfDazraLM_Common => Construct(0x10a09c);
        public static FormLink<IAStoryManagerNodeGetter> SFBGS001LC48_Node => Construct(0x1141d3);
        public static FormLink<IAStoryManagerNodeGetter> SFBGS001_HV_DazraCity_PostQuest => Construct(0x119320);
        public static FormLink<IAStoryManagerNodeGetter> SFBGS001LC01Node => Construct(0x127cc1);
        public static FormLink<IAStoryManagerNodeGetter> SFBGS001_DazraCity_RC_Plaza => Construct(0x170f37);
        public static FormLink<IAStoryManagerNodeGetter> SFBGS001_DazraCity_RC_HallsOfHealing => Construct(0x170f38);
        public static FormLink<IAStoryManagerNodeGetter> SFBGS001_DazraCity_RC_HeraldsRest => Construct(0x170f39);
        public static FormLink<IAStoryManagerNodeGetter> SFBGS001_DazraCity_RC_RefugeeCamp => Construct(0x170f3a);
        public static FormLink<IAStoryManagerNodeGetter> SFBGS001_DazraCity_RC_Starport => Construct(0x170f3b);
        public static FormLink<IAStoryManagerNodeGetter> SFBGS001_DazraCity_RC_TheKeep => Construct(0x170f3c);
        public static FormLink<IAStoryManagerNodeGetter> SFBGS001_BESurfaceSpecificShipNode => Construct(0x172f9f);
    }
}
