// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class ShatteredSpace
{
    public static partial class BoneModifier
    {
        private static FormLink<IBoneModifierGetter> Construct(uint id) => new FormLink<IBoneModifierGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IBoneModifierGetter> SFGBS001_BM_Redeemed_L_Piston_Rear_End_Aim => Construct(0x14da5);
        public static FormLink<IBoneModifierGetter> SFGBS001_BM_Redeemed_L_Piston_Rear_Start_Aim => Construct(0x14da6);
        public static FormLink<IBoneModifierGetter> SFGBS001_BM_Redeemed_R_Piston_Front_Top_End_Aim => Construct(0x14da7);
        public static FormLink<IBoneModifierGetter> SFGBS001_BM_Redeemed_R_Piston_Front_Top_Start_Aim => Construct(0x14da8);
        public static FormLink<IBoneModifierGetter> SFGBS001_BM_Redeemed_R_Piston_Front_Bottom_End_Aim => Construct(0x14da9);
        public static FormLink<IBoneModifierGetter> SFGBS001_BM_Redeemed_R_Piston_Front_Bottom_Start_Aim => Construct(0x14daa);
        public static FormLink<IBoneModifierGetter> SFGBS001_BM_Redeemed_L_Piston_Front_Bottom_End_Aim => Construct(0x14dab);
        public static FormLink<IBoneModifierGetter> SFGBS001_BM_Redeemed_L_Piston_Front_Bottom_Start_Aim => Construct(0x14dac);
        public static FormLink<IBoneModifierGetter> SFGBS001_BM_Redeemed_L_Piston_Front_Top_End_Aim => Construct(0x14dad);
        public static FormLink<IBoneModifierGetter> SFGBS001_BM_Redeemed_L_Piston_Front_Top_Start_Aim => Construct(0x14dae);
        public static FormLink<IBoneModifierGetter> SFGBS001_BM_Redeemed_R_Piston_Rear_End_Aim => Construct(0x100315);
        public static FormLink<IBoneModifierGetter> SFGBS001_BM_Redeemed_R_Piston_Rear_Start_Aim => Construct(0x100316);
    }
}
