// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class ShatteredSpace
{
    public static partial class CameraPath
    {
        private static FormLink<ICameraPathGetter> Construct(uint id) => new FormLink<ICameraPathGetter>(ModKey.MakeFormKey(id));
        public static FormLink<ICameraPathGetter> SFBGS001_SpaceshipTakeoff_Dazra => Construct(0xdeeed);
        public static FormLink<ICameraPathGetter> SFBGS001_SpaceshipLanding_DazraCity => Construct(0xdeeee);
    }
}
