// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class ShatteredSpace
{
    public static partial class CombatStyle
    {
        private static FormLink<ICombatStyleGetter> Construct(uint id) => new FormLink<ICombatStyleGetter>(ModKey.MakeFormKey(id));
        public static FormLink<ICombatStyleGetter> SFBGS001_csAnasko_Sniper => Construct(0x12bd);
        public static FormLink<ICombatStyleGetter> SFBGS001_csAnasko_Assault => Construct(0x12be);
        public static FormLink<ICombatStyleGetter> SFBGS001_csVortexHorror => Construct(0x25750);
        public static FormLink<ICombatStyleGetter> SFBGS001_csVaruun_Sniper => Construct(0x2c430);
        public static FormLink<ICombatStyleGetter> SFBGS001_csVaruun_Heavy => Construct(0x2c431);
        public static FormLink<ICombatStyleGetter> SFBGS001_csAnasko_Charger => Construct(0xdd72d);
        public static FormLink<ICombatStyleGetter> SFBGS001_csVaruunRedeemed => Construct(0x11c509);
    }
}
