// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class ShatteredSpace
{
    public static partial class Container
    {
        private static FormLink<IContainerGetter> Construct(uint id) => new FormLink<IContainerGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IContainerGetter> SFBGS001LC20_SlateCrate => Construct(0x121d2);
        public static FormLink<IContainerGetter> SFBGS001_Loot_Storage_Cooler_Common => Construct(0x31b13);
        public static FormLink<IContainerGetter> SFBGS001_Loot_Storage_Miscbox02_Rare => Construct(0x31b79);
        public static FormLink<IContainerGetter> SFBGS001_Loot_Storage_Miscbox03_Common => Construct(0x335da);
        public static FormLink<IContainerGetter> SFBGS001_Loot_Storage_Miscbox02_Common => Construct(0x335e5);
        public static FormLink<IContainerGetter> SFBGS001_Loot_Storage_Miscbox04_Common => Construct(0x335e6);
        public static FormLink<IContainerGetter> SFBGS001_Loot_Storage_Miscbox05_Common => Construct(0x335e9);
        public static FormLink<IContainerGetter> SFBGS001_Loot_Storage_Miscbox_Crate_Large_Rare => Construct(0x335ec);
        public static FormLink<IContainerGetter> SFBGS001_Loot_Storage_Safe_Floor_Reg_Common => Construct(0x34c84);
        public static FormLink<IContainerGetter> SFBGS001_Loot_Storage_Safe_Floor_Tall_Rare => Construct(0x34c86);
        public static FormLink<IContainerGetter> SFBGS001_Loot_Storage_Safe_Table_Common => Construct(0x34c8b);
        public static FormLink<IContainerGetter> SFBGS001_Loot_Storage_Safe_Table_Rare => Construct(0x34c8d);
        public static FormLink<IContainerGetter> SFBGS001_Loot_Storage_Safe_Wall_Reg_Common => Construct(0x34c91);
        public static FormLink<IContainerGetter> SFBGS001_Loot_Storage_Safe_Wall_Tall_Rare => Construct(0x34c92);
        public static FormLink<IContainerGetter> SFBGS001_MS01_ShrineContainer => Construct(0x3525f);
        public static FormLink<IContainerGetter> SFBGS001_MS01_JandarRestContainer => Construct(0x35260);
        public static FormLink<IContainerGetter> SFBGS001_MS01_Vendor_Weapons_Container => Construct(0x35b35);
        public static FormLink<IContainerGetter> SFBGS001_Loot_Display_Backpackstand_01_Standing_Any_Common => Construct(0x3ccbe);
        public static FormLink<IContainerGetter> SFBGS001_Loot_Display_Backpackstand_01_Standing_Any_Rare => Construct(0x3ccbf);
        public static FormLink<IContainerGetter> SFBGS001_Loot_Display_Backpackstand_02_Table_Any_Common => Construct(0x3ccc0);
        public static FormLink<IContainerGetter> SFBGS001_Loot_Display_Backpackstand_02_Table_Any_Rare => Construct(0x3ccc1);
        public static FormLink<IContainerGetter> SFBGS001_Loot_Display_Backpackstand_03_Wall_Any_Common => Construct(0x3ccc3);
        public static FormLink<IContainerGetter> SFBGS001_Loot_Display_Backpackstand_03_Wall_Any_Rare => Construct(0x3ccc4);
        public static FormLink<IContainerGetter> SFBGS001_Loot_Display_HelmetCase_Common => Construct(0x3cccb);
        public static FormLink<IContainerGetter> SFBGS001_Loot_Display_HelmetCase_Rare => Construct(0x3cccc);
        public static FormLink<IContainerGetter> SFBGS001_Loot_Display_Helmetstand_Common => Construct(0x3ccd2);
        public static FormLink<IContainerGetter> SFBGS001_Loot_Display_Helmetstand_Rare => Construct(0x3ccd5);
        public static FormLink<IContainerGetter> SFBGS001_Loot_Display_WeaponRack01_Common => Construct(0x3ccdd);
        public static FormLink<IContainerGetter> SFBGS001_Loot_Display_WeaponRack02_Common => Construct(0x3ccee);
        public static FormLink<IContainerGetter> SFBGS001_Loot_Display_WeaponRack03_Rare => Construct(0x3ccef);
        public static FormLink<IContainerGetter> SFBGS001_Loot_Storage_AmmoCase_Large_Rare => Construct(0x3e2cc);
        public static FormLink<IContainerGetter> SFBGS001_MS05_StorageChest => Construct(0x3e969);
        public static FormLink<IContainerGetter> SFBGS001_Container_Reigen_Safe => Construct(0x3f07a);
        public static FormLink<IContainerGetter> SFBGS001LC02_Loot_Display_Backpackstand_01_Standing_Boostpack_Common_200YearOldIsolated => Construct(0x45442);
        public static FormLink<IContainerGetter> SFBGS001LC02_Loot_Storage_Safe_Table_Rare_200YearOldIsolated => Construct(0x4544a);
        public static FormLink<IContainerGetter> SFBGS001LC02_Loot_Storage_Cooler01_NoFoodOrDrink => Construct(0x4544b);
        public static FormLink<IContainerGetter> SFBGS001_Loot_Storage_TraumaPack => Construct(0x9556e);
        public static FormLink<IContainerGetter> SFBGS001_Loot_ZeroGField_SpacesuitRare => Construct(0x9556f);
        public static FormLink<IContainerGetter> SFBGS001_Vendor_ShipServicesContainer => Construct(0x973c0);
        public static FormLink<IContainerGetter> SFBGS001_MS01_Vendor_ShipServicesContainer => Construct(0xab04b);
        public static FormLink<IContainerGetter> SFBGS001_DazraZ02_RewardSafe => Construct(0xb2bf6);
        public static FormLink<IContainerGetter> SFBGS001_MS02_OrahimDepositContainer => Construct(0xc1f46);
        public static FormLink<IContainerGetter> SFBGS001_MS01Crate => Construct(0xc2298);
        public static FormLink<IContainerGetter> SFBGS001AliasContainer => Construct(0xc6410);
        public static FormLink<IContainerGetter> SFBGS001_JamJar_Empty => Construct(0xdb489);
        public static FormLink<IContainerGetter> SFBGS001L02_BrazierContainer => Construct(0xe841d);
        public static FormLink<IContainerGetter> SFBGS001_LC08_Treasure => Construct(0xfe172);
        public static FormLink<IContainerGetter> SFBGS001_Vendor_City_Dazra_VaruunDepositoryContainer => Construct(0x1024c5);
        public static FormLink<IContainerGetter> SFBGS001_Vendor_City_Dazra_MeatHouseContainer => Construct(0x1024c6);
        public static FormLink<IContainerGetter> SFBGS001_Vendor_City_Dazra_TheKeepContainer => Construct(0x1024cb);
        public static FormLink<IContainerGetter> SFBGS001_Vendor_City_Dazra_GoodsExchangeContainer => Construct(0x1024cd);
        public static FormLink<IContainerGetter> SFBGS001_Vendor_City_Dazra_HeraldsRestContainer => Construct(0x1024d3);
        public static FormLink<IContainerGetter> SFBGS001_Vendor_City_Dazra_HallsOfHealingContainer => Construct(0x1024d7);
        public static FormLink<IContainerGetter> SFBGS001_Loot_Display_WeaponsCase_Heavy_Common => Construct(0x10f795);
        public static FormLink<IContainerGetter> SFBGS001_Loot_Display_WeaponsCase_MS05_FangRifle => Construct(0x11c6d2);
        public static FormLink<IContainerGetter> SFBGS001_Loot_Display_Backpackstand_MS05_FangBackpack => Construct(0x11c6d4);
        public static FormLink<IContainerGetter> SFBGS001_Loot_Storage_Miscbox02_Common_ZeroGField => Construct(0x121488);
        public static FormLink<IContainerGetter> SFBGS001_Loot_Storage_Miscbox02_Rare_ZeroGField => Construct(0x121489);
        public static FormLink<IContainerGetter> SFBGS001_Loot_Storage_Offering01 => Construct(0x12ef79);
        public static FormLink<IContainerGetter> SFBGS001_Loot_Display_WeaponsCase_Rifles_Common => Construct(0x1508a7);
        public static FormLink<IContainerGetter> SFBGS001_Loot_Display_WeaponsCase_Heavy_Rare => Construct(0x1508a8);
        public static FormLink<IContainerGetter> SFBGS001_Loot_Display_WeaponsCase_Pistols_Common => Construct(0x1508a9);
        public static FormLink<IContainerGetter> SFBGS001_VKaiZ03_SlateCrate => Construct(0x150c84);
        public static FormLink<IContainerGetter> SFBGS001_SecureBreifcase_Container_01_CraterOfficeDebris => Construct(0x1512de);
        public static FormLink<IContainerGetter> SFBGS001_Loot_Storage_BossChest_Science_Rare => Construct(0x151c2f);
        public static FormLink<IContainerGetter> SFBGS001_Loot_Storage_BossChest_Industrial_Rare => Construct(0x151c33);
        public static FormLink<IContainerGetter> SFBGS001_Loot_Storage_BossChest_Military_Rare => Construct(0x151c3a);
        public static FormLink<IContainerGetter> SFBGS001_CraterCorpseBackpack01 => Construct(0x1536a3);
        public static FormLink<IContainerGetter> SFBGS001_VkaiZ03_VendorContainerEmptyBase => Construct(0x16fd14);
    }
}
