// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class ShatteredSpace
{
    public static partial class DefaultObject
    {
        private static FormLink<IDefaultObjectGetter> Construct(uint id) => new FormLink<IDefaultObjectGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IDefaultObjectGetter> DestructibleArmorKeyword_DO => Construct(0x103503);
        public static FormLink<IDefaultObjectGetter> LocationTypeHiddenSystem => Construct(0x1294d7);
    }
}
