// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class ShatteredSpace
{
    public static partial class Explosion
    {
        private static FormLink<IExplosionGetter> Construct(uint id) => new FormLink<IExplosionGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IExplosionGetter> SFBGS001_VortexItemMarkerPlacement_UnstableRandom => Construct(0x816);
        public static FormLink<IExplosionGetter> SFBGS001_VortexItemExplosion_Phase => Construct(0x81a);
        public static FormLink<IExplosionGetter> SFBGS001_VortexItemExplosion_Anchor => Construct(0x81f);
        public static FormLink<IExplosionGetter> SFBGS001_VortexItemExplosion_Summon => Construct(0x82d);
        public static FormLink<IExplosionGetter> SFBGS001_VortexItemMarkerPlacement_StableSummon => Construct(0x830);
        public static FormLink<IExplosionGetter> SFBGS001_VortexItemExplosion_Explosion => Construct(0x832);
        public static FormLink<IExplosionGetter> ArtifactPower_CreateVacuumCOPY0000 => Construct(0x833);
        public static FormLink<IExplosionGetter> DLC001_LC01_TRP_Electrical_Sm_Explosion => Construct(0xae1d);
        public static FormLink<IExplosionGetter> SFBGS001_VortexModulatorDamageSmall => Construct(0x1ae78);
        public static FormLink<IExplosionGetter> SFBGS001_VortexModulatorDestroyedSmall => Construct(0x1ae79);
        public static FormLink<IExplosionGetter> SFBGS001_VortexModulatorExplosionSmall => Construct(0x1ae7a);
        public static FormLink<IExplosionGetter> SFBGS001_HavokExplosion => Construct(0x1af86);
        public static FormLink<IExplosionGetter> SFBGS001_VortexPhantomTeleportInExplosion => Construct(0x2533c);
        public static FormLink<IExplosionGetter> SFBGS001_VortexPhantomTeleportOutExplosion => Construct(0x2533d);
        public static FormLink<IExplosionGetter> SFBGS001_ParticleRocketlauncherExplosion => Construct(0x2c474);
        public static FormLink<IExplosionGetter> SFBGS001_VortexSpawnExplosion => Construct(0x337eb);
        public static FormLink<IExplosionGetter> SFBGS001_MQ03_EmptyExplosionCameraShake => Construct(0x402c9);
        public static FormLink<IExplosionGetter> SFBGS001_VkaiZ03_HavokExplosion => Construct(0x40830);
        public static FormLink<IExplosionGetter> SFBGS001_VortexHorrorTeleportInExplosion => Construct(0x4709d);
        public static FormLink<IExplosionGetter> SFBGS001_VortexHorrorTeleportOutExplosion => Construct(0x4709e);
        public static FormLink<IExplosionGetter> Explosion_Electricboxtrap01 => Construct(0x7dfc7);
        public static FormLink<IExplosionGetter> SFBGS001_VortexSpawn_Spit_Exp => Construct(0x958e1);
        public static FormLink<IExplosionGetter> SFBGS001_VortexCollapse_CameraShakeExp => Construct(0x96327);
        public static FormLink<IExplosionGetter> SFBGS001_VortexCollapse_ShockWaveExp => Construct(0x98e87);
        public static FormLink<IExplosionGetter> SFBGS001LC06_AmbientExplosionVortexEnergy => Construct(0x99b4c);
        public static FormLink<IExplosionGetter> SFBGS001LC06_AmbientExplosionVortexSmoke => Construct(0x99b4d);
        public static FormLink<IExplosionGetter> SFBGS001LC06_AmbientExplosionVortexEnergyFlow_01 => Construct(0x99b4e);
        public static FormLink<IExplosionGetter> SFBGS001LC06_AmbientExplosionVortexEnergyFlow_02 => Construct(0x99b4f);
        public static FormLink<IExplosionGetter> SFBGS001LC06_AmbientExplosionNoVFX_01 => Construct(0xb48b5);
        public static FormLink<IExplosionGetter> SFBGS001LC06_AmbientExplosionNoVFX_02 => Construct(0xb48b6);
        public static FormLink<IExplosionGetter> SFBGS001LC06_AmbientExplosionNoVFX_03 => Construct(0xb48b7);
        public static FormLink<IExplosionGetter> SFBGS001LC06_AmbientExplosionNoVFX_04 => Construct(0xb48b8);
        public static FormLink<IExplosionGetter> SFBGS001LC06_AmbientExplosionNoVFX_05 => Construct(0xb48b9);
        public static FormLink<IExplosionGetter> SFBGS001LC06_AmbientExplosionNoVFX_Large => Construct(0xb48ba);
        public static FormLink<IExplosionGetter> SFBGS001LC06_AmbientExplosionNoVFX_Medium => Construct(0xb48bb);
        public static FormLink<IExplosionGetter> SFBGS001LC06_AmbientExplosionNoVFX_Small => Construct(0xb48bc);
        public static FormLink<IExplosionGetter> SFBGS001_VortexModulatorExplosion => Construct(0xb5796);
        public static FormLink<IExplosionGetter> SFBGS001_VortexGrenadeEnergy => Construct(0xc0a60);
        public static FormLink<IExplosionGetter> SFBGS001_VortexModulatorDamage => Construct(0xcf5b6);
        public static FormLink<IExplosionGetter> SFBGS001_VortexModulatorDestroyed => Construct(0xcf5b7);
        public static FormLink<IExplosionGetter> SFBGS001_VortexPhantomDeathExplosion => Construct(0xd5e57);
        public static FormLink<IExplosionGetter> SFBGS001_Weather_Explosion_EnergyStorm_01_Lightning => Construct(0x112168);
        public static FormLink<IExplosionGetter> SFBGS001_VortexSmallObjectTeleport => Construct(0x11694f);
        public static FormLink<IExplosionGetter> SFBGS001_VortexHorror_Ranged_Explosion => Construct(0x12b30e);
        public static FormLink<IExplosionGetter> SFBGS001_MQIN_ElectricalExplosionSmall => Construct(0x141d25);
        public static FormLink<IExplosionGetter> SFBGS001LC07_AmbientExplosionNoVFX_Large => Construct(0x14bfa7);
        public static FormLink<IExplosionGetter> SFBGS001_VortexGatePullInHavokExplosion => Construct(0x155689);
        public static FormLink<IExplosionGetter> SFBGS001_VortexGatePullOutHavokExplosion => Construct(0x15568a);
        public static FormLink<IExplosionGetter> SFBGS001_VortexGrenadeSummon => Construct(0x161753);
        public static FormLink<IExplosionGetter> SFBGS001_VortexGrenadeSummonBurst => Construct(0x161754);
        public static FormLink<IExplosionGetter> SFBGS001_LC01_NoVFXExplosion => Construct(0x166707);
        public static FormLink<IExplosionGetter> SFBGS001_VortexGrenadeAnchor => Construct(0x16996d);
        public static FormLink<IExplosionGetter> SFBGS001_VortexHorror_Ranged_Explosion_Small => Construct(0x16e3fe);
        public static FormLink<IExplosionGetter> SFBGS001_VortexGrenadePhase => Construct(0x16fd8e);
    }
}
