// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class ShatteredSpace
{
    public static partial class Faction
    {
        private static FormLink<IFactionGetter> Construct(uint id) => new FormLink<IFactionGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IFactionGetter> SFBGS001LC06_VortexPhantomFriendFaction => Construct(0x12bb);
        public static FormLink<IFactionGetter> SFBGS001_CrewElite_PersonalCrimeFaction_SahimaKadic => Construct(0x423b);
        public static FormLink<IFactionGetter> SFBGS001_CrewElite_PersonalCrimeFaction_TaneSalavea => Construct(0x423c);
        public static FormLink<IFactionGetter> SFBGS001_AnaskoFaction => Construct(0x2532e);
        public static FormLink<IFactionGetter> SFBGS001_LC13_CrimeFaction => Construct(0x26599);
        public static FormLink<IFactionGetter> SFBGS001_MQ01_VortexPhantomFaction => Construct(0x2ba22);
        public static FormLink<IFactionGetter> SFBGS001_VortexPhantomFaction => Construct(0x2c413);
        public static FormLink<IFactionGetter> SFBGS001_GroupFactionVortexPhantom => Construct(0x2c427);
        public static FormLink<IFactionGetter> SFBGS001_MS01_ZealotCaveFaction => Construct(0x335cc);
        public static FormLink<IFactionGetter> SFBGS001_MS01_ZealotPriestFaction => Construct(0x335cf);
        public static FormLink<IFactionGetter> SFGBS001_MS01_HeraldFaction => Construct(0x3525e);
        public static FormLink<IFactionGetter> SFBGS001_MS01_JandarRestBarFaction => Construct(0x35261);
        public static FormLink<IFactionGetter> SFBGS001_MS01_JandarScholarFaction => Construct(0x352a5);
        public static FormLink<IFactionGetter> SFBGS001_MS01_JandarRestWeaponFaction => Construct(0x35b2f);
        public static FormLink<IFactionGetter> SFBGS001_MS01_JandarRestFaction => Construct(0x35eb0);
        public static FormLink<IFactionGetter> SFBGS001_MS02_KhaslavFaction => Construct(0x3e826);
        public static FormLink<IFactionGetter> SFBGS001_MS02_ZealotFaction => Construct(0x3e827);
        public static FormLink<IFactionGetter> SFBGS001_MS02_OrahimFaction => Construct(0x3e828);
        public static FormLink<IFactionGetter> SFBGS001_MQ05_PhantomHostileFaction => Construct(0x45e4f);
        public static FormLink<IFactionGetter> SFBGS001_MQ03_CrimeFaction => Construct(0x5a214);
        public static FormLink<IFactionGetter> SFBGS001_WNPC_Pilgrims01Faction => Construct(0x5a215);
        public static FormLink<IFactionGetter> SFBGS001_WNPC_GroatFarmer01Faction => Construct(0x5a21b);
        public static FormLink<IFactionGetter> SFBGS001_WNPC_VarmilPatrol01Faction => Construct(0x5a21d);
        public static FormLink<IFactionGetter> SFBGS001_MQ03_NegotiationsFaction => Construct(0x687ca);
        public static FormLink<IFactionGetter> SFBGS001_LC04_CrimeFaction => Construct(0x7517d);
        public static FormLink<IFactionGetter> SFBGS001_CrimeFactionDazra => Construct(0x7bdb6);
        public static FormLink<IFactionGetter> SFBGS001_DazraGuardFaction => Construct(0x7d6da);
        public static FormLink<IFactionGetter> SFBGS001_DazraGenericFaction => Construct(0x7f655);
        public static FormLink<IFactionGetter> SFBGS001_DazraGenericChildFaction => Construct(0x7f656);
        public static FormLink<IFactionGetter> SFBGS001_DazraGenericSoldierFaction => Construct(0x7f657);
        public static FormLink<IFactionGetter> SFBGS001_DazraGenericHealerFaction => Construct(0x80586);
        public static FormLink<IFactionGetter> SFBGS001_DazraGenericCitizenFaction => Construct(0x8baa4);
        public static FormLink<IFactionGetter> SFBGS001_DazraGenericWorkerFaction => Construct(0x8baa5);
        public static FormLink<IFactionGetter> SFBGS001_MB_SmugglerCaptainFaction => Construct(0x93eb6);
        public static FormLink<IFactionGetter> SFBGS001_MQPostHostileFaction => Construct(0x94972);
        public static FormLink<IFactionGetter> SFBGS001_DazraShipServices_Vendor_Faction => Construct(0x973bf);
        public static FormLink<IFactionGetter> SFBGS001_LC18_CrimeFactionCrimsonFleet => Construct(0x9f563);
        public static FormLink<IFactionGetter> SFBGS001_LC18_GroupFactionCrimsonFleet => Construct(0x9f564);
        public static FormLink<IFactionGetter> SFBGS001_MS01_ZealotCaveFriendFaction => Construct(0x9f7aa);
        public static FormLink<IFactionGetter> SFBGS001_VortexHorrorFaction => Construct(0xa062c);
        public static FormLink<IFactionGetter> SFBGS001_MS01Vendor_ShipServicesFaction => Construct(0xab04c);
        public static FormLink<IFactionGetter> SFBGS001_HamadiStationFaction => Construct(0xac8fd);
        public static FormLink<IFactionGetter> SFBGS001_MS01_ZealotDazraFaction => Construct(0xc1fc9);
        public static FormLink<IFactionGetter> SFBGS001_MS01_QisraniDazraFaction => Construct(0xc1fca);
        public static FormLink<IFactionGetter> SFBGS001_MQ03_HostageDialogueFaction => Construct(0xe857e);
        public static FormLink<IFactionGetter> SFBGS001_MQ03_ZealotGuardDialogueFaction => Construct(0xe8591);
        public static FormLink<IFactionGetter> SFBGS001_Dazra_GenericSpaceportWorkerFaction => Construct(0xfd3ea);
        public static FormLink<IFactionGetter> SFBGS001_Vendor_City_Dazra_MeatHouse_Faction => Construct(0x1024c8);
        public static FormLink<IFactionGetter> SFBGS001_Vendor_City_Dazra_HallsofHealing_Faction => Construct(0x1024ce);
        public static FormLink<IFactionGetter> SFBGS001_Vendor_City_Dazra_GoodsExchange_Faction => Construct(0x1024cf);
        public static FormLink<IFactionGetter> SFBGS001_Vendor_City_Dazra_VaruunDepository_Faction => Construct(0x1024d1);
        public static FormLink<IFactionGetter> SFBGS001_Vendor_City_Dazra_HeraldsRest_Faction => Construct(0x1024d5);
        public static FormLink<IFactionGetter> SFBGS001_Vendor_City_Dazra_TheKeep_Faction => Construct(0x1024d6);
        public static FormLink<IFactionGetter> SFBGS001_DazraGenericMourningDeviceFaction => Construct(0x107f84);
        public static FormLink<IFactionGetter> SFBGS001_DazraGenericEnvoy => Construct(0x111469);
        public static FormLink<IFactionGetter> SFBGS001_DazraGenericWarden => Construct(0x11146a);
        public static FormLink<IFactionGetter> SFBGS001_GroatFarmerFaction => Construct(0x11768f);
        public static FormLink<IFactionGetter> SFBGS001_LC13GenericModelA => Construct(0x11ae0a);
        public static FormLink<IFactionGetter> SFBGS001_DazraGenericExecutor => Construct(0x11bbc0);
        public static FormLink<IFactionGetter> SFBGS001_PilgrimFaction => Construct(0x11ca3f);
        public static FormLink<IFactionGetter> SFBGS001_DazraPatrolFaction => Construct(0x11ca40);
        public static FormLink<IFactionGetter> SFBGS001_LC13_IrinaZenBedOwnershipFaction => Construct(0x151936);
        public static FormLink<IFactionGetter> SFBGS001_SE_DazraFaction => Construct(0x15856f);
        public static FormLink<IFactionGetter> SFBGS001_SE_DazraEnemyFaction => Construct(0x158570);
        public static FormLink<IFactionGetter> SFBGS001_VortexCitizenFaction => Construct(0x15bbcc);
        public static FormLink<IFactionGetter> SFBGS001_MS01_JandarRestMedicalFaction => Construct(0x15c27c);
        public static FormLink<IFactionGetter> SFBGS001LC06_CitadelRobotFaction => Construct(0x172aa3);
        public static FormLink<IFactionGetter> SFBGS001_MS03_BrothersFaction => Construct(0x173c16);
    }
}
