// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class ShatteredSpace
{
    public static partial class FogVolume
    {
        private static FormLink<IFogVolumeGetter> Construct(uint id) => new FormLink<IFogVolumeGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IFogVolumeGetter> DLC001_ATM_Fog_Varuun_Int_Med_White_Stnd => Construct(0x30c72);
        public static FormLink<IFogVolumeGetter> SFBGS001_ATM_Fog_Int_SerpentsPath => Construct(0x111b13);
        public static FormLink<IFogVolumeGetter> SFBGS001_CraterFog_Temp01 => Construct(0x14d076);
        public static FormLink<IFogVolumeGetter> SFBGS001_ATM_GroundFog_Dazra => Construct(0x1573e8);
        public static FormLink<IFogVolumeGetter> SFBGS001_ATM_Fog_POI_Crater => Construct(0x16a87b);
    }
}
