// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class ShatteredSpace
{
    public static partial class FormList
    {
        private static FormLink<IFormListGetter> Construct(uint id) => new FormLink<IFormListGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IFormListGetter> SFBGS001_FactionSharedCrimeList_Varuun => Construct(0x423a);
        public static FormLink<IFormListGetter> SFBGS001_MS02_VoicesDialogueVaruun_Zealots_NoFemale03 => Construct(0xc11f);
        public static FormLink<IFormListGetter> SFBGS001_PhotoModeCategory01Poses_AddToList => Construct(0x18fd8);
        public static FormLink<IFormListGetter> OutpostStructureVaruunHabsList01 => Construct(0x23964);
        public static FormLink<IFormListGetter> OutpostStructures_VaruunHallwaysList => Construct(0x23967);
        public static FormLink<IFormListGetter> SFBGS001_MS01_StarbornSaveActorValue => Construct(0x31783);
        public static FormLink<IFormListGetter> SFBGS001_MS01_GiftList => Construct(0x352a2);
        public static FormLink<IFormListGetter> SFBGS001_VoicesDialogueVaruun_All => Construct(0x3b56c);
        public static FormLink<IFormListGetter> SFBGS001_VoicesDialogueVaruun_Ship => Construct(0x3b56d);
        public static FormLink<IFormListGetter> SFBGS001_CREW_VoiceTypes_Generic => Construct(0x3bbc4);
        public static FormLink<IFormListGetter> SFBGS001_VkaiZ03_StorageList => Construct(0x3f07b);
        public static FormLink<IFormListGetter> SFBGS001_SE_VaruunRefugees_ResourceList => Construct(0x40c8c);
        public static FormLink<IFormListGetter> SFBGS001_StarbornSaveActorValues => Construct(0x40fa9);
        public static FormLink<IFormListGetter> SFBGS001_VoicesDialogueUnique => Construct(0x7d94d);
        public static FormLink<IFormListGetter> SFBGS001_HVVoicesDialogueVaruunGuards => Construct(0x838d0);
        public static FormLink<IFormListGetter> SFBGS001_VoicesDialogueVaruun_GenericNOMALE04 => Construct(0x8a266);
        public static FormLink<IFormListGetter> SFBGS001_SQ_Group_Faction_List_VaruunAll => Construct(0x90e2a);
        public static FormLink<IFormListGetter> SFBGS001_VoicesDialogueVaruun_Female => Construct(0x980e9);
        public static FormLink<IFormListGetter> SFBGS001_VoicesDialogueVaruun_Male => Construct(0x980ea);
        public static FormLink<IFormListGetter> SFBGS001_VoicesDialogueVaruun_Child => Construct(0x980eb);
        public static FormLink<IFormListGetter> SFBGS001_VoicesDialogueVaruun_Generic => Construct(0xa6c8b);
        public static FormLink<IFormListGetter> SFBGS001_VoicesDialogueVaruun_PlayerAddress => Construct(0xa6c8c);
        public static FormLink<IFormListGetter> SFBGS001_SlowTimeMagicEffects => Construct(0xa6f55);
        public static FormLink<IFormListGetter> SFBGS001_ToggleableCombatOverridePackageList => Construct(0xc20eb);
        public static FormLink<IFormListGetter> SFBGS001_VoicesDialogueVaruun_Zealots => Construct(0xce17f);
        public static FormLink<IFormListGetter> SFBGS001_VoicesDialogueVaruun_Zealots_NewVoicesONLY => Construct(0xce385);
        public static FormLink<IFormListGetter> SFBGS001_VoicesDialogueVaruun_Redeemed => Construct(0xd0865);
        public static FormLink<IFormListGetter> SFBGS001_SQ_Group_Faction_List_VaruunCivilians => Construct(0xd6baf);
        public static FormLink<IFormListGetter> SFBGS001_SQ_Group_Faction_List_VaruunMilitary_Enemy => Construct(0xd6bb0);
        public static FormLink<IFormListGetter> SFBGS001_BlockingHellosExcludedVoicetypes => Construct(0xe772e);
        public static FormLink<IFormListGetter> SFBGS001_FactionSharedCrimeList_Tane => Construct(0xee8c5);
        public static FormLink<IFormListGetter> SFBGS001LC06_PreplacedBattleOverridePackageList => Construct(0xf5d3f);
        public static FormLink<IFormListGetter> SFBGS001_VoicesDialogueVaruun_Security => Construct(0xf6cc9);
        public static FormLink<IFormListGetter> SFBGS001_VoicesDialogueUnique_NoBlockHelloExclVTYPs => Construct(0xfb685);
        public static FormLink<IFormListGetter> SFBGS001_VoicesDialogueVaruun_Phantom => Construct(0x1035f5);
        public static FormLink<IFormListGetter> SFBGS001_MS01_JandarsRestCitizens => Construct(0x10483b);
        public static FormLink<IFormListGetter> SFBGS001_VoicesDialogueVaruun_PostQuestSpeaker => Construct(0x10953a);
        public static FormLink<IFormListGetter> SFBGS001_VoicesDialogueUnique_MQNPCsGoodbye => Construct(0x10f239);
        public static FormLink<IFormListGetter> SFBGS001_CrimeFactionDazraFormlist => Construct(0x110b2e);
        public static FormLink<IFormListGetter> SFBGS001_MQ02_GenericVoice0508 => Construct(0x1112c2);
        public static FormLink<IFormListGetter> SFBGS001_MQ02_GenericVoice0104 => Construct(0x1112c3);
        public static FormLink<IFormListGetter> SFBGS001_VoicesDialogueVaruun_Farmers => Construct(0x117681);
        public static FormLink<IFormListGetter> SFBGS001_Actors_Farmers => Construct(0x117689);
        public static FormLink<IFormListGetter> SFBGS001_SE_VoiceTypes_Generic => Construct(0x119356);
        public static FormLink<IFormListGetter> SFBGS001_MS03_StarbornSaveActorValue => Construct(0x11a4c8);
        public static FormLink<IFormListGetter> SFBGS001_MS02_StarbornSaveActorValue => Construct(0x11a4cb);
        public static FormLink<IFormListGetter> SFBGS001_SQ_WanderingNPC_Pilgrim_LocationsFormlist => Construct(0x11cc7b);
        public static FormLink<IFormListGetter> SFBGS001_MS05_HeirloomsFormList => Construct(0x11cc97);
        public static FormLink<IFormListGetter> SFBGS001_VoicesDialogueVaruun_WanderingNPC_Pilgrims => Construct(0x11cde0);
        public static FormLink<IFormListGetter> SFBGS001_VoicesDialogueVaruun_WanderingNPC_VaruunSecurity => Construct(0x11cde1);
        public static FormLink<IFormListGetter> SFBGS001_VoicesDialogueVaruun_WanderingNPC_Farmers => Construct(0x11cde2);
        public static FormLink<IFormListGetter> SFBGS001LC06_Ext_VortexFieldTeleportMarkersPrequestList => Construct(0x12cccb);
        public static FormLink<IFormListGetter> SFBGS001LC06_Ext_VortexFieldTeleportMarkersQuestList => Construct(0x12cccc);
        public static FormLink<IFormListGetter> SFBGS001_CrimeFactionDazraFormlist_AmeliaOnly => Construct(0x12f17e);
        public static FormLink<IFormListGetter> SFBGS001_CraterDebrisNormalLootPackins => Construct(0x15080d);
        public static FormLink<IFormListGetter> SFBGS001_CraterDebrisNatural => Construct(0x155050);
        public static FormLink<IFormListGetter> SFBGS001_CraterDebrisLoot => Construct(0x15505a);
        public static FormLink<IFormListGetter> SFBGS001_VKaiZ01_TempleSpellsList => Construct(0x15ed0d);
        public static FormLink<IFormListGetter> SFBGS001_CraterDebrisValuableLootPackins => Construct(0x16323a);
    }
}
