// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class ShatteredSpace
{
    public static partial class Furniture
    {
        private static FormLink<IFurnitureGetter> Construct(uint id) => new FormLink<IFurnitureGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IFurnitureGetter> SFBGS001_MQ04_1000_Eggie_QuestioningScene_FurnitureMarker => Construct(0x154d);
        public static FormLink<IFurnitureGetter> SFBGS001_NPCKneeling_NoFrontActivate => Construct(0x7565);
        public static FormLink<IFurnitureGetter> SFBGS001_NPCSitOnGround02_HearthTable => Construct(0x10adb);
        public static FormLink<IFurnitureGetter> NPCSitOnGround02_MustExit => Construct(0x11bdf);
        public static FormLink<IFurnitureGetter> SFBGS001_NPCWritingAtDesk_Tech03Chair => Construct(0x1c6ea);
        public static FormLink<IFurnitureGetter> SFBGS001_MacKitChair_01_NoDesk => Construct(0x1df7d);
        public static FormLink<IFurnitureGetter> SFBGS001_MacKitBench_01 => Construct(0x1df81);
        public static FormLink<IFurnitureGetter> SFBGS001_MacKitBench_02 => Construct(0x1e037);
        public static FormLink<IFurnitureGetter> SFBGS001_MacKitBench_03 => Construct(0x1e039);
        public static FormLink<IFurnitureGetter> SFBGS001_MacKitBench_04 => Construct(0x1e03d);
        public static FormLink<IFurnitureGetter> DLC001MQ01_ZeroG_Suffering_FurnitureMarker => Construct(0x253cd);
        public static FormLink<IFurnitureGetter> SFBGS001_MQ06_Stage570_ActivatedPhantoms02_FurnitureMarker => Construct(0x28918);
        public static FormLink<IFurnitureGetter> DLC001MQ01_ZeroG_Frustration_FurnitureMarker => Construct(0x35dda);
        public static FormLink<IFurnitureGetter> DLC001_Standing_Suffering_FurnitureMarker => Construct(0x3ac8e);
        public static FormLink<IFurnitureGetter> DLC001_Standing_Frustration_FurnitureMarker => Construct(0x3b901);
        public static FormLink<IFurnitureGetter> SFBGS001LC06_Bench_UtilityE01_SpeakersHall => Construct(0x3d0e6);
        public static FormLink<IFurnitureGetter> SFBGS001_Vortex_Pod_FurnitureMarker => Construct(0x3d51d);
        public static FormLink<IFurnitureGetter> SFBGS001_MS01_Standing_Woozy_OneHand_FurnitureMarker => Construct(0x3e9b8);
        public static FormLink<IFurnitureGetter> SFBGS001_MS01_Standing_Woozy_TwoHands_FurnitureMarker => Construct(0x3e9ba);
        public static FormLink<IFurnitureGetter> SFBGS001_Kneeling_Varuun_Prayer_FurnitureMarker => Construct(0x4708d);
        public static FormLink<IFurnitureGetter> SFBGS001_Standing_Varuun_Prayer_FurnitureMarker => Construct(0x50acc);
        public static FormLink<IFurnitureGetter> SFBGS001_BenchA_1Way01 => Construct(0x53c8a);
        public static FormLink<IFurnitureGetter> SFBGS001_BenchA_1Way02 => Construct(0x53c8b);
        public static FormLink<IFurnitureGetter> SFBGS001_BenchAKit_1Way04 => Construct(0x53c8c);
        public static FormLink<IFurnitureGetter> SFBGS001_BenchAKit_1Way02 => Construct(0x53c8d);
        public static FormLink<IFurnitureGetter> SFBGS001_BenchAKit_1Way05 => Construct(0x53c8e);
        public static FormLink<IFurnitureGetter> SFBGS001_BenchAKit_2Way01 => Construct(0x53c8f);
        public static FormLink<IFurnitureGetter> SFBGS001_BenchAKit_3Way01 => Construct(0x53c90);
        public static FormLink<IFurnitureGetter> SFBGS001_BenchAKit_4Way01 => Construct(0x53c91);
        public static FormLink<IFurnitureGetter> SFBGS001_BenchAKit_1Way06Endcap01 => Construct(0x53c92);
        public static FormLink<IFurnitureGetter> SFBGS001_BenchAKit_2Way02 => Construct(0x53c95);
        public static FormLink<IFurnitureGetter> SFBGS001_BenchAKit_1Way06Endcap02 => Construct(0x53c97);
        public static FormLink<IFurnitureGetter> SFBGS001_BenchAKit_3Way02 => Construct(0x53c98);
        public static FormLink<IFurnitureGetter> SFBGS001_BenchAKit_1Way03 => Construct(0x53c9d);
        public static FormLink<IFurnitureGetter> SFBGS001_BenchAKit_1Way01 => Construct(0x53c9e);
        public static FormLink<IFurnitureGetter> SFBGS001_BenchA_4Way01 => Construct(0x53cb3);
        public static FormLink<IFurnitureGetter> SFBGS001_BenchA_2Way01 => Construct(0x53cb4);
        public static FormLink<IFurnitureGetter> SFBGS001_BenchA_3Way01 => Construct(0x53cb5);
        public static FormLink<IFurnitureGetter> SFBGS001_BenchA_1Way02NoSitNoBase => Construct(0x53cbf);
        public static FormLink<IFurnitureGetter> SFBGS001_BenchAKit_1Way05NoSitNoBase => Construct(0x53cc1);
        public static FormLink<IFurnitureGetter> SFBGS001_BenchAKit_UTurn01 => Construct(0x53cc9);
        public static FormLink<IFurnitureGetter> SFBGS001_BenchAKit_UTurn02 => Construct(0x53cd0);
        public static FormLink<IFurnitureGetter> SFBGS001_BenchAKit_2WayToCurveR01 => Construct(0x53cd5);
        public static FormLink<IFurnitureGetter> SFBGS001_BenchA_1Way01NoSitNoBase => Construct(0x53ce1);
        public static FormLink<IFurnitureGetter> SFBGS001_BenchA_1Way00NoSitNoBase => Construct(0x53ce3);
        public static FormLink<IFurnitureGetter> SFBGS001_BenchAKit_2WayToCurveL01 => Construct(0x53cf2);
        public static FormLink<IFurnitureGetter> NPCStanding_Mourn_NoKeywordsTest => Construct(0x5c2e2);
        public static FormLink<IFurnitureGetter> SFBGS001_NPCStanding_DataSlate_MustExit => Construct(0x5f9ed);
        public static FormLink<IFurnitureGetter> SFBGS001_MQ06_PlayerWakeUp_FurnitureMarker => Construct(0x83e02);
        public static FormLink<IFurnitureGetter> SFBFGS001_Ambush_VortexHorror_Teleport => Construct(0x9a18b);
        public static FormLink<IFurnitureGetter> SFBGS001_HidingLeft_Standing_FurnitureMarker_NOEXIT => Construct(0x9b358);
        public static FormLink<IFurnitureGetter> SFBGS001_Invisible_DazraWorkbenchFood02 => Construct(0x9f572);
        public static FormLink<IFurnitureGetter> SFBGS001_MQ01_1410_Sirak_TransformationScene_FurnitureMarker => Construct(0xe6f2b);
        public static FormLink<IFurnitureGetter> SFBGS001_NA_LobbyU_ChunskInt_Clutter_ChairA_01_DeskEatDrink => Construct(0xe859f);
        public static FormLink<IFurnitureGetter> SFBGS001_HidingLeft_Standing_FurnitureMarker => Construct(0xedeeb);
        public static FormLink<IFurnitureGetter> SFBGS001_MQ01_1410_Sirak_TransformationScene_ZeroG_FurnitureMarker => Construct(0xedeec);
        public static FormLink<IFurnitureGetter> SFBGS001_HidingRight_Crouch_FurnitureMarker => Construct(0xf4d8b);
        public static FormLink<IFurnitureGetter> SFBGS001_MS03_10_CeremonialDrinksScene_Borhal_FurnitureMarker => Construct(0xf6f68);
        public static FormLink<IFurnitureGetter> SFBGS001_MS03_10_CeremonialDrinksScene_Amila_FurnitureMarker => Construct(0xf9d53);
        public static FormLink<IFurnitureGetter> SFBGS001_GenuflectSinglePlay => Construct(0xf9d83);
        public static FormLink<IFurnitureGetter> SFBGS001_Genuflect => Construct(0xf9d85);
        public static FormLink<IFurnitureGetter> SFBGS001_CitadelEscapeFurniture => Construct(0xfc0b0);
        public static FormLink<IFurnitureGetter> SFBGS001_VKaiZ03_060_Greeting_ReigenMusicbox_FurnitureMarker => Construct(0x106de4);
        public static FormLink<IFurnitureGetter> NPCStanding_AnimFlavorArmsCrossedCasual_MustExit => Construct(0x11762c);
        public static FormLink<IFurnitureGetter> SFBGS001_Worried_FurnitureMarker => Construct(0x11abaa);
        public static FormLink<IFurnitureGetter> SFBGS001_MourningDevice_NPCChairTech03_Console => Construct(0x11cff6);
        public static FormLink<IFurnitureGetter> SFBGS001_MourningDevice_NPCConsoleStanding => Construct(0x11cff7);
        public static FormLink<IFurnitureGetter> SFBGS001_MQ04_Irina_FurnitureMarker => Construct(0x122602);
        public static FormLink<IFurnitureGetter> SFBGS001_Standing_Mourning_Device_FurnitureMarker => Construct(0x13e1e1);
        public static FormLink<IFurnitureGetter> SFBGS001_MQ04_Irina_FurnitureMarker_MustExitToTalk => Construct(0x14d4e8);
        public static FormLink<IFurnitureGetter> SFBGS001_Worried_FurnitureMarker_MustExitToTalk => Construct(0x14d4e9);
        public static FormLink<IFurnitureGetter> SFBGS001_Invisible_DazraWorkbenchFood01 => Construct(0x15806a);
        public static FormLink<IFurnitureGetter> SFBGS001_NA_LobbyU_ChunskInt_Clutter_ChairA_01_Free => Construct(0x15fd6e);
        public static FormLink<IFurnitureGetter> SFBGS001_NA_LobbyU_ChunskInt_Clutter_ChairA_01_NoDesk => Construct(0x15fd6f);
        public static FormLink<IFurnitureGetter> SFBGS001_MacKitChair_01_Desk => Construct(0x15fd79);
        public static FormLink<IFurnitureGetter> SFBGS001_MacKitChair_01_Free => Construct(0x15fd7a);
        public static FormLink<IFurnitureGetter> SFBGS001_Vortex_Pod_Off_FurnitureMarker => Construct(0x1620c5);
        public static FormLink<IFurnitureGetter> NPCStanding_AnimFlavorArmsFrontCasual_MustExit => Construct(0x162da8);
        public static FormLink<IFurnitureGetter> SFBGS001_Kneeling_Varuun_Prayer_FurnitureMarker_CitadelPilgrim => Construct(0x163254);
        public static FormLink<IFurnitureGetter> SurgicalBedForAnim01_NoExitToTalk => Construct(0x16ad8f);
        public static FormLink<IFurnitureGetter> AK_Bed_Style01_NoExitToTalk => Construct(0x16ad90);
        public static FormLink<IFurnitureGetter> SFBGS001_Vortex_Pod_Opti01_FurnitureMarker => Construct(0x174670);
        public static FormLink<IFurnitureGetter> SFBGS001_Vortex_Pod_Opti01_Off_FurnitureMarker => Construct(0x174671);
    }
}
