// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class ShatteredSpace
{
    public static partial class GenericBaseForm
    {
        private static FormLink<IGenericBaseFormGetter> Construct(uint id) => new FormLink<IGenericBaseFormGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IGenericBaseFormGetter> DLC001LC01_Station => Construct(0x84c9);
        public static FormLink<IGenericBaseFormGetter> SettleECSConstantShip_CustomCOPY0000 => Construct(0x13b84);
        public static FormLink<IGenericBaseFormGetter> SFBGS001_LvlShip_HouseVaruun_Combat => Construct(0x3ac6b);
        public static FormLink<IGenericBaseFormGetter> SFBGS001_LvlShip_HouseVaruun_Combat_50 => Construct(0x3ac6c);
        public static FormLink<IGenericBaseFormGetter> SFBGS001_SE_Player_MQ03_MihaelShip => Construct(0x9453d);
        public static FormLink<IGenericBaseFormGetter> SFBGS001_DazraMourningShip01 => Construct(0xca713);
        public static FormLink<IGenericBaseFormGetter> SFBGS001_DazraMourningShip02 => Construct(0xd1f1d);
        public static FormLink<IGenericBaseFormGetter> SFBGS001_MQ03_MihaelShip => Construct(0x11090e);
        public static FormLink<IGenericBaseFormGetter> SFBGS001_GenericCitizen_Female02_Template => Construct(0x15854e);
        public static FormLink<IGenericBaseFormGetter> SFBGS001_GenericCitizen_Female01_Template => Construct(0x15854f);
        public static FormLink<IGenericBaseFormGetter> SFBGS001_GenericCitizen_Female03_Template => Construct(0x158553);
        public static FormLink<IGenericBaseFormGetter> SFBGS001_GenericCitizen_Female04_Template => Construct(0x158555);
        public static FormLink<IGenericBaseFormGetter> SFBGS001_GenericCitizen_Female05_Template => Construct(0x158557);
        public static FormLink<IGenericBaseFormGetter> SFBGS001_GenericCitizen_Female06_Template => Construct(0x158559);
        public static FormLink<IGenericBaseFormGetter> SFBGS001_GenericCitizen_Female07_Template => Construct(0x15855b);
        public static FormLink<IGenericBaseFormGetter> SFBGS001_GenericCitizen_Female08_Template => Construct(0x15855d);
        public static FormLink<IGenericBaseFormGetter> SFBGS001_GenericCitizen_Male08_Template => Construct(0x15855f);
        public static FormLink<IGenericBaseFormGetter> SFBGS001_GenericCitizen_Male07_Template => Construct(0x158561);
        public static FormLink<IGenericBaseFormGetter> SFBGS001_GenericCitizen_Male06_Template => Construct(0x158563);
        public static FormLink<IGenericBaseFormGetter> SFBGS001_GenericCitizen_Male05_Template => Construct(0x158565);
        public static FormLink<IGenericBaseFormGetter> SFBGS001_GenericCitizen_Male04_Template => Construct(0x158567);
        public static FormLink<IGenericBaseFormGetter> SFBGS001_GenericCitizen_Male03_Template => Construct(0x158569);
        public static FormLink<IGenericBaseFormGetter> SFBGS001_GenericCitizen_Male02_Template => Construct(0x15856b);
        public static FormLink<IGenericBaseFormGetter> SFBGS001_GenericCitizen_Male01_Template => Construct(0x15856d);
    }
}
