// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class ShatteredSpace
{
    public static partial class GroundCover
    {
        private static FormLink<IGroundCoverGetter> Construct(uint id) => new FormLink<IGroundCoverGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IGroundCoverGetter> SFBGS001_GC_GrassVarrun01 => Construct(0x614e3);
        public static FormLink<IGroundCoverGetter> SFBGS001_GC_RocksLayered05 => Construct(0x13cbe8);
    }
}
