// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class ShatteredSpace
{
    public static partial class HeadPart
    {
        private static FormLink<IHeadPartGetter> Construct(uint id) => new FormLink<IHeadPartGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IHeadPartGetter> SFBGS001_Human_Female_Hair_Back_Buzz => Construct(0x2e268);
        public static FormLink<IHeadPartGetter> SFBGS001_Human_Male_Hair_Back_Buzz => Construct(0x2e269);
        public static FormLink<IHeadPartGetter> SFBGS001_Human_Female_Hair_Messy_Mullet => Construct(0x2eeef);
        public static FormLink<IHeadPartGetter> SFBGS001_Human_Male_Hair_Messy_Mullet => Construct(0x2eef0);
        public static FormLink<IHeadPartGetter> SFBGS001_Human_Female_Hair_Shaved_Top_Knot => Construct(0x2eef1);
        public static FormLink<IHeadPartGetter> SFBGS001_Human_Male_Hair_Shaved_Top_Knot => Construct(0x2eef2);
    }
}
