// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class ShatteredSpace
{
    public static partial class ImageSpaceAdapter
    {
        private static FormLink<IImageSpaceAdapterGetter> Construct(uint id) => new FormLink<IImageSpaceAdapterGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IImageSpaceAdapterGetter> ExplosionVortexDestabilizationImod => Construct(0x1c2e0);
        public static FormLink<IImageSpaceAdapterGetter> SFBGS_VortexWarpImod => Construct(0x3d5e4);
        public static FormLink<IImageSpaceAdapterGetter> HallucinogenicGas_Loop_Imod => Construct(0x8cc22);
        public static FormLink<IImageSpaceAdapterGetter> HallucinogenicGas_Start_Imod => Construct(0x8cc23);
        public static FormLink<IImageSpaceAdapterGetter> HallucinogenicGas_Stop_Imod => Construct(0x8cc24);
        public static FormLink<IImageSpaceAdapterGetter> SFBGS001LC06_VortexWarningImod => Construct(0x946ff);
        public static FormLink<IImageSpaceAdapterGetter> SFBGS001_FX_WhiteScreenImod => Construct(0x98e85);
        public static FormLink<IImageSpaceAdapterGetter> SFBGS001_VortexCollapseFlash => Construct(0x98e86);
        public static FormLink<IImageSpaceAdapterGetter> SFBGS001_VortexWallTeleport_In_Imod => Construct(0x9b7b4);
        public static FormLink<IImageSpaceAdapterGetter> SFBGS001_VortexWallTeleport_Out_Imod => Construct(0x9b7b5);
        public static FormLink<IImageSpaceAdapterGetter> SFBGS001_VortexWallTeleport_Hold_Imod => Construct(0x9f734);
        public static FormLink<IImageSpaceAdapterGetter> SFBGS001_ShrineBuff_Devotion_Imod => Construct(0xaaf39);
        public static FormLink<IImageSpaceAdapterGetter> SFBGS001_ShrineBuff_Obedience_Imod => Construct(0xaaf3a);
        public static FormLink<IImageSpaceAdapterGetter> SFBGS001_ShrineBuff_Perseverance_Imod => Construct(0xaaf3b);
        public static FormLink<IImageSpaceAdapterGetter> SFBGS001_ShrineBuff_Redemption_Imod => Construct(0xaaf3c);
        public static FormLink<IImageSpaceAdapterGetter> SFBGS001_ShrineBuff_Strength_Imod => Construct(0xaaf3d);
        public static FormLink<IImageSpaceAdapterGetter> SFBGS001_VortexShift_FadeIn_BlurBloomBlack_Imod => Construct(0xc6b1a);
    }
}
