// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class ShatteredSpace
{
    public static partial class ImageSpace
    {
        private static FormLink<IImageSpaceGetter> Construct(uint id) => new FormLink<IImageSpaceGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IImageSpaceGetter> SFBGS001_LGT_LUT_Ext_Varuun_Interior => Construct(0x30c70);
        public static FormLink<IImageSpaceGetter> SFBGS001_LGT_LUT_Int_LC08 => Construct(0x3f628);
        public static FormLink<IImageSpaceGetter> SFBGS001_LGT_LUT_Int_LC20 => Construct(0x3f629);
        public static FormLink<IImageSpaceGetter> SFBGS001_LGT_LUT_Int_LC48 => Construct(0x3f62a);
        public static FormLink<IImageSpaceGetter> SFBGS001_LGT_LUT_Int_LC60_A => Construct(0x3f62b);
        public static FormLink<IImageSpaceGetter> DLC001_LGT_PreLight_Int => Construct(0x450ab);
        public static FormLink<IImageSpaceGetter> SFBGS001_IS_Atmo_Unique_Varuunkai_LUT_Night => Construct(0x5be04);
        public static FormLink<IImageSpaceGetter> SFBGS001_IS_Atmo_Unique_Varuunkai_LUT_Day => Construct(0x5be05);
        public static FormLink<IImageSpaceGetter> SFBGS001_ISExteriorUniqueVaruunkaiClearDay01 => Construct(0x5be06);
        public static FormLink<IImageSpaceGetter> SFBGS001_ISExteriorUniqueVaruunkaiPartlyCloudyNight01 => Construct(0x5ee65);
        public static FormLink<IImageSpaceGetter> SFBGS001_LGT_LUT_Int_DazraCity => Construct(0x73bc0);
        public static FormLink<IImageSpaceGetter> SFBGS001_Day_Interior_LUT => Construct(0x74031);
        public static FormLink<IImageSpaceGetter> SFBGS001_LGT_LUT_Int_HajitalHome => Construct(0x74032);
        public static FormLink<IImageSpaceGetter> SFBGS001_LGT_LUT_Int_Citadel01_Escape => Construct(0x745af);
        public static FormLink<IImageSpaceGetter> SFBGS001_LGT_LUT_Int_AdlamHouse => Construct(0x801db);
        public static FormLink<IImageSpaceGetter> SFBGS001_LGT_LUT_Int_HouseKadic => Construct(0x9453c);
        public static FormLink<IImageSpaceGetter> SFBGS001_LGT_LUT_Int_SecurityCenter => Construct(0x948b9);
        public static FormLink<IImageSpaceGetter> SFBGS001_LGT_LUT_Int_HallOfObedience => Construct(0x948c0);
        public static FormLink<IImageSpaceGetter> SFBGS001_LGT_LUT_Int_GoodsExchange => Construct(0x948c8);
        public static FormLink<IImageSpaceGetter> SFBGS001_LGT_LUT_Int_HallsOfHealingLobby => Construct(0x94975);
        public static FormLink<IImageSpaceGetter> SFBGS001_LGT_LUT_Int_MeatHouse => Construct(0x94982);
        public static FormLink<IImageSpaceGetter> SFBGS001_LGT_LUT_Int_Clinic => Construct(0x94989);
        public static FormLink<IImageSpaceGetter> SFBGS001_LGT_LUT_Int_LC05 => Construct(0x9530e);
        public static FormLink<IImageSpaceGetter> SFBGS001_LGT_LUT_Int_Citadel02 => Construct(0x9694a);
        public static FormLink<IImageSpaceGetter> SFBGS001_LGT_LUT_Int_LC20_Emergency => Construct(0x97bed);
        public static FormLink<IImageSpaceGetter> SFBGS001_LGT_LUT_Int_TheKeep => Construct(0x97d17);
        public static FormLink<IImageSpaceGetter> SFBGS001_LGT_LUT_Int_LC18 => Construct(0x995fc);
        public static FormLink<IImageSpaceGetter> SFBGS001_LGT_LUT_Int_SerpentsPath => Construct(0x111b14);
        public static FormLink<IImageSpaceGetter> SFBGS001_ISExteriorUniqueVaruunkaiEnergyStormDay => Construct(0x112166);
        public static FormLink<IImageSpaceGetter> SFBGS001_ISExteriorUniqueVaruunkaiEnergyStormNight => Construct(0x11216a);
        public static FormLink<IImageSpaceGetter> DLC001_LGT_PreLight_Int_Fixed => Construct(0x1241a2);
        public static FormLink<IImageSpaceGetter> SFBGS003_LGT_LUT_Transition_IntCrit => Construct(0x1302ba);
        public static FormLink<IImageSpaceGetter> SFBGS001_LGT_LUT_Int_Citadel01 => Construct(0x145a72);
        public static FormLink<IImageSpaceGetter> SFBGS001_LGT_LUT_Int_NoLut => Construct(0x14a300);
        public static FormLink<IImageSpaceGetter> SFBGS001_LGT_LUT_Int_Citadel03 => Construct(0x1513b2);
        public static FormLink<IImageSpaceGetter> SFBGS001_LGT_LUT_Int_HallsOfHealing => Construct(0x153bdd);
        public static FormLink<IImageSpaceGetter> SFBGS001_LGT_LUT_Int_Oracle => Construct(0x15f34c);
        public static FormLink<IImageSpaceGetter> SFBGS001_LGT_LUT_SpaceStation_Oracle => Construct(0x162bee);
        public static FormLink<IImageSpaceGetter> SFBGS001_LGT_LUT_Int_LC19 => Construct(0x164c66);
        public static FormLink<IImageSpaceGetter> SFBGS001_LGT_LUT_Int_LC07 => Construct(0x164c9b);
    }
}
