// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class ShatteredSpace
{
    public static partial class ImpactDataSet
    {
        private static FormLink<IImpactDataSetGetter> Construct(uint id) => new FormLink<IImpactDataSetGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IImpactDataSetGetter> SFBGS001_FSTDefaultFootstepJumpDownImpact => Construct(0x12ea);
        public static FormLink<IImpactDataSetGetter> SFBGS001_FSTDefaultFootstepJumpUpImpact => Construct(0x12eb);
        public static FormLink<IImpactDataSetGetter> SFBGS001_FSTDefaultFootstepRunLImpactSet => Construct(0x12ec);
        public static FormLink<IImpactDataSetGetter> SFBGS001_FSTDefaultFootstepRunRImpactSet => Construct(0x12ed);
        public static FormLink<IImpactDataSetGetter> SFBGS001_FSTDefaultFootstepSneakRImpactSet => Construct(0x12ee);
        public static FormLink<IImpactDataSetGetter> SFBGS001_FSTDefaultFootstepSneakLImpactSet => Construct(0x12ef);
        public static FormLink<IImpactDataSetGetter> SFBGS001_FSTDefaultFootstepSprintLImpactSet => Construct(0x12f0);
        public static FormLink<IImpactDataSetGetter> SFBGS001_FSTDefaultFootstepSprintRImpactSet => Construct(0x12f1);
        public static FormLink<IImpactDataSetGetter> SFBGS001_FSTDefaultFootstepWalkLImpactSet => Construct(0x12f2);
        public static FormLink<IImpactDataSetGetter> SFBGS001_FSTDefaultFootstepWalkRImpactset => Construct(0x12f3);
        public static FormLink<IImpactDataSetGetter> SFBGS001_FSTDefaultMantleImpactSet => Construct(0x1309);
        public static FormLink<IImpactDataSetGetter> SFBGS001_FSTDefaultSlideImpactSet => Construct(0x130a);
        public static FormLink<IImpactDataSetGetter> SFBGS001_PHYWeaponBerserkerSwordImpactSet => Construct(0x2afc9);
        public static FormLink<IImpactDataSetGetter> SFBGS001_WPNHandBladeSmall_BerserkerSword_ImpactSet => Construct(0x3b71e);
        public static FormLink<IImpactDataSetGetter> SFBGS001_FXProjectile_VortexSpawn_SpitImpactSet => Construct(0x958df);
        public static FormLink<IImpactDataSetGetter> SFBGS001_FSTDefaultRedeemedFootstepJumpDownImpact => Construct(0x9627a);
        public static FormLink<IImpactDataSetGetter> SFBGS001_FSTDefaultRedeemedFootstepJumpUpImpact => Construct(0x9627b);
        public static FormLink<IImpactDataSetGetter> SFBGS001_FSTDefaultRedeemedFootstepRunLImpactSet => Construct(0x9627c);
        public static FormLink<IImpactDataSetGetter> SFBGS001_FSTDefaultRedeemedFootstepRunRImpactSet => Construct(0x9627d);
        public static FormLink<IImpactDataSetGetter> SFBGS001_FSTDefaultRedeemedFootstepSneakLImpactSet => Construct(0x9627e);
        public static FormLink<IImpactDataSetGetter> SFBGS001_FSTDefaultRedeemedFootstepSneakRImpactSet => Construct(0x9627f);
        public static FormLink<IImpactDataSetGetter> SFBGS001_FSTDefaultRedeemedFootstepSprintLImpactSet => Construct(0x96280);
        public static FormLink<IImpactDataSetGetter> SFBGS001_FSTDefaultRedeemedFootstepSprintRImpactSet => Construct(0x96281);
        public static FormLink<IImpactDataSetGetter> SFBGS001_FSTDefaultRedeemedFootstepWalkLImpactSet => Construct(0x96282);
        public static FormLink<IImpactDataSetGetter> SFBGS001_FSTDefaultRedeemedFootstepWalkRImpactSet => Construct(0x96283);
        public static FormLink<IImpactDataSetGetter> SFBGS001_PHYMusicBox => Construct(0xca37a);
        public static FormLink<IImpactDataSetGetter> SFBGS001_FX_VortexPhantom_ParticleShotgunImpactSet => Construct(0xdfa30);
        public static FormLink<IImpactDataSetGetter> SFBGS001_FX_VortexPhantom_ParticlePistolImpactSet => Construct(0xdfa34);
        public static FormLink<IImpactDataSetGetter> SFBGS001_FX_VortexPhantom_ParticleImpactSet => Construct(0xdfa38);
        public static FormLink<IImpactDataSetGetter> SFBGS001_Vortex_WPNMeleeBashGunSmallImpactSet => Construct(0xfe166);
        public static FormLink<IImpactDataSetGetter> SFBGS001_Vortex_WPNMeleeBashGunMediumImpactSet => Construct(0xfe169);
        public static FormLink<IImpactDataSetGetter> SFBGS001_VortexPhantom_LeftFadedStepImpactSet => Construct(0x13148c);
        public static FormLink<IImpactDataSetGetter> SFBGS001_VortexPhantom_LeftStepImpactSet => Construct(0x13148d);
        public static FormLink<IImpactDataSetGetter> SFBGS001_VortexPhantom_RightFadedStepImpactSet => Construct(0x13148e);
        public static FormLink<IImpactDataSetGetter> SFBGS001_VortexPhantom_RightStepImpactSet => Construct(0x13148f);
    }
}
