// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class ShatteredSpace
{
    public static partial class Ingestible
    {
        private static FormLink<IIngestibleGetter> Construct(uint id) => new FormLink<IIngestibleGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IIngestibleGetter> SFBGS001_Food_Craft_GroatPie => Construct(0x35df3);
        public static FormLink<IIngestibleGetter> SFBGS001_Food_Craft_SeaweedEggPorridge => Construct(0x35df4);
        public static FormLink<IIngestibleGetter> SFBGS001_Food_ChunksSingle_Chunks_GroatChunks => Construct(0x35df5);
        public static FormLink<IIngestibleGetter> SFBGS001_Food_Produce_Seaweed => Construct(0x35df8);
        public static FormLink<IIngestibleGetter> SFBGS001_Food_Meat_Groat => Construct(0x35df9);
        public static FormLink<IIngestibleGetter> SFBGS001_Drink_VaRuun_GroatMilk => Construct(0x3634b);
        public static FormLink<IIngestibleGetter> SFBGS001_Drink_Alc_VaRuun_Koza => Construct(0x3634c);
        public static FormLink<IIngestibleGetter> SFBGS001_Drink_Alc_VaRuun_Seaweed => Construct(0x3634d);
        public static FormLink<IIngestibleGetter> SFBGS001_Food_ChunksPack_Chunks_GroatChunks => Construct(0x60f02);
        public static FormLink<IIngestibleGetter> SFBGS001_LC18_Wine01_Malsiir => Construct(0x7dfc6);
        public static FormLink<IIngestibleGetter> SFBGS001_Chem_VortexIchor => Construct(0x103fe2);
    }
}
