// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class ShatteredSpace
{
    public static partial class Key
    {
        private static FormLink<IKeyGetter> Construct(uint id) => new FormLink<IKeyGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IKeyGetter> SFBGS001_DazraPlayerHouseKey => Construct(0x10a93);
        public static FormLink<IKeyGetter> SFBGS001_DazraHallOfObedienceKey => Construct(0x10a9e);
        public static FormLink<IKeyGetter> SFBGS001_MeatHousePenKey => Construct(0x10e7f);
        public static FormLink<IKeyGetter> SFBGS001LC06_AnaskosIDCard => Construct(0x1101d);
        public static FormLink<IKeyGetter> SFBGS001LC20_ClosetPassword => Construct(0x133f1);
        public static FormLink<IKeyGetter> SFBGS001LC20_SecurityKey => Construct(0x133f3);
        public static FormLink<IKeyGetter> SFBGS001LC07Int01_Key => Construct(0x240bc);
        public static FormLink<IKeyGetter> SFBGS001_MS01_CaveKey => Construct(0x2af96);
        public static FormLink<IKeyGetter> SFBGS001_MS01_DumpsterKey => Construct(0x2b727);
        public static FormLink<IKeyGetter> SFBGS001_MS01_OchimTerminalKey => Construct(0x2b72b);
        public static FormLink<IKeyGetter> SFBGS001_LC08_BossChestKey => Construct(0x2ea4b);
        public static FormLink<IKeyGetter> DLC_LC018ExitKey_DONTUSE => Construct(0x3477d);
        public static FormLink<IKeyGetter> SFBGS001_HouseKadicStorageKey => Construct(0x357f5);
        public static FormLink<IKeyGetter> SFBGS001LC05_Keycard => Construct(0x36b08);
        public static FormLink<IKeyGetter> SFBGS001_MS01_MujeenPasscode => Construct(0x38c6e);
        public static FormLink<IKeyGetter> SFBGS001LC19_VaultKey => Construct(0x3ca3d);
        public static FormLink<IKeyGetter> SFBGS001_VkaiZ03_SupplyKey => Construct(0x3f07d);
        public static FormLink<IKeyGetter> SFBGS001_LC01_Keycard => Construct(0x54d2c);
        public static FormLink<IKeyGetter> SFBGS001LC18Key_Exit => Construct(0x90bbe);
        public static FormLink<IKeyGetter> SFBGS001_MQ04_MazurKey => Construct(0x988f2);
        public static FormLink<IKeyGetter> SFBGS001LC21_BarnStorageKey => Construct(0x9fe90);
        public static FormLink<IKeyGetter> SFBGS001_UkaruComputer_Keycard => Construct(0xaac57);
        public static FormLink<IKeyGetter> SFBGS001LC13_StorageKey => Construct(0xaaca4);
        public static FormLink<IKeyGetter> SFBGS001LC20_VentShaftPassword => Construct(0xad8ea);
        public static FormLink<IKeyGetter> SFBGS001_DazraZ02_QuestRewardKey => Construct(0xb2bfb);
        public static FormLink<IKeyGetter> SFBGS001_MS02_OrahimDepositBoxKey => Construct(0xc1f47);
        public static FormLink<IKeyGetter> SFBGS001_MS01_KeycardDeadDrop => Construct(0xc289c);
        public static FormLink<IKeyGetter> SFBGS001LC48_BossKey => Construct(0xc3c2a);
        public static FormLink<IKeyGetter> SFBGS001_MS01_AdminKeycard => Construct(0xca72c);
        public static FormLink<IKeyGetter> SFBGS001LC42ShipKey => Construct(0xcdd5d);
        public static FormLink<IKeyGetter> SFBGS001_VkaiZ03_OrphanageKeycard => Construct(0xdb497);
        public static FormLink<IKeyGetter> SSFBGS001_MQ05Key => Construct(0xe0bee);
        public static FormLink<IKeyGetter> SFBGS001_MQ03_MirekPasscode => Construct(0xe40f8);
        public static FormLink<IKeyGetter> SFBGS001_MQ03_SahimaPasscode => Construct(0xe40f9);
        public static FormLink<IKeyGetter> SFBGS001_MQ03_SahimaDoorKey => Construct(0xe40fa);
        public static FormLink<IKeyGetter> SFBGS001_MS04_Key => Construct(0x104919);
        public static FormLink<IKeyGetter> SFBGS001LC18KeyMalsiir => Construct(0x10dbeb);
        public static FormLink<IKeyGetter> SFBGS001LC18KeyMalsiirQuest => Construct(0x10dd75);
        public static FormLink<IKeyGetter> SFBGS001LC53_FarmhouseKey => Construct(0x11a33d);
        public static FormLink<IKeyGetter> SFBGS001LC45_OrahimSafeKey => Construct(0x11aac2);
        public static FormLink<IKeyGetter> SFBGS001LC17Key_EldersRoom => Construct(0x11bdcb);
        public static FormLink<IKeyGetter> SFBGS001LC10_StorageKey => Construct(0x11f7af);
        public static FormLink<IKeyGetter> SFBGS001_LC19_KhaslavKey => Construct(0x12bdb4);
        public static FormLink<IKeyGetter> SFBGS001_VkaiZ03_StorageKey => Construct(0x150c86);
        public static FormLink<IKeyGetter> SFBGS001_CraterOfficeSafeKey01 => Construct(0x1512dd);
        public static FormLink<IKeyGetter> SFBGS001_CraterCorpseKey01 => Construct(0x1536a7);
        public static FormLink<IKeyGetter> SFBGS001_MQ01_SirakAccessCard => Construct(0x1578f8);
        public static FormLink<IKeyGetter> SFBGS001_MQ01_BasiraAccessCard => Construct(0x1578f9);
        public static FormLink<IKeyGetter> SFBGS001LC55SafeKey => Construct(0x159c91);
    }
}
