// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class ShatteredSpace
{
    public static partial class LandscapeTexture
    {
        private static FormLink<ILandscapeTextureGetter> Construct(uint id) => new FormLink<ILandscapeTextureGetter>(ModKey.MakeFormKey(id));
        public static FormLink<ILandscapeTextureGetter> SFBGS001LGrassLive01_Red => Construct(0xacc92);
        public static FormLink<ILandscapeTextureGetter> SFBGS001LGrassAridSparse02_Red => Construct(0xacc93);
        public static FormLink<ILandscapeTextureGetter> SFBGS001LRockFractured01 => Construct(0xacc94);
        public static FormLink<ILandscapeTextureGetter> SFBGS001LRockLayered09 => Construct(0xacc95);
        public static FormLink<ILandscapeTextureGetter> SFBGS001LSandRipple01 => Construct(0xaccd2);
        public static FormLink<ILandscapeTextureGetter> SFBGS001LSandRipple02 => Construct(0xaccd3);
        public static FormLink<ILandscapeTextureGetter> SFBGS001LSandRipple03 => Construct(0xaccd4);
        public static FormLink<ILandscapeTextureGetter> SFBGS001LDirtPacked02 => Construct(0xaccd5);
        public static FormLink<ILandscapeTextureGetter> SFBGS001LGravelSmoothLarge03 => Construct(0xadab7);
        public static FormLink<ILandscapeTextureGetter> SFBGS001LRockLayeredFlat01_BlueGrey => Construct(0xe0426);
        public static FormLink<ILandscapeTextureGetter> SFBGS001LRockAnomaly => Construct(0xebdf1);
        public static FormLink<ILandscapeTextureGetter> SFBGS001LCrystalRock => Construct(0xebdf2);
        public static FormLink<ILandscapeTextureGetter> SFBGS001LCrystal => Construct(0xebdf3);
    }
}
