// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class ShatteredSpace
{
    public static partial class LegendaryItem
    {
        private static FormLink<ILegendaryItemGetter> Construct(uint id) => new FormLink<ILegendaryItemGetter>(ModKey.MakeFormKey(id));
        public static FormLink<ILegendaryItemGetter> SFBGS001_LegendaryRangedWeapons => Construct(0x31b7a);
        public static FormLink<ILegendaryItemGetter> SFBGS001_DefaultLegendaryWeapons => Construct(0x31bc0);
        public static FormLink<ILegendaryItemGetter> SFBGS001_DefaultLegendaryArmor => Construct(0x31bc3);
        public static FormLink<ILegendaryItemGetter> SFBGS001_LegendaryArmorBackpack => Construct(0x31bc8);
        public static FormLink<ILegendaryItemGetter> SFBGS001_LegendaryArmorHelmet => Construct(0x31bca);
        public static FormLink<ILegendaryItemGetter> SFBGS001_DefaultLegendaryWeapons_Small => Construct(0x335df);
        public static FormLink<ILegendaryItemGetter> SFBGS001_DefaultLegendaryWeapons_Pistols => Construct(0x3cce6);
        public static FormLink<ILegendaryItemGetter> SFBGS001_LegendaryRiflesShotguns_Common => Construct(0x3cceb);
        public static FormLink<ILegendaryItemGetter> SFBGS001_LegendaryArmorHelmet_MQ06_Reward => Construct(0x91775);
        public static FormLink<ILegendaryItemGetter> SFBGS001_LegendaryArmor_MQ06_Reward => Construct(0x91776);
        public static FormLink<ILegendaryItemGetter> SFBGS001_LegendaryRedeemedBlade => Construct(0x9248d);
        public static FormLink<ILegendaryItemGetter> SFBGS001_LegendaryHeavyWeapons => Construct(0x10f799);
    }
}
