// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class ShatteredSpace
{
    public static partial class LeveledBaseForm
    {
        private static FormLink<ILeveledBaseFormGetter> Construct(uint id) => new FormLink<ILeveledBaseFormGetter>(ModKey.MakeFormKey(id));
        public static FormLink<ILeveledBaseFormGetter> SFBGS001_LShip_HumanHostile_Any => Construct(0xe58ce);
        public static FormLink<ILeveledBaseFormGetter> SFBGS001_LShip_GenericCitizen_Template => Construct(0x15854d);
    }
}
