// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class ShatteredSpace
{
    public static partial class MaterialPath
    {
        private static FormLink<IMaterialPathGetter> Construct(uint id) => new FormLink<IMaterialPathGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IMaterialPathGetter> SFBGS001DecalShearedMetal01_Path => Construct(0x18e0);
        public static FormLink<IMaterialPathGetter> VortexWallIntersectDecal01 => Construct(0x3d5e8);
        public static FormLink<IMaterialPathGetter> Floormat01_Decal_Path => Construct(0x8540b);
        public static FormLink<IMaterialPathGetter> SFBGS001_Decal_VortexSpawnSpit_Material => Construct(0x958de);
        public static FormLink<IMaterialPathGetter> DecalSFBGS001_VarHouseMaleenSigil_Path => Construct(0x12a2a2);
        public static FormLink<IMaterialPathGetter> DecalSFBGS001_VarHouseDulkehfSigil_Path => Construct(0x12a2a9);
        public static FormLink<IMaterialPathGetter> DecalSFBGS001_VarHouseVethaalSigil_Path => Construct(0x12a2ab);
        public static FormLink<IMaterialPathGetter> DecalSFBGS001_VarHouseKadicSigil_Path => Construct(0x12a2ac);
        public static FormLink<IMaterialPathGetter> SFBGS001DecalGrassLive01_Red_Dazra_Path => Construct(0x12ed9d);
        public static FormLink<IMaterialPathGetter> SFBGS001DecalLeavesTropical01_Red_Path => Construct(0x12f98e);
        public static FormLink<IMaterialPathGetter> SFBGS001_DecalBurn02Glow_Vortex => Construct(0x131a35);
        public static FormLink<IMaterialPathGetter> SFBGS001_VaruunHouseKit_Panel03_Path => Construct(0x135fe6);
        public static FormLink<IMaterialPathGetter> SFBGS001_VaruunHouseKit_Panel01_Path => Construct(0x135fe7);
        public static FormLink<IMaterialPathGetter> SFBGS001_VaruunHouseKit_Panel02_Path => Construct(0x135fe8);
        public static FormLink<IMaterialPathGetter> DecalCaveClutterDirtRocks01 => Construct(0x154d69);
        public static FormLink<IMaterialPathGetter> SFBGS001DecalGoose01_Path => Construct(0x154f1f);
        public static FormLink<IMaterialPathGetter> SFBGS001_DecalDirtPacked04_Flat_NoBiome_Path => Construct(0x16599c);
        public static FormLink<IMaterialPathGetter> SFBGS001_DecalDirtPacked04_NoBiome_Path => Construct(0x1659b5);
    }
}
