// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class ShatteredSpace
{
    public static partial class MiscItem
    {
        private static FormLink<IMiscItemGetter> Construct(uint id) => new FormLink<IMiscItemGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IMiscItemGetter> SFBGS001_WoodenGoose01_LC08_01 => Construct(0x105c9);
        public static FormLink<IMiscItemGetter> SFBGS001_WoodenGoose01_LC08_02 => Construct(0x105ca);
        public static FormLink<IMiscItemGetter> SFBGS001_WoodenGoose01_LC08_03 => Construct(0x105cd);
        public static FormLink<IMiscItemGetter> SFBGS001_WoodenGoose01_LC08_04 => Construct(0x105cf);
        public static FormLink<IMiscItemGetter> SFBGS001_WoodenGoose02_LC08_01 => Construct(0x105d1);
        public static FormLink<IMiscItemGetter> SFBGS001_WoodenGoose02_LC08_02 => Construct(0x105d3);
        public static FormLink<IMiscItemGetter> SFBGS001_WoodenGoose02_LC08_03 => Construct(0x105d5);
        public static FormLink<IMiscItemGetter> SFBGS001_WoodenGoose02_LC08_04 => Construct(0x105d6);
        public static FormLink<IMiscItemGetter> SFBGS001_CREW_SahimaPlushie_Cat01 => Construct(0x203bd);
        public static FormLink<IMiscItemGetter> SFBGS001_MS01_KeyParts => Construct(0x2af97);
        public static FormLink<IMiscItemGetter> SFBGS001_MQ03_SahimasResearch => Construct(0x3751c);
        public static FormLink<IMiscItemGetter> SFBGS001_MQ04_HouseVethaalSignetRing_01 => Construct(0x3b129);
        public static FormLink<IMiscItemGetter> SFBGS001_MS04_BiosampleCollector01 => Construct(0x3b602);
        public static FormLink<IMiscItemGetter> SFBGS001_MS03TranquilizerVial => Construct(0x3d06e);
        public static FormLink<IMiscItemGetter> SFBGS001_MS05_BrokenSpacesuit => Construct(0x3e966);
        public static FormLink<IMiscItemGetter> SFBGS001_MS05_BrokenBoostPack => Construct(0x3e967);
        public static FormLink<IMiscItemGetter> SFBGS001_MS05_BrokenRifle => Construct(0x3e968);
        public static FormLink<IMiscItemGetter> SFBGS001_VkaiZ03_Trash => Construct(0x3f085);
        public static FormLink<IMiscItemGetter> SFBGS001_MS04_AnimalSampleA => Construct(0x4077a);
        public static FormLink<IMiscItemGetter> SFBGS001_MS04_AnimalSampleB => Construct(0x4077b);
        public static FormLink<IMiscItemGetter> SFBGS001_MS04_AnimalSampleC => Construct(0x4077c);
        public static FormLink<IMiscItemGetter> SFBGS001_MS04_PlantSampleA => Construct(0x4077d);
        public static FormLink<IMiscItemGetter> SFBGS001_MS04_PlantSampleB => Construct(0x4077e);
        public static FormLink<IMiscItemGetter> SFBGS001_MS04_PlantSampleC => Construct(0x4077f);
        public static FormLink<IMiscItemGetter> SFBGS001_MS04_Chemical => Construct(0x40786);
        public static FormLink<IMiscItemGetter> SFBGS001_VortexCore_01_Intact => Construct(0x46e23);
        public static FormLink<IMiscItemGetter> SFBGS001_VortexCore_02_Damaged => Construct(0x490c0);
        public static FormLink<IMiscItemGetter> SFBGS001_MQ04_PowerGridAccessCode => Construct(0x5733b);
        public static FormLink<IMiscItemGetter> SFBGS001_VortexIchor01_Misc_Test => Construct(0x5733d);
        public static FormLink<IMiscItemGetter> SFBGS001_VKaiZ02_PackageFihran => Construct(0x5fd0c);
        public static FormLink<IMiscItemGetter> SFBGS001_VKaiZ02_PackageAlicja => Construct(0x5fd0d);
        public static FormLink<IMiscItemGetter> SFBGS001_VKaiZ02_PackageLazim => Construct(0x5fd0e);
        public static FormLink<IMiscItemGetter> SFBGS001_VaruunSerpentStatueSmall => Construct(0xaaabb);
        public static FormLink<IMiscItemGetter> SFBGS001_VortexShard => Construct(0xfaf4c);
        public static FormLink<IMiscItemGetter> SFBGS001_VkaiZ03_Toyplushie_Dog01 => Construct(0x1070ce);
        public static FormLink<IMiscItemGetter> SFBGS001_VortexCyst_Glowing => Construct(0x1072bf);
        public static FormLink<IMiscItemGetter> SFBGS001_VortexCyst_Dark => Construct(0x1072c0);
        public static FormLink<IMiscItemGetter> SFBGS001_VortexCyst => Construct(0x1072c1);
        public static FormLink<IMiscItemGetter> SFBGS001_WoodenGoose01 => Construct(0x154d6a);
        public static FormLink<IMiscItemGetter> SFBGS001_WoodenGoose02 => Construct(0x154d6d);
        public static FormLink<IMiscItemGetter> SFBGS001_MQ02_RitualItem01b => Construct(0x164c2b);
        public static FormLink<IMiscItemGetter> SFBGS001_MQ02_RitualItem04b => Construct(0x164c2c);
        public static FormLink<IMiscItemGetter> SFBGS001_MQ02_RitualItem02b => Construct(0x164c2d);
        public static FormLink<IMiscItemGetter> SFBGS001_MQ02_RitualItem03b => Construct(0x164c2e);
    }
}
