// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class ShatteredSpace
{
    public static partial class MorphableObject
    {
        private static FormLink<IMorphableObjectGetter> Construct(uint id) => new FormLink<IMorphableObjectGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IMorphableObjectGetter> SFBGS001_MORPH_Spacesuit_Varuun_UpperBody_02_M => Construct(0x16819);
        public static FormLink<IMorphableObjectGetter> SFBGS001_MORPH_Spacesuit_Varuun_UpperBody_Armor_02_M => Construct(0x1681a);
        public static FormLink<IMorphableObjectGetter> SFBGS001_MORPH_Spacesuit_Varuun_UpperBody_Details_02_M => Construct(0x1681b);
        public static FormLink<IMorphableObjectGetter> SFBGS001_MORPH_Spacesuit_Varuun_LowerBody_02_M => Construct(0x1681c);
        public static FormLink<IMorphableObjectGetter> SFBGS001_MORPH_Spacesuit_Varuun_LowerBody_Armor_02_M => Construct(0x1681d);
        public static FormLink<IMorphableObjectGetter> SFBGS001_MORPH_Spacesuit_Varuun_Sleeves_02_M => Construct(0x1681e);
        public static FormLink<IMorphableObjectGetter> SFBGS001_MORPH_Spacesuit_Varuun_Sleeves_Details_02_M => Construct(0x1681f);
        public static FormLink<IMorphableObjectGetter> SFBGS001_MORPH_Spacesuit_Varuun_Sleeves_Armor_02_M => Construct(0x16820);
        public static FormLink<IMorphableObjectGetter> SFBGS001_MORPH_Spacesuit_Varuun_LowerBody_02_F => Construct(0x16821);
        public static FormLink<IMorphableObjectGetter> SFBGS001_MORPH_Spacesuit_Varuun_LowerBody_Armor_02_F => Construct(0x16822);
        public static FormLink<IMorphableObjectGetter> SFBGS001_MORPH_Spacesuit_Varuun_Sleeves_02_F => Construct(0x16823);
        public static FormLink<IMorphableObjectGetter> SFBGS001_MORPH_Spacesuit_Varuun_Sleeves_Armor_02_F => Construct(0x16824);
        public static FormLink<IMorphableObjectGetter> SFBGS001_MORPH_Spacesuit_Varuun_Sleeves_Details_02_F => Construct(0x16825);
        public static FormLink<IMorphableObjectGetter> SFBGS001_MORPH_Spacesuit_Varuun_UpperBody_02_F => Construct(0x16826);
        public static FormLink<IMorphableObjectGetter> SFBGS001_MORPH_Spacesuit_Varuun_UpperBody_Armor_02_F => Construct(0x16827);
        public static FormLink<IMorphableObjectGetter> SFBGS001_MORPH_Spacesuit_Varuun_UpperBody_Details_02_F => Construct(0x16828);
        public static FormLink<IMorphableObjectGetter> SFBGS001_MORPH_Human_Female_Hair_Back_Buzz => Construct(0x2e26a);
        public static FormLink<IMorphableObjectGetter> SGBGS001_MORPH_Human_Male_Hair_Back_Buzz => Construct(0x2e26b);
        public static FormLink<IMorphableObjectGetter> SFBGS001_MORPH_Human_Female_Hair_Messy_Mullet => Construct(0x2eef3);
        public static FormLink<IMorphableObjectGetter> SGBGS001_MORPH_Human_Male_Hair_Messy_Mullet => Construct(0x2eef4);
        public static FormLink<IMorphableObjectGetter> SFBGS001_MORPH_Human_Female_Hair_Shaved_TopKnot => Construct(0x2eef5);
        public static FormLink<IMorphableObjectGetter> SGBGS001_MORPH_Human_Male_Hair_Shaved_TopKnot => Construct(0x2eef6);
        public static FormLink<IMorphableObjectGetter> SFBGS001_MORPH_Clothes_Varuun_Administrator_LowerBody_F => Construct(0x807f9);
        public static FormLink<IMorphableObjectGetter> SFBGS001_MORPH_Clothes_Varuun_Administrator_LowerBody_M => Construct(0x807fa);
        public static FormLink<IMorphableObjectGetter> SFBGS001_MORPH_Clothes_Varuun_Administrator_Sleeves_F => Construct(0x807fb);
        public static FormLink<IMorphableObjectGetter> SFBGS001_MORPH_Clothes_Varuun_Administrator_Sleeves_M => Construct(0x807fc);
        public static FormLink<IMorphableObjectGetter> SFBGS001_MORPH_Clothes_Varuun_Administrator_UpperBody_F => Construct(0x807fd);
        public static FormLink<IMorphableObjectGetter> SFBGS001_MORPH_Clothes_Varuun_Administrator_UpperBody_M => Construct(0x807fe);
        public static FormLink<IMorphableObjectGetter> SFBGS001_MORPH_Clothes_Varuun_Administrator_Banner_F => Construct(0x807ff);
        public static FormLink<IMorphableObjectGetter> SFBGS001_MORPH_Clothes_Varuun_Administrator_Cape_F => Construct(0x80800);
        public static FormLink<IMorphableObjectGetter> SFBGS001_FORPH_Clothes_Varuun_Administrator_Banner_M => Construct(0x80801);
        public static FormLink<IMorphableObjectGetter> SFBGS001_FORPH_Clothes_Varuun_Administrator_Cape_M => Construct(0x80802);
        public static FormLink<IMorphableObjectGetter> SFBGS001_MORPH_Clothes_Varuun_Unique_2_LowerBody_F => Construct(0x15d615);
        public static FormLink<IMorphableObjectGetter> SFBGS001_MORPH_Clothes_Varuun_Unique_2_LowerBody_M => Construct(0x15d616);
        public static FormLink<IMorphableObjectGetter> SFBGS001_MORPH_Clothes_Varuun_Unique_2_Sleeves_F => Construct(0x15d617);
        public static FormLink<IMorphableObjectGetter> SFBGS001_MORPH_Clothes_Varuun_Unique_2_Sleeves_M => Construct(0x15d618);
        public static FormLink<IMorphableObjectGetter> SFBGS001_MORPH_Clothes_Varuun_Unique_2_UpperBody_F => Construct(0x15d619);
        public static FormLink<IMorphableObjectGetter> SFBGS001_MORPH_Clothes_Varuun_Unique_2_UpperBody_M => Construct(0x15d61a);
        public static FormLink<IMorphableObjectGetter> SFBGS001_MORPH_Clothes_Varuun_Unique_2_Pouches_F => Construct(0x15d61b);
        public static FormLink<IMorphableObjectGetter> SFBGS001_MORPH_Clothes_Varuun_Unique_2_Pouches_M => Construct(0x15d61c);
        public static FormLink<IMorphableObjectGetter> SFBGS001_MORPH_Clothes_Varuun_Unique_2_Scarf_F => Construct(0x15d61d);
        public static FormLink<IMorphableObjectGetter> SFBGS001_MORPH_Clothes_Varuun_Unique_2_Scarf_M => Construct(0x15d61e);
        public static FormLink<IMorphableObjectGetter> SFBGS001_MORPH_Clothes_Varuun_Unique_2_ShoulderPad_F => Construct(0x15d61f);
        public static FormLink<IMorphableObjectGetter> SFBGS001_MORPH_Clothes_Varuun_Unique_2_ShoulderPad_M => Construct(0x15d620);
    }
}
