// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class ShatteredSpace
{
    public static partial class ObjectEffect
    {
        private static FormLink<IObjectEffectGetter> Construct(uint id) => new FormLink<IObjectEffectGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IObjectEffectGetter> SFBGS001VortexItem_PhaseEnch => Construct(0x81c);
        public static FormLink<IObjectEffectGetter> SFBGS001VortexItem_AnchorEnch => Construct(0x81d);
    }
}
