// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class ShatteredSpace
{
    public static partial class Outfit
    {
        private static FormLink<IOutfitGetter> Construct(uint id) => new FormLink<IOutfitGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IOutfitGetter> SFBGS001_Outfit_Clothes_Varuun_Unique_2_Variant_01 => Construct(0x1803);
        public static FormLink<IOutfitGetter> SFBGS001_Outfit_Elite_TaneSalavea => Construct(0x4221);
        public static FormLink<IOutfitGetter> SFBGS001_Outfit_Spacesuit_Elite_TaneSalavea => Construct(0x4222);
        public static FormLink<IOutfitGetter> SFBGS001_Outfit_Elite_SahimaKadic => Construct(0x4223);
        public static FormLink<IOutfitGetter> SFBGS001_Outfit_Spacesuit_Elite_SahimaKadic => Construct(0x4224);
        public static FormLink<IOutfitGetter> SFBGS001_Outfit_Clothes_Varuun_Administrator_Kadic => Construct(0x18291);
        public static FormLink<IOutfitGetter> SFBGS001_Outfit_Clothes_Varuun_Administrator_Vethaal => Construct(0x18292);
        public static FormLink<IOutfitGetter> SFBGS001_Outfit_Clothes_Varuun_Administrator_Zealots => Construct(0x18297);
        public static FormLink<IOutfitGetter> SFBGS001_Outfit_Spacesuit_Varuun_01_Zealot => Construct(0x1e7e6);
        public static FormLink<IOutfitGetter> SFBGS001_Outfit_Spacesuit_Varuun_02_Zealot_Armored => Construct(0x1e7e8);
        public static FormLink<IOutfitGetter> SFBGS001_Outfit_Spacesuit_Varuun_02_Zealot => Construct(0x1e7ee);
        public static FormLink<IOutfitGetter> SFBGS001_Outfit_Spacesuit_Varuun_Zealot_AllVariants => Construct(0x1e810);
        public static FormLink<IOutfitGetter> SFBGS001_Outfit_Spacesuit_Varuun_AllVariants => Construct(0x23b4c);
        public static FormLink<IOutfitGetter> SFBGS001_Outfit_Spacesuit_Varuun_02_Armored => Construct(0x23b4d);
        public static FormLink<IOutfitGetter> SFBGS001_Outfit_Spacesuit_Varuun_02_NoHelmet => Construct(0x23b4e);
        public static FormLink<IOutfitGetter> SFBGS001_Outfit_Spacesuit_Varuun_02_Armored_NoHelmet => Construct(0x23b4f);
        public static FormLink<IOutfitGetter> SFBGS001_Outfit_Clothes_Varuun_Unique_2 => Construct(0x36b3c);
        public static FormLink<IOutfitGetter> SFBGS001_Outfit_Clothes_Varuun_Unique_2_Variant_02 => Construct(0x36b3d);
        public static FormLink<IOutfitGetter> SFBGS001_Outfit_Clothes_Varuun_Unique_2_Variant_03 => Construct(0x36b3e);
        public static FormLink<IOutfitGetter> SFBGS001_Outfit_Clothes_Varuun_Unique_2_Zealots => Construct(0x36b3f);
        public static FormLink<IOutfitGetter> SFBGS001_Outfit_DazraVaeric => Construct(0x7517b);
        public static FormLink<IOutfitGetter> SFBGS001_Outfit_LC04Vaeric => Construct(0x7517c);
        public static FormLink<IOutfitGetter> SFBGS001_Outfit_ZenMazur => Construct(0x78319);
        public static FormLink<IOutfitGetter> SFBGS001_Outfit_Clothes_Neon_Gang_Strikers_Varuun => Construct(0x7eddf);
        public static FormLink<IOutfitGetter> SFBGS001_Outfit_Clothes_HouseDulkehfLab => Construct(0x8a290);
        public static FormLink<IOutfitGetter> SFBGS001_Outfit_Clothes_HouseDulkehfLab_NoShield => Construct(0x8a291);
        public static FormLink<IOutfitGetter> SFBGS001_Outfit_Clothes_HouseVethaalLab => Construct(0x8a292);
        public static FormLink<IOutfitGetter> SFBGS001_Outfit_Clothes_HouseVethaalLab_NoShield => Construct(0x8a294);
        public static FormLink<IOutfitGetter> SFBGS001_Outfit_Clothes_HouseKadicLab => Construct(0x8a296);
        public static FormLink<IOutfitGetter> SFBGS001_Outfit_Clothes_HouseKadicLab_NoShield => Construct(0x8a297);
        public static FormLink<IOutfitGetter> SFBGS001_Outfit_Clothes_ZealotsLab => Construct(0x8a298);
        public static FormLink<IOutfitGetter> SFBGS001_Outfit_Clothes_ZealotsLab_NoShield => Construct(0x8a299);
        public static FormLink<IOutfitGetter> SFBGS001_Outfit_IrinaMazur => Construct(0x928e8);
        public static FormLink<IOutfitGetter> SFBGS001_Outfit_MilaMazur => Construct(0x928e9);
        public static FormLink<IOutfitGetter> SFBGS001_Outfit_BiancaLatif => Construct(0x928ea);
        public static FormLink<IOutfitGetter> SFBGS001_Outfit_EgboKazmi => Construct(0x928eb);
        public static FormLink<IOutfitGetter> SFBGS001_khaslavoutfit => Construct(0x928ec);
        public static FormLink<IOutfitGetter> SFBGS001_GenericLaborerOutfits => Construct(0x928ee);
        public static FormLink<IOutfitGetter> SFBGS001_Outfit_VaruunPilgrim => Construct(0x9f54c);
        public static FormLink<IOutfitGetter> SFBGS001_Outfit_Crew_Generic => Construct(0xaec7f);
        public static FormLink<IOutfitGetter> SFBGS001_Outfit_Spacesuit_VaruunRedeemed => Construct(0xafd61);
        public static FormLink<IOutfitGetter> SFBGS001_Outfit_Spacesuit_Miner_Varuun => Construct(0xc0af2);
        public static FormLink<IOutfitGetter> SFBGS001_Outfit_Clothes_Scrubs_Varuun => Construct(0xc3f88);
        public static FormLink<IOutfitGetter> SFBGS001_Outfit_Clothes_Security_Guard_01_Varuun_with_Helmet => Construct(0xc94c7);
        public static FormLink<IOutfitGetter> SFBGS001_Outfit_Clothes_Security_Guard_01_Varuun_with_EliteHelmet => Construct(0xc94c8);
        public static FormLink<IOutfitGetter> SFBGS001_Outfit_Clothes_Security_Guard_01_Varuun_NoHelmet => Construct(0xc94c9);
        public static FormLink<IOutfitGetter> SFBGS001_Outfit_Clothes_Neon_Gang_Strikers_NoHeadgear_Varuun => Construct(0xcb678);
        public static FormLink<IOutfitGetter> SFBGS001_Outfit_Clothes_Child_JacketPants_Varuun => Construct(0xcd16d);
        public static FormLink<IOutfitGetter> SFBGS001_Outfit_Clothes_Child_JacketPantsBoots_Varuun => Construct(0xcd16e);
        public static FormLink<IOutfitGetter> SFBGS001_Outfit_Clothes_Child_Jumpsuit_Varuun => Construct(0xcd16f);
        public static FormLink<IOutfitGetter> SFBGS001_Outfit_Spacesuit_VaruunRedeemed_PowerBoost => Construct(0xeadf2);
        public static FormLink<IOutfitGetter> SFBGS001_Outfit_Clothes_ScienceLabTec => Construct(0xee4c4);
        public static FormLink<IOutfitGetter> SFBGS001_Outfit_Clothes_ScienceLabTec_NoShield => Construct(0xee4c6);
        public static FormLink<IOutfitGetter> SFBGS001_Outfit_Clothes_Child_VaruunAny => Construct(0xfcfa5);
        public static FormLink<IOutfitGetter> SFBGS001_Outfit_Clothes_Varuun_Ambassador => Construct(0xfd3c0);
        public static FormLink<IOutfitGetter> SFBGS001_Outfit_Clothes_ScienceLabTec_Any => Construct(0xfd8d6);
        public static FormLink<IOutfitGetter> SFBGS001_OrahimOutfit => Construct(0x10409b);
        public static FormLink<IOutfitGetter> SFBGS001_Outfit_MalikVosh => Construct(0x10409c);
        public static FormLink<IOutfitGetter> SFBGS001_Outfit_Spacesuit_Fang_Varuun => Construct(0x11bb9b);
        public static FormLink<IOutfitGetter> SFBGS001_Outfit_Spacesuit_Varuun_01_NoHelmet => Construct(0x125a79);
        public static FormLink<IOutfitGetter> SFBGS001_Outfit_Clothes_VortexPhantom_LowLevel => Construct(0x131df3);
        public static FormLink<IOutfitGetter> SFBGS001_Outfit_Clothes_UtilityWorker => Construct(0x1478f7);
        public static FormLink<IOutfitGetter> SFBGS001_Outfit_Clothes_Varuun_Administrator => Construct(0x1531ff);
        public static FormLink<IOutfitGetter> SFBGS001_Outfit_VaruunCitizen => Construct(0x15fdae);
        public static FormLink<IOutfitGetter> SFBGS001_Outfit_VaruunSecurity => Construct(0x15fdaf);
        public static FormLink<IOutfitGetter> SFBGS001_Outfit_Clothes_Varuun_Unique_1 => Construct(0x1606c5);
        public static FormLink<IOutfitGetter> SFBGS001_Outfit_Clothes_Varuun_Administrator_Dulkehf => Construct(0x160d56);
        public static FormLink<IOutfitGetter> SFBGS001_MS01_Outfit_VaruunCitizen => Construct(0x1665c8);
    }
}
