// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class ShatteredSpace
{
    public static partial class PlanetContentManagerBranchNode
    {
        private static FormLink<IPlanetContentManagerBranchNodeGetter> Construct(uint id) => new FormLink<IPlanetContentManagerBranchNodeGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IPlanetContentManagerBranchNodeGetter> PCM_BlockCreation_DebugBranch_SFBGS001 => Construct(0x121a3);
        public static FormLink<IPlanetContentManagerBranchNodeGetter> PCM_BlockCreation_DebugBranch_SFBGS001_Content01_OEs => Construct(0x121a4);
        public static FormLink<IPlanetContentManagerBranchNodeGetter> PCM_BlockCreation_SFBGS001Branch => Construct(0x121a5);
        public static FormLink<IPlanetContentManagerBranchNodeGetter> PCM_BlockCreation_SFBGS001_OELocations => Construct(0x121a6);
        public static FormLink<IPlanetContentManagerBranchNodeGetter> PCM_OE_Dazra_RequestNode => Construct(0xffeed);
        public static FormLink<IPlanetContentManagerBranchNodeGetter> PCM_BlockCreation_OEWorlds_SFBGS001_Natural => Construct(0xffeee);
        public static FormLink<IPlanetContentManagerBranchNodeGetter> PCM_BlockCreation_NearLocation_Dazra_Landmass => Construct(0xffeef);
        public static FormLink<IPlanetContentManagerBranchNodeGetter> PCM_BlockCreation_NearLocation_Dazra => Construct(0xffef0);
        public static FormLink<IPlanetContentManagerBranchNodeGetter> PCM_BlockCreation_NearLocation_Dazra_Caves => Construct(0xffef1);
        public static FormLink<IPlanetContentManagerBranchNodeGetter> PCM_BlockCreation_NearLocation_Dazra_Dungeons => Construct(0xffef2);
        public static FormLink<IPlanetContentManagerBranchNodeGetter> PCM_BlockCreation_SFBGS001_Vortex_Branch => Construct(0xffef3);
    }
}
