// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class ShatteredSpace
{
    public static partial class Projectile
    {
        private static FormLink<IProjectileGetter> Construct(uint id) => new FormLink<IProjectileGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IProjectileGetter> SFBGS001_VortexGrenadeProjectile_UnstableRandom => Construct(0x815);
        public static FormLink<IProjectileGetter> SFBGS001_VortexGrenadeProjectile_StableAnchor => Construct(0x825);
        public static FormLink<IProjectileGetter> SFBGS001_VortexGrenadeProjectile_StablePhase => Construct(0x82a);
        public static FormLink<IProjectileGetter> SFBGS001_VortexGrenadeProjectile_StableExplosion => Construct(0x82b);
        public static FormLink<IProjectileGetter> SFBGS001_VortexGrenadeProjectile_StableSummon => Construct(0x82c);
        public static FormLink<IProjectileGetter> SFBGS001_ParticleRocketlauncherProjectile => Construct(0x2c473);
        public static FormLink<IProjectileGetter> SFBGS001_VortexSpawn_Spit_Projectile => Construct(0x958dc);
        public static FormLink<IProjectileGetter> SFBGS001_VortexPhantom_ParticleProjectile_BigBang => Construct(0xdfa2f);
        public static FormLink<IProjectileGetter> SFBGS001_VortexPhantom_ParticleProjectile_ParticleRocketLauncher => Construct(0xdfa32);
        public static FormLink<IProjectileGetter> SFBGS001_VortexPhantom_ParticleProjectile_InflictorPistol => Construct(0xdfa33);
        public static FormLink<IProjectileGetter> SFBGS001_VortexPhantom_ParticleProjectile_FuseHeavy => Construct(0xdfa35);
        public static FormLink<IProjectileGetter> SFBGS001_VortexPhantom_BulletProjectile_HardTarget => Construct(0xdfa39);
        public static FormLink<IProjectileGetter> SFBGS001_VortexHorror_Ranged_Projectile => Construct(0x12b30f);
        public static FormLink<IProjectileGetter> ParticleFuseHeavyProjectile_Large => Construct(0x13c058);
        public static FormLink<IProjectileGetter> SFBGS001_VortexHorror_Ranged_Projectile_Small => Construct(0x16e3ff);
    }
}
