// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class ShatteredSpace
{
    public static partial class ProjectedDecal
    {
        private static FormLink<IProjectedDecalGetter> Construct(uint id) => new FormLink<IProjectedDecalGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IProjectedDecalGetter> proj_SFBGS001DecalShearedMetal01 => Construct(0x18dd);
        public static FormLink<IProjectedDecalGetter> VortexIntersectionProjectedDecal01 => Construct(0x3d5e9);
        public static FormLink<IProjectedDecalGetter> Proj_Decal_FloorMat01 => Construct(0x8540a);
        public static FormLink<IProjectedDecalGetter> SFBGS001_Decal_VortexSpawn_Spit => Construct(0x958dd);
        public static FormLink<IProjectedDecalGetter> proj_Decal_SFBGS001_VarHouseMaleenSigil => Construct(0x12a2a1);
        public static FormLink<IProjectedDecalGetter> proj_Decal_SFBGS001_VarHouseDulkehfSigil => Construct(0x12a2a4);
        public static FormLink<IProjectedDecalGetter> proj_Decal_SFBGS001_VarHouseVethaalSigil => Construct(0x12a2a5);
        public static FormLink<IProjectedDecalGetter> proj_Decal_SFBGS001_VarHouseKadicSigil => Construct(0x12a2a6);
        public static FormLink<IProjectedDecalGetter> proj_SFBGS001DecalGrassLive01_Red_Dazra => Construct(0x12ed9c);
        public static FormLink<IProjectedDecalGetter> proj_SFBGS001DecalLeavesTropical01_Red_Dazra => Construct(0x12f99c);
        public static FormLink<IProjectedDecalGetter> proj_Decal_SFBGS001_Burn02Glow_Vortex => Construct(0x131a34);
        public static FormLink<IProjectedDecalGetter> proj_DecalCaveClutterDirtRocks01 => Construct(0x154d66);
        public static FormLink<IProjectedDecalGetter> proj_SFBGS001DecalGoose01 => Construct(0x154f1e);
        public static FormLink<IProjectedDecalGetter> proj_Decal_SFBGS001_DirtPacked04_NoBiome => Construct(0x16598c);
        public static FormLink<IProjectedDecalGetter> proj_Decal_SFBGS001_DirtPacked04_Flat_NoBiome => Construct(0x1659a2);
    }
}
