// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class ShatteredSpace
{
    public static partial class SnapTemplateBehavior
    {
        private static FormLink<ISnapTemplateBehaviorGetter> Construct(uint id) => new FormLink<ISnapTemplateBehaviorGetter>(ModKey.MakeFormKey(id));
        public static FormLink<ISnapTemplateBehaviorGetter> OB_OPV_HabSmWalls01 => Construct(0x23969);
        public static FormLink<ISnapTemplateBehaviorGetter> OB_OPV_HabSmWalls01B => Construct(0x2396a);
        public static FormLink<ISnapTemplateBehaviorGetter> SFBGS001_OB_OPV_HabSmWalls01 => Construct(0x25526);
    }
}
