// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class ShatteredSpace
{
    public static partial class SoundKeywordMapping
    {
        private static FormLink<ISoundKeywordMappingGetter> Construct(uint id) => new FormLink<ISoundKeywordMappingGetter>(ModKey.MakeFormKey(id));
        public static FormLink<ISoundKeywordMappingGetter> SFBGS001_SKMHandParticleMachineGunPCAuto_HighPowered => Construct(0x11fd);
        public static FormLink<ISoundKeywordMappingGetter> SFBGS001_SKMHandParticleRocketlauncherNPCSemi => Construct(0x20136);
        public static FormLink<ISoundKeywordMappingGetter> SFBGS001_SKMHandParticleRocketlauncherPCSemi => Construct(0x20137);
        public static FormLink<ISoundKeywordMappingGetter> SFBGS001_SKMHandParticleRocketlauncherPCSemiHighPower => Construct(0x39069);
        public static FormLink<ISoundKeywordMappingGetter> SFBGS001_SKMHandParticleMachineGunPCAuto_Normal => Construct(0x7c034);
        public static FormLink<ISoundKeywordMappingGetter> SFBGS001_SKMHandParticleMachineGunNPCAuto => Construct(0x7c036);
        public static FormLink<ISoundKeywordMappingGetter> SFBGS001_SKM_VortexPhantom_InflictorRifle_Semi => Construct(0xdfa22);
        public static FormLink<ISoundKeywordMappingGetter> SFBGS001_SKM_VortexPhantom_BigBang_Semi => Construct(0xdfa24);
        public static FormLink<ISoundKeywordMappingGetter> SFBGS001_SKM_VortexPhantom_HardTarget_Suppressed_Semi => Construct(0xdfa26);
        public static FormLink<ISoundKeywordMappingGetter> SFBGS001_SKM_VortexPhantom_HardTarget_Semi => Construct(0xdfa27);
        public static FormLink<ISoundKeywordMappingGetter> SFBGS001_SKM_VortexPhantom_InflictorPistol_Semi => Construct(0xdfa29);
        public static FormLink<ISoundKeywordMappingGetter> SFBGS001_SKM_VortexPhantom_InflictorPistol_Burst => Construct(0xdfa2a);
        public static FormLink<ISoundKeywordMappingGetter> SFBGS001_SKM_VortexPhantom_ParticleRocketLauncher_Semi => Construct(0xdfa2c);
        public static FormLink<ISoundKeywordMappingGetter> SFBGS001_SKM_VortexPhantom_ParticleMachinegun_Auto => Construct(0xdfa2e);
    }
}
