// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class ShatteredSpace
{
    public static partial class SpeechChallenge
    {
        private static FormLink<ISpeechChallengeGetter> Construct(uint id) => new FormLink<ISpeechChallengeGetter>(ModKey.MakeFormKey(id));
        public static FormLink<ISpeechChallengeGetter> SFBGS001_MS01_SpeechChallenge_MoC => Construct(0x11e58);
        public static FormLink<ISpeechChallengeGetter> SFBGS001_MS01_SpeechChallenge_Mujeen => Construct(0x2afc4);
        public static FormLink<ISpeechChallengeGetter> SFBGS001_MQ03_MirekHardSC => Construct(0x337e2);
        public static FormLink<ISpeechChallengeGetter> SFBGS001_MQ03_MihaelSC => Construct(0x37520);
        public static FormLink<ISpeechChallengeGetter> SFBGS001_DazraZ01_AndrahSpeechChallenge => Construct(0x3cb01);
        public static FormLink<ISpeechChallengeGetter> SFBGS001_MS01_SpeechChallenge_BrotherOnamide => Construct(0x45168);
        public static FormLink<ISpeechChallengeGetter> SFBGS001_MQ04_GennaHardSC => Construct(0x455bc);
        public static FormLink<ISpeechChallengeGetter> SFBGS001_MQ04_GennaMediumSC => Construct(0x455bd);
        public static FormLink<ISpeechChallengeGetter> SFBGS001_MQ04_GennaEasySC => Construct(0x455be);
        public static FormLink<ISpeechChallengeGetter> SFBGS001_MQ04_EgboSC => Construct(0x455c0);
        public static FormLink<ISpeechChallengeGetter> SFBGS001_MQ04_BiancaMediumSC => Construct(0x455c2);
        public static FormLink<ISpeechChallengeGetter> SFBGS001_MQ04_VaericSC => Construct(0x5733a);
        public static FormLink<ISpeechChallengeGetter> SFBGS001_MS03_BorhalSpeechChallenge => Construct(0x75621);
        public static FormLink<ISpeechChallengeGetter> SFBGS001_MS03_AmilaSpeechChallenge => Construct(0x75622);
        public static FormLink<ISpeechChallengeGetter> SFBGS001_MS01_MadriSC => Construct(0xc216c);
        public static FormLink<ISpeechChallengeGetter> SFBGS001_MQ03_MirekEasySC => Construct(0xcb66e);
        public static FormLink<ISpeechChallengeGetter> SFBGS001_MS05_SCO => Construct(0xd7320);
        public static FormLink<ISpeechChallengeGetter> SFBGS001_MQ05_KaviilSpeechChallenge => Construct(0xdfa84);
        public static FormLink<ISpeechChallengeGetter> SFBGS001_MQ04_BiancaEasySC => Construct(0x1046c2);
        public static FormLink<ISpeechChallengeGetter> SFBGS001_COM_Barrett_SpeechChallenge_AngerScene => Construct(0x13242d);
        public static FormLink<ISpeechChallengeGetter> SFBGS001_COM_Andreja_SpeechChallenge_AngerScene => Construct(0x1325f0);
        public static FormLink<ISpeechChallengeGetter> SFBGS001_COM_SamCoe_SpeechChallenge_AngerScene => Construct(0x132707);
        public static FormLink<ISpeechChallengeGetter> SFBGS001_COM_SarahMorgan_SpeechChallenge_AngerScene => Construct(0x136f95);
    }
}
