// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class ShatteredSpace
{
    public static partial class SunPreset
    {
        private static FormLink<ISunPresetGetter> Construct(uint id) => new FormLink<ISunPresetGetter>(ModKey.MakeFormKey(id));
        public static FormLink<ISunPresetGetter> SFBGS001_SunPresetVaruun => Construct(0x5be07);
    }
}
