// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class ShatteredSpace
{
    public static partial class SurfacePatternStyle
    {
        private static FormLink<ISurfacePatternStyleGetter> Construct(uint id) => new FormLink<ISurfacePatternStyleGetter>(ModKey.MakeFormKey(id));
        public static FormLink<ISurfacePatternStyleGetter> SFBGS001PatternStyleFieldsDunesMesaPools => Construct(0x336bf);
    }
}
