// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class ShatteredSpace
{
    public static partial class VolumetricLighting
    {
        private static FormLink<IVolumetricLightingGetter> Construct(uint id) => new FormLink<IVolumetricLightingGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IVolumetricLightingGetter> SFBGS001_VLFogHeightUniqueVaruunkai => Construct(0x5be08);
        public static FormLink<IVolumetricLightingGetter> SFBGS001_VLFogHeightUniqueVaruunkai_VeryHeavy => Construct(0x148fe4);
    }
}
