// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class ShatteredSpace
{
    public static partial class Water
    {
        private static FormLink<IWaterGetter> Construct(uint id) => new FormLink<IWaterGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IWaterGetter> SFBGS001LC02_WaterPoisonPool => Construct(0xe8404);
        public static FormLink<IWaterGetter> SFBGS001_WaterMudBrown => Construct(0x11abad);
        public static FormLink<IWaterGetter> SFBGS001_WaterVaruunWok_On => Construct(0x158073);
        public static FormLink<IWaterGetter> SFBGS001_WaterVaruunWok_Off => Construct(0x158074);
    }
}
