// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class ShatteredSpace
{
    public static partial class WeatherSetting
    {
        private static FormLink<IWeatherSettingGetter> Construct(uint id) => new FormLink<IWeatherSettingGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IWeatherSettingGetter> SFBGS001_Weather_Clear_C0_NorthernLights => Construct(0x39bc4);
        public static FormLink<IWeatherSettingGetter> SFBGS001_Weather_Cloudy => Construct(0x5be0a);
        public static FormLink<IWeatherSettingGetter> SFBGS001_Weather_Clear_C1_NorthernLights => Construct(0xf8f64);
        public static FormLink<IWeatherSettingGetter> SFBGS001_Weather_Clear_C2_NorthernLights => Construct(0x10d6f2);
        public static FormLink<IWeatherSettingGetter> SFBGS001_Weather_Clear_C3_NorthernLights => Construct(0x10d6f4);
        public static FormLink<IWeatherSettingGetter> SFBGS001_Weather_CloudyEnergyStorm => Construct(0x112164);
    }
}
