// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class ShatteredSpace
{
    public static partial class Worldspace
    {
        private static FormLink<IWorldspaceGetter> Construct(uint id) => new FormLink<IWorldspaceGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IWorldspaceGetter> OverlayTestBlock02 => Construct(0x26ae);
        public static FormLink<IWorldspaceGetter> OverlayTestBlock01 => Construct(0x256f7);
        public static FormLink<IWorldspaceGetter> SFBGS001LandscapePOILakes01 => Construct(0x403ea);
        public static FormLink<IWorldspaceGetter> SFBGS001LandscapePOILakes02 => Construct(0x403ec);
        public static FormLink<IWorldspaceGetter> SFBGS001LandscapePOIMesas01 => Construct(0x403ee);
        public static FormLink<IWorldspaceGetter> SFBGS001LandscapePOIMesas03 => Construct(0x403f0);
        public static FormLink<IWorldspaceGetter> SFBGS001LandscapePOIMesas02 => Construct(0x403f2);
        public static FormLink<IWorldspaceGetter> SFBGS001LandscapePOIPools01 => Construct(0x403f4);
        public static FormLink<IWorldspaceGetter> SFBGS001LandscapePOIPools02 => Construct(0x403f6);
        public static FormLink<IWorldspaceGetter> SFBGS001LandscapePOIDunes01 => Construct(0x40422);
        public static FormLink<IWorldspaceGetter> SFBGS001LandscapePOIDunes02 => Construct(0x40424);
        public static FormLink<IWorldspaceGetter> SFBGS001LandscapePOIDunes03 => Construct(0x4076d);
        public static FormLink<IWorldspaceGetter> SFBGS001LandscapePOIDunes04 => Construct(0x4076f);
        public static FormLink<IWorldspaceGetter> SFBGS001LandscapePOIDunes05 => Construct(0x40771);
        public static FormLink<IWorldspaceGetter> SFBGS001DazraWorld => Construct(0x470cb);
        public static FormLink<IWorldspaceGetter> OverlayPOIBiomeGrottoFungal01 => Construct(0x9c0df);
        public static FormLink<IWorldspaceGetter> OverlayPOIBiomeRocksSharp02 => Construct(0x9c2ed);
        public static FormLink<IWorldspaceGetter> OverlayPOIBiomeRocksSharp03 => Construct(0x9c728);
        public static FormLink<IWorldspaceGetter> OverlayPOIBiomeRocksLayered01 => Construct(0x9d996);
        public static FormLink<IWorldspaceGetter> OverlayPOIBiomeRocksLayered02 => Construct(0x9de13);
        public static FormLink<IWorldspaceGetter> OverlayPOIBiomeRocksLayered03 => Construct(0x9e403);
        public static FormLink<IWorldspaceGetter> SFBGS001TestVaruunAssets => Construct(0xac211);
        public static FormLink<IWorldspaceGetter> SFBGS001OE09World => Construct(0xcb673);
        public static FormLink<IWorldspaceGetter> SFBGS001OE05World => Construct(0xe03a0);
        public static FormLink<IWorldspaceGetter> SFBGS001OE10World => Construct(0xe3d84);
        public static FormLink<IWorldspaceGetter> SFBGS001OE11World => Construct(0xe96b1);
        public static FormLink<IWorldspaceGetter> SFBGS001OE14World => Construct(0xec63a);
        public static FormLink<IWorldspaceGetter> SFBGS001OE12World => Construct(0xec7f5);
        public static FormLink<IWorldspaceGetter> SFBGS001OE07World => Construct(0xec7f6);
        public static FormLink<IWorldspaceGetter> SFBGS001OE01World => Construct(0xedf47);
        public static FormLink<IWorldspaceGetter> SFBGS001OE06World => Construct(0xf413b);
        public static FormLink<IWorldspaceGetter> SFBGS001OE17World => Construct(0xf4d89);
        public static FormLink<IWorldspaceGetter> SFBGS001OE15World => Construct(0xf4eac);
        public static FormLink<IWorldspaceGetter> SFBGS001OE19World => Construct(0xf4eae);
        public static FormLink<IWorldspaceGetter> SFBGS001OE02World => Construct(0xf5222);
        public static FormLink<IWorldspaceGetter> SFBGS001OE03World => Construct(0xf715e);
        public static FormLink<IWorldspaceGetter> SFBGS001OE18World => Construct(0xf9c07);
        public static FormLink<IWorldspaceGetter> SFBGS001OE08World => Construct(0x106fb6);
        public static FormLink<IWorldspaceGetter> SFBGS001OE16World => Construct(0x1081ed);
        public static FormLink<IWorldspaceGetter> SFBGS001OE20World => Construct(0x109ace);
        public static FormLink<IWorldspaceGetter> SFBGS001OE13World => Construct(0x10b199);
        public static FormLink<IWorldspaceGetter> SFBGS001OE04World => Construct(0x1116bf);
    }
}
