// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class ShatteredSpace
{
    public static partial class Zoom
    {
        private static FormLink<IZoomGetter> Construct(uint id) => new FormLink<IZoomGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IZoomGetter> SFBGS001_ZM_ParticleMachineGun => Construct(0xeee6);
        public static FormLink<IZoomGetter> SFBGS001_ZM_ParticleRocketlauncher_IronSights => Construct(0xef67);
        public static FormLink<IZoomGetter> SFBGS001_ZM_ParticleRocketlauncher_ReflexSight => Construct(0xef68);
        public static FormLink<IZoomGetter> SFBGS001_ZM_ParticleRocketlauncher_ShortScope => Construct(0xef69);
    }
}
