// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class Starfield
{
    public static partial class AddonNode
    {
        private static FormLink<IAddonNodeGetter> Construct(uint id) => new FormLink<IAddonNodeGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IAddonNodeGetter> LightNodeShipLandingLightSpot => Construct(0x6695);
        public static FormLink<IAddonNodeGetter> LightNodeShipLandingLightFill => Construct(0x6696);
        public static FormLink<IAddonNodeGetter> MPSShipDustKickup => Construct(0x7d8f);
        public static FormLink<IAddonNodeGetter> MPSShipDustKickupFire => Construct(0x7d90);
        public static FormLink<IAddonNodeGetter> MPSMetalSparks02 => Construct(0xd01e);
        public static FormLink<IAddonNodeGetter> MPSStoneImpactDust02 => Construct(0xd01f);
        public static FormLink<IAddonNodeGetter> MPSStoneImpactDebris => Construct(0xd020);
        public static FormLink<IAddonNodeGetter> MPSGenImpactSmallBits => Construct(0xd021);
        public static FormLink<IAddonNodeGetter> MPSSmokeDustGeneric => Construct(0xd022);
        public static FormLink<IAddonNodeGetter> MPSDirtImpactDebris01 => Construct(0xd023);
        public static FormLink<IAddonNodeGetter> MPSDirtImpactDust02 => Construct(0xd024);
        public static FormLink<IAddonNodeGetter> MPSSmokeDustDrift => Construct(0xd025);
        public static FormLink<IAddonNodeGetter> MPSSmokeDustStone => Construct(0xd026);
        public static FormLink<IAddonNodeGetter> MPSMetalImpactSparks => Construct(0xd027);
        public static FormLink<IAddonNodeGetter> MPSLaserImpact => Construct(0x11f2a);
        public static FormLink<IAddonNodeGetter> MPSLaserImpactSparks => Construct(0x11f2b);
        public static FormLink<IAddonNodeGetter> BoostPackFXAddOn => Construct(0x16726);
        public static FormLink<IAddonNodeGetter> MPSBoostPackSparks => Construct(0x16728);
        public static FormLink<IAddonNodeGetter> MPSBoostDustStone => Construct(0x1675b);
        public static FormLink<IAddonNodeGetter> LightNodeHeadLamp => Construct(0x16a7f);
        public static FormLink<IAddonNodeGetter> LightNodeHeadLampBounce => Construct(0x16a82);
        public static FormLink<IAddonNodeGetter> LightNodeGravJumpFlash => Construct(0x16e15);
        public static FormLink<IAddonNodeGetter> LightNodeMineElevatorBounceLight => Construct(0x1cab4);
        public static FormLink<IAddonNodeGetter> LightNodeMineElevatorOverheadPointLight => Construct(0x1cab5);
        public static FormLink<IAddonNodeGetter> LightNodeMineElevatorOverheadSpot => Construct(0x1cab6);
        public static FormLink<IAddonNodeGetter> MPSLaserCutterSlag => Construct(0x21a4b);
        public static FormLink<IAddonNodeGetter> MPSLaserCutterSmoke => Construct(0x21a4c);
        public static FormLink<IAddonNodeGetter> MPSLaserCutterCrossSparks => Construct(0x21a4d);
        public static FormLink<IAddonNodeGetter> MPSFootDirtBits01 => Construct(0x237a1);
        public static FormLink<IAddonNodeGetter> MPSFootDirtDust01 => Construct(0x237a2);
        public static FormLink<IAddonNodeGetter> MPSFootPADirtBits => Construct(0x237a4);
        public static FormLink<IAddonNodeGetter> MPSFootPADirtDust => Construct(0x237a5);
        public static FormLink<IAddonNodeGetter> BoostPackFXAddOnSmall => Construct(0x259e3);
        public static FormLink<IAddonNodeGetter> LightNodeShipHullBlue => Construct(0x288e3);
        public static FormLink<IAddonNodeGetter> LightNodeShipHullLight => Construct(0x2ae7b);
        public static FormLink<IAddonNodeGetter> MPSMeleeBladeSmokeDustMediumGeneric => Construct(0x2b91f);
        public static FormLink<IAddonNodeGetter> MPSImpactShipDebrisSmall => Construct(0x2ba3a);
        public static FormLink<IAddonNodeGetter> ShipJetFXAddOn => Construct(0x2f440);
        public static FormLink<IAddonNodeGetter> MPSImpactMeleeWoodSplintersMedium => Construct(0x3a3a6);
        public static FormLink<IAddonNodeGetter> MPSImpactMeleeSparksMedium => Construct(0x3a3a7);
        public static FormLink<IAddonNodeGetter> MpsDynamicShipDebrisSmoke => Construct(0x3f7d1);
        public static FormLink<IAddonNodeGetter> MpsDynamicShipDebrisTrail => Construct(0x4faca);
        public static FormLink<IAddonNodeGetter> LightNodeShipHullSpotlight => Construct(0x51868);
        public static FormLink<IAddonNodeGetter> MPSImpactShipDebrisFire => Construct(0x5192f);
        public static FormLink<IAddonNodeGetter> MpsDynamicShipDebrisBigSmoke => Construct(0x51c2a);
        public static FormLink<IAddonNodeGetter> MPSImpactMeleeBloodMedium => Construct(0x5c49a);
        public static FormLink<IAddonNodeGetter> MPSMist01 => Construct(0x6108b);
        public static FormLink<IAddonNodeGetter> MPSMistUpper => Construct(0x6108c);
        public static FormLink<IAddonNodeGetter> MPSImpactGenericBlood => Construct(0x6108d);
        public static FormLink<IAddonNodeGetter> PaperDollKeyAddOnLight => Construct(0x68e03);
        public static FormLink<IAddonNodeGetter> PaperDollFillAddOnLight => Construct(0x68e04);
        public static FormLink<IAddonNodeGetter> PaperDollRimAddOnLight => Construct(0x68e05);
        public static FormLink<IAddonNodeGetter> LightNodeShipHullBlueLG => Construct(0x6ab85);
        public static FormLink<IAddonNodeGetter> MPSShipDustKickupThin => Construct(0x753b9);
        public static FormLink<IAddonNodeGetter> LightNodeShipHullSpotBright => Construct(0xbb846);
        public static FormLink<IAddonNodeGetter> LightNodeShipHullRed => Construct(0xdd4b9);
        public static FormLink<IAddonNodeGetter> LightNodeShipHullGreen => Construct(0xea1b6);
        public static FormLink<IAddonNodeGetter> MPSFootGrassBits => Construct(0x140f0a);
        public static FormLink<IAddonNodeGetter> MPSFootLeavesBits => Construct(0x140f0b);
        public static FormLink<IAddonNodeGetter> MPSFootStoneDust => Construct(0x140f14);
        public static FormLink<IAddonNodeGetter> MPSFootPAStoneDust => Construct(0x140f1b);
        public static FormLink<IAddonNodeGetter> MPSFootStoneBits => Construct(0x140f24);
        public static FormLink<IAddonNodeGetter> MPSFootWaterSplash => Construct(0x140f44);
        public static FormLink<IAddonNodeGetter> MPSFootWaterSplashPA => Construct(0x140f47);
        public static FormLink<IAddonNodeGetter> LightNodeMagPulseLaserGobo => Construct(0x21a375);
        public static FormLink<IAddonNodeGetter> MPSLaserBeamMuzSmoke => Construct(0x24e770);
        public static FormLink<IAddonNodeGetter> LightNodeHeadLamp_Dummy => Construct(0x24ea2a);
        public static FormLink<IAddonNodeGetter> MPSFootDustSmall => Construct(0x250335);
        public static FormLink<IAddonNodeGetter> MPSFootRunDustSmall => Construct(0x250336);
        public static FormLink<IAddonNodeGetter> MPSFootPebblesSmall => Construct(0x250337);
        public static FormLink<IAddonNodeGetter> MPSFootRunPebblesSmall => Construct(0x250338);
        public static FormLink<IAddonNodeGetter> MPSOreCrackingSparks => Construct(0x25232e);
        public static FormLink<IAddonNodeGetter> MPSShipDustKickupFireSM => Construct(0x252add);
        public static FormLink<IAddonNodeGetter> spaceMine_Light => Construct(0x255eb7);
        public static FormLink<IAddonNodeGetter> MPSFootDustStoneSmall => Construct(0x260bce);
        public static FormLink<IAddonNodeGetter> MPSImpactMeleeDustMediumGeneric => Construct(0x27bbfc);
        public static FormLink<IAddonNodeGetter> MPSBoostPackSmoke => Construct(0x2bca65);
    }
}
