// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class Starfield
{
    public static partial class AnimationSoundTagSet
    {
        private static FormLink<IAnimationSoundTagSetGetter> Construct(uint id) => new FormLink<IAnimationSoundTagSetGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IAnimationSoundTagSetGetter> DRS_IndIntParSmWallA_MidFull_GateSm_ATS => Construct(0xcab2);
        public static FormLink<IAnimationSoundTagSetGetter> DRS_IndIntParSmWallA_MidFull_GateLg_ATS => Construct(0xcab3);
        public static FormLink<IAnimationSoundTagSetGetter> VEHCrimsonFleetShip => Construct(0x75ba8);
        public static FormLink<IAnimationSoundTagSetGetter> NPC_RobotModelA_Kaiser_ATS => Construct(0x89f2f);
        public static FormLink<IAnimationSoundTagSetGetter> WPN_AutoRivet_ATS => Construct(0x13d70c);
        public static FormLink<IAnimationSoundTagSetGetter> WPN_Arc_Welder_ATS => Construct(0x143670);
        public static FormLink<IAnimationSoundTagSetGetter> WPN_Novablast_ATS => Construct(0x149060);
        public static FormLink<IAnimationSoundTagSetGetter> NPC_RobotModelA_Heavy_ATS => Construct(0x1a41ac);
        public static FormLink<IAnimationSoundTagSetGetter> PlayerATS => Construct(0x1c40a1);
        public static FormLink<IAnimationSoundTagSetGetter> NPC_RobotModelA_Lithe_ATS => Construct(0x1c9899);
        public static FormLink<IAnimationSoundTagSetGetter> WPN_MagSniper_ATS => Construct(0x24a9d4);
    }
}
