// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class Starfield
{
    public static partial class BiomeMarker
    {
        private static FormLink<IBiomeMarkerGetter> Construct(uint id) => new FormLink<IBiomeMarkerGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IBiomeMarkerGetter> BiomeMarker_PlanetResourceGas => Construct(0x163cf);
        public static FormLink<IBiomeMarkerGetter> BiomeMarker_PlanetResourceLiquidNEW => Construct(0x163d1);
        public static FormLink<IBiomeMarkerGetter> BiomeMarker_PlanetResourceGas_INCORRECT_VERSION_OBSOLETE => Construct(0x21807);
        public static FormLink<IBiomeMarkerGetter> BiomeMarker_Predator_Interior => Construct(0x2ba81);
        public static FormLink<IBiomeMarkerGetter> BiomeMarker_Predator_NoLair_Solitary => Construct(0x2f14d);
        public static FormLink<IBiomeMarkerGetter> BiomeMarker_Predator_Ambush => Construct(0x5ad11);
        public static FormLink<IBiomeMarkerGetter> BiomeMarker_Predator_Apex_Ambush => Construct(0x5ad12);
        public static FormLink<IBiomeMarkerGetter> BiomeMarker_Predator_Apex => Construct(0x6e06b);
        public static FormLink<IBiomeMarkerGetter> BiomeMarker_Predator_FactionC_Only => Construct(0x74d72);
        public static FormLink<IBiomeMarkerGetter> BiomeMarker_Predator_FactionB_Only => Construct(0x74d73);
        public static FormLink<IBiomeMarkerGetter> BiomeMarker_Predator_FactionA_Only => Construct(0x74d74);
        public static FormLink<IBiomeMarkerGetter> BiomeMarker_Predator_FactionC_Apex => Construct(0x74d75);
        public static FormLink<IBiomeMarkerGetter> BiomeMarker_Predator_FactionB_Apex => Construct(0x74d76);
        public static FormLink<IBiomeMarkerGetter> BiomeMarker_Predator_FactionA_Apex => Construct(0x74d77);
        public static FormLink<IBiomeMarkerGetter> ENV_BiomeMarker_WetVent => Construct(0x93518);
        public static FormLink<IBiomeMarkerGetter> BiomeMarker_Predator_Flyer => Construct(0x13f72a);
        public static FormLink<IBiomeMarkerGetter> BiomeMarker_Predator_Interior_HerdLarge => Construct(0x140514);
        public static FormLink<IBiomeMarkerGetter> BiomeMarker_Predator_Interior_HerdMedium => Construct(0x140515);
        public static FormLink<IBiomeMarkerGetter> BiomeMarker_Predator_Interior_HerdSmall => Construct(0x140517);
        public static FormLink<IBiomeMarkerGetter> BiomeMarker_Predator_Interior_Solitary => Construct(0x140518);
        public static FormLink<IBiomeMarkerGetter> ENV_BiomeMarker_Flora_Cloud => Construct(0x155987);
        public static FormLink<IBiomeMarkerGetter> ENV_BiomeMarker_Spray => Construct(0x155989);
        public static FormLink<IBiomeMarkerGetter> ENV_BiomeMarker_Vent_GasResource => Construct(0x1562f3);
        public static FormLink<IBiomeMarkerGetter> ENV_BiomeMarker_Pool_Emitter => Construct(0x162801);
        public static FormLink<IBiomeMarkerGetter> ENV_BiomeMarker_Pool => Construct(0x166dc6);
        public static FormLink<IBiomeMarkerGetter> BiomeMarker_Prey_FactionC => Construct(0x166ed2);
        public static FormLink<IBiomeMarkerGetter> BiomeMarker_Prey_FactionB => Construct(0x166ed3);
        public static FormLink<IBiomeMarkerGetter> BiomeMarker_Prey_FactionA => Construct(0x166ed4);
        public static FormLink<IBiomeMarkerGetter> BiomeMarker_Predator_FactionC => Construct(0x166ed7);
        public static FormLink<IBiomeMarkerGetter> BiomeMarker_Predator_FactionB => Construct(0x166ed8);
        public static FormLink<IBiomeMarkerGetter> BiomeMarker_Predator_FactionA => Construct(0x166ed9);
        public static FormLink<IBiomeMarkerGetter> BiomeMarker_PlanetResourceLooseSolid => Construct(0x1734d9);
        public static FormLink<IBiomeMarkerGetter> BiomeMarker_Predator_Lair => Construct(0x179637);
        public static FormLink<IBiomeMarkerGetter> BiomeMarker_Prey_Lair => Construct(0x17963f);
        public static FormLink<IBiomeMarkerGetter> BiomeMarker_Prey_FactionA_HerdMedium => Construct(0x1b04aa);
        public static FormLink<IBiomeMarkerGetter> BiomeMarker_Predator_FactionA_HerdMedium => Construct(0x1b04ab);
        public static FormLink<IBiomeMarkerGetter> BiomeMarker_Prey_NoLair_Herd => Construct(0x1b9bd2);
        public static FormLink<IBiomeMarkerGetter> BiomeMarker_Prey_NoLair_HerdLarge => Construct(0x1b9bd6);
        public static FormLink<IBiomeMarkerGetter> BiomeMarker_Prey_NoLair_HerdMedium => Construct(0x1b9bd7);
        public static FormLink<IBiomeMarkerGetter> BiomeMarker_Prey_NoLair_HerdSmall => Construct(0x1b9bd8);
        public static FormLink<IBiomeMarkerGetter> BiomeMarker_Predator_NoLair => Construct(0x1bee3d);
        public static FormLink<IBiomeMarkerGetter> BiomeMarker_Predator_NoLair_Herd => Construct(0x1bee3e);
        public static FormLink<IBiomeMarkerGetter> BiomeMarker_Prey_NoLair => Construct(0x1bee3f);
        public static FormLink<IBiomeMarkerGetter> BiomeMarker_PlanetShrubSecondary => Construct(0x1c090b);
        public static FormLink<IBiomeMarkerGetter> BiomeMarker_Predator_HerdMedium => Construct(0x1e46ff);
        public static FormLink<IBiomeMarkerGetter> BiomeMarker_Prey_HerdMedium => Construct(0x1fa5c3);
        public static FormLink<IBiomeMarkerGetter> DONTUSEBiomeMarker_PlanetExotic => Construct(0x23be23);
        public static FormLink<IBiomeMarkerGetter> BiomeMarker_PlanetShrubPrimary => Construct(0x23cf65);
        public static FormLink<IBiomeMarkerGetter> BiomeMarker_PlanetRockSmall => Construct(0x23cf67);
        public static FormLink<IBiomeMarkerGetter> BiomeMarker_PlanetRockMedium => Construct(0x23cf68);
        public static FormLink<IBiomeMarkerGetter> BiomeMarker_PlanetRockLarge => Construct(0x23cf69);
        public static FormLink<IBiomeMarkerGetter> BiomeMarker_PlanetTree => Construct(0x23cf6a);
        public static FormLink<IBiomeMarkerGetter> BiomeMarker_PlanetResourceLooseLiquidGas => Construct(0x251817);
        public static FormLink<IBiomeMarkerGetter> BiomeMarker_Predator_NoFlier => Construct(0x257a4a);
        public static FormLink<IBiomeMarkerGetter> BiomeMarker_PlanetResourceSolid => Construct(0x26ba64);
        public static FormLink<IBiomeMarkerGetter> BiomeMarker_PlanetFlora => Construct(0x26ba65);
        public static FormLink<IBiomeMarkerGetter> BiomeMarker_Critter_Swimmer => Construct(0x276be1);
        public static FormLink<IBiomeMarkerGetter> BiomeMarker_PlanetResourceLooseLiquidGas_Small => Construct(0x287189);
        public static FormLink<IBiomeMarkerGetter> BiomeMarker_Prey_Solitary => Construct(0x2a4364);
        public static FormLink<IBiomeMarkerGetter> BiomeMarker_Predator_Solitary => Construct(0x2a4366);
        public static FormLink<IBiomeMarkerGetter> BiomeMarker_Predator => Construct(0x2cc9f3);
        public static FormLink<IBiomeMarkerGetter> BiomeMarker_Prey => Construct(0x2cc9f4);
        public static FormLink<IBiomeMarkerGetter> BiomeMarker_Critter => Construct(0x2cc9f6);
        public static FormLink<IBiomeMarkerGetter> BiomeMarker_Predator_HerdLarge => Construct(0x2cc9fb);
        public static FormLink<IBiomeMarkerGetter> BiomeMarker_Predator_HerdSmall => Construct(0x2cc9fc);
        public static FormLink<IBiomeMarkerGetter> BiomeMarker_Prey_HerdLarge => Construct(0x2cc9fd);
        public static FormLink<IBiomeMarkerGetter> BiomeMarker_Prey_HerdSmall => Construct(0x2cc9fe);
        public static FormLink<IBiomeMarkerGetter> BiomeMarker_Prey_Swimmer => Construct(0x37cebb);
        public static FormLink<IBiomeMarkerGetter> BiomeMarker_Predator_Swimmer => Construct(0x37cebc);
        public static FormLink<IBiomeMarkerGetter> BiomeMarker_Prey_Swimmer_Herd => Construct(0x37cec0);
        public static FormLink<IBiomeMarkerGetter> BiomeMarker_Predator_Swimmer_Herd => Construct(0x37cec2);
    }
}
