// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class Starfield
{
    public static partial class BodyPartData
    {
        private static FormLink<IBodyPartDataGetter> Construct(uint id) => new FormLink<IBodyPartDataGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IBodyPartDataGetter> DefaultBodyPartData => Construct(0x1d);
        public static FormLink<IBodyPartDataGetter> HumanBodyPartData => Construct(0x3481);
        public static FormLink<IBodyPartDataGetter> ModelABodyPartData => Construct(0x562c);
        public static FormLink<IBodyPartDataGetter> HopperABodyPartData => Construct(0xb09b);
        public static FormLink<IBodyPartDataGetter> ModelSBodyPartData => Construct(0x130f3);
        public static FormLink<IBodyPartDataGetter> ChildBodyPartData => Construct(0x15511);
        public static FormLink<IBodyPartDataGetter> OctopedeABodyPartData => Construct(0x15b1a);
        public static FormLink<IBodyPartDataGetter> CritterBodyPartData => Construct(0x176b9);
        public static FormLink<IBodyPartDataGetter> FloaterABodyPartData => Construct(0x2e9ba);
        public static FormLink<IBodyPartDataGetter> SecurityCameraBodyPartData => Construct(0x4770d);
        public static FormLink<IBodyPartDataGetter> QuadrupedABodyPartData => Construct(0x50300);
        public static FormLink<IBodyPartDataGetter> EyeBotBodyPartData => Construct(0xb268f);
        public static FormLink<IBodyPartDataGetter> BallisticTurretBodyPartData => Construct(0x1cc9bb);
        public static FormLink<IBodyPartDataGetter> LaserTurretBodyPartData => Construct(0x1ea1e5);
        public static FormLink<IBodyPartDataGetter> TerrormorphBodyPartData => Construct(0x21e736);
        public static FormLink<IBodyPartDataGetter> MiniBotABodyPartData => Construct(0x227704);
        public static FormLink<IBodyPartDataGetter> BipedABodyPartData => Construct(0x243bfb);
        public static FormLink<IBodyPartDataGetter> FlyerABodyPartData => Construct(0x243e10);
        public static FormLink<IBodyPartDataGetter> QuadrupedCBodyPartData => Construct(0x261646);
        public static FormLink<IBodyPartDataGetter> SwimmerABodyPartData => Construct(0x26aecb);
        public static FormLink<IBodyPartDataGetter> MantaABodyPartData => Construct(0x28b3e3);
        public static FormLink<IBodyPartDataGetter> LarvaABodyPartData => Construct(0x29a908);
        public static FormLink<IBodyPartDataGetter> MantidABodyPartData => Construct(0x29f8a6);
        public static FormLink<IBodyPartDataGetter> ParasiteABodyPartData => Construct(0x2aad57);
        public static FormLink<IBodyPartDataGetter> HumanCrowdBodyPartData => Construct(0x2bbc0a);
        public static FormLink<IBodyPartDataGetter> QuadrupedBBodyPartData => Construct(0x2ccaa9);
        public static FormLink<IBodyPartDataGetter> HexapodABodyPartData => Construct(0x2ccaab);
    }
}
