// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class Starfield
{
    public static partial class Climate
    {
        private static FormLink<IClimateGetter> Construct(uint id) => new FormLink<IClimateGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IClimateGetter> DefaultClimate => Construct(0x15f);
        public static FormLink<IClimateGetter> ClimateNoneFrozen => Construct(0xac30);
        public static FormLink<IClimateGetter> ClimateUniqueRedMile => Construct(0x2139c);
        public static FormLink<IClimateGetter> ClimateUniqueLightingTestGI02 => Construct(0x334d1);
        public static FormLink<IClimateGetter> ClimateUniqueVenus => Construct(0x515cb);
        public static FormLink<IClimateGetter> ClimateUniqueEarth => Construct(0x64d14);
        public static FormLink<IClimateGetter> ClimateUniqueLC135_ScorpiusPuzzle => Construct(0x8bdaa);
        public static FormLink<IClimateGetter> ClimateUniqueVecteraBase => Construct(0x9eaa3);
        public static FormLink<IClimateGetter> ClimateUniqueKreetBase => Construct(0x9eaa4);
        public static FormLink<IClimateGetter> ClimateUniqueVecteraDesertRocky => Construct(0xa86de);
        public static FormLink<IClimateGetter> ClimateUniqueKreetVolcanic => Construct(0xaa386);
        public static FormLink<IClimateGetter> ClimateUniqueGagarin => Construct(0xccbfa);
        public static FormLink<IClimateGetter> ClimateUniqueTitan => Construct(0xf3d3b);
        public static FormLink<IClimateGetter> ClimateUniqueHomestead => Construct(0xf762b);
        public static FormLink<IClimateGetter> ClimateUniquePluto => Construct(0x10c498);
        public static FormLink<IClimateGetter> ClimateUniqueMercury => Construct(0x10c499);
        public static FormLink<IClimateGetter> ClimateWetlands01 => Construct(0x13ec20);
        public static FormLink<IClimateGetter> ClimateOcean01 => Construct(0x13ec21);
        public static FormLink<IClimateGetter> ClimateMountains01 => Construct(0x13ec22);
        public static FormLink<IClimateGetter> ClimateHills01 => Construct(0x13ec23);
        public static FormLink<IClimateGetter> ClimateFrozen01 => Construct(0x13ec24);
        public static FormLink<IClimateGetter> ClimateCratered01 => Construct(0x13ec25);
        public static FormLink<IClimateGetter> ClimateCanyons01 => Construct(0x13ec26);
        public static FormLink<IClimateGetter> ClimateArchipelago01 => Construct(0x13ec27);
        public static FormLink<IClimateGetter> ClimateVolcanicWorn01 => Construct(0x13ec28);
        public static FormLink<IClimateGetter> ClimateVolcanicRough01 => Construct(0x13ec29);
        public static FormLink<IClimateGetter> ClimateForestTropical01 => Construct(0x13ec2a);
        public static FormLink<IClimateGetter> ClimateForestConiferous01 => Construct(0x13ec2b);
        public static FormLink<IClimateGetter> ClimateForestDecidous01 => Construct(0x13ec2c);
        public static FormLink<IClimateGetter> ClimateDesertSandy01 => Construct(0x13ec2d);
        public static FormLink<IClimateGetter> ClimateSavanna01 => Construct(0x13ec2e);
        public static FormLink<IClimateGetter> ClimateDesertRocky01 => Construct(0x13f0ca);
        public static FormLink<IClimateGetter> ClimateUniqueNiira => Construct(0x174e32);
        public static FormLink<IClimateGetter> ClimateUniqueSuvorov => Construct(0x1e094d);
        public static FormLink<IClimateGetter> ClimateUniqueNewAtlantis => Construct(0x24e982);
        public static FormLink<IClimateGetter> ClimateUniqueNeon => Construct(0x2ab909);
        public static FormLink<IClimateGetter> ClimateUniqueKreetFrozen => Construct(0x2edea1);
        public static FormLink<IClimateGetter> ClimateUniqueVecteraFrozen => Construct(0x2edea2);
        public static FormLink<IClimateGetter> ClimateUniqueEarthFrozen => Construct(0x2edea3);
        public static FormLink<IClimateGetter> ClimateUniqueNiiraFrozen => Construct(0x2edea4);
        public static FormLink<IClimateGetter> ClimateUniqueCydoniaFrozen => Construct(0x2edea5);
        public static FormLink<IClimateGetter> ClimateUniqueTitanFrozen => Construct(0x2edea6);
        public static FormLink<IClimateGetter> ClimateUniqueCydonia => Construct(0x310db1);
        public static FormLink<IClimateGetter> ClimateUniqueParadiso => Construct(0x3319de);
        public static FormLink<IClimateGetter> ClimateUniqueAkila => Construct(0x3319e1);
        public static FormLink<IClimateGetter> ClimateUniqueLondinion => Construct(0x34e83e);
        public static FormLink<IClimateGetter> ClimateNone => Construct(0x3d248e);
    }
}
