// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class Starfield
{
    public static partial class Clouds
    {
        private static FormLink<ICloudsGetter> Construct(uint id) => new FormLink<ICloudsGetter>(ModKey.MakeFormKey(id));
        public static FormLink<ICloudsGetter> CloudsPartlyCloudy03 => Construct(0xb7903);
        public static FormLink<ICloudsGetter> CloudsPartlyCloudy04 => Construct(0xb80d0);
        public static FormLink<ICloudsGetter> CloudsPartlyCloudy02 => Construct(0xd91f5);
        public static FormLink<ICloudsGetter> CloudsOvercast01 => Construct(0xd91f6);
        public static FormLink<ICloudsGetter> CloudsCloudy02 => Construct(0xd91f7);
        public static FormLink<ICloudsGetter> CloudsCloudy03 => Construct(0x117a28);
        public static FormLink<ICloudsGetter> CloudsFog02 => Construct(0x117a34);
        public static FormLink<ICloudsGetter> CloudsThunderstorm01 => Construct(0x11d9e6);
        public static FormLink<ICloudsGetter> CloudsRain01 => Construct(0x11d9e7);
        public static FormLink<ICloudsGetter> CloudsFog01 => Construct(0x11d9e8);
        public static FormLink<ICloudsGetter> CloudsSnow01 => Construct(0x12121f);
        public static FormLink<ICloudsGetter> CloudsSandstorm01 => Construct(0x133b12);
        public static FormLink<ICloudsGetter> CloudsOvercast02 => Construct(0x134e2a);
        public static FormLink<ICloudsGetter> CloudsPartlyCloudy01 => Construct(0x13786e);
        public static FormLink<ICloudsGetter> CloudsCloudy01 => Construct(0x13786f);
        public static FormLink<ICloudsGetter> CloudsPartlyCloudy05 => Construct(0x39fcaa);
    }
}
