// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class Starfield
{
    public static partial class ColorRecord
    {
        private static FormLink<IColorRecordGetter> Construct(uint id) => new FormLink<IColorRecordGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IColorRecordGetter> ShipBuilderRecentColor12 => Construct(0x5b97e);
        public static FormLink<IColorRecordGetter> ShipBuilderRecentColor11 => Construct(0x5b97f);
        public static FormLink<IColorRecordGetter> ShipBuilderRecentColor10 => Construct(0x5b980);
        public static FormLink<IColorRecordGetter> ShipBuilderRecentColor09 => Construct(0x5b981);
        public static FormLink<IColorRecordGetter> ShipBuilderRecentColor08 => Construct(0x5b982);
        public static FormLink<IColorRecordGetter> ShipBuilderRecentColor07 => Construct(0x5b983);
        public static FormLink<IColorRecordGetter> ShipBuilderRecentColor06 => Construct(0x5b984);
        public static FormLink<IColorRecordGetter> ShipBuilderRecentColor05 => Construct(0x5b985);
        public static FormLink<IColorRecordGetter> ShipBuilderRecentColor04 => Construct(0x5b986);
        public static FormLink<IColorRecordGetter> ShipBuilderRecentColor03 => Construct(0x5b987);
        public static FormLink<IColorRecordGetter> ShipBuilderRecentColor01 => Construct(0x5b988);
        public static FormLink<IColorRecordGetter> ShipBuilderRecentColor02 => Construct(0x5b989);
    }
}
