// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class Starfield
{
    public static partial class DefaultObjectManager
    {
        private static FormLink<IDefaultObjectManagerGetter> Construct(uint id) => new FormLink<IDefaultObjectManagerGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IDefaultObjectManagerGetter> _DefaultObjectManager => Construct(0x800);
    }
}
