// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class Starfield
{
    public static partial class DialogBranch
    {
        private static FormLink<IDialogBranchGetter> Construct(uint id) => new FormLink<IDialogBranchGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IDialogBranchGetter> CREW_EliteCrew_AdoringFanNewBranch0 => Construct(0x259f1);
        public static FormLink<IDialogBranchGetter> COM_SarahMorganCSBranch => Construct(0x1091a);
        public static FormLink<IDialogBranchGetter> DialogueCrimsonFleetNewBranch0DUPLICATE003DUPLICATE000 => Construct(0x1e1f44);
        public static FormLink<IDialogBranchGetter> DialogueUCNewAtlantis_DoctorBranch => Construct(0x337dc8);
        public static FormLink<IDialogBranchGetter> CREW_EliteCrew_GideonAker_Branch => Construct(0x27071e);
        public static FormLink<IDialogBranchGetter> DialogueCFTheKey_DoctorBranch => Construct(0x133c03);
        public static FormLink<IDialogBranchGetter> DialogueGenericPlayer_Branch => Construct(0x303974);
        public static FormLink<IDialogBranchGetter> ZZZCKrietzTestQuestBranchTwo => Construct(0xc585b);
        public static FormLink<IDialogBranchGetter> ZZZCKrietzTestQuestBranch => Construct(0x1d207a);
        public static FormLink<IDialogBranchGetter> CREW_EliteCrew_SophiaGrace_Branch => Construct(0x14794c);
        public static FormLink<IDialogBranchGetter> CREW_EliteCrew_BettyHowser_Branch => Construct(0x14e855);
        public static FormLink<IDialogBranchGetter> CREW_EliteCrew_OmariHassan_Branch => Construct(0x1593f3);
        public static FormLink<IDialogBranchGetter> CREW_EliteCrew_AndromedaKepler_Branch => Construct(0x16b3c3);
        public static FormLink<IDialogBranchGetter> CREW_EliteCrew_MickeyCaviar_Branch => Construct(0x16d166);
        public static FormLink<IDialogBranchGetter> CREW_EliteCrew_Ezekiel_Branch => Construct(0x17a85b);
        public static FormLink<IDialogBranchGetter> CREW_EliteCrew_OtherPlayer_Branch => Construct(0x185a79);
        public static FormLink<IDialogBranchGetter> CREW_EliteCrew_CoraCoe_Branch => Construct(0x187a26);
        public static FormLink<IDialogBranchGetter> SQ_Doctors_Branch => Construct(0x189603);
        public static FormLink<IDialogBranchGetter> MQ302B_Bridge_IntroLines => Construct(0x125452);
        public static FormLink<IDialogBranchGetter> City_GG_Connections_Branch => Construct(0x143490);
        public static FormLink<IDialogBranchGetter> CREW_EliteCrew_AmeliaEarhart_Branch => Construct(0x18e131);
        public static FormLink<IDialogBranchGetter> CREW_EliteCrew_RafaelAguerro_Branch => Construct(0x193279);
        public static FormLink<IDialogBranchGetter> CREW_EliteCrew_ErickvonPrice_Branch => Construct(0x19657f);
        public static FormLink<IDialogBranchGetter> CREW_EliteCrew_AutumnMacMillan_Branch => Construct(0x19aa69);
        public static FormLink<IDialogBranchGetter> DialogueTerrormorphThrallHuman_TakenOver_Start => Construct(0x33900a);
        public static FormLink<IDialogBranchGetter> CREW_EliteCrew_MoaraOtero_Branch => Construct(0x1a4284);
        public static FormLink<IDialogBranchGetter> CREW_EliteCrew_Lin_Branch => Construct(0x1a8c6f);
        public static FormLink<IDialogBranchGetter> CREW_EliteCrew_Heller_Branch => Construct(0x1ad206);
        public static FormLink<IDialogBranchGetter> CREW_EliteCrew_Hadrian_Branch => Construct(0x1b3a83);
        public static FormLink<IDialogBranchGetter> DialogueGenericSpacersNewBranch0 => Construct(0x1b9fb0);
        public static FormLink<IDialogBranchGetter> CREW_EliteCrew_MathisCastillo_Branch => Construct(0x1bebf6);
        public static FormLink<IDialogBranchGetter> DialogueFCClinic_DoctorBranch => Construct(0x14a803);
        public static FormLink<IDialogBranchGetter> FFParadisoZ04_Guest_Say => Construct(0x1c3892);
        public static FormLink<IDialogBranchGetter> RQ_Dialogue_Branch => Construct(0x1c3959);
        public static FormLink<IDialogBranchGetter> CREW_EliteCrew_LyleBrewer_Branch => Construct(0x1c26c7);
        public static FormLink<IDialogBranchGetter> COM_Barrett_CustomTopics => Construct(0x1c6e18);
        public static FormLink<IDialogBranchGetter> CREW_EliteCrew_DaniGarcia_Branch => Construct(0x1ccaf9);
        public static FormLink<IDialogBranchGetter> SQ_Captive_FreedPrisonerGratitude => Construct(0x1c395c);
        public static FormLink<IDialogBranchGetter> CREW_EliteCrew_RosieTannehill_Branch => Construct(0x1d6355);
        public static FormLink<IDialogBranchGetter> CREW_EliteCrew_JessamineGriffin_Branch => Construct(0x1d8991);
        public static FormLink<IDialogBranchGetter> CREW_EliteCrew_SimeonBankowski_Branch => Construct(0x1ddaf2);
        public static FormLink<IDialogBranchGetter> CREW_EliteCrew_MarikaBoros_Branch => Construct(0x1e5c50);
        public static FormLink<IDialogBranchGetter> BE_City_CY_RedTape02_Ship_Branch => Construct(0xf4281);
        public static FormLink<IDialogBranchGetter> BE_City_CY_RedTape02_Captain_TimesUpBranch => Construct(0xf428b);
        public static FormLink<IDialogBranchGetter> FFConstantZ06_Janet_TopicBranch => Construct(0x211772);
        public static FormLink<IDialogBranchGetter> DialogueFCAkilaCity_HotelBranch => Construct(0xa6bf6);
        public static FormLink<IDialogBranchGetter> City_CY_Psych01_LeonaBranch => Construct(0x2020f7);
        public static FormLink<IDialogBranchGetter> City_CY_Runaway01_0415_Natan_ApproachBranch => Construct(0x1ef706);
        public static FormLink<IDialogBranchGetter> DialogueFCNeon_HotelBranch => Construct(0x33a8f9);
        public static FormLink<IDialogBranchGetter> City_CY_RedTape03_Hank_Branch => Construct(0xed7d6);
        public static FormLink<IDialogBranchGetter> COM_AndrejaCSBranch => Construct(0x23b32f);
        public static FormLink<IDialogBranchGetter> UC_TerrormorphSupportQuest_Branch => Construct(0x273bfa);
        public static FormLink<IDialogBranchGetter> DialogueNewHomestead_Doctors_Branch => Construct(0x33a1b7);
        public static FormLink<IDialogBranchGetter> DialogueFreestarRangers_DoctorBranch => Construct(0x997e4);
        public static FormLink<IDialogBranchGetter> DialogueCydonia_Trevor_City_CY_Runaway01_Branch => Construct(0xccf96);
        public static FormLink<IDialogBranchGetter> DialogueCydonia_Psych01_Tia_Branch => Construct(0xe8d39);
        public static FormLink<IDialogBranchGetter> DialogueCydonia_Doctors_Branch => Construct(0x33a1b6);
        public static FormLink<IDialogBranchGetter> CREW_EliteCrew_Vasco_Branch => Construct(0x1a1cb8);
        public static FormLink<IDialogBranchGetter> MS06_2400_AminBranch => Construct(0x1860a9);
        public static FormLink<IDialogBranchGetter> DialogueParadiso_Hotelier_Branch => Construct(0x33a1b9);
        public static FormLink<IDialogBranchGetter> COM_CompanionCSBranch => Construct(0x26bdb2);
        public static FormLink<IDialogBranchGetter> DialogueECSConstant_Doctors_Branch => Construct(0x33a1b8);
        public static FormLink<IDialogBranchGetter> MQ207C_Support_BarakovaBranch => Construct(0x180f6d);
        public static FormLink<IDialogBranchGetter> DialogueSeokguhSyndicateNewBranch => Construct(0x1e1f4a);
        public static FormLink<IDialogBranchGetter> DialogueCrucible_HotelBranch => Construct(0xa6c0d);
        public static FormLink<IDialogBranchGetter> DialogueGenericEclipticANDSoldiersNewBranch0DUPLICATE003DUPLICATE000 => Construct(0x1e1f49);
        public static FormLink<IDialogBranchGetter> RI03_SayCustomLines => Construct(0x23de17);
        public static FormLink<IDialogBranchGetter> UC05_EmbassySupportQuestBranch => Construct(0x21ca55);
        public static FormLink<IDialogBranchGetter> DialogueHopeTown_HotelBranch => Construct(0xa6bf4);
        public static FormLink<IDialogBranchGetter> UC04_Branch => Construct(0x12314);
        public static FormLink<IDialogBranchGetter> UC02_PerrysMeatsSupportQuest_Branch => Construct(0x26ffab);
        public static FormLink<IDialogBranchGetter> DialogueRedMile_Hotelier_Branch => Construct(0x33a1be);
        public static FormLink<IDialogBranchGetter> DialogueGenericCitizensNewBranch0DUPLICATE003DUPLICATE000 => Construct(0x1e1f45);
        public static FormLink<IDialogBranchGetter> DialogueGenericScumNewBranch0DUPLICATE003DUPLICATE000 => Construct(0x1e1f46);
        public static FormLink<IDialogBranchGetter> DialogueGenericGuardsNewBranch0DUPLICATE003DUPLICATE000 => Construct(0x1e1f47);
        public static FormLink<IDialogBranchGetter> DialogueGenericStarbornNewBranch0DUPLICATE003DUPLICATE000 => Construct(0x1e1f48);
        public static FormLink<IDialogBranchGetter> DialogueUCFactionBranch => Construct(0x17f933);
        public static FormLink<IDialogBranchGetter> SQ_PEO_SustenanceDialogueBranch => Construct(0x2ef263);
        public static FormLink<IDialogBranchGetter> SQ_Hotelier_Branch => Construct(0x32af94);
    }
}
