// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class Starfield
{
    public static partial class EffectShader
    {
        private static FormLink<IEffectShaderGetter> Construct(uint id) => new FormLink<IEffectShaderGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IEffectShaderGetter> OreMineFXS => Construct(0x1914f);
        public static FormLink<IEffectShaderGetter> CargoDropGlowFXS => Construct(0x1c06e);
        public static FormLink<IEffectShaderGetter> GassyFXS => Construct(0x22851);
        public static FormLink<IEffectShaderGetter> ArtifactPower_PrecognitionImpactFXS => Construct(0x25267);
        public static FormLink<IEffectShaderGetter> TerrorMorph_MentalInfluenceNPC_FXS => Construct(0x2dfa4);
        public static FormLink<IEffectShaderGetter> Starborn_EntryShader => Construct(0x2e54d);
        public static FormLink<IEffectShaderGetter> Starborn_DeathShader => Construct(0x2e550);
        public static FormLink<IEffectShaderGetter> ArtifactPower_ParallelSelfFXS => Construct(0x49dae);
        public static FormLink<IEffectShaderGetter> ArtifactPower_ParallelSelfCastingFXS => Construct(0x49db0);
        public static FormLink<IEffectShaderGetter> ShipAbility_CloakingFXS => Construct(0x5d4ce);
        public static FormLink<IEffectShaderGetter> Damage_Fire01_FXShader => Construct(0x622aa);
        public static FormLink<IEffectShaderGetter> ArtifactPower_EarthboundFXS => Construct(0x714ca);
        public static FormLink<IEffectShaderGetter> RadioActiveLegendary_FXS => Construct(0x7917c);
        public static FormLink<IEffectShaderGetter> LacerateLegendary_FXS => Construct(0x79193);
        public static FormLink<IEffectShaderGetter> PoisonLegendary_FXS => Construct(0xc4b7d);
        public static FormLink<IEffectShaderGetter> Crit_FireDisolve_FXS => Construct(0xd16ef);
        public static FormLink<IEffectShaderGetter> ArtifactPower_QuantumEssenceFXS => Construct(0xef400);
        public static FormLink<IEffectShaderGetter> IncendiaryLegendary_FXS => Construct(0xf20f9);
        public static FormLink<IEffectShaderGetter> StarbornPuzzle_PlayerFXS => Construct(0x13d708);
        public static FormLink<IEffectShaderGetter> ArtifactPower_InnerDemonFXS => Construct(0x141504);
        public static FormLink<IEffectShaderGetter> ArtifactPower_ReactiveShieldFXS => Construct(0x1454e1);
        public static FormLink<IEffectShaderGetter> ArtifactPower_LifeForcedFXS => Construct(0x15c59d);
        public static FormLink<IEffectShaderGetter> ArtifactPower_MoonFormFXS => Construct(0x167ae5);
        public static FormLink<IEffectShaderGetter> ArtifactPower_AlienReAnimationFXS => Construct(0x1722c4);
        public static FormLink<IEffectShaderGetter> ArtifactPower_VoidFormFXS => Construct(0x179dc2);
        public static FormLink<IEffectShaderGetter> ArtifactPower_SunlessSpaceFrozenFXS => Construct(0x199e21);
        public static FormLink<IEffectShaderGetter> _RENAME_TestGrantShader => Construct(0x1a3b8c);
        public static FormLink<IEffectShaderGetter> TerrorMorph_MentalInfluenceSelf_FXS => Construct(0x1e0948);
        public static FormLink<IEffectShaderGetter> ArtifactPower_SolarFlareBurningFXS => Construct(0x2452e0);
        public static FormLink<IEffectShaderGetter> CritLaserDisintegration => Construct(0x26319b);
        public static FormLink<IEffectShaderGetter> NeuralDisruptorFXS => Construct(0x2636b6);
        public static FormLink<IEffectShaderGetter> Armor_VoidFormFXS => Construct(0x286a48);
        public static FormLink<IEffectShaderGetter> ArtifactPower_VoidInvisibleFXS => Construct(0x28e74f);
        public static FormLink<IEffectShaderGetter> ArtifactPowerSenseStarStuffStarbornFXS => Construct(0x290814);
        public static FormLink<IEffectShaderGetter> ReconTargetingFXS => Construct(0x29591b);
        public static FormLink<IEffectShaderGetter> ArtifactPowerParticleBeamFXS => Construct(0x29634d);
        public static FormLink<IEffectShaderGetter> AnnihilatorLegendary_FXS => Construct(0x2bce34);
        public static FormLink<IEffectShaderGetter> StunHitShader_FXS => Construct(0x2c43d5);
        public static FormLink<IEffectShaderGetter> ArtifactPowerSenseStarStuffFXS => Construct(0x2c9404);
        public static FormLink<IEffectShaderGetter> GrenadeTrajectoryEndPointFXS => Construct(0x2d88d9);
        public static FormLink<IEffectShaderGetter> StarbornShipDestruction_DissolveFXS => Construct(0x2dbea2);
        public static FormLink<IEffectShaderGetter> Power_AbsorbQuantumEssenceFXS => Construct(0x2dc0c8);
        public static FormLink<IEffectShaderGetter> CorrosiveLegendary_FXS => Construct(0x2e1bae);
        public static FormLink<IEffectShaderGetter> CCT_SignalGlowFXS => Construct(0x3bdbb6);
        public static FormLink<IEffectShaderGetter> RegenHealthFXS => Construct(0x3befb0);
        public static FormLink<IEffectShaderGetter> GhostFXS => Construct(0x3bf230);
        public static FormLink<IEffectShaderGetter> ArtifactPower_SupernovaFXS => Construct(0x3cd809);
    }
}
