// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class Starfield
{
    public static partial class EquipType
    {
        private static FormLink<IEquipTypeGetter> Construct(uint id) => new FormLink<IEquipTypeGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IEquipTypeGetter> DefaultSlot => Construct(0x46);
        public static FormLink<IEquipTypeGetter> RightHand => Construct(0x13f42);
        public static FormLink<IEquipTypeGetter> LeftHand => Construct(0x13f43);
        public static FormLink<IEquipTypeGetter> EitherHand => Construct(0x13f44);
        public static FormLink<IEquipTypeGetter> BothHands => Construct(0x13f45);
        public static FormLink<IEquipTypeGetter> MiddleHand => Construct(0x1a02f);
        public static FormLink<IEquipTypeGetter> Voice => Construct(0x25bee);
        public static FormLink<IEquipTypeGetter> Potion => Construct(0x35698);
        public static FormLink<IEquipTypeGetter> BothHandsLeftOptional => Construct(0x4334d);
        public static FormLink<IEquipTypeGetter> LeftHandOptional => Construct(0x4334e);
        public static FormLink<IEquipTypeGetter> OTHER => Construct(0x4334f);
        public static FormLink<IEquipTypeGetter> GrenadeSlot => Construct(0x46aac);
        public static FormLink<IEquipTypeGetter> RightLeg => Construct(0x49be1);
        public static FormLink<IEquipTypeGetter> LeftLeg => Construct(0x49be2);
        public static FormLink<IEquipTypeGetter> BothLegs => Construct(0x49be4);
        public static FormLink<IEquipTypeGetter> CreatureHead => Construct(0x56cbf);
        public static FormLink<IEquipTypeGetter> CreatureTail => Construct(0x56cc0);
        public static FormLink<IEquipTypeGetter> AltAttackSlot1 => Construct(0x136255);
        public static FormLink<IEquipTypeGetter> AltAttackSlot2 => Construct(0x136256);
        public static FormLink<IEquipTypeGetter> CreatureRangedMouth2 => Construct(0x1f6808);
        public static FormLink<IEquipTypeGetter> CreatureRangedTail => Construct(0x1f6809);
        public static FormLink<IEquipTypeGetter> CreatureRangedMouth1 => Construct(0x1f680a);
        public static FormLink<IEquipTypeGetter> CreatureClaw => Construct(0x29eaeb);
        public static FormLink<IEquipTypeGetter> CreatureBase => Construct(0x29eaec);
        public static FormLink<IEquipTypeGetter> CreatureMouth => Construct(0x2d01c9);
    }
}
