// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class Starfield
{
    public static partial class FacialExpression
    {
        private static FormLink<IFacialExpressionGetter> Construct(uint id) => new FormLink<IFacialExpressionGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IFacialExpressionGetter> facialExpression_Afraid => Construct(0x20d3a0);
        public static FormLink<IFacialExpressionGetter> facialExpression_Amused => Construct(0x20d3a1);
        public static FormLink<IFacialExpressionGetter> facialExpression_Angry => Construct(0x20d3a2);
        public static FormLink<IFacialExpressionGetter> facialExpression_Apologetic => Construct(0x20d3a3);
        public static FormLink<IFacialExpressionGetter> facialExpression_Awed => Construct(0x20d3a4);
        public static FormLink<IFacialExpressionGetter> facialExpression_Concentrating => Construct(0x20d3a5);
        public static FormLink<IFacialExpressionGetter> facialExpression_Concerned => Construct(0x20d3a6);
        public static FormLink<IFacialExpressionGetter> facialExpression_Confused => Construct(0x20d3a7);
        public static FormLink<IFacialExpressionGetter> facialExpression_Boggled => Construct(0x20d3a8);
        public static FormLink<IFacialExpressionGetter> facialExpression_Duck => Construct(0x20d3a9);
        public static FormLink<IFacialExpressionGetter> facialExpression_HoldBreath => Construct(0x20d3aa);
        public static FormLink<IFacialExpressionGetter> facialExpression_Depressed => Construct(0x20d3ab);
        public static FormLink<IFacialExpressionGetter> facialExpression_Disbelief => Construct(0x20d3ac);
        public static FormLink<IFacialExpressionGetter> facialExpression_Disgust => Construct(0x20d3ad);
        public static FormLink<IFacialExpressionGetter> facialExpression_Dying => Construct(0x20d3ae);
        public static FormLink<IFacialExpressionGetter> facialExpression_EyesClosed => Construct(0x20d3af);
        public static FormLink<IFacialExpressionGetter> facialExpression_Flirt => Construct(0x20d3b0);
        public static FormLink<IFacialExpressionGetter> facialExpression_Happy => Construct(0x20d3b1);
        public static FormLink<IFacialExpressionGetter> facialExpression_Impressed => Construct(0x20d3b2);
        public static FormLink<IFacialExpressionGetter> facialExpression_Irritated => Construct(0x20d3b3);
        public static FormLink<IFacialExpressionGetter> facialExpression_Pain => Construct(0x20d3b4);
        public static FormLink<IFacialExpressionGetter> facialExpression_Rage => Construct(0x20d3c3);
        public static FormLink<IFacialExpressionGetter> facialExpression_Sarcastic => Construct(0x20d3c4);
        public static FormLink<IFacialExpressionGetter> facialExpression_Shocked => Construct(0x20d3d3);
        public static FormLink<IFacialExpressionGetter> facialExpression_Sinister => Construct(0x20d3d4);
        public static FormLink<IFacialExpressionGetter> facialExpression_Smirk => Construct(0x20d478);
        public static FormLink<IFacialExpressionGetter> facialExpression_Smug => Construct(0x20d479);
        public static FormLink<IFacialExpressionGetter> facialExpression_Surprise => Construct(0x20d47a);
        public static FormLink<IFacialExpressionGetter> facialExpression_VeryAngry => Construct(0x20d47b);
        public static FormLink<IFacialExpressionGetter> facialExpression_Worry => Construct(0x20d47c);
        public static FormLink<IFacialExpressionGetter> facialExpression_Yawn => Construct(0x20d514);
    }
}
