// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class Starfield
{
    public static partial class FogVolume
    {
        private static FormLink<IFogVolumeGetter> Construct(uint id) => new FormLink<IFogVolumeGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IFogVolumeGetter> ATM_Fog_Int_Heavy_White_Stnd_03 => Construct(0x34fc);
        public static FormLink<IFogVolumeGetter> ATM_GroundFog_Int_Heavy_Warm01_Stnd_02 => Construct(0x90a4);
        public static FormLink<IFogVolumeGetter> ATM_Fog_Int_Med_White_Stnd_06 => Construct(0x270c9);
        public static FormLink<IFogVolumeGetter> ATM_Fog_ShipKit_Table_01 => Construct(0x293fd);
        public static FormLink<IFogVolumeGetter> ATM_Fog_ShipKit_Table_02 => Construct(0x293fe);
        public static FormLink<IFogVolumeGetter> ATM_GroundFog_Int_Heavy_Warm01_Stnd_03 => Construct(0x2ed6c);
        public static FormLink<IFogVolumeGetter> ATM_Fog_None => Construct(0x46f59);
        public static FormLink<IFogVolumeGetter> ATM_Fog_Int_Unique_Cydonia_Ext_Heavy => Construct(0x62b84);
        public static FormLink<IFogVolumeGetter> ATM_Fog_Int_Unique_Cydonia_Ext_Medium => Construct(0x62cca);
        public static FormLink<IFogVolumeGetter> ATM_Fog_Int_Hab_01 => Construct(0x64e8c);
        public static FormLink<IFogVolumeGetter> ATM_Fog_Int_Heavy_Black_Stnd_01 => Construct(0x6d571);
        public static FormLink<IFogVolumeGetter> ATM_GroundFog_Ext_Heavy_Anim_01 => Construct(0x74d55);
        public static FormLink<IFogVolumeGetter> ATM_Fog_Int_Unique_LC135_Ext_01 => Construct(0x8bdaf);
        public static FormLink<IFogVolumeGetter> ATM_Fog_Int_Unique_LC135_Ext_02 => Construct(0x8bdb3);
        public static FormLink<IFogVolumeGetter> ATM_Fog_Int_Heavy_White_Stnd_02 => Construct(0x9591e);
        public static FormLink<IFogVolumeGetter> ATM_Fog_Int_Unique_Neon_Ext_Light => Construct(0x9757c);
        public static FormLink<IFogVolumeGetter> ATM_Fog_Int_Unique_Neon_Ext_Medium => Construct(0x97593);
        public static FormLink<IFogVolumeGetter> ATM_Fog_Int_Unique_Londinion_Ext_Light => Construct(0x9854c);
        public static FormLink<IFogVolumeGetter> ATM_Fog_Int_Lite_Blue_Stnd_02 => Construct(0xa3ad0);
        public static FormLink<IFogVolumeGetter> ATM_GroundFog_Int_Heavy_Warm01_Stnd_01 => Construct(0xe8286);
        public static FormLink<IFogVolumeGetter> ATM_Fog_Int_Heavy_Warm_Stnd_01 => Construct(0xe8287);
        public static FormLink<IFogVolumeGetter> ATM_Fog_Int_Med_White_Stnd_05 => Construct(0xf455b);
        public static FormLink<IFogVolumeGetter> ATM_Fog_Int_Med_White_Anim_03 => Construct(0xf4ce7);
        public static FormLink<IFogVolumeGetter> ATM_Fog_Int_Med_White_Stnd_04 => Construct(0xf4ce8);
        public static FormLink<IFogVolumeGetter> ATM_GroundFog_Int_Heavy_Cool_Anim_01 => Construct(0xf4ce9);
        public static FormLink<IFogVolumeGetter> ATM_GroundFog_Int_Heavy_Cool_Stnd_02 => Construct(0xf4cea);
        public static FormLink<IFogVolumeGetter> ATM_Fog_Int_Med_White_Stnd_03 => Construct(0x101e08);
        public static FormLink<IFogVolumeGetter> ATM_Fog_ShipKit => Construct(0x103bc5);
        public static FormLink<IFogVolumeGetter> ATM_Fog_Int_Lite_White_Stnd_08 => Construct(0x10a355);
        public static FormLink<IFogVolumeGetter> ATM_Fog_Int_Lite_White_Stnd_07 => Construct(0x10a356);
        public static FormLink<IFogVolumeGetter> ATM_Fog_Int_Lite_White_Stnd_06 => Construct(0x12002b);
        public static FormLink<IFogVolumeGetter> ATM_Fog_Int_Lite_White_Anim_06 => Construct(0x121205);
        public static FormLink<IFogVolumeGetter> ATM_Fog_Int_Lite_White_Stnd_05 => Construct(0x121243);
        public static FormLink<IFogVolumeGetter> ATM_Fog_Int_Heavy_White_Stnd_01 => Construct(0x12126d);
        public static FormLink<IFogVolumeGetter> ATM_Fog_Int_Med_White_Stnd_01 => Construct(0x127e7d);
        public static FormLink<IFogVolumeGetter> ATM_Fog_Int_Med_White_Stnd_02 => Construct(0x127e7e);
        public static FormLink<IFogVolumeGetter> ATM_Fog_Int_Lite_White_Stnd_04 => Construct(0x12a744);
        public static FormLink<IFogVolumeGetter> ATM_Fog_Int_Lite_White_Anim_04 => Construct(0x12f26c);
        public static FormLink<IFogVolumeGetter> ATM_Fog_Int_Lite_White_Anim_03 => Construct(0x12f26d);
        public static FormLink<IFogVolumeGetter> ATM_Fog_Int_Lite_White_Stnd_03 => Construct(0x12f26e);
        public static FormLink<IFogVolumeGetter> ATM_Fog_Int_Unique_Neon_Core => Construct(0x13147c);
        public static FormLink<IFogVolumeGetter> ATM_Fog_Int_Med_White_Anim_02 => Construct(0x133b11);
        public static FormLink<IFogVolumeGetter> ATM_Fog_Int_Heavy_White_Anim_02 => Construct(0x138cc7);
        public static FormLink<IFogVolumeGetter> ATM_Fog_Int_Lite_White_Stnd_02 => Construct(0x146893);
        public static FormLink<IFogVolumeGetter> ATM_Fog_Int_Lite_White_Anim_02 => Construct(0x14775e);
        public static FormLink<IFogVolumeGetter> ATM_Fog_Int_Med_White_Anim_01 => Construct(0x14cf39);
        public static FormLink<IFogVolumeGetter> ATM_Fog_Int_Lite_White_Stnd_01 => Construct(0x14cf4c);
        public static FormLink<IFogVolumeGetter> ATM_Fog_Int_Heavy_White_Anim_01 => Construct(0x14cf4f);
        public static FormLink<IFogVolumeGetter> VideoShipInterior_Fog_Hangar_Windows => Construct(0x16637a);
        public static FormLink<IFogVolumeGetter> VideoShipInterior_Fog_Hangar => Construct(0x16638f);
        public static FormLink<IFogVolumeGetter> VideoShipInterior_Fog_Hangar_Ground => Construct(0x166390);
        public static FormLink<IFogVolumeGetter> VideoShipInterior_Fog_Hangar_Shot03 => Construct(0x166397);
        public static FormLink<IFogVolumeGetter> VideoShipInterior_Fog_Cockpit_SkyLight => Construct(0x167aee);
        public static FormLink<IFogVolumeGetter> VideoShipInterior_Fog_GunTable_Shot05 => Construct(0x167af4);
        public static FormLink<IFogVolumeGetter> VideoShipInterior_Fog_GunTable_Shot04 => Construct(0x167af5);
        public static FormLink<IFogVolumeGetter> VideoShipInterior_Fog_MapTable => Construct(0x167af8);
        public static FormLink<IFogVolumeGetter> VideoShipInterior_Fog_001 => Construct(0x17aaa7);
        public static FormLink<IFogVolumeGetter> _RENAME_TestFogRoom01 => Construct(0x18a9fb);
        public static FormLink<IFogVolumeGetter> _RENAME_TestGrantFofVolume => Construct(0x190b9e);
        public static FormLink<IFogVolumeGetter> _RENAME_TestShipMenuFog01 => Construct(0x190fc5);
        public static FormLink<IFogVolumeGetter> _RENAME_TestFogLondinion01 => Construct(0x19211f);
        public static FormLink<IFogVolumeGetter> _RENAME_TestFogGymFX01 => Construct(0x19b4f9);
        public static FormLink<IFogVolumeGetter> ATM_Fog_ShipKit_Derelict => Construct(0x1b7bf9);
        public static FormLink<IFogVolumeGetter> ATM_Fog_Int_Unique_Legacy_Escape => Construct(0x1caded);
        public static FormLink<IFogVolumeGetter> ATM_Fog_Int_Heavy_Warm_Stnd_03 => Construct(0x22a8e8);
        public static FormLink<IFogVolumeGetter> ATM_GroundFog_Ext_Medium_Anim_01 => Construct(0x23c4bd);
        public static FormLink<IFogVolumeGetter> ATM_Fog_Int_Lite_Blue_Stnd_01 => Construct(0x26139c);
        public static FormLink<IFogVolumeGetter> ATM_Fog_Int_Unique_Gagarin_Ext_Medium => Construct(0x27fe95);
        public static FormLink<IFogVolumeGetter> ATM_Fog_Int_Unique_Londinion_Ext_Medium => Construct(0x27fe96);
        public static FormLink<IFogVolumeGetter> ATM_Fog_Int_Heavy_Warm_Stnd_02 => Construct(0x2dddbb);
        public static FormLink<IFogVolumeGetter> ATM_GroundFog_Int_Heavy_Cool_Anim_02 => Construct(0x3a4b42);
        public static FormLink<IFogVolumeGetter> ATM_GroundFog_Int_Heavy_Cool_Stnd_03 => Construct(0x3b42c6);
        public static FormLink<IFogVolumeGetter> ATM_GroundFog_Int_Heavy_Warm01_Stnd_04 => Construct(0x3eabcd);
    }
}
