// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class Starfield
{
    public static partial class Footstep
    {
        private static FormLink<IFootstepGetter> Construct(uint id) => new FormLink<IFootstepGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IFootstepGetter> FSTDefaultFootstepWalkLFootstep => Construct(0x12f0f);
        public static FormLink<IFootstepGetter> FSTDefaultFootstepWalkRFootstep => Construct(0x12f10);
        public static FormLink<IFootstepGetter> FSTDefaultFootstepRunLFootstep => Construct(0x12f11);
        public static FormLink<IFootstepGetter> FSTDefaultFootstepRunRFootstep => Construct(0x12f12);
        public static FormLink<IFootstepGetter> FSTDefaultFootstepSneakRFootstep => Construct(0x12f13);
        public static FormLink<IFootstepGetter> FSTDefaultFootstepSneakLFootstep => Construct(0x12f14);
        public static FormLink<IFootstepGetter> FSTDefaultFootstepJumpDownFootstep => Construct(0x12f15);
        public static FormLink<IFootstepGetter> FSTBarefootWalkLFootstep => Construct(0x21466);
        public static FormLink<IFootstepGetter> FSTBarefootWalkRFootstep => Construct(0x21467);
        public static FormLink<IFootstepGetter> FSTDefaultFootstepSprintLFootstep => Construct(0x225a5);
        public static FormLink<IFootstepGetter> FSTDefaultFootstepSprintRFootstep => Construct(0x225a6);
        public static FormLink<IFootstepGetter> FSTDefaultFootstepJumpUpFootstep => Construct(0x5a289);
        public static FormLink<IFootstepGetter> NPCMantidAFootWalkLFootstep => Construct(0x647dd);
        public static FormLink<IFootstepGetter> NPCMantidAFootWalkRFootstep => Construct(0x647de);
        public static FormLink<IFootstepGetter> FSTMetalLadderRungWalkFootstep => Construct(0x68f3e);
        public static FormLink<IFootstepGetter> NPCRobotModelAWalkLFootstep => Construct(0x77808);
        public static FormLink<IFootstepGetter> NPCRobotModelAWalkRFootstep => Construct(0x77809);
        public static FormLink<IFootstepGetter> FSTBarefootJumpDownFootstep => Construct(0x8f515);
        public static FormLink<IFootstepGetter> FSTBarefootJumpUpFootstep => Construct(0xa667a);
        public static FormLink<IFootstepGetter> NPCRobotModelASneakRFootstep => Construct(0xd8865);
        public static FormLink<IFootstepGetter> NPCRobotModelASneakLFootstep => Construct(0xd8866);
        public static FormLink<IFootstepGetter> FSTDefaultMovementMantleHands => Construct(0xd8867);
        public static FormLink<IFootstepGetter> NPCRobotModelARunRFootstep => Construct(0xd8869);
        public static FormLink<IFootstepGetter> NPCRobotModelARunLFootstep => Construct(0xd886a);
        public static FormLink<IFootstepGetter> FSTBarefootRunLFootstep => Construct(0xe41ec);
        public static FormLink<IFootstepGetter> FSTBarefootRunRFootstep => Construct(0xe41ed);
        public static FormLink<IFootstepGetter> FSTBarefootSprintLFootstep => Construct(0xe41ee);
        public static FormLink<IFootstepGetter> FSTBarefootSprintRFootstep => Construct(0xe41ef);
        public static FormLink<IFootstepGetter> FSTBarefootSneakLFootstep => Construct(0x11ba36);
        public static FormLink<IFootstepGetter> FSTBarefootSneakRFootstep => Construct(0x11ba37);
        public static FormLink<IFootstepGetter> FSTWalkStartFootstep => Construct(0x133987);
        public static FormLink<IFootstepGetter> FSTWalkStopFootstep => Construct(0x13398a);
        public static FormLink<IFootstepGetter> NPCHopperAJumpUpFootstep => Construct(0x13f2b8);
        public static FormLink<IFootstepGetter> NPCHopperAJumpDownFootstep => Construct(0x13f2b9);
        public static FormLink<IFootstepGetter> NPCHexapodAFootWalkJumpDownFootstep => Construct(0x13f2ba);
        public static FormLink<IFootstepGetter> NPCHexapodAFootWalkJumpUpFootstep => Construct(0x13f2bb);
        public static FormLink<IFootstepGetter> NPCQuadrupedCWalkRFootstep => Construct(0x167666);
        public static FormLink<IFootstepGetter> NPCQuadrupedCWalkLFootstep => Construct(0x167667);
        public static FormLink<IFootstepGetter> NPCQuadrupedCRunRFootstep => Construct(0x167669);
        public static FormLink<IFootstepGetter> NPCQuadrupedCRunLFootstep => Construct(0x16766a);
        public static FormLink<IFootstepGetter> FSTDefaultCompanionFootstepJumpDownFootstep => Construct(0x1eb804);
        public static FormLink<IFootstepGetter> FSTDefaultCompanionFootstepJumpUpFootstep => Construct(0x1eb805);
        public static FormLink<IFootstepGetter> FSTDefaultCompanionFootstepRunLFootstep => Construct(0x1eb806);
        public static FormLink<IFootstepGetter> FSTDefaultCompanionFootstepRunRFootstep => Construct(0x1eb807);
        public static FormLink<IFootstepGetter> FSTDefaultCompanionFootstepSneakLFootstep => Construct(0x1eb808);
        public static FormLink<IFootstepGetter> FSTDefaultCompanionFootstepSneakRFootstep => Construct(0x1eb809);
        public static FormLink<IFootstepGetter> FSTDefaultCompanionFootstepSprintLFootstep => Construct(0x1eb80a);
        public static FormLink<IFootstepGetter> FSTDefaultCompanionFootstepSprintRFootstep => Construct(0x1eb80b);
        public static FormLink<IFootstepGetter> FSTDefaultCompanionFootstepWalkLFootstep => Construct(0x1eb80c);
        public static FormLink<IFootstepGetter> FSTDefaultCompanionFootstepWalkRFootstep => Construct(0x1eb80d);
        public static FormLink<IFootstepGetter> NPCBipedASneakLFootstep => Construct(0x1f8f72);
        public static FormLink<IFootstepGetter> NPCBipedASneakRFootstep => Construct(0x1f8f73);
        public static FormLink<IFootstepGetter> NPCBipedASprintRFootstep => Construct(0x1f8f74);
        public static FormLink<IFootstepGetter> NPCBipedASprintLFootstep => Construct(0x1f8f75);
        public static FormLink<IFootstepGetter> NPCModelSFootWalkRFootstep => Construct(0x20269b);
        public static FormLink<IFootstepGetter> NPCModelSFootWalkLFootstep => Construct(0x20269c);
        public static FormLink<IFootstepGetter> NPCModelSFootRunRFootstep => Construct(0x20269d);
        public static FormLink<IFootstepGetter> NPCModelSFootRunLFootstep => Construct(0x20269e);
        public static FormLink<IFootstepGetter> NPCHexapodAFootWalkRFootstep => Construct(0x2074c3);
        public static FormLink<IFootstepGetter> NPCHexapodAFootWalkLFootstep => Construct(0x2074c4);
        public static FormLink<IFootstepGetter> NPCHexapodAFootRunRFootstep => Construct(0x2074c5);
        public static FormLink<IFootstepGetter> NPCHexapodAFootRunLFootstep => Construct(0x2074c6);
        public static FormLink<IFootstepGetter> NPCBipedARunRFootstep => Construct(0x20bff8);
        public static FormLink<IFootstepGetter> NPCBipedARunLFootstep => Construct(0x20bff9);
        public static FormLink<IFootstepGetter> NPCBipedAWalkRFootstep => Construct(0x20bffa);
        public static FormLink<IFootstepGetter> NPCBipedAWalkLFootstep => Construct(0x20bffb);
        public static FormLink<IFootstepGetter> NPCTerrormorphFootRunRFootstep => Construct(0x20c56e);
        public static FormLink<IFootstepGetter> NPCTerrormorphFootRunLFootstep => Construct(0x20c56f);
        public static FormLink<IFootstepGetter> NPCTerrormorphFootWalkRFootstep => Construct(0x20c570);
        public static FormLink<IFootstepGetter> NPCTerrormorphFootWalkLFootstep => Construct(0x20c571);
        public static FormLink<IFootstepGetter> NPCQuadrupedAWalkRFootstep => Construct(0x20c5a0);
        public static FormLink<IFootstepGetter> NPCQuadrupedAWalkLFootstep => Construct(0x20c5a1);
        public static FormLink<IFootstepGetter> NPCQuadrupedARunRFootstep => Construct(0x20c5a3);
        public static FormLink<IFootstepGetter> NPCQuadrupedARunLFootstep => Construct(0x20c5a4);
        public static FormLink<IFootstepGetter> NPCHopperAFootWalkRFootstep => Construct(0x211328);
        public static FormLink<IFootstepGetter> NPCHopperAFootWalkLFootstep => Construct(0x211329);
        public static FormLink<IFootstepGetter> NPCHopperAFootRunRFootstep => Construct(0x21132c);
        public static FormLink<IFootstepGetter> NPCHopperAFootRunLFootstep => Construct(0x21132d);
        public static FormLink<IFootstepGetter> NPCQuadrupedBRunRFootstep => Construct(0x211c52);
        public static FormLink<IFootstepGetter> NPCQuadrupedBWalkRFootstep => Construct(0x211c53);
        public static FormLink<IFootstepGetter> NPCQuadrupedBRunLFootstep => Construct(0x211c54);
        public static FormLink<IFootstepGetter> NPCQuadrupedBWalkLFootstep => Construct(0x211c55);
        public static FormLink<IFootstepGetter> FSTDefaultMovementSlide => Construct(0x214677);
        public static FormLink<IFootstepGetter> NPCOctopedeAFootRunRFootstep => Construct(0x22b29e);
        public static FormLink<IFootstepGetter> NPCOctopedeAFootRunLFootstep => Construct(0x22b29f);
        public static FormLink<IFootstepGetter> NPCOctopedeAFootWalkRFootstep => Construct(0x22b2a0);
        public static FormLink<IFootstepGetter> NPCOctopedeAFootWalkLFootstep => Construct(0x22b2a1);
        public static FormLink<IFootstepGetter> NPCLarvaARunFootstep => Construct(0x231a21);
        public static FormLink<IFootstepGetter> NPCMantidAFootRunRFootstep => Construct(0x231eaf);
        public static FormLink<IFootstepGetter> NPCMantidAFootRunLFootstep => Construct(0x231eb0);
        public static FormLink<IFootstepGetter> NPCLarvaAWalkFootstep => Construct(0x2362d5);
    }
}
