// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class Starfield
{
    public static partial class ForceData
    {
        private static FormLink<IForceDataGetter> Construct(uint id) => new FormLink<IForceDataGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IForceDataGetter> ForceDataWindVeryHeavy01 => Construct(0x10e4b9);
        public static FormLink<IForceDataGetter> ForceDataWindHeavy01 => Construct(0x10e4ba);
        public static FormLink<IForceDataGetter> ForceDataWindMedium01 => Construct(0x10e4bb);
        public static FormLink<IForceDataGetter> ForceDataWindLight01 => Construct(0x13094e);
        public static FormLink<IForceDataGetter> ForceDataWindNone => Construct(0x3d2490);
    }
}
