// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class Starfield
{
    public static partial class Hazard
    {
        private static FormLink<IHazardGetter> Construct(uint id) => new FormLink<IHazardGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IHazardGetter> ENV_PoolHazard_ParasiticContamination => Construct(0xb25);
        public static FormLink<IHazardGetter> Terrormorph_ENV_CloudHazard_Spores_Toxic => Construct(0xb7a);
        public static FormLink<IHazardGetter> ENV_GenericHazard_Cold_CryoLeak => Construct(0x38914);
        public static FormLink<IHazardGetter> ENV_PoolHazard_Heat => Construct(0x40464);
        public static FormLink<IHazardGetter> ENV_PoolHazard_ToxicGas => Construct(0x40466);
        public static FormLink<IHazardGetter> ENV_PoolHazard_MicrobialContamination => Construct(0x4046f);
        public static FormLink<IHazardGetter> ENV_PoolHazard_CorrosiveLiquid => Construct(0x40474);
        public static FormLink<IHazardGetter> ENV_PoolHazard_Radiation => Construct(0x47386);
        public static FormLink<IHazardGetter> TestEngineFireHazard => Construct(0x496c2);
        public static FormLink<IHazardGetter> LC088_ENV_ReactorRadiationHazard => Construct(0x9ea98);
        public static FormLink<IHazardGetter> LC107_ENV_GasVentHazard_ToxicGas => Construct(0xac0bf);
        public static FormLink<IHazardGetter> SpaceDistortionCloudHazard => Construct(0xbf72b);
        public static FormLink<IHazardGetter> ENV_GasVentHazard_ToxicGas_Central => Construct(0xd0afa);
        public static FormLink<IHazardGetter> ScannerGuideHazard => Construct(0x10bcd3);
        public static FormLink<IHazardGetter> DamageShipShieldsandHullHazard => Construct(0x115997);
        public static FormLink<IHazardGetter> Legendary_Wep_TeslaPylons_Hazard => Construct(0x124f3f);
        public static FormLink<IHazardGetter> LC165_ScriptedGravWellHazard => Construct(0x12547c);
        public static FormLink<IHazardGetter> CreatorsPeaceHazard => Construct(0x1434e8);
        public static FormLink<IHazardGetter> DamageShipWeaponsHazard => Construct(0x147e40);
        public static FormLink<IHazardGetter> LC051_Trap_ToxicGasHazard => Construct(0x14ac5e);
        public static FormLink<IHazardGetter> ENV_GenericHazard_Heat_Flames_novfx_2m => Construct(0x14d798);
        public static FormLink<IHazardGetter> ENV_GeyserHazard_Heat => Construct(0x153203);
        public static FormLink<IHazardGetter> ENV_CloudHazard_Spores_Toxic => Construct(0x153204);
        public static FormLink<IHazardGetter> ENV_SteamVentHazard_Heat => Construct(0x15d39a);
        public static FormLink<IHazardGetter> ENV_Pool_Lava_Heat => Construct(0x15e761);
        public static FormLink<IHazardGetter> MQ207C_ArtifactExperimentBeamHazard => Construct(0x1639ca);
        public static FormLink<IHazardGetter> CreateVacuumHazard => Construct(0x19f9d8);
        public static FormLink<IHazardGetter> SE_SD05_Hazard_ToxicGas_DangerousArea => Construct(0x1b2eb4);
        public static FormLink<IHazardGetter> ENV_GenericHazard_Heat_Flames_TRP => Construct(0x1e80e8);
        public static FormLink<IHazardGetter> SpaceStormCloudHazard => Construct(0x1facde);
        public static FormLink<IHazardGetter> ENV_FlameHazard_Heat => Construct(0x1fe66d);
        public static FormLink<IHazardGetter> ENV_GenericHazard_Heat_DangerousArea => Construct(0x206124);
        public static FormLink<IHazardGetter> DamageShipShieldsHazard => Construct(0x207f1a);
        public static FormLink<IHazardGetter> DamageShipHullHazard => Construct(0x2080f1);
        public static FormLink<IHazardGetter> ENV_GenericHazard_Heat_Flames => Construct(0x21568f);
        public static FormLink<IHazardGetter> ENV_GenericHazard_Cold_DangerousArea => Construct(0x215691);
        public static FormLink<IHazardGetter> ENV_GasVentHazard_RadioactiveGas => Construct(0x21bbd1);
        public static FormLink<IHazardGetter> ENV_GasVentHazard_CorrosiveGas => Construct(0x21bbe9);
        public static FormLink<IHazardGetter> PointGravHazard_LG => Construct(0x21c451);
        public static FormLink<IHazardGetter> PointGravHazard_SM => Construct(0x21c454);
        public static FormLink<IHazardGetter> IncendiaryGrenade_Hazard => Construct(0x21c4f9);
        public static FormLink<IHazardGetter> TeslaMine_Hazard => Construct(0x21c500);
        public static FormLink<IHazardGetter> InverseGravFieldHazard_NOACTOR => Construct(0x23c33a);
        public static FormLink<IHazardGetter> InverseGravFieldHazard => Construct(0x23c33b);
        public static FormLink<IHazardGetter> DebugSB_PlayerGravFieldHazardL => Construct(0x23f747);
        public static FormLink<IHazardGetter> ENV_GasVentHazard_ToxicGas => Construct(0x245b6c);
        public static FormLink<IHazardGetter> DebugSB_CenterGravFieldHazardL => Construct(0x247db4);
        public static FormLink<IHazardGetter> DebugSB_GravFieldHazardL => Construct(0x247db5);
        public static FormLink<IHazardGetter> DebugSB_AntiGravFieldHazardL => Construct(0x247db6);
        public static FormLink<IHazardGetter> ENV_GasVentHazard_Heat => Construct(0x248d28);
        public static FormLink<IHazardGetter> PrecogHazard => Construct(0x255dcc);
        public static FormLink<IHazardGetter> AntiGravFieldHazardL => Construct(0x25e181);
        public static FormLink<IHazardGetter> AntiGravFieldHazardM => Construct(0x25e182);
        public static FormLink<IHazardGetter> AntiGravFieldHazard => Construct(0x25e185);
        public static FormLink<IHazardGetter> GravWellHazard => Construct(0x29576e);
        public static FormLink<IHazardGetter> FireHazardStrong3m_OBSOLETE => Construct(0x2a31be);
        public static FormLink<IHazardGetter> SE_SP01_Hazard_ToxicGas_DangerousArea => Construct(0x2c4118);
        public static FormLink<IHazardGetter> ModWeapon_Annihilator_Hazard => Construct(0x336bfe);
        public static FormLink<IHazardGetter> ENV_GasVentHazard_CorrosiveGas_SE_KT12 => Construct(0x3796b8);
        public static FormLink<IHazardGetter> SE_KT11_ENV_Hazard_Heat => Construct(0x379a13);
        public static FormLink<IHazardGetter> ENV_CryoHazard_IceFloor => Construct(0x388adc);
        public static FormLink<IHazardGetter> Legendary_Wep_TeslaRounds_Hazard => Construct(0x38d6ca);
        public static FormLink<IHazardGetter> ENV_GenericHazard_Cold_CryoBlast => Construct(0x3bc932);
        public static FormLink<IHazardGetter> ENV_GenericHazard_ToxicGas_DangerousArea => Construct(0x3bc936);
        public static FormLink<IHazardGetter> ENV_GenericHazard_ToxicGas_Leak => Construct(0x3bc938);
        public static FormLink<IHazardGetter> ENV_GenericHazard_Radiation_DangerousArea => Construct(0x3bc93e);
        public static FormLink<IHazardGetter> ENV_GenericHazard_Radiation_NuclearMaterial => Construct(0x3bc93f);
        public static FormLink<IHazardGetter> ENV_GenericHazard_Electricity_ElectricalField => Construct(0x3bcc11);
        public static FormLink<IHazardGetter> ENV_GenericHazard_Electricity_ElectrifiedLiquid => Construct(0x3bcc13);
        public static FormLink<IHazardGetter> ENV_GenericHazard_CorrosiveGas_DangerousArea => Construct(0x3bcc16);
        public static FormLink<IHazardGetter> ENV_GenericHazard_CorrosiveGas_Leak => Construct(0x3bcc19);
        public static FormLink<IHazardGetter> ENV_GenericHazard_CorrosiveSubstance_DangerousArea => Construct(0x3bcc1e);
        public static FormLink<IHazardGetter> ENV_GenericHazard_CorrosiveSubstance_Sludge => Construct(0x3bcc1f);
        public static FormLink<IHazardGetter> ENV_GooPuddleHazard_Corrosive => Construct(0x3e5dcb);
        public static FormLink<IHazardGetter> SleepGasMine_Hazard => Construct(0x3e9943);
    }
}
