// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class Starfield
{
    public static partial class InstanceNamingRules
    {
        private static FormLink<IInstanceNamingRulesGetter> Construct(uint id) => new FormLink<IInstanceNamingRulesGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IInstanceNamingRulesGetter> dn_CommonArmor => Construct(0x184bc1);
        public static FormLink<IInstanceNamingRulesGetter> dn_CCTPrefixes => Construct(0x220394);
        public static FormLink<IInstanceNamingRulesGetter> dn_CommonGun => Construct(0x2377cf);
        public static FormLink<IInstanceNamingRulesGetter> dn_CommonMelee => Construct(0x2fbe25);
        public static FormLink<IInstanceNamingRulesGetter> dn_CCTSuffixes => Construct(0x3e8650);
    }
}
