// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class Starfield
{
    public static partial class LensFlare
    {
        private static FormLink<ILensFlareGetter> Construct(uint id) => new FormLink<ILensFlareGetter>(ModKey.MakeFormKey(id));
        public static FormLink<ILensFlareGetter> LGT_LensFlare_ShipHeadlights => Construct(0xe066);
        public static FormLink<ILensFlareGetter> GravJumpFlare => Construct(0x16e16);
        public static FormLink<ILensFlareGetter> ShipMainEngineBoostLensFlare00 => Construct(0x5ad13);
        public static FormLink<ILensFlareGetter> BoostPackLensFlare => Construct(0x5b7b6);
        public static FormLink<ILensFlareGetter> ArtifactRiftFlare => Construct(0x63376);
        public static FormLink<ILensFlareGetter> SunFlare_OverCast => Construct(0x183348);
        public static FormLink<ILensFlareGetter> MQ206B_ScorpionStarFlare => Construct(0x1856e8);
        public static FormLink<ILensFlareGetter> AlliedOrionLightLensFlare => Construct(0x1b0359);
        public static FormLink<ILensFlareGetter> SunFlare_Clear => Construct(0x1b88e1);
        public static FormLink<ILensFlareGetter> ParticleFuse02SmallLightLensFlare => Construct(0x1c26c2);
        public static FormLink<ILensFlareGetter> ParticleFuseLightLensFlare => Construct(0x1c3937);
        public static FormLink<ILensFlareGetter> ShipLandingLightLensFlare => Construct(0x1f5496);
        public static FormLink<ILensFlareGetter> SBPuzzleAnomalyFlare => Construct(0x221d41);
        public static FormLink<ILensFlareGetter> SpotlightLensFlare => Construct(0x239223);
        public static FormLink<ILensFlareGetter> SpotlightLensFlareBright => Construct(0x24886b);
        public static FormLink<ILensFlareGetter> SunFlare_Space => Construct(0x24a047);
        public static FormLink<ILensFlareGetter> HelmetLightFlare => Construct(0x24e7da);
        public static FormLink<ILensFlareGetter> LGTLensFlaretest => Construct(0x252003);
        public static FormLink<ILensFlareGetter> LC165_ArtifactFlare => Construct(0x27fcd3);
        public static FormLink<ILensFlareGetter> LGT_LensFlare_Industrial_001 => Construct(0x2c38c0);
        public static FormLink<ILensFlareGetter> LGT_LensFlare_Industrial_Circles => Construct(0x2c4b82);
        public static FormLink<ILensFlareGetter> ShipDestructionExplosionLensFlare => Construct(0x337ebb);
        public static FormLink<ILensFlareGetter> _RENAME_TestParticleFuseLightLensFlare => Construct(0x397025);
    }
}
