// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class Starfield
{
    public static partial class LeveledPackIn
    {
        private static FormLink<ILeveledPackInGetter> Construct(uint id) => new FormLink<ILeveledPackInGetter>(ModKey.MakeFormKey(id));
        public static FormLink<ILeveledPackInGetter> ENV_LPI_Vent_Geyser_ExtremeHeat_Statics => Construct(0xb22);
        public static FormLink<ILeveledPackInGetter> ENV_LPI_Vent_Steam_ExtremeHeat_Statics => Construct(0xb28);
        public static FormLink<ILeveledPackInGetter> ENV_LPI_Vent_Steam_ExtremeHeat_HazardCentral_Variations => Construct(0xb29);
        public static FormLink<ILeveledPackInGetter> LPIHumanHostileMinePI_Any => Construct(0x54b1a);
        public static FormLink<ILeveledPackInGetter> LPIHumanHostileMinePI_Any_50 => Construct(0x54b1b);
        public static FormLink<ILeveledPackInGetter> LPIHumanHostileMinePI_FragMine => Construct(0x70d1f);
        public static FormLink<ILeveledPackInGetter> LPIHumanHostileMinePI_InfernoMine => Construct(0x7aa72);
        public static FormLink<ILeveledPackInGetter> LPIHumanHostileMinePI_ToxicGasMine => Construct(0x7aa7b);
        public static FormLink<ILeveledPackInGetter> LPIHumanHostileMinePI_SleepGasMine => Construct(0x7aa7c);
        public static FormLink<ILeveledPackInGetter> LPIHumanHostileMinePI_TeslaMine => Construct(0x7aa7d);
        public static FormLink<ILeveledPackInGetter> LPIHumanHostileMinePI_CryoMine => Construct(0x7aa7e);
        public static FormLink<ILeveledPackInGetter> OECave_InorgResource_Bonus_Packin => Construct(0xc70b2);
        public static FormLink<ILeveledPackInGetter> CF_LvlPI_CredTank => Construct(0xedafc);
        public static FormLink<ILeveledPackInGetter> ENV_LPI_GasVent_ExtremeHeat_Statics => Construct(0x148186);
        public static FormLink<ILeveledPackInGetter> LVLPI_PCM_Manmade_CratesSmall01 => Construct(0x1dbee9);
        public static FormLink<ILeveledPackInGetter> LVLPI_PCM_Manmade_CratesClusterLarge01 => Construct(0x1dbeea);
        public static FormLink<ILeveledPackInGetter> ENV_LPI_GasVent_Corrosive_HazardCentral_Variations => Construct(0x1e021d);
        public static FormLink<ILeveledPackInGetter> ENV_LPI_GasVent_Corrosive_Statics => Construct(0x1e021e);
        public static FormLink<ILeveledPackInGetter> ENV_LPI_GasVent_ExtremeHeat_HazardCentral_Variations => Construct(0x1e0223);
        public static FormLink<ILeveledPackInGetter> ENV_LPI_GasVent_Radioactive_HazardCentral_Variations => Construct(0x1e0224);
        public static FormLink<ILeveledPackInGetter> ENV_LPI_GasVent_Radioactive_Statics => Construct(0x1e0236);
        public static FormLink<ILeveledPackInGetter> ENV_LPI_GasVent_SmokeUndergroundBurning_HazardCentral_Variations => Construct(0x1e023d);
        public static FormLink<ILeveledPackInGetter> ENV_LPI_GasVent_SmokeUndergroundBurning_Statics => Construct(0x1e0241);
        public static FormLink<ILeveledPackInGetter> ENV_LPI_GasVent_ToxicGas_HazardCentral_Variations => Construct(0x1e0244);
        public static FormLink<ILeveledPackInGetter> ENV_LPI_GasVent_ToxicGas_Statics => Construct(0x1e0245);
        public static FormLink<ILeveledPackInGetter> ENV_LPI_GasVent_Small_OBSOLETE => Construct(0x2184c5);
        public static FormLink<ILeveledPackInGetter> ENV_LPI_GasVent_Large_OBSOLETE => Construct(0x2184cc);
        public static FormLink<ILeveledPackInGetter> LVLPI_PCM_Manmade_CratesSmall02 => Construct(0x2197db);
        public static FormLink<ILeveledPackInGetter> LVLPI_PCM_Manmade_SmallClutter50 => Construct(0x2197e4);
        public static FormLink<ILeveledPackInGetter> LVLPI_AsteroidsRockyLarge => Construct(0x21a7ec);
        public static FormLink<ILeveledPackInGetter> LVLPI_AsteroidsRockyXLarge => Construct(0x21a7ed);
        public static FormLink<ILeveledPackInGetter> LVLPI_AsteroidsRockyMedium => Construct(0x21a7fa);
        public static FormLink<ILeveledPackInGetter> LVLPI_ResourcesSolidPocked => Construct(0x21d5e3);
        public static FormLink<ILeveledPackInGetter> LVLPI_ResourcesSolidIce => Construct(0x226abc);
        public static FormLink<ILeveledPackInGetter> LVLPI_PCM_Manmade_CratesShipping => Construct(0x2512b5);
        public static FormLink<ILeveledPackInGetter> OECave_InorgResourceGasLiquid_Bonus_Packin => Construct(0x25180f);
        public static FormLink<ILeveledPackInGetter> OECave_InorgResourceGasLiquid_Leveled_Packin => Construct(0x251818);
        public static FormLink<ILeveledPackInGetter> LVLPI_PCM_Manmade_CratesShipping50 => Construct(0x251d53);
        public static FormLink<ILeveledPackInGetter> LVLPI_ResourcesLiquid => Construct(0x2543b2);
        public static FormLink<ILeveledPackInGetter> LVLPI_ResourcesGas => Construct(0x2543b3);
        public static FormLink<ILeveledPackInGetter> ClutterLPI_Tabletop_Ind_Med01 => Construct(0x26bafa);
        public static FormLink<ILeveledPackInGetter> ClutterLPI_Shelf_Ind_SmLow => Construct(0x26bafb);
        public static FormLink<ILeveledPackInGetter> ClutterLPI_Shelf_Ind_Sm => Construct(0x26bbfa);
        public static FormLink<ILeveledPackInGetter> LVLPI_ResourcesSolidLayered => Construct(0x2d41b5);
        public static FormLink<ILeveledPackInGetter> LVLPI_ResourcesSolidRough => Construct(0x2d41b6);
        public static FormLink<ILeveledPackInGetter> LVLPI_ResourcesSolidSediment => Construct(0x2d41b7);
        public static FormLink<ILeveledPackInGetter> LVLPI_ResourcesSolidSharp => Construct(0x2d41b8);
        public static FormLink<ILeveledPackInGetter> LVLPI_ResourcesSolidVeiny => Construct(0x2d41b9);
        public static FormLink<ILeveledPackInGetter> LVLPI_ResourcesSolidVolcanicRough => Construct(0x2d41ba);
        public static FormLink<ILeveledPackInGetter> LVLPI_ResourcesSolidVolcanicWorn => Construct(0x2d41bb);
        public static FormLink<ILeveledPackInGetter> OECave_InorgResource_Leveled_Packin => Construct(0x2dddf0);
    }
}
