// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class Starfield
{
    public static partial class LeveledSpaceCell
    {
        private static FormLink<ILeveledSpaceCellGetter> Construct(uint id) => new FormLink<ILeveledSpaceCellGetter>(ModKey.MakeFormKey(id));
        public static FormLink<ILeveledSpaceCellGetter> LVLSC_SpacePOIsObjectsOnly => Construct(0x131149);
        public static FormLink<ILeveledSpaceCellGetter> LVLSC_Icy => Construct(0x1d8552);
        public static FormLink<ILeveledSpaceCellGetter> LVLSC_Rocky => Construct(0x1d8553);
        public static FormLink<ILeveledSpaceCellGetter> LVLSC_Empty => Construct(0x1d8554);
        public static FormLink<ILeveledSpaceCellGetter> LVLSC_DebrisFields => Construct(0x1f91ee);
        public static FormLink<ILeveledSpaceCellGetter> LVLSC_AllSpacePOIs => Construct(0x2239d9);
    }
}
