// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class Starfield
{
    public static partial class MovementType
    {
        private static FormLink<IMovementTypeGetter> Construct(uint id) => new FormLink<IMovementTypeGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IMovementTypeGetter> Human_Default_MT => Construct(0x3482);
        public static FormLink<IMovementTypeGetter> ModelA_Default_MT => Construct(0x584f);
        public static FormLink<IMovementTypeGetter> Human_Sneak_MT => Construct(0x7f6f);
        public static FormLink<IMovementTypeGetter> Spaceship_Default => Construct(0x8e74);
        public static FormLink<IMovementTypeGetter> Human_Sighted_MT => Construct(0xc481);
        public static FormLink<IMovementTypeGetter> ModelS_Default_MT => Construct(0x130f8);
        public static FormLink<IMovementTypeGetter> CritterDefault_MT => Construct(0x177e7);
        public static FormLink<IMovementTypeGetter> NPC_Sneak_MT => Construct(0x18a58);
        public static FormLink<IMovementTypeGetter> ModelA_Injured_MT => Construct(0x18b28);
        public static FormLink<IMovementTypeGetter> Human_Injured_MT => Construct(0x18d7a);
        public static FormLink<IMovementTypeGetter> Human_SneakSighted_MT => Construct(0x1a0d7);
        public static FormLink<IMovementTypeGetter> CreatureSwimmer_Default_MT => Construct(0x24bc3);
        public static FormLink<IMovementTypeGetter> FloaterADefault_MT => Construct(0x2e9be);
        public static FormLink<IMovementTypeGetter> NPC_Default_MT => Construct(0x3580d);
        public static FormLink<IMovementTypeGetter> NPC_Swimming_MT => Construct(0x36d42);
        public static FormLink<IMovementTypeGetter> ModelT_Default_MT => Construct(0x463c9);
        public static FormLink<IMovementTypeGetter> Spaceship_NonModular_MT => Construct(0x51b25);
        public static FormLink<IMovementTypeGetter> Human_Blocking_MT => Construct(0x5576e);
        public static FormLink<IMovementTypeGetter> NPC_BleedOut_MT => Construct(0x57f68);
        public static FormLink<IMovementTypeGetter> NPC_Blocking_MT => Construct(0x57f69);
        public static FormLink<IMovementTypeGetter> NPC_Injured_MT => Construct(0x57f6a);
        public static FormLink<IMovementTypeGetter> NPC_Sighted_MT => Construct(0x57f6b);
        public static FormLink<IMovementTypeGetter> NPC_SneakSighted_MT => Construct(0x57f6c);
        public static FormLink<IMovementTypeGetter> Human_BleedOut_MT => Construct(0x57f6e);
        public static FormLink<IMovementTypeGetter> NPC_Ready_MT => Construct(0x6ca99);
        public static FormLink<IMovementTypeGetter> NPC_ZeroGBleedOut_MT => Construct(0xbe375);
        public static FormLink<IMovementTypeGetter> FlyerA_Default_MT => Construct(0xe66a5);
        public static FormLink<IMovementTypeGetter> AIControlledNPC_Sprinting_MT => Construct(0xf3469);
        public static FormLink<IMovementTypeGetter> Terrormorph_Default_MT => Construct(0xf5982);
        public static FormLink<IMovementTypeGetter> Human_FastWalk_MT => Construct(0x12ac09);
        public static FormLink<IMovementTypeGetter> Human_Swimming_MT => Construct(0x15598b);
        public static FormLink<IMovementTypeGetter> ParasiteA_Default_MT => Construct(0x22c0bb);
        public static FormLink<IMovementTypeGetter> NPC_ZeroG_MT => Construct(0x28bed1);
        public static FormLink<IMovementTypeGetter> Human_ZeroG_MT => Construct(0x28bed2);
        public static FormLink<IMovementTypeGetter> MantaA_Default_MT => Construct(0x2a79c4);
        public static FormLink<IMovementTypeGetter> CritterStrafing_MT => Construct(0x2a9540);
        public static FormLink<IMovementTypeGetter> CreatureStrafing_Default_MT => Construct(0x2ce281);
        public static FormLink<IMovementTypeGetter> CreatureStrafing_Block_MT => Construct(0x2ce282);
        public static FormLink<IMovementTypeGetter> CreatureStrafing_BleedOut_MT => Construct(0x2ce283);
        public static FormLink<IMovementTypeGetter> CreatureNonStrafing_BleedOut_MT => Construct(0x2cf5e2);
        public static FormLink<IMovementTypeGetter> CreatureNonStrafing_Default_MT => Construct(0x2cf5e3);
        public static FormLink<IMovementTypeGetter> CreatureNonStrafing_Block_MT => Construct(0x2cf5e4);
        public static FormLink<IMovementTypeGetter> Terrormorph_Elder_MT => Construct(0x3e4f52);
    }
}
