// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class Starfield
{
    public static partial class MusicType
    {
        private static FormLink<IMusicTypeGetter> Construct(uint id) => new FormLink<IMusicTypeGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IMusicTypeGetter> MUSDiscoveryLocationCave => Construct(0x2954);
        public static FormLink<IMusicTypeGetter> MUSDiscoveryLocationCity => Construct(0x2955);
        public static FormLink<IMusicTypeGetter> MUSDiscoveryLocationDungeon => Construct(0x2956);
        public static FormLink<IMusicTypeGetter> MUSDiscoveryLocationMainThemeA => Construct(0x2957);
        public static FormLink<IMusicTypeGetter> MUSDiscoveryLocationMainThemeB => Construct(0x2958);
        public static FormLink<IMusicTypeGetter> MUSDiscoveryLocationSpace => Construct(0x2ced);
        public static FormLink<IMusicTypeGetter> MUSGenesisStingerDread4TerrormorphTransform => Construct(0x7d99);
        public static FormLink<IMusicTypeGetter> MUSGenesisSpaceMASTER => Construct(0x7e17);
        public static FormLink<IMusicTypeGetter> MUSGenesisSpaceStationA => Construct(0x7eff);
        public static FormLink<IMusicTypeGetter> MUSGenesisSpecialChargenWakeUp => Construct(0xa1b5);
        public static FormLink<IMusicTypeGetter> MUSGenesisPlanetA_Mountains => Construct(0xc5d2);
        public static FormLink<IMusicTypeGetter> MUSGenesisDungeonCaveA => Construct(0x107d0);
        public static FormLink<IMusicTypeGetter> MUSGenesisCityA_NewAtlantis => Construct(0x10dfe);
        public static FormLink<IMusicTypeGetter> MUSGenesisSpecialDeath => Construct(0x13686);
        public static FormLink<IMusicTypeGetter> MUSGenesisCombat => Construct(0x13d5f);
        public static FormLink<IMusicTypeGetter> MUSGenesisCityB_Cydonia => Construct(0x13d61);
        public static FormLink<IMusicTypeGetter> _NONE => Construct(0x1ba72);
        public static FormLink<IMusicTypeGetter> MUSGenesisDungeonIndustrialA => Construct(0x21bff);
        public static FormLink<IMusicTypeGetter> MUSGenesisCityC_Akila => Construct(0x2428c);
        public static FormLink<IMusicTypeGetter> BE_KT02_MUSPartyTrack => Construct(0x27a44);
        public static FormLink<IMusicTypeGetter> MUSGenesisSpaceXBoardingDerelict => Construct(0x3138b);
        public static FormLink<IMusicTypeGetter> MUSGenesisSpecialLevelUp => Construct(0x3b565);
        public static FormLink<IMusicTypeGetter> MUSGenesisStingerGravJumpUnity => Construct(0x414c1);
        public static FormLink<IMusicTypeGetter> MUSGenesisStingerReveal4PlayerExitsHab => Construct(0x4565e);
        public static FormLink<IMusicTypeGetter> _PIPBOY_MUSIC_BLOCKER => Construct(0x498d6);
        public static FormLink<IMusicTypeGetter> MUSGenesisSpecialArtifactVision => Construct(0x59650);
        public static FormLink<IMusicTypeGetter> MUSGenesisStingerDread3Large => Construct(0x5b523);
        public static FormLink<IMusicTypeGetter> MUSGenesisStingerReveal3Large => Construct(0x5b524);
        public static FormLink<IMusicTypeGetter> MUSGenesisStingerFlightStart => Construct(0x5b862);
        public static FormLink<IMusicTypeGetter> MUSGenesisStingerReveal1Small => Construct(0x5e5a3);
        public static FormLink<IMusicTypeGetter> MUSGenesisStingerCutsceneTransitionTEST => Construct(0x5f841);
        public static FormLink<IMusicTypeGetter> MUSGenesisSpecialCardTitleOpening => Construct(0x66316);
        public static FormLink<IMusicTypeGetter> MUSGenesisStingerGravJumpStart => Construct(0x698ae);
        public static FormLink<IMusicTypeGetter> MUSGenesisStingerGravJumpStop => Construct(0x698af);
        public static FormLink<IMusicTypeGetter> MUSGenesisStingerReveal2Medium => Construct(0x6d203);
        public static FormLink<IMusicTypeGetter> MUSGenesisSpaceMASTER_LowestPriotityForStarmap => Construct(0x812f1);
        public static FormLink<IMusicTypeGetter> MUSGenesisPlanet_LC032LondinionWorld => Construct(0x87f27);
        public static FormLink<IMusicTypeGetter> MUSGenesisCombatBoss_MQ302B_A_Battles => Construct(0x972fe);
        public static FormLink<IMusicTypeGetter> MUSGenesisCityA_NewAtlantisVaruunEmbassy => Construct(0xc5856);
        public static FormLink<IMusicTypeGetter> MUSGenesisPlanetA_Mountains_LC001World_Vectera => Construct(0xf770e);
        public static FormLink<IMusicTypeGetter> MUSGenesisSpaceA => Construct(0x12342b);
        public static FormLink<IMusicTypeGetter> MUSGenesisDungeon_LC062TauGourmetWorld => Construct(0x12cc75);
        public static FormLink<IMusicTypeGetter> _MUSExplore_WwiseSilence => Construct(0x13e4e7);
        public static FormLink<IMusicTypeGetter> MUSGenesisStingerStarbornAppear => Construct(0x141d6e);
        public static FormLink<IMusicTypeGetter> MUSGenesisCitySettlement => Construct(0x17b4f3);
        public static FormLink<IMusicTypeGetter> MUSGenesisSpaceC => Construct(0x17e00d);
        public static FormLink<IMusicTypeGetter> MUSGenesisDungeonIndustrialC => Construct(0x1804d6);
        public static FormLink<IMusicTypeGetter> MUSGenesisCityD_Neon => Construct(0x1804d9);
        public static FormLink<IMusicTypeGetter> MUSGenesisCombatBoss_MQ302B_B_BattleFinal => Construct(0x18a2bc);
        public static FormLink<IMusicTypeGetter> MUSGenesisSpaceStationBTheEye => Construct(0x1a0d9c);
        public static FormLink<IMusicTypeGetter> MUSGenesisCombatBoss_CF08SpaceBattle => Construct(0x1a427f);
        public static FormLink<IMusicTypeGetter> MUSGenesisPlanetF_FrozenAndOcean => Construct(0x1a6ef2);
        public static FormLink<IMusicTypeGetter> MUSGenesisSpecialUnity => Construct(0x1b5104);
        public static FormLink<IMusicTypeGetter> MUS_DiscoverLocation_MainThemeC_Obelisk => Construct(0x1baa12);
        public static FormLink<IMusicTypeGetter> MUSGenesisStingerStarbornAppearB => Construct(0x1bc2bf);
        public static FormLink<IMusicTypeGetter> MUSGenesisStingerStarbornAppearC => Construct(0x1bc2c0);
        public static FormLink<IMusicTypeGetter> MUSGenesisCombatBoss_CF08VigilanceAndKey => Construct(0x1bd418);
        public static FormLink<IMusicTypeGetter> MUSGenesisCity_TheWell => Construct(0x1d6184);
        public static FormLink<IMusicTypeGetter> MUSGenesisStingerDread1Small => Construct(0x1f006d);
        public static FormLink<IMusicTypeGetter> MUSGenesisStingerDread2Medium => Construct(0x1f006e);
        public static FormLink<IMusicTypeGetter> MUSGenesisCombatBoss_MQ302_SpaceBattle => Construct(0x1f075c);
        public static FormLink<IMusicTypeGetter> MUSGenesisDungeon_LC042BattleOfNira => Construct(0x1f324b);
        public static FormLink<IMusicTypeGetter> MUSGenesisSpecialCredits => Construct(0x210e0c);
        public static FormLink<IMusicTypeGetter> MUSGenesisCombatBoss_MQ204_A_Hunter => Construct(0x212fdf);
        public static FormLink<IMusicTypeGetter> MUSGenesisStingerOutpostEstablishedMusicType => Construct(0x237bec);
        public static FormLink<IMusicTypeGetter> MUSGenesisFactionFreestar => Construct(0x23c7f8);
        public static FormLink<IMusicTypeGetter> MUSGenesisSpecialStarbornPowerReceived => Construct(0x23cebb);
        public static FormLink<IMusicTypeGetter> MUSGenesisSpaceB => Construct(0x2407f9);
        public static FormLink<IMusicTypeGetter> MUSGenesisFactionStarbornUnity => Construct(0x2496ab);
        public static FormLink<IMusicTypeGetter> MUSGenesisSpecialChargenComplete => Construct(0x251f4b);
        public static FormLink<IMusicTypeGetter> MUSGenesisCombat_MQ101SpaceBattle => Construct(0x25af25);
        public static FormLink<IMusicTypeGetter> MUSGenesisFactionMilitaryA => Construct(0x260ba7);
        public static FormLink<IMusicTypeGetter> MUSGenesisCombatBoss_Key => Construct(0x26fcc5);
        public static FormLink<IMusicTypeGetter> MUSGenesisCombatBoss_Vigilance => Construct(0x26fcc6);
        public static FormLink<IMusicTypeGetter> MUSGenesisDungeonCaveB => Construct(0x2733a5);
        public static FormLink<IMusicTypeGetter> MUSGenesisCombat_UC04 => Construct(0x2aa950);
        public static FormLink<IMusicTypeGetter> MUSGenesisDungeonIndustrialB => Construct(0x2be2db);
        public static FormLink<IMusicTypeGetter> MUSDiscoveryLocationGeneric => Construct(0x2c0318);
        public static FormLink<IMusicTypeGetter> MUSGenesisPlanetE_Desert => Construct(0x2c2eac);
        public static FormLink<IMusicTypeGetter> MUSGenesisCombat_MQ207C_Nishina => Construct(0x2c3e79);
        public static FormLink<IMusicTypeGetter> MUSGenesisPlanetD_Volcanic => Construct(0x2c5752);
        public static FormLink<IMusicTypeGetter> MUSGenesisPlanetC_Forest => Construct(0x2c7ac7);
        public static FormLink<IMusicTypeGetter> MUSGenesisPlanetB_Hills => Construct(0x2cd295);
    }
}
