// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class Starfield
{
    public static partial class ParticleSystemDefineCollision
    {
        private static FormLink<IParticleSystemDefineCollisionGetter> Construct(uint id) => new FormLink<IParticleSystemDefineCollisionGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IParticleSystemDefineCollisionGetter> TracerRifle01 => Construct(0xe3b9);
        public static FormLink<IParticleSystemDefineCollisionGetter> SpaceDust => Construct(0x12c9e6);
        public static FormLink<IParticleSystemDefineCollisionGetter> ShipWeaponImpact_PDC => Construct(0x13d923);
        public static FormLink<IParticleSystemDefineCollisionGetter> NPCImpactsJump_Medium => Construct(0x13ec18);
        public static FormLink<IParticleSystemDefineCollisionGetter> NPCImpactsWalk_Large => Construct(0x1410ae);
        public static FormLink<IParticleSystemDefineCollisionGetter> NPCImpactsWalk_Medium => Construct(0x144d73);
        public static FormLink<IParticleSystemDefineCollisionGetter> Weapon_Tracers => Construct(0x238fa8);
        public static FormLink<IParticleSystemDefineCollisionGetter> TerrormorphMeleeImpactSet_PDC => Construct(0x2efcc3);
        public static FormLink<IParticleSystemDefineCollisionGetter> TerrormorphMeleePowermpactSet_PDC => Construct(0x2efcc4);
    }
}
