// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class Starfield
{
    public static partial class PhotoModeFeature
    {
        private static FormLink<IPhotoModeFeatureGetter> Construct(uint id) => new FormLink<IPhotoModeFeatureGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IPhotoModeFeatureGetter> PhotoModeFrame_Letterbox01 => Construct(0x7e2ca);
        public static FormLink<IPhotoModeFeatureGetter> PhotoModeFrame_BookCover => Construct(0x100a0b);
        public static FormLink<IPhotoModeFeatureGetter> PhotoModeFrame_Chronomark => Construct(0x100a0c);
        public static FormLink<IPhotoModeFeatureGetter> PhotoModeFrame_Danger => Construct(0x100a0d);
        public static FormLink<IPhotoModeFeatureGetter> PhotoModeFrame_Forever => Construct(0x100a0f);
        public static FormLink<IPhotoModeFeatureGetter> PhotoModeFrame_Into => Construct(0x100a10);
        public static FormLink<IPhotoModeFeatureGetter> PhotoModeFrame_Launch => Construct(0x100a12);
        public static FormLink<IPhotoModeFeatureGetter> PhotoModeFrame_Freestar => Construct(0x100a13);
        public static FormLink<IPhotoModeFeatureGetter> PhotoModeFrame_GravWave => Construct(0x100a14);
        public static FormLink<IPhotoModeFeatureGetter> PhotoModeFrame_LogoBracketed => Construct(0x100a15);
        public static FormLink<IPhotoModeFeatureGetter> PhotoModeFrame_LogoWave => Construct(0x100a16);
        public static FormLink<IPhotoModeFeatureGetter> PhotoModeFrame_Quote => Construct(0x100a17);
        public static FormLink<IPhotoModeFeatureGetter> PhotoModeFrame_Wanderers => Construct(0x100a18);
        public static FormLink<IPhotoModeFeatureGetter> PhotoModeFrame_Ryujin => Construct(0x100a1f);
        public static FormLink<IPhotoModeFeatureGetter> PhotoModeFrame_Vanguard => Construct(0x100a20);
        public static FormLink<IPhotoModeFeatureGetter> PhotoModeFrame_FieldScope => Construct(0x100a22);
        public static FormLink<IPhotoModeFeatureGetter> PhotoModeFrame_StripesVert => Construct(0x100a25);
        public static FormLink<IPhotoModeFeatureGetter> PhotoModeFrame_StripesHoriz => Construct(0x100a26);
        public static FormLink<IPhotoModeFeatureGetter> PhotoModeFrame_Constellation => Construct(0x100a27);
        public static FormLink<IPhotoModeFeatureGetter> PhotoModeFrame_Nasa => Construct(0x100a28);
        public static FormLink<IPhotoModeFeatureGetter> PhotoModeFrame_LogoSmall => Construct(0x100a29);
        public static FormLink<IPhotoModeFeatureGetter> PhotoModeFrame_LogoMed => Construct(0x100a2a);
        public static FormLink<IPhotoModeFeatureGetter> PhotoModeTexture_ReseauGrid => Construct(0x100b65);
        public static FormLink<IPhotoModeFeatureGetter> PhotoModeTexture_ReseauGrid2 => Construct(0x100b66);
        public static FormLink<IPhotoModeFeatureGetter> PhotoModeTexture_OpticReticle1 => Construct(0x100b69);
        public static FormLink<IPhotoModeFeatureGetter> PhotoModeTexture_OpticReticle2 => Construct(0x100b6a);
        public static FormLink<IPhotoModeFeatureGetter> NoirPhotoModeFeatureFilter1 => Construct(0x103407);
        public static FormLink<IPhotoModeFeatureGetter> BlackWhitePhotoModeFeatureFilter1 => Construct(0x103408);
        public static FormLink<IPhotoModeFeatureGetter> NightVisionPhotoModeFeatureFilter1 => Construct(0x103bc8);
        public static FormLink<IPhotoModeFeatureGetter> RedShiftPhotoModeFeatureFilter2 => Construct(0x1239fa);
        public static FormLink<IPhotoModeFeatureGetter> BlueShiftPhotoModeFeatureFilter1 => Construct(0x1239fb);
        public static FormLink<IPhotoModeFeatureGetter> BleachPhotoModeFeatureFilter1 => Construct(0x1c9975);
        public static FormLink<IPhotoModeFeatureGetter> BluePhotoModeFeatureFilter1 => Construct(0x1c9976);
        public static FormLink<IPhotoModeFeatureGetter> CandlesPhotoModeFeatureFilter1 => Construct(0x1c9977);
        public static FormLink<IPhotoModeFeatureGetter> CrispCoolPhotoModeFeatureFilter1 => Construct(0x1c9978);
        public static FormLink<IPhotoModeFeatureGetter> EnhancedPhotoModeFeatureFilter1 => Construct(0x1c9979);
        public static FormLink<IPhotoModeFeatureGetter> FallPhotoModeFeatureFilter1 => Construct(0x1c9bdc);
        public static FormLink<IPhotoModeFeatureGetter> GammaPhotoModeFeatureFilter1 => Construct(0x1c9bdd);
        public static FormLink<IPhotoModeFeatureGetter> HorrorPhotoModeFeatureFilter1 => Construct(0x1c9bde);
        public static FormLink<IPhotoModeFeatureGetter> MarsPhotoModeFeatureFilter1 => Construct(0x1c9be0);
        public static FormLink<IPhotoModeFeatureGetter> NeonPartyPhotoModeFeatureFilter1 => Construct(0x1c9be1);
        public static FormLink<IPhotoModeFeatureGetter> NeptunePhotoModeFeatureFilter1 => Construct(0x1c9be2);
        public static FormLink<IPhotoModeFeatureGetter> NovaPhotoModeFeatureFilter1 => Construct(0x1c9be3);
        public static FormLink<IPhotoModeFeatureGetter> OnlyRedPhotoModeFeatureFilter1 => Construct(0x1cedd3);
        public static FormLink<IPhotoModeFeatureGetter> SoftVintagePhotoModeFeatureFilter1 => Construct(0x1cedd4);
        public static FormLink<IPhotoModeFeatureGetter> SweetPhotoModeFeatureFilter1 => Construct(0x1e5be1);
        public static FormLink<IPhotoModeFeatureGetter> VibrantPhotoModeFeatureFilter1 => Construct(0x1e5be2);
        public static FormLink<IPhotoModeFeatureGetter> WarmPhotoModeFeatureFilter1 => Construct(0x1e5bee);
        public static FormLink<IPhotoModeFeatureGetter> SwampPhotoModeFeatureFilter1 => Construct(0x226380);
        public static FormLink<IPhotoModeFeatureGetter> AbandonedPhotoModeFeatureFilter1 => Construct(0x226381);
        public static FormLink<IPhotoModeFeatureGetter> BloodshotPhotoModeFeatureFilter1 => Construct(0x226382);
        public static FormLink<IPhotoModeFeatureGetter> VintagePhotoModeFeatureFilter1 => Construct(0x226383);
        public static FormLink<IPhotoModeFeatureGetter> DustyPhotoModeFeatureFilter1 => Construct(0x226384);
        public static FormLink<IPhotoModeFeatureGetter> Apollo1PhotoModeFeatureFilter1 => Construct(0x226385);
        public static FormLink<IPhotoModeFeatureGetter> BinaryPhotoModeFeatureFilter1 => Construct(0x226386);
        public static FormLink<IPhotoModeFeatureGetter> GrungePhotoModeFeatureFilter1 => Construct(0x226387);
        public static FormLink<IPhotoModeFeatureGetter> DystopiaPhotoModeFeatureFilter1 => Construct(0x226388);
        public static FormLink<IPhotoModeFeatureGetter> AstralPhotoModeFeatureFilter1 => Construct(0x226389);
        public static FormLink<IPhotoModeFeatureGetter> PearlescentPhotoModeFeatureFilter1 => Construct(0x22638a);
        public static FormLink<IPhotoModeFeatureGetter> NegativePhotoModeFeatureFilter1 => Construct(0x22638b);
        public static FormLink<IPhotoModeFeatureGetter> Apollo2PhotoModeFeatureFilter1 => Construct(0x22638c);
        public static FormLink<IPhotoModeFeatureGetter> MercuryPhotoModeFeatureFilter1 => Construct(0x22638d);
        public static FormLink<IPhotoModeFeatureGetter> GeminiPhotoModeFeatureFilter1 => Construct(0x22638e);
        public static FormLink<IPhotoModeFeatureGetter> BleachBypassPhotoModeFeatureFilter1 => Construct(0x22638f);
        public static FormLink<IPhotoModeFeatureGetter> PhotoModeFrame_FlightManual => Construct(0x2c3b86);
        public static FormLink<IPhotoModeFeatureGetter> PhotoModeFrame_Constellation2 => Construct(0x2c3b87);
        public static FormLink<IPhotoModeFeatureGetter> PhotoModeFrame_Constellation3 => Construct(0x2c3b88);
        public static FormLink<IPhotoModeFeatureGetter> PhotoModeFrame_Poster => Construct(0x2c3b89);
        public static FormLink<IPhotoModeFeatureGetter> PhotoModeFrame_Crimson => Construct(0x2c3b8a);
        public static FormLink<IPhotoModeFeatureGetter> PhotoModeFrame_UC => Construct(0x2c3b8b);
        public static FormLink<IPhotoModeFeatureGetter> PhotoModeFrame_FieldNotes => Construct(0x2c3b8c);
        public static FormLink<IPhotoModeFeatureGetter> PhotoModeFrame_ViewFinder => Construct(0x2c3b8d);
        public static FormLink<IPhotoModeFeatureGetter> PhotoModeFrame_ReseauPlate => Construct(0x2c3b8e);
        public static FormLink<IPhotoModeFeatureGetter> PhotoModeFrame_LogoFrameBlue => Construct(0x2c3b8f);
        public static FormLink<IPhotoModeFeatureGetter> PhotoModeFrame_LogoFrameWhite => Construct(0x2c3b90);
    }
}
