// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class Starfield
{
    public static partial class PlanetContentManagerTree
    {
        private static FormLink<IPlanetContentManagerTreeGetter> Construct(uint id) => new FormLink<IPlanetContentManagerTreeGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IPlanetContentManagerTreeGetter> PCM_SpaceshipLandingRequest => Construct(0x18bb1);
        public static FormLink<IPlanetContentManagerTreeGetter> PCM_BlockCreationRequest => Construct(0x5b625);
        public static FormLink<IPlanetContentManagerTreeGetter> PCM_CellLoadRequest => Construct(0x5b62b);
        public static FormLink<IPlanetContentManagerTreeGetter> PCM_ScanPlanetRequest => Construct(0x5b62c);
        public static FormLink<IPlanetContentManagerTreeGetter> PCM_QuestRequest => Construct(0xf455a);
    }
}
