// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class Starfield
{
    public static partial class Region
    {
        private static FormLink<IRegionGetter> Construct(uint id) => new FormLink<IRegionGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IRegionGetter> Region112 => Construct(0x45a50);
        public static FormLink<IRegionGetter> AudioExtGoodneighbor => Construct(0x117eba);
        public static FormLink<IRegionGetter> SpaceRegion => Construct(0x249fa5);
    }
}
