// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class Starfield
{
    public static partial class ResearchProject
    {
        private static FormLink<IResearchProjectGetter> Construct(uint id) => new FormLink<IResearchProjectGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IResearchProjectGetter> Equipment_Research_Backpack_01 => Construct(0xc11a5);
        public static FormLink<IResearchProjectGetter> Equipment_Research_Backpack_02 => Construct(0xc11a6);
        public static FormLink<IResearchProjectGetter> Equipment_Research_Backpack_03 => Construct(0xc11a7);
        public static FormLink<IResearchProjectGetter> Outpost_Research_Decoration_02 => Construct(0x100b8a);
        public static FormLink<IResearchProjectGetter> Outpost_Research_Decoration_01 => Construct(0x100b8b);
        public static FormLink<IResearchProjectGetter> Outpost_Research_Decoration_03 => Construct(0x100b8c);
        public static FormLink<IResearchProjectGetter> Equipment_Research_Spacesuit_01 => Construct(0x1520b9);
        public static FormLink<IResearchProjectGetter> Equipment_Research_Spacesuit_02 => Construct(0x178d03);
        public static FormLink<IResearchProjectGetter> Equipment_Research_Spacesuit_03 => Construct(0x178d1a);
        public static FormLink<IResearchProjectGetter> Equipment_Research_Helmet_01 => Construct(0x178d1b);
        public static FormLink<IResearchProjectGetter> Equipment_Research_Helmet_02 => Construct(0x178d1c);
        public static FormLink<IResearchProjectGetter> Equipment_Research_Helmet_03 => Construct(0x178d1d);
        public static FormLink<IResearchProjectGetter> Weapon_Research_Ammo_01 => Construct(0x2c0d72);
        public static FormLink<IResearchProjectGetter> Weapon_Research_Ammo_02 => Construct(0x2c0d73);
        public static FormLink<IResearchProjectGetter> Weapon_Research_Ammo_03 => Construct(0x2c0d75);
        public static FormLink<IResearchProjectGetter> Weapon_Research_Blades_02 => Construct(0x2fb456);
        public static FormLink<IResearchProjectGetter> Weapon_Research_Blades_01 => Construct(0x2fb457);
        public static FormLink<IResearchProjectGetter> Weapon_Research_Handle_02 => Construct(0x2fb458);
        public static FormLink<IResearchProjectGetter> Weapon_Research_Handle_01 => Construct(0x2fb459);
        public static FormLink<IResearchProjectGetter> Weapon_Research_Magazine_03 => Construct(0x380c4d);
        public static FormLink<IResearchProjectGetter> Chem_Research_MedicalTreatment_01 => Construct(0x389eea);
        public static FormLink<IResearchProjectGetter> Chem_Research_MedicalTreatment_02 => Construct(0x389eeb);
        public static FormLink<IResearchProjectGetter> Chem_Research_MedicalTreatment_03 => Construct(0x389eec);
        public static FormLink<IResearchProjectGetter> Chem_Research_MedicalTreatment_04 => Construct(0x389eed);
        public static FormLink<IResearchProjectGetter> Chem_Research_PerformanceEnhancement_01 => Construct(0x389eef);
        public static FormLink<IResearchProjectGetter> Chem_Research_PerformanceEnhancement_02 => Construct(0x389ef0);
        public static FormLink<IResearchProjectGetter> Chem_Research_PerformanceEnhancement_03 => Construct(0x389ef1);
        public static FormLink<IResearchProjectGetter> Chem_Research_PerformanceEnhancement_04 => Construct(0x389ef2);
        public static FormLink<IResearchProjectGetter> Chem_Research_InnovativeSynthesis_01 => Construct(0x389ef4);
        public static FormLink<IResearchProjectGetter> Chem_Research_InnovativeSynthesis_02 => Construct(0x389ef5);
        public static FormLink<IResearchProjectGetter> Chem_Research_InnovativeSynthesis_03 => Construct(0x389ef6);
        public static FormLink<IResearchProjectGetter> Food_Research_Mixology_01 => Construct(0x389ef9);
        public static FormLink<IResearchProjectGetter> Food_Research_Mixology_02 => Construct(0x389efa);
        public static FormLink<IResearchProjectGetter> Food_Research_Mixology_03 => Construct(0x389efb);
        public static FormLink<IResearchProjectGetter> Food_Research_Mixology_04 => Construct(0x389efc);
        public static FormLink<IResearchProjectGetter> Food_Research_BeverageDevelopment_01 => Construct(0x389efd);
        public static FormLink<IResearchProjectGetter> Food_Research_BeverageDevelopment_02 => Construct(0x389efe);
        public static FormLink<IResearchProjectGetter> Food_Research_BeverageDevelopment_03 => Construct(0x389eff);
        public static FormLink<IResearchProjectGetter> Food_Research_BeverageDevelopment_04 => Construct(0x389f00);
        public static FormLink<IResearchProjectGetter> Food_Research_OldEarthCuisine_01 => Construct(0x389f01);
        public static FormLink<IResearchProjectGetter> Food_Research_OldEarthCuisine_02 => Construct(0x389f02);
        public static FormLink<IResearchProjectGetter> Food_Research_OldEarthCuisine_03 => Construct(0x389f03);
        public static FormLink<IResearchProjectGetter> Food_Research_OldEarthCuisine_04 => Construct(0x389f04);
        public static FormLink<IResearchProjectGetter> Food_Research_ExoticRecipes_01 => Construct(0x389f05);
        public static FormLink<IResearchProjectGetter> Food_Research_ExoticRecipes_02 => Construct(0x389f06);
        public static FormLink<IResearchProjectGetter> Food_Research_ExoticRecipes_03 => Construct(0x389f07);
        public static FormLink<IResearchProjectGetter> Food_Research_ExoticRecipes_04 => Construct(0x389f08);
        public static FormLink<IResearchProjectGetter> Outpost_Research_Horticulture_01 => Construct(0x389f09);
        public static FormLink<IResearchProjectGetter> Outpost_Research_Horticulture_02 => Construct(0x389f0a);
        public static FormLink<IResearchProjectGetter> Outpost_Research_ResourceExtraction_01 => Construct(0x389f0b);
        public static FormLink<IResearchProjectGetter> Outpost_Research_ResourceExtraction_02 => Construct(0x389f0c);
        public static FormLink<IResearchProjectGetter> Outpost_Research_OutpostDefense_01 => Construct(0x389f0d);
        public static FormLink<IResearchProjectGetter> Outpost_Research_OutpostDefense_02 => Construct(0x389f0e);
        public static FormLink<IResearchProjectGetter> Outpost_Research_Robots_01 => Construct(0x389f0f);
        public static FormLink<IResearchProjectGetter> Outpost_Research_Robots_02 => Construct(0x389f10);
        public static FormLink<IResearchProjectGetter> Outpost_Research_Manufacturing_01 => Construct(0x389f11);
        public static FormLink<IResearchProjectGetter> Outpost_Research_Manufacturing_02 => Construct(0x389f12);
        public static FormLink<IResearchProjectGetter> Outpost_Research_Manufacturing_03 => Construct(0x389f13);
        public static FormLink<IResearchProjectGetter> Outpost_Research_PowerGeneration_01 => Construct(0x389f14);
        public static FormLink<IResearchProjectGetter> Outpost_Research_PowerGeneration_02 => Construct(0x389f15);
        public static FormLink<IResearchProjectGetter> Outpost_Research_PowerGeneration_03 => Construct(0x389f16);
        public static FormLink<IResearchProjectGetter> Outpost_Research_PowerGeneration_04 => Construct(0x389f17);
        public static FormLink<IResearchProjectGetter> Weapon_Research_Barrel_01 => Construct(0x389f18);
        public static FormLink<IResearchProjectGetter> Weapon_Research_Barrel_02 => Construct(0x389f19);
        public static FormLink<IResearchProjectGetter> Weapon_Research_Magazine_01 => Construct(0x389f1a);
        public static FormLink<IResearchProjectGetter> Weapon_Research_Magazine_02 => Construct(0x389f1b);
        public static FormLink<IResearchProjectGetter> Weapon_Research_OpticsSights_01 => Construct(0x389f1c);
        public static FormLink<IResearchProjectGetter> Weapon_Research_OpticsSights_02 => Construct(0x389f1d);
        public static FormLink<IResearchProjectGetter> Weapon_Research_OpticsSights_03 => Construct(0x389f1e);
        public static FormLink<IResearchProjectGetter> Weapon_Research_Internal_01 => Construct(0x389f1f);
        public static FormLink<IResearchProjectGetter> Weapon_Research_Internal_02 => Construct(0x389f20);
        public static FormLink<IResearchProjectGetter> Weapon_Research_Internal_03 => Construct(0x389f21);
        public static FormLink<IResearchProjectGetter> Weapon_Research_Grip_01 => Construct(0x389f22);
        public static FormLink<IResearchProjectGetter> Weapon_Research_Grip_02 => Construct(0x389f23);
        public static FormLink<IResearchProjectGetter> Weapon_Research_Grip_03 => Construct(0x389f24);
        public static FormLink<IResearchProjectGetter> Weapon_Research_Receiver_01 => Construct(0x389f25);
        public static FormLink<IResearchProjectGetter> Weapon_Research_Receiver_02 => Construct(0x389f26);
        public static FormLink<IResearchProjectGetter> Weapon_Research_Muzzle_01 => Construct(0x389f27);
        public static FormLink<IResearchProjectGetter> Weapon_Research_Muzzle_02 => Construct(0x389f28);
        public static FormLink<IResearchProjectGetter> Weapon_Research_Muzzle_03 => Construct(0x389f29);
        public static FormLink<IResearchProjectGetter> Outpost_Research_Domestication_01 => Construct(0x3e3d4d);
        public static FormLink<IResearchProjectGetter> Outpost_Research_Domestication_02 => Construct(0x3e3d4e);
    }
}
