// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class Starfield
{
    public static partial class ResourceGenerationData
    {
        private static FormLink<IResourceGenerationDataGetter> Construct(uint id) => new FormLink<IResourceGenerationDataGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IResourceGenerationDataGetter> MountainDefaultRes => Construct(0x7edd);
        public static FormLink<IResourceGenerationDataGetter> MountainNoLifeDefaultRes => Construct(0x83d8);
        public static FormLink<IResourceGenerationDataGetter> ArchipelagoDefaultRes => Construct(0x83da);
        public static FormLink<IResourceGenerationDataGetter> DesertSandDefaultRes => Construct(0x83dd);
        public static FormLink<IResourceGenerationDataGetter> DesertRocksDefaultRes => Construct(0x83de);
        public static FormLink<IResourceGenerationDataGetter> CrateredNoLifeDefaultRes => Construct(0x83e0);
        public static FormLink<IResourceGenerationDataGetter> ForestConiferousRes => Construct(0x83e3);
        public static FormLink<IResourceGenerationDataGetter> HillsDefaultRes => Construct(0x83e6);
        public static FormLink<IResourceGenerationDataGetter> SavannaDefaultRes => Construct(0x83e7);
        public static FormLink<IResourceGenerationDataGetter> VolcanicDefaultRes => Construct(0x83ea);
        public static FormLink<IResourceGenerationDataGetter> WetlandsDefaultRes => Construct(0x83eb);
        public static FormLink<IResourceGenerationDataGetter> OceanDefaultRes => Construct(0x83ed);
        public static FormLink<IResourceGenerationDataGetter> FrozenBarrenDefaultRes => Construct(0x83f0);
        public static FormLink<IResourceGenerationDataGetter> HillsNoLifeDefaultRes => Construct(0x83f1);
        public static FormLink<IResourceGenerationDataGetter> CrateredNoLifeVecteraRes => Construct(0x12c876);
        public static FormLink<IResourceGenerationDataGetter> DesertRocksVecteraRes => Construct(0x12c877);
        public static FormLink<IResourceGenerationDataGetter> UniqueVolcanicNoLifeVerylRes => Construct(0x18cdff);
        public static FormLink<IResourceGenerationDataGetter> UniqueCrateredBarrenVytiniumRes => Construct(0x18ce00);
        public static FormLink<IResourceGenerationDataGetter> UniqueMountainNoLifeTasineRes => Construct(0x18ce01);
        public static FormLink<IResourceGenerationDataGetter> UniqueFrozenNoLifeIndiciteRes => Construct(0x18ce02);
        public static FormLink<IResourceGenerationDataGetter> UniqueTablelandsCanyonsAldumiteRes => Construct(0x18ce03);
        public static FormLink<IResourceGenerationDataGetter> UniqueHillsRothicitetRes => Construct(0x18ce04);
        public static FormLink<IResourceGenerationDataGetter> SavannaDefaultResSettled => Construct(0x203e9c);
        public static FormLink<IResourceGenerationDataGetter> FrozenBarrenDefaultResSettled => Construct(0x203e9d);
        public static FormLink<IResourceGenerationDataGetter> ForestDefaultResSettled => Construct(0x203e9e);
        public static FormLink<IResourceGenerationDataGetter> MountainDefaultRes_Kreet => Construct(0x244ccb);
        public static FormLink<IResourceGenerationDataGetter> VolcanicDefaultRes_Kreet => Construct(0x244ccc);
        public static FormLink<IResourceGenerationDataGetter> CanyonsDefaultRes => Construct(0x258050);
        public static FormLink<IResourceGenerationDataGetter> ForestTropicalRes => Construct(0x37c669);
        public static FormLink<IResourceGenerationDataGetter> ForestDeciduousRes => Construct(0x37c66c);
        public static FormLink<IResourceGenerationDataGetter> FrozenBarrenDefaultRes02 => Construct(0x37c66f);
        public static FormLink<IResourceGenerationDataGetter> FrozenBarrenDefaultRes03 => Construct(0x37c672);
    }
}
