// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class Starfield
{
    public static partial class ReverbParameters
    {
        private static FormLink<IReverbParametersGetter> Construct(uint id) => new FormLink<IReverbParametersGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IReverbParametersGetter> Reverb_D_Int_StarbornTemple_Large => Construct(0xa1b7);
        public static FormLink<IReverbParametersGetter> Reverb_C_IntRoomStoneMedium => Construct(0xc5b6c);
        public static FormLink<IReverbParametersGetter> DefaultReverb => Construct(0xc5b6e);
        public static FormLink<IReverbParametersGetter> Reverb_B_IntRoomStoneNarrow => Construct(0xe322e);
        public static FormLink<IReverbParametersGetter> Reverb_D_IntRoomStoneLarge => Construct(0xe3246);
        public static FormLink<IReverbParametersGetter> Reverb_D_Int_Cave_Large => Construct(0xf521c);
        public static FormLink<IReverbParametersGetter> Reverb_B_IntShipPlayableDefault => Construct(0x11687e);
        public static FormLink<IReverbParametersGetter> Reverb_A_IntIndustrialDungeonSmall => Construct(0x153e26);
        public static FormLink<IReverbParametersGetter> Reverb_B_IntStoneCaveTunnels => Construct(0x1e4f32);
        public static FormLink<IReverbParametersGetter> Reverb_D_IntNeonClubLarge => Construct(0x1ec6d6);
        public static FormLink<IReverbParametersGetter> Reverb_C_IntNeonClubMedium => Construct(0x1ec6d7);
        public static FormLink<IReverbParametersGetter> Reverb_B_IntNeonClubMedium => Construct(0x1ec6d8);
        public static FormLink<IReverbParametersGetter> Reverb_B_Int_Star_Station_Medium => Construct(0x1f96fa);
        public static FormLink<IReverbParametersGetter> Reverb_C_Int_Star_Station_Medium => Construct(0x1f96fb);
        public static FormLink<IReverbParametersGetter> Reverb_D_Int_Star_Station_Large => Construct(0x1f96fc);
        public static FormLink<IReverbParametersGetter> Reverb_E_IntIndustrialDungeonCavernLarge => Construct(0x1faa04);
        public static FormLink<IReverbParametersGetter> Reverb_B_IntIndustrialDungeonMedium => Construct(0x1faa05);
        public static FormLink<IReverbParametersGetter> Reverb_C_IntIndustrialDungeonMedium => Construct(0x1faa06);
        public static FormLink<IReverbParametersGetter> Reverb_D_IntIndustrialDungeonLarge => Construct(0x1faa07);
        public static FormLink<IReverbParametersGetter> Reverb_E_IntTestWeapon => Construct(0x1feb0e);
        public static FormLink<IReverbParametersGetter> Reverb_D_IntTestWeapon => Construct(0x1feb0f);
        public static FormLink<IReverbParametersGetter> Reverb_C_IntTestWeapon => Construct(0x1feb10);
        public static FormLink<IReverbParametersGetter> Reverb_B_IntTestWeapon => Construct(0x1feb11);
        public static FormLink<IReverbParametersGetter> Reverb_A_IntTestWeapon => Construct(0x1feb12);
        public static FormLink<IReverbParametersGetter> Reverb_B_IntGenericMedium => Construct(0x1ffc21);
        public static FormLink<IReverbParametersGetter> Reverb_C_IntGenericMedium => Construct(0x1ffc22);
        public static FormLink<IReverbParametersGetter> Reverb_B_IntIndustrialMedium => Construct(0x22d145);
        public static FormLink<IReverbParametersGetter> Reverb_C_IntHighTechMedium => Construct(0x2313d7);
        public static FormLink<IReverbParametersGetter> Reverb_B_IntHighTechMedium => Construct(0x2313d8);
        public static FormLink<IReverbParametersGetter> Reverb_E_IntStoneCaveLarge => Construct(0x238a9b);
        public static FormLink<IReverbParametersGetter> Reverb_D_IntIndustrialLarge => Construct(0x238bd6);
        public static FormLink<IReverbParametersGetter> Reverb_D_IntGenericLarge => Construct(0x238cd4);
        public static FormLink<IReverbParametersGetter> Reverb_C_IntIndustrialMedium => Construct(0x239b34);
        public static FormLink<IReverbParametersGetter> Reverb_B_IntFakeBrickMedium => Construct(0x239e57);
        public static FormLink<IReverbParametersGetter> Reverb_C_IntFakeBrickMedium => Construct(0x239e58);
        public static FormLink<IReverbParametersGetter> Reverb_D_IntFakeMetalLarge => Construct(0x239e60);
        public static FormLink<IReverbParametersGetter> Reverb_C_IntFakeMetalMedium => Construct(0x239e61);
        public static FormLink<IReverbParametersGetter> Reverb_B_IntFakeMetalMedium => Construct(0x239e62);
        public static FormLink<IReverbParametersGetter> Reverb_C_IntFakeWoodMedium => Construct(0x239e64);
        public static FormLink<IReverbParametersGetter> Reverb_B_IntFakeWoodMedium => Construct(0x239e65);
        public static FormLink<IReverbParametersGetter> Reverb_D_IntHighTechLarge => Construct(0x23ab4d);
    }
}
