// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class Starfield
{
    public static partial class SecondaryDamageList
    {
        private static FormLink<ISecondaryDamageListGetter> Construct(uint id) => new FormLink<ISecondaryDamageListGetter>(ModKey.MakeFormKey(id));
        public static FormLink<ISecondaryDamageListGetter> TRP_SDL_AllDamageTypes => Construct(0x200b27);
        public static FormLink<ISecondaryDamageListGetter> HzTest_2DL_Test_Barrel => Construct(0x208dca);
    }
}
