// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class Starfield
{
    public static partial class SnapTemplateBehavior
    {
        private static FormLink<ISnapTemplateBehaviorGetter> Construct(uint id) => new FormLink<ISnapTemplateBehaviorGetter>(ModKey.MakeFormKey(id));
        public static FormLink<ISnapTemplateBehaviorGetter> ShipBehavior_Ext_DoorPlugRemoval01 => Construct(0x4fb78);
        public static FormLink<ISnapTemplateBehaviorGetter> ShipBehavior_Int_HatchPlugs01 => Construct(0x51cf5);
        public static FormLink<ISnapTemplateBehaviorGetter> ShipBehavior_Int_Fore_HabHopeDocker_Replace => Construct(0x5b783);
        public static FormLink<ISnapTemplateBehaviorGetter> ShipBehavior_Int_Fore_HabHopeDocker_Remove => Construct(0x5b784);
        public static FormLink<ISnapTemplateBehaviorGetter> ShipBehavior_Int_Nova_ShipRmWall_PortStbd => Construct(0xb7bc3);
        public static FormLink<ISnapTemplateBehaviorGetter> ShipBehavior_Int_Nova_WallToDoorwayForeAft_Left => Construct(0xce207);
        public static FormLink<ISnapTemplateBehaviorGetter> OB_FoundationWatchtower01 => Construct(0xdb02c);
        public static FormLink<ISnapTemplateBehaviorGetter> ShipBehavior_Int_Nova_WallToDoorwayForeAft_Mid => Construct(0xe0b8c);
        public static FormLink<ISnapTemplateBehaviorGetter> ShipBehavior_Int_Nova_WallToDoorwayForeAft_Right => Construct(0xe0b8d);
        public static FormLink<ISnapTemplateBehaviorGetter> ShipBehavior_Int_Nova_WallToDoorwayForeAft_1Wide => Construct(0xe0bae);
        public static FormLink<ISnapTemplateBehaviorGetter> ShipBehavior_Int_ShpGenInt_WallToDoorwayStbd01A => Construct(0x127399);
        public static FormLink<ISnapTemplateBehaviorGetter> ShipBehavior_Int_ShpGenInt_WallToDoorwayPort01A => Construct(0x12739a);
        public static FormLink<ISnapTemplateBehaviorGetter> ShipBehavior_Int_ShpGenInt_WallToDoorwayAft01 => Construct(0x1273ae);
        public static FormLink<ISnapTemplateBehaviorGetter> OB_FoundationHarvesterLiquid01Sm => Construct(0x128445);
        public static FormLink<ISnapTemplateBehaviorGetter> OB_FoundationHarvesterLiquid01Med => Construct(0x12844a);
        public static FormLink<ISnapTemplateBehaviorGetter> OB_FoundationHarvesterLiquid01Large => Construct(0x128451);
        public static FormLink<ISnapTemplateBehaviorGetter> OB_FoundationHarvesterSolids01Med => Construct(0x14a686);
        public static FormLink<ISnapTemplateBehaviorGetter> OB_FoundationHarvesterSolids01Large => Construct(0x14a690);
        public static FormLink<ISnapTemplateBehaviorGetter> OB_FoundationPowerTurbineAdvanced01 => Construct(0x165532);
        public static FormLink<ISnapTemplateBehaviorGetter> OB_FoundationLandingPadSmall01 => Construct(0x16c1d0);
        public static FormLink<ISnapTemplateBehaviorGetter> OB_FoundationHarvesterFlora01 => Construct(0x176699);
        public static FormLink<ISnapTemplateBehaviorGetter> OB_FoundationHarvesterFlora02 => Construct(0x17669a);
        public static FormLink<ISnapTemplateBehaviorGetter> OB_FoundationHarvesterFlora03 => Construct(0x17669b);
        public static FormLink<ISnapTemplateBehaviorGetter> OB_FoundationGenAirlock01 => Construct(0x178a51);
        public static FormLink<ISnapTemplateBehaviorGetter> OB_OPG_HabPlugRemoval01 => Construct(0x178a53);
        public static FormLink<ISnapTemplateBehaviorGetter> OB_FoundationOutpostPowerConnector01 => Construct(0x17de96);
        public static FormLink<ISnapTemplateBehaviorGetter> OB_FoundationOpiExtLightPost01 => Construct(0x1cf8c8);
        public static FormLink<ISnapTemplateBehaviorGetter> OB_FoundationOpiExtLightPostLG01 => Construct(0x1cf8d2);
        public static FormLink<ISnapTemplateBehaviorGetter> OB_FoundationPowerReactor01Sm => Construct(0x1e7357);
        public static FormLink<ISnapTemplateBehaviorGetter> OB_FoundationStorage01Sm => Construct(0x1e7416);
        public static FormLink<ISnapTemplateBehaviorGetter> OB_FoundationStorage01Med => Construct(0x1e7417);
        public static FormLink<ISnapTemplateBehaviorGetter> OB_OPH_HabSmWalls01B => Construct(0x1e8d8b);
        public static FormLink<ISnapTemplateBehaviorGetter> OB_OPH_HabSmWalls01A => Construct(0x1e8d8c);
        public static FormLink<ISnapTemplateBehaviorGetter> OB_OPH_HabSmRndWalls01 => Construct(0x1e8d8d);
        public static FormLink<ISnapTemplateBehaviorGetter> OB_OPM_HabSmSide01 => Construct(0x1e8d8e);
        public static FormLink<ISnapTemplateBehaviorGetter> OB_OPM_HabSmFront01 => Construct(0x1e8d8f);
        public static FormLink<ISnapTemplateBehaviorGetter> OB_OPS_HabSmRndWalls01 => Construct(0x1e8d90);
        public static FormLink<ISnapTemplateBehaviorGetter> OB_OPM_HabSmBack01 => Construct(0x1e8d91);
        public static FormLink<ISnapTemplateBehaviorGetter> OB_OPS_HabSmWalls01B => Construct(0x1e8d92);
        public static FormLink<ISnapTemplateBehaviorGetter> OB_OPS_HabSmWalls01 => Construct(0x1e8d93);
        public static FormLink<ISnapTemplateBehaviorGetter> OB_OPI_HabMedWalls01 => Construct(0x1e8d94);
        public static FormLink<ISnapTemplateBehaviorGetter> OB_OPI_HabSmWalls01 => Construct(0x1e8d95);
        public static FormLink<ISnapTemplateBehaviorGetter> StnBehavior_Int_HelperToDoorway01Left => Construct(0x202eab);
        public static FormLink<ISnapTemplateBehaviorGetter> StnBehavior_Int_HelperToDoorway01Right => Construct(0x202eac);
        public static FormLink<ISnapTemplateBehaviorGetter> OB_FoundationHarvesterAtmospheric03Large => Construct(0x207703);
        public static FormLink<ISnapTemplateBehaviorGetter> OB_FoundationTransferContainer01 => Construct(0x207cd9);
        public static FormLink<ISnapTemplateBehaviorGetter> StnBehavior_Int_WallRemoval01 => Construct(0x209634);
        public static FormLink<ISnapTemplateBehaviorGetter> StnBehavior_Int_HelperToDoorway01 => Construct(0x209636);
        public static FormLink<ISnapTemplateBehaviorGetter> StnBehavior_Ext_DoorPlugRemoval01 => Construct(0x209646);
        public static FormLink<ISnapTemplateBehaviorGetter> OB_FoundationOPLPad_40m_Edge01 => Construct(0x219193);
        public static FormLink<ISnapTemplateBehaviorGetter> OB_FoundationPlatformLegsSm01 => Construct(0x2217a3);
        public static FormLink<ISnapTemplateBehaviorGetter> OB_FoundationPlatformLegsMed01 => Construct(0x2217a4);
        public static FormLink<ISnapTemplateBehaviorGetter> OB_FoundationStorage01Large => Construct(0x2217f3);
        public static FormLink<ISnapTemplateBehaviorGetter> OB_FoundationPlatformLegsLg01 => Construct(0x2217f7);
        public static FormLink<ISnapTemplateBehaviorGetter> ShipBehavior_Int_ShpIndInt_WallToDoorwayPortStbd01A => Construct(0x2254ef);
        public static FormLink<ISnapTemplateBehaviorGetter> ShipBehavior_Int_ShpIndInt_WallToDoorwayForeAft01 => Construct(0x2254f0);
        public static FormLink<ISnapTemplateBehaviorGetter> OB_FoundationBuilderAssembled01 => Construct(0x22a459);
        public static FormLink<ISnapTemplateBehaviorGetter> ShipBehavior_Int_ShpGenInt_WallToDoorwayFore01 => Construct(0x23334b);
        public static FormLink<ISnapTemplateBehaviorGetter> OB_FoundationCargoLink01 => Construct(0x23c31b);
        public static FormLink<ISnapTemplateBehaviorGetter> OB_FoundationHarvesterSolids01Sm => Construct(0x23c31f);
        public static FormLink<ISnapTemplateBehaviorGetter> OB_FoundationHarvesterAtmospheric01Sm => Construct(0x23eb4d);
        public static FormLink<ISnapTemplateBehaviorGetter> OB_FoundationBuilderFlora02 => Construct(0x23f812);
        public static FormLink<ISnapTemplateBehaviorGetter> OB_FoundationBuilderFlora01 => Construct(0x23f816);
        public static FormLink<ISnapTemplateBehaviorGetter> OB_FoundationPowerFueledGenerator01 => Construct(0x261683);
        public static FormLink<ISnapTemplateBehaviorGetter> OB_FoundationGenAirlock02 => Construct(0x27fad4);
        public static FormLink<ISnapTemplateBehaviorGetter> OB_FoundationLandingPad01 => Construct(0x28dabd);
        public static FormLink<ISnapTemplateBehaviorGetter> DEBUG_SnapBehavior_TestOutpostFoundationTower01 => Construct(0x2a08b5);
        public static FormLink<ISnapTemplateBehaviorGetter> OB_FoundationHab01 => Construct(0x2b29c0);
        public static FormLink<ISnapTemplateBehaviorGetter> ShipBehavior_Int_HabHope_WallToDoorwayPortStbd01A => Construct(0x2c5732);
        public static FormLink<ISnapTemplateBehaviorGetter> ShipBehavior_Int_Gen_HallSmCap01 => Construct(0x2cb845);
        public static FormLink<ISnapTemplateBehaviorGetter> OB_OPI_HabSmMidHex01 => Construct(0x2cbd26);
        public static FormLink<ISnapTemplateBehaviorGetter> OB_OPI_HabLgMidHex01 => Construct(0x2cf5f6);
        public static FormLink<ISnapTemplateBehaviorGetter> OB_FoundationHarvesterGas01Med => Construct(0x31588d);
        public static FormLink<ISnapTemplateBehaviorGetter> OB_FoundationHarvesterGas01Large => Construct(0x315896);
        public static FormLink<ISnapTemplateBehaviorGetter> OB_FoundationHarvesterGas01Sm => Construct(0x31589b);
        public static FormLink<ISnapTemplateBehaviorGetter> OB_FoundationRadarDish01 => Construct(0x3551c5);
        public static FormLink<ISnapTemplateBehaviorGetter> OB_FoundationReactor01 => Construct(0x3556d2);
        public static FormLink<ISnapTemplateBehaviorGetter> OB_FoundationBarn01Sm => Construct(0x3626c2);
        public static FormLink<ISnapTemplateBehaviorGetter> OB_FoundationBarn01Med => Construct(0x3626cc);
        public static FormLink<ISnapTemplateBehaviorGetter> OB_FoundationBarn01Lg => Construct(0x3626d4);
        public static FormLink<ISnapTemplateBehaviorGetter> OB_FoundationScanBooster03 => Construct(0x366162);
        public static FormLink<ISnapTemplateBehaviorGetter> OB_FoundationSolarDome01 => Construct(0x3684a3);
        public static FormLink<ISnapTemplateBehaviorGetter> OB_FoundationSolarArray01 => Construct(0x3684c3);
        public static FormLink<ISnapTemplateBehaviorGetter> OB_FoundationBuilderC01 => Construct(0x36eba4);
        public static FormLink<ISnapTemplateBehaviorGetter> OB_FoundationBuilderB01 => Construct(0x36ebad);
        public static FormLink<ISnapTemplateBehaviorGetter> OB_FoundationBuilderA01 => Construct(0x36ebb6);
        public static FormLink<ISnapTemplateBehaviorGetter> ShipBehavior_Int_CrossPassagePlugs01 => Construct(0x3e4024);
    }
}
