// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class Starfield
{
    public static partial class Traversal
    {
        private static FormLink<ITraversalGetter> Construct(uint id) => new FormLink<ITraversalGetter>(ModKey.MakeFormKey(id));
        public static FormLink<ITraversalGetter> TraversalActivateButton => Construct(0xa39e);
        public static FormLink<ITraversalGetter> TraversalJumpDefault => Construct(0xaff2);
        public static FormLink<ITraversalGetter> TraversalLadderEnterLeftUpExitLeft => Construct(0x1bcff);
        public static FormLink<ITraversalGetter> TraversalLadderEnterLeftDownExitLeft => Construct(0x1bd00);
        public static FormLink<ITraversalGetter> TraversalLadderEnterLeftUpExitRight => Construct(0x1bd01);
        public static FormLink<ITraversalGetter> TraversalLadderEnterLeftDownExitRight => Construct(0x1bd02);
        public static FormLink<ITraversalGetter> TraversalLadderEnterLeftDownExitBottom => Construct(0x1bd03);
        public static FormLink<ITraversalGetter> TraversalLadderEnterLeftUpExitTop => Construct(0x1bd04);
        public static FormLink<ITraversalGetter> TraversalLadderEnterRightUpExitTop => Construct(0x1bd05);
        public static FormLink<ITraversalGetter> TraversalLadderEnterRightUpExitRight => Construct(0x1bd06);
        public static FormLink<ITraversalGetter> TraversalLadderEnterRightUpExitLeft => Construct(0x1bd07);
        public static FormLink<ITraversalGetter> TraversalLadderEnterRightDownExitRight => Construct(0x1bd08);
        public static FormLink<ITraversalGetter> TraversalLadderEnterRightDownExitLeft => Construct(0x1bd09);
        public static FormLink<ITraversalGetter> TraversalLadderEnterRightDownExitBottom => Construct(0x1bd0a);
        public static FormLink<ITraversalGetter> TraversalLadderEnterTopExitLeft => Construct(0x1bd0b);
        public static FormLink<ITraversalGetter> TraversalLadderEnterTopExitRight => Construct(0x1bd0c);
        public static FormLink<ITraversalGetter> TraversalLadderEnterTopExitBottom => Construct(0x1bd0d);
        public static FormLink<ITraversalGetter> TraversalLadderEnterBottomExitRight => Construct(0x1bd0e);
        public static FormLink<ITraversalGetter> TraversalLadderEnterBottomExitLeft => Construct(0x1bd0f);
        public static FormLink<ITraversalGetter> TraversalLadderEnterBottomExitTop => Construct(0x1bd10);
        public static FormLink<ITraversalGetter> TraversalVaultSmall => Construct(0x5988d);
        public static FormLink<ITraversalGetter> TraversalDoorwayStandard => Construct(0x5abcc);
        public static FormLink<ITraversalGetter> TraversalActivateLever => Construct(0x385045);
    }
}
