// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class Starfield
{
    public static partial class WeaponBarrelModel
    {
        private static FormLink<IWeaponBarrelModelGetter> Construct(uint id) => new FormLink<IWeaponBarrelModelGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IWeaponBarrelModelGetter> Rifle_VeryLong_BD => Construct(0x25cd23);
        public static FormLink<IWeaponBarrelModelGetter> Pistol_Long_BD => Construct(0x25cd24);
        public static FormLink<IWeaponBarrelModelGetter> Rifle_Long_BD => Construct(0x25cd25);
        public static FormLink<IWeaponBarrelModelGetter> Pistol_Short_BD => Construct(0x25cd26);
        public static FormLink<IWeaponBarrelModelGetter> Rifle_Short_BD => Construct(0x25cd27);
        public static FormLink<IWeaponBarrelModelGetter> HeavyGun_BD => Construct(0x25cd28);
    }
}
