// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class Starfield
{
    public static partial class WWiseKeywordMapping
    {
        private static FormLink<IWWiseKeywordMappingGetter> Construct(uint id) => new FormLink<IWWiseKeywordMappingGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IWWiseKeywordMappingGetter> WKM_CCT_Skin_05 => Construct(0xdf23);
        public static FormLink<IWWiseKeywordMappingGetter> WKM_ShipEngine_Starborn_NPC_A => Construct(0x22ce1);
        public static FormLink<IWWiseKeywordMappingGetter> WKM_ShipEngine_DefensiveBattery_Thrusters => Construct(0x2b31b);
        public static FormLink<IWWiseKeywordMappingGetter> WKM_CCT_Skin_06 => Construct(0x627ee);
        public static FormLink<IWWiseKeywordMappingGetter> WKM_CCT_Skin_06_Size_01 => Construct(0x627f2);
        public static FormLink<IWWiseKeywordMappingGetter> WKM_ShipGravDrive_Starborn_PC => Construct(0x7a16d);
        public static FormLink<IWWiseKeywordMappingGetter> WKM_ShipGravDrive_DeepCore_NPC => Construct(0x8e0ac);
        public static FormLink<IWWiseKeywordMappingGetter> WKM_ShipGravDrive_Nova_NPC => Construct(0x8e0ad);
        public static FormLink<IWWiseKeywordMappingGetter> WKM_ShipGravDrive_Reladyne_NPC => Construct(0x8e0ae);
        public static FormLink<IWWiseKeywordMappingGetter> WKM_ShipGravDrive_Slayton_NPC => Construct(0x8e0af);
        public static FormLink<IWWiseKeywordMappingGetter> WKM_ShipEngine_Reladyne_A_WhiteDwarf => Construct(0xef106);
        public static FormLink<IWWiseKeywordMappingGetter> WKM_CCT_Skin_04 => Construct(0xf4cf4);
        public static FormLink<IWWiseKeywordMappingGetter> WKM_CCT_Skin_06_Size_02 => Construct(0xffa8f);
        public static FormLink<IWWiseKeywordMappingGetter> WKM_CCT_Skin_06_Size_03 => Construct(0xffa90);
        public static FormLink<IWWiseKeywordMappingGetter> WKM_Cockpit_HopeTech => Construct(0x101df4);
        public static FormLink<IWWiseKeywordMappingGetter> WKM_Cockpit_TaiyoAstroneering => Construct(0x101df6);
        public static FormLink<IWWiseKeywordMappingGetter> WKM_Cockpit_StroudEklund => Construct(0x101df7);
        public static FormLink<IWWiseKeywordMappingGetter> WKM_Cockpit_DeimosStaryards => Construct(0x101df8);
        public static FormLink<IWWiseKeywordMappingGetter> WKM_Cockpit_NovaGalactic => Construct(0x101dfa);
        public static FormLink<IWWiseKeywordMappingGetter> WKM_CCT_Skin_03 => Construct(0x136ffe);
        public static FormLink<IWWiseKeywordMappingGetter> WKM_CCT_Skin_02 => Construct(0x136fff);
        public static FormLink<IWWiseKeywordMappingGetter> WKM_CCT_Skin_01 => Construct(0x137000);
        public static FormLink<IWWiseKeywordMappingGetter> WKM_CCT_Size_03 => Construct(0x138ede);
        public static FormLink<IWWiseKeywordMappingGetter> WKM_CCT_Size_01 => Construct(0x138edf);
        public static FormLink<IWWiseKeywordMappingGetter> WKM_CCT_Size_02 => Construct(0x138ee0);
        public static FormLink<IWWiseKeywordMappingGetter> WKM_ShipGravDrive_DeepCore_PC => Construct(0x14258e);
        public static FormLink<IWWiseKeywordMappingGetter> WKM_ShipGravDrive_Slayton_PC => Construct(0x14258f);
        public static FormLink<IWWiseKeywordMappingGetter> WKM_ShipGravDrive_Nova_PC => Construct(0x142590);
        public static FormLink<IWWiseKeywordMappingGetter> WKM_ShipGravDrive_Reladyne_PC => Construct(0x142598);
        public static FormLink<IWWiseKeywordMappingGetter> WKM_ShipEngine_Reladyne_M_Quasar => Construct(0x160ba2);
        public static FormLink<IWWiseKeywordMappingGetter> WKM_ShipEngine_Reladyne_C_SuperNova => Construct(0x160ba3);
        public static FormLink<IWWiseKeywordMappingGetter> WKM_ShipEngine_Reladyne_B_Nova => Construct(0x160ba4);
        public static FormLink<IWWiseKeywordMappingGetter> WKM_ShipEngine_Reladyne_A_WhiteDwarf_TEMPORARY => Construct(0x160ba5);
        public static FormLink<IWWiseKeywordMappingGetter> WKM_ShipEngine_Panoptes_M_Atlas => Construct(0x160ba6);
        public static FormLink<IWWiseKeywordMappingGetter> WKM_ShipEngine_Panoptes_C_Poseidon => Construct(0x160ba7);
        public static FormLink<IWWiseKeywordMappingGetter> WKM_ShipEngine_Panoptes_B_Hercules => Construct(0x160ba8);
        public static FormLink<IWWiseKeywordMappingGetter> WKM_ShipEngine_Panoptes_A_Ares => Construct(0x160ba9);
        public static FormLink<IWWiseKeywordMappingGetter> WKM_ShipEngine_AmunDunn_M_AmunDunnA => Construct(0x160baa);
        public static FormLink<IWWiseKeywordMappingGetter> WKM_ShipEngine_AmunDunn_C_AmunDunnX => Construct(0x160bab);
        public static FormLink<IWWiseKeywordMappingGetter> WKM_ShipEngine_AmunDunn_B_Dunn => Construct(0x160bac);
        public static FormLink<IWWiseKeywordMappingGetter> WKM_ShipEngine_AmunDunn_A_Amun => Construct(0x160bad);
        public static FormLink<IWWiseKeywordMappingGetter> WKM_ShipEngine_AmunDunn_NPC_A => Construct(0x19789a);
        public static FormLink<IWWiseKeywordMappingGetter> WKM_ShipEngine_Starborn_A => Construct(0x1b1c41);
        public static FormLink<IWWiseKeywordMappingGetter> WKM_ShipEngine_Slayton_C_SAL => Construct(0x1b5683);
        public static FormLink<IWWiseKeywordMappingGetter> WKM_ShipEngine_Slayton_M_SAH => Construct(0x1b5684);
        public static FormLink<IWWiseKeywordMappingGetter> WKM_ShipEngine_Slayton_B_SAE => Construct(0x1d3d74);
        public static FormLink<IWWiseKeywordMappingGetter> WKM_ShipEngine_Slayton_A_SA => Construct(0x1d51b7);
        public static FormLink<IWWiseKeywordMappingGetter> WKM_Cockpit_Starborn => Construct(0x1ecd29);
        public static FormLink<IWWiseKeywordMappingGetter> WKM_CCT_Skin_01_Size_03 => Construct(0x22559a);
        public static FormLink<IWWiseKeywordMappingGetter> WKM_CCT_Skin_01_Size_01 => Construct(0x22559b);
        public static FormLink<IWWiseKeywordMappingGetter> WKM_CCT_Skin_01_Size_02 => Construct(0x22559c);
        public static FormLink<IWWiseKeywordMappingGetter> WKM_CCT_Skin_02_Size_03 => Construct(0x22559d);
        public static FormLink<IWWiseKeywordMappingGetter> WKM_CCT_Skin_02_Size_01 => Construct(0x22559e);
        public static FormLink<IWWiseKeywordMappingGetter> WKM_CCT_Skin_02_Size_02 => Construct(0x22559f);
        public static FormLink<IWWiseKeywordMappingGetter> WKM_CCT_Skin_03_Size_03 => Construct(0x2255a0);
        public static FormLink<IWWiseKeywordMappingGetter> WKM_CCT_Skin_03_Size_01 => Construct(0x2255a1);
        public static FormLink<IWWiseKeywordMappingGetter> WKM_CCT_Skin_03_Size_02 => Construct(0x2255a2);
        public static FormLink<IWWiseKeywordMappingGetter> WKM_CCT_Skin_04_Size_03 => Construct(0x2255a3);
        public static FormLink<IWWiseKeywordMappingGetter> WKM_CCT_Skin_04_Size_01 => Construct(0x2255a4);
        public static FormLink<IWWiseKeywordMappingGetter> WKM_CCT_Skin_04_Size_02 => Construct(0x2255a5);
        public static FormLink<IWWiseKeywordMappingGetter> WKM_CCT_Skin_05_Size_03 => Construct(0x2255a6);
        public static FormLink<IWWiseKeywordMappingGetter> WKM_CCT_Skin_05_Size_01 => Construct(0x2255a7);
        public static FormLink<IWWiseKeywordMappingGetter> WKM_CCT_Skin_05_Size_02 => Construct(0x2255a8);
        public static FormLink<IWWiseKeywordMappingGetter> WKM_ShipEngine_Reladyne_NPC_A_WhiteDwarf_TEMPORARY => Construct(0x26a47f);
        public static FormLink<IWWiseKeywordMappingGetter> WKM_ShipEngine_Panoptes_NPC_A => Construct(0x31eb42);
        public static FormLink<IWWiseKeywordMappingGetter> WKM_ShipEngine_Reladyne_NPC_A => Construct(0x31eb43);
        public static FormLink<IWWiseKeywordMappingGetter> WKM_ShipEngine_Slayton_NPC_A => Construct(0x31eb45);
        public static FormLink<IWWiseKeywordMappingGetter> WKM_ShipEngine_AmunDunn_NPC_B => Construct(0x31eb46);
        public static FormLink<IWWiseKeywordMappingGetter> WKM_ShipEngine_AmunDunn_NPC_C => Construct(0x31eb47);
        public static FormLink<IWWiseKeywordMappingGetter> WKM_ShipEngine_AmunDunn_NPC_M => Construct(0x31eb49);
        public static FormLink<IWWiseKeywordMappingGetter> WKM_ShipEngine_Panoptes_NPC_B => Construct(0x31eb4a);
        public static FormLink<IWWiseKeywordMappingGetter> WKM_ShipEngine_Panoptes_NPC_C => Construct(0x31eb4b);
        public static FormLink<IWWiseKeywordMappingGetter> WKM_ShipEngine_Panoptes_NPC_M => Construct(0x31eb4d);
        public static FormLink<IWWiseKeywordMappingGetter> WKM_ShipEngine_Reladyne_NPC_B => Construct(0x31eb4e);
        public static FormLink<IWWiseKeywordMappingGetter> WKM_ShipEngine_Reladyne_NPC_C => Construct(0x31eb4f);
        public static FormLink<IWWiseKeywordMappingGetter> WKM_ShipEngine_Reladyne_NPC_M => Construct(0x31eb51);
        public static FormLink<IWWiseKeywordMappingGetter> WKM_ShipEngine_Slayton_NPC_B => Construct(0x31eb52);
        public static FormLink<IWWiseKeywordMappingGetter> WKM_ShipEngine_Slayton_NPC_C => Construct(0x31eb53);
        public static FormLink<IWWiseKeywordMappingGetter> WKM_ShipEngine_Slayton_NPC_M => Construct(0x31eb55);
    }
}
