// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class SFBGS003
{
    public static partial class AcousticSpace
    {
        private static FormLink<IAcousticSpaceGetter> Construct(uint id) => new FormLink<IAcousticSpaceGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IAcousticSpaceGetter> SFBGS003_AMB_Bathroom_Occ35_S => Construct(0x5902);
        public static FormLink<IAcousticSpaceGetter> SFBGS003_AMB_TrackersAllianceHQ_Dusty_Occludable_M => Construct(0x5903);
        public static FormLink<IAcousticSpaceGetter> SFBGS003_AMB_Cells_Occ40_M => Construct(0x5905);
        public static FormLink<IAcousticSpaceGetter> SFBGS003_AMB_ChopShop_Occludable_L => Construct(0xf37a);
    }
}
