// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class SFBGS003
{
    public static partial class Activator
    {
        private static FormLink<IActivatorGetter> Construct(uint id) => new FormLink<IActivatorGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IActivatorGetter> SFBGS003_MissionBoardConsole_Activator => Construct(0x50);
        public static FormLink<IActivatorGetter> SFBGS003_AMB_TrackersAllianceHQ_Triggers_WoodFloorCreaks => Construct(0x58fb);
        public static FormLink<IActivatorGetter> SFTA00_MissilePodTrigger => Construct(0x5c06);
        public static FormLink<IActivatorGetter> SFTA00_LoadingBayDoorTrigger => Construct(0x5c08);
        public static FormLink<IActivatorGetter> SFTA00_ControlRoomTrigger => Construct(0x5c0e);
        public static FormLink<IActivatorGetter> SFTA00_LockedShipTrigger => Construct(0x5c11);
        public static FormLink<IActivatorGetter> SFTA00_WatchHannibalTrigger => Construct(0x5c18);
        public static FormLink<IActivatorGetter> SFBGS003_BountyBoard01_ButtonLeft01 => Construct(0x6c07);
        public static FormLink<IActivatorGetter> SFBGS003_BountyBoard01_ButtonRight01 => Construct(0x6c08);
        public static FormLink<IActivatorGetter> SFTA00_ControlRoomDoorTrigger => Construct(0xf5a6);
        public static FormLink<IActivatorGetter> SFTA00_LivingQuartersDoorTrigger => Construct(0xf643);
        public static FormLink<IActivatorGetter> SFTA00_MissileDoorTrigger => Construct(0xff8a);
    }
}
