// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class SFBGS003
{
    public static partial class ActorValueInformation
    {
        private static FormLink<IActorValueInformationGetter> Construct(uint id) => new FormLink<IActorValueInformationGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IActorValueInformationGetter> SFBGS003_PlayerTrackerNameAV => Construct(0xeb5);
        public static FormLink<IActorValueInformationGetter> SFTA00_ForeknowledgeAV => Construct(0x4ca3);
        public static FormLink<IActorValueInformationGetter> SFBGS003_BountyWantedAliveAV => Construct(0x578a);
        public static FormLink<IActorValueInformationGetter> SFBGS003_SQ_Bounty_isScannedAV => Construct(0x6796);
        public static FormLink<IActorValueInformationGetter> SFBGS003_SQ_Bounty_SurrenderChanceAV => Construct(0xba59);
        public static FormLink<IActorValueInformationGetter> SFBGS003_SQ_Bounty_TemperamentAV => Construct(0xf569);
        public static FormLink<IActorValueInformationGetter> SFBGS003_SQ_Bounty_AmountAV => Construct(0xf56b);
    }
}
