// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class SFBGS003
{
    public static partial class AmbienceSet
    {
        private static FormLink<IAmbienceSetGetter> Construct(uint id) => new FormLink<IAmbienceSetGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IAmbienceSetGetter> SFBGS003_AmbienceSet_Int_Bathroom_MwP => Construct(0x58fd);
        public static FormLink<IAmbienceSetGetter> SFBGS003_AmbienceSet_Int_Cells_MwP => Construct(0x58fe);
        public static FormLink<IAmbienceSetGetter> SFBGS003_Ambienceset_Int_TrackersAllianceHQ_Dusty_Occludable => Construct(0x5900);
        public static FormLink<IAmbienceSetGetter> SFBGS003_AmbienceSet_Int_ChopShop_Occludable => Construct(0xf374);
    }
}
