// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class SFBGS003
{
    public static partial class AObjectModification
    {
        private static FormLink<IAObjectModificationGetter> Construct(uint id) => new FormLink<IAObjectModificationGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IAObjectModificationGetter> mod_AVM_MagStorm_SFBGS003_MantisVariant => Construct(0x475);
        public static FormLink<IAObjectModificationGetter> mod_PlasmaCutter_Additive_Accelerant => Construct(0x6c1d);
        public static FormLink<IAObjectModificationGetter> mod_PlasmaCutter_Additive_None => Construct(0x6c1e);
        public static FormLink<IAObjectModificationGetter> mod_PlasmaCutter_Mag_L => Construct(0x6c1f);
        public static FormLink<IAObjectModificationGetter> mod_PlasmaCutter_Mag_Standard => Construct(0x6c20);
        public static FormLink<IAObjectModificationGetter> mod_PlasmaCutter_Grip_ShieldedLarge => Construct(0x6c21);
        public static FormLink<IAObjectModificationGetter> mod_PlasmaCutter_Grip_Shielded => Construct(0x6c22);
        public static FormLink<IAObjectModificationGetter> mod_PlasmaCutter_Grip_Standard => Construct(0x6c23);
        public static FormLink<IAObjectModificationGetter> mod_PlasmaCutter_Barrel_Long => Construct(0x6c24);
        public static FormLink<IAObjectModificationGetter> mod_PlasmaCutter_Barrel_Standard => Construct(0x6c25);
        public static FormLink<IAObjectModificationGetter> mod_PlasmaCutter_Muzzle_FocusNozzle => Construct(0x6c26);
        public static FormLink<IAObjectModificationGetter> mod_PlasmaCutter_Muzzle_None => Construct(0x6c28);
        public static FormLink<IAObjectModificationGetter> mod_PlasmaCutter_Receiver_Standard => Construct(0x6c29);
        public static FormLink<IAObjectModificationGetter> mod_PlasmaCutter_Quality_01 => Construct(0xac79);
        public static FormLink<IAObjectModificationGetter> mod_PlasmaCutter_Quality_02 => Construct(0xac7a);
        public static FormLink<IAObjectModificationGetter> mod_PlasmaCutter_Quality_03 => Construct(0xac7b);
        public static FormLink<IAObjectModificationGetter> mod_PlasmaCutter_Quality_04 => Construct(0xac7c);
        public static FormLink<IAObjectModificationGetter> mod_PlasmaCutter_Quality_TiersAny => Construct(0xac7d);
        public static FormLink<IAObjectModificationGetter> mod_AVM_Cutter_SFBGS003_Cutter_TrackersAlliance => Construct(0xfd32);
    }
}
