// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class SFBGS003
{
    public static partial class ArmorAddon
    {
        private static FormLink<IArmorAddonGetter> Construct(uint id) => new FormLink<IArmorAddonGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IArmorAddonGetter> SFBGS003_AA_Inevitable_Apparel_BountyHunter_02_UpperBody => Construct(0x5440);
        public static FormLink<IArmorAddonGetter> SFBGS003_AA_Inevitable_Apparel_BountyHunter_02_LowerBody => Construct(0x5442);
        public static FormLink<IArmorAddonGetter> SFBGS003_AA_Inevitable_Apparel_BountyHunter_02_Sleeves => Construct(0x5443);
        public static FormLink<IArmorAddonGetter> SFBGS003_AA_Inevitable_Apparel_SpaceSuit_Gloves_03 => Construct(0x5444);
        public static FormLink<IArmorAddonGetter> SFBGS003_AA_Spacesuit_ETES_Backpack => Construct(0x676f);
        public static FormLink<IArmorAddonGetter> SFBGS003_AA_Spacesuit_ETES_Helmet => Construct(0x6770);
        public static FormLink<IArmorAddonGetter> SFBGS003_AA_Spacesuit_ETES_Sleeves => Construct(0x6771);
        public static FormLink<IArmorAddonGetter> SFBGS003_AA_Spacesuit_ETES_LowerBody => Construct(0x6772);
        public static FormLink<IArmorAddonGetter> SFBGS003_AA_Spacesuit_ETES_UpperBody => Construct(0x6773);
    }
}
