// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class SFBGS003
{
    public static partial class AStoryManagerNode
    {
        private static FormLink<IAStoryManagerNodeGetter> Construct(uint id) => new FormLink<IAStoryManagerNodeGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IAStoryManagerNodeGetter> MissionBranch_TA => Construct(0x57);
        public static FormLink<IAStoryManagerNodeGetter> SFBGS003_ChangeLocationBranch => Construct(0x24aa);
        public static FormLink<IAStoryManagerNodeGetter> SFBGS003_TrackersAllianceHQBranch => Construct(0x24ab);
        public static FormLink<IAStoryManagerNodeGetter> MissionNodeBounty_TA => Construct(0x58);
        public static FormLink<IAStoryManagerNodeGetter> MissionNodeBountySpace_TA => Construct(0x5a);
        public static FormLink<IAStoryManagerNodeGetter> SFBGS003_ScannerBounties_NewAtlantis => Construct(0x194);
        public static FormLink<IAStoryManagerNodeGetter> SFBGS003QuestNode => Construct(0x24ac);
        public static FormLink<IAStoryManagerNodeGetter> SFBGS003_ScannerBounties_Gagarin => Construct(0x3331);
        public static FormLink<IAStoryManagerNodeGetter> SFBGS003_ScannerBounties_AkilaCity => Construct(0x3332);
        public static FormLink<IAStoryManagerNodeGetter> SFBGS003TrackersAllianceHQConvoNode => Construct(0x505e);
        public static FormLink<IAStoryManagerNodeGetter> SFBGS003_ScannerBounties_Cydonia => Construct(0xa880);
        public static FormLink<IAStoryManagerNodeGetter> SFBGS003_ScannerBounties_Hopetown => Construct(0xa881);
        public static FormLink<IAStoryManagerNodeGetter> SFBGS003_ScannerBounties_Paradiso => Construct(0xa882);
        public static FormLink<IAStoryManagerNodeGetter> SFBGS003_ScannerBounties_RedMile => Construct(0xa883);
        public static FormLink<IAStoryManagerNodeGetter> SFBGS003_ScannerBounties_NewHomestead => Construct(0xa884);
        public static FormLink<IAStoryManagerNodeGetter> SFBGS003_ScannerBounties_Neon => Construct(0xa885);
        public static FormLink<IAStoryManagerNodeGetter> SFBGS003_ScannterBounties_OE_Civilians => Construct(0xe08f);
    }
}
