// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class SFBGS003
{
    public static partial class Cell
    {
        private static FormLink<ICellGetter> Construct(uint id) => new FormLink<ICellGetter>(ModKey.MakeFormKey(id));
        public static FormLink<ICellGetter> PackInSFBGS003ChopShopPIDockingArm01StorageCell => Construct(0x6eaa);
        public static FormLink<ICellGetter> PackInSFBGS003PIChopshopColumn01StorageCell => Construct(0xa686);
        public static FormLink<ICellGetter> PackInSFBGS003PIDrawingBattleship01StorageCell => Construct(0x33b8);
        public static FormLink<ICellGetter> SFBGS003scChopShop => Construct(0x26a2);
        public static FormLink<ICellGetter> PackInSFBGS003PI0GToilet02StorageCell => Construct(0x9b6e);
        public static FormLink<ICellGetter> SFTA00JunkerShipCreatedExterior => Construct(0x3e9);
        public static FormLink<ICellGetter> PackInSFBGS003ChopShopPIDockingArm02StorageCell => Construct(0x6ea1);
        public static FormLink<ICellGetter> PackInSGBGS003ChopShopPITracks01StorageCell => Construct(0x6ea2);
        public static FormLink<ICellGetter> PackInSFBGS003PI0GToiletSetup01StorageCell => Construct(0x9b70);
        public static FormLink<ICellGetter> SFBGS003TrackersAllianceHQ => Construct(0xa2b);
        public static FormLink<ICellGetter> PackInSGBGS003ChopShopPIVent01StorageCell => Construct(0x6ea3);
        public static FormLink<ICellGetter> SFBGS003WantedBoardRendersCell01 => Construct(0x6bc9);
        public static FormLink<ICellGetter> SFTA00JunkerShipCreatedInterior => Construct(0x47e4);
        public static FormLink<ICellGetter> PackInSGBGS003ChopShopPIVent02StorageCell => Construct(0x6ea4);
        public static FormLink<ICellGetter> PackInSFBGS003ChopShopSunsailGeoPKINStorageCell => Construct(0x3358);
        public static FormLink<ICellGetter> CTESTHQ => Construct(0x36);
        public static FormLink<ICellGetter> SFTA00DecoyShipCreatedExterior => Construct(0xa892);
        public static FormLink<ICellGetter> aaaMarkersSFBGS003 => Construct(0xcf3);
        public static FormLink<ICellGetter> PackInSFBGS003ChopShopPIDockingArm03StorageCell => Construct(0x6ea5);
        public static FormLink<ICellGetter> SFBGS003ChopShopInterior => Construct(0x269d);
        public static FormLink<ICellGetter> PackInSGBGS003ChopShopPIWallGreeblesRoomAStorageCell => Construct(0x6ea6);
        public static FormLink<ICellGetter> PackInSFBGS003ChopShopPIWallVents01StorageCell => Construct(0xa682);
        public static FormLink<ICellGetter> PackInSFBGS003PIChopShopDoor01BrokenStorageCell => Construct(0xba6e);
        public static FormLink<ICellGetter> SFTA00DecoyShipCreatedInterior => Construct(0x551a);
        public static FormLink<ICellGetter> PackInSFBGS003ChopShopUniqueCable02StorageCell => Construct(0xf115);
        public static FormLink<ICellGetter> PackInSFBGS003ChopShopPIDockingArm04StorageCell => Construct(0x6ea7);
        public static FormLink<ICellGetter> PackInSFBGS003PIChopShopDoor01StorageCell => Construct(0xba6f);
        public static FormLink<ICellGetter> CTESTCOPY0000 => Construct(0xc55);
        public static FormLink<ICellGetter> PackInSFBGS003ChopShopUniqueRedCable01StorageCell => Construct(0xf116);
        public static FormLink<ICellGetter> PackInSFBGS003ChopShopPIRailing01StorageCell => Construct(0x6ea8);
        public static FormLink<ICellGetter> PackInSFBGS003PIChopShopEntranceWelding01StorageCell => Construct(0xba70);
        public static FormLink<ICellGetter> PackInSFBGS003ChopShopThresherGeoPKINStorageCell => Construct(0x3352);
        public static FormLink<ICellGetter> PackInSFBGS003PI0GToilet01StorageCell => Construct(0x9b6c);
        public static FormLink<ICellGetter> PackInSFBGS003ElevatorPlatformLargeStorageCell => Construct(0x306e);
        public static FormLink<ICellGetter> PackInSGBGS003ChopShopPICratesWall01StorageCell => Construct(0x6ea9);
        public static FormLink<ICellGetter> PackInSFBGS003ChopShopPIContainerHolder01Wall01StorageCell => Construct(0xc057);
        public static FormLink<ICellGetter> SFBGS003ChopShopExterior => Construct(0x26a1);
    }
}
