// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class SFBGS003
{
    public static partial class Container
    {
        private static FormLink<IContainerGetter> Construct(uint id) => new FormLink<IContainerGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IContainerGetter> SFBGS003_Loot_Storage_PrimerCase => Construct(0x333d);
        public static FormLink<IContainerGetter> SFTA00_Loot_Storage_BossChest => Construct(0x5c27);
        public static FormLink<IContainerGetter> SFBGS003_Vendor_TAHQ_TwoShotContainer => Construct(0xe302);
        public static FormLink<IContainerGetter> SFBGS003_BountyBoard01_ => Construct(0xf8ed);
    }
}
