// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class SFBGS003
{
    public static partial class DefaultObject
    {
        private static FormLink<IDefaultObjectGetter> Construct(uint id) => new FormLink<IDefaultObjectGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IDefaultObjectGetter> FactionTrackersAlliance_DO => Construct(0x4ee);
        public static FormLink<IDefaultObjectGetter> HandScannerBountyTargetScannedDO => Construct(0x6c1a);
        public static FormLink<IDefaultObjectGetter> ActorBountyTemperamentAV_DO => Construct(0xf56a);
        public static FormLink<IDefaultObjectGetter> ActorBountyAmountAV_DO => Construct(0xf56c);
        public static FormLink<IDefaultObjectGetter> HandScannerBountyTargetWantedDeadOrAlive_DO => Construct(0xff8d);
    }
}
