// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class SFBGS003
{
    public static partial class DialogTopic
    {
        private static FormLink<IDialogTopicGetter> Construct(uint id) => new FormLink<IDialogTopicGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IDialogTopicGetter> DialogueTAHQ_AgentNo1_ReserveLines => Construct(0x4a25);
        public static FormLink<IDialogTopicGetter> STFA00_Roach_CuffAdrastos => Construct(0x59e3);
        public static FormLink<IDialogTopicGetter> SFTA00_Roach_SpottedAdrastos => Construct(0x5a42);
    }
}
