// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class SFBGS003
{
    public static partial class Faction
    {
        private static FormLink<IFactionGetter> Construct(uint id) => new FormLink<IFactionGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IFactionGetter> SFTA00_ChopShopStationFriendFaction => Construct(0x3ea);
        public static FormLink<IFactionGetter> SFTA00_HannibalFaction => Construct(0x53f1);
        public static FormLink<IFactionGetter> SFBGS003_BountyFaction => Construct(0x577c);
        public static FormLink<IFactionGetter> SFTA00_ChopShopStationFaction => Construct(0x5c31);
        public static FormLink<IFactionGetter> SFBGS003_Criminal_Faction => Construct(0xba43);
        public static FormLink<IFactionGetter> SFBGS003_TrackersAllianceFaction => Construct(0xe2ef);
        public static FormLink<IFactionGetter> SFBGS003_Vendor_TAHQ_TwoShotFaction => Construct(0xe2fe);
        public static FormLink<IFactionGetter> SFBGS003_PersonalCrimeFaction_Hannibal => Construct(0xf6d9);
    }
}
