// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class SFBGS003
{
    public static partial class FormList
    {
        private static FormLink<IFormListGetter> Construct(uint id) => new FormLink<IFormListGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IFormListGetter> SFBGS003_BountyCrimes_Uncommon => Construct(0x19a);
        public static FormLink<IFormListGetter> SFBGS003_BountyCrimes_Common => Construct(0x426);
        public static FormLink<IFormListGetter> SFBGS003_BountyCrimes_Rare => Construct(0x4ef);
        public static FormLink<IFormListGetter> SFBGS003_OutpostBountyPosterList => Construct(0x52d);
        public static FormLink<IFormListGetter> SFBGS003_HannibalCrimesList => Construct(0x595);
        public static FormLink<IFormListGetter> SFBGS003_PlayerTrackerNames => Construct(0xeaa);
        public static FormLink<IFormListGetter> SFBGS003_ScannerBountyVoiceTypeMale => Construct(0x579a);
        public static FormLink<IFormListGetter> SFBGS003_ScannerBountyVoiceTypeFemale => Construct(0x579b);
        public static FormLink<IFormListGetter> SFBGS003_Formlist_RandomNames_NonBinary => Construct(0xaca1);
        public static FormLink<IFormListGetter> SFBGS003_Formlist_RandomNames_Masc => Construct(0xaca2);
        public static FormLink<IFormListGetter> SFBGS003_Formlist_RandomNames_Femme => Construct(0xaca5);
        public static FormLink<IFormListGetter> SFBGS003_Formlist_RandomNames_Faction_CrimsonFleet => Construct(0xe093);
        public static FormLink<IFormListGetter> SFBGS003_Formlist_RandomNames_Faction_Eclipse => Construct(0xe094);
        public static FormLink<IFormListGetter> SFBGS003_Formlist_RandomNames_Faction_Spacers => Construct(0xe095);
        public static FormLink<IFormListGetter> SFBGS003_Formlist_RandomNames_Faction_Any => Construct(0xe096);
        public static FormLink<IFormListGetter> SFBGS003_VoicesDialogueTAHQUniqueCrime => Construct(0xe2ff);
        public static FormLink<IFormListGetter> SFBGS003_HandScannerTemperamentFormlist => Construct(0xf565);
        public static FormLink<IFormListGetter> BEHazardFormListCOPY0000 => Construct(0xf56d);
        public static FormLink<IFormListGetter> SFBGS003_ScannerBountyVoiceTypeMaleCOPY0000 => Construct(0xf5f4);
        public static FormLink<IFormListGetter> SFBGS003_VoicesDialogueCitizens => Construct(0xf5f5);
        public static FormLink<IFormListGetter> SFBGS003_BountyBoard_DisplayFilter => Construct(0xf900);
    }
}
