// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class SFBGS003
{
    public static partial class Furniture
    {
        private static FormLink<IFurnitureGetter> Construct(uint id) => new FormLink<IFurnitureGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IFurnitureGetter> SFBGS003_ZeroG_Welder_FurnitureMarker => Construct(0x9e);
        public static FormLink<IFurnitureGetter> SFBGS003_NPCPushUp_ExitToTalk => Construct(0x540f);
        public static FormLink<IFurnitureGetter> AK_Chair_Bar_01_AtBar_WideActivation => Construct(0xf362);
    }
}
