// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class SFBGS003
{
    public static partial class GenericBaseForm
    {
        private static FormLink<IGenericBaseFormGetter> Construct(uint id) => new FormLink<IGenericBaseFormGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IGenericBaseFormGetter> SFBGS003ChopShopStation => Construct(0x2806);
        public static FormLink<IGenericBaseFormGetter> SFTA00_JunkerShip => Construct(0x47e5);
        public static FormLink<IGenericBaseFormGetter> SFTA00_DecoyShip => Construct(0x551b);
    }
}
