// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class SFBGS003
{
    public static partial class Global
    {
        private static FormLink<IGlobalGetter> Construct(uint id) => new FormLink<IGlobalGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IGlobalGetter> SFBGS003_MiscPointer_MoveValue => Construct(0x8);
        public static FormLink<IGlobalGetter> SFBGS003_MiscPointer_MoveValueThreshold => Construct(0x9);
        public static FormLink<IGlobalGetter> MissionBoardAccessAllowed_TA => Construct(0x4b);
        public static FormLink<IGlobalGetter> MissionBoardBounty05RewardActualCOPY0001 => Construct(0x4d);
        public static FormLink<IGlobalGetter> MissionBoardBountySpace04RewardCOPY0000 => Construct(0x52);
        public static FormLink<IGlobalGetter> MissionBoardBountySpace04RewardActualCOPY0000 => Construct(0x53);
        public static FormLink<IGlobalGetter> MissionBoardBountyRewardUnused => Construct(0x55);
        public static FormLink<IGlobalGetter> MissionBoardBountySRewardActualUnused => Construct(0x56);
        public static FormLink<IGlobalGetter> SFBGS003_Global_MissionBoardEliteBounty_Reward_01 => Construct(0x5b);
        public static FormLink<IGlobalGetter> SFBGS003_Global_MissionBoardEliteBounty_RewardActual_01 => Construct(0x5c);
        public static FormLink<IGlobalGetter> MissionBoardEliteBountySpace01Reward_TA => Construct(0x5e);
        public static FormLink<IGlobalGetter> MissionBoardEliteBountySpace01RewardActual_TA => Construct(0x5f);
        public static FormLink<IGlobalGetter> MissionBoardEliteBountySpace02Reward_TA => Construct(0x60);
        public static FormLink<IGlobalGetter> MissionBoardEliteBountySpace02RewardActual_TA => Construct(0x61);
        public static FormLink<IGlobalGetter> MissionBoardBounty06Reward_TACOPY0000 => Construct(0x64);
        public static FormLink<IGlobalGetter> MissionBoardBounty06RewardActual_TACOPY0000 => Construct(0x65);
        public static FormLink<IGlobalGetter> SFBGS003_NPCDemandMoney_Medium => Construct(0x495);
        public static FormLink<IGlobalGetter> SFBGS003_NPCDemandMoney_Small => Construct(0x4f5);
        public static FormLink<IGlobalGetter> SFBGS003_NPCDemandMoney_Large => Construct(0x4f6);
        public static FormLink<IGlobalGetter> SFBGS003_BountyScanner_Timestamp => Construct(0x50e);
        public static FormLink<IGlobalGetter> SFBGS003_CooldownNextBounty => Construct(0x50f);
        public static FormLink<IGlobalGetter> _SFBGS003 => Construct(0x893);
        public static FormLink<IGlobalGetter> SFBGS003_DialogueTAHQ_YourMomCount => Construct(0xee9);
        public static FormLink<IGlobalGetter> SFBGS003_PlayerFoundValue => Construct(0xef0);
        public static FormLink<IGlobalGetter> SFBGS003_Bounties_Dead_Total => Construct(0x11d4);
        public static FormLink<IGlobalGetter> SFBGS003_Bounties_Alive_Total => Construct(0x11d5);
        public static FormLink<IGlobalGetter> MB_MissionsCompleted19Bounty_TA => Construct(0x24b0);
        public static FormLink<IGlobalGetter> XPRewardMissionBoardEliteBountySmall => Construct(0x24b1);
        public static FormLink<IGlobalGetter> SFBGS003_Global_MissionBoardEliteBounty_Reward_02 => Construct(0x283c);
        public static FormLink<IGlobalGetter> SFBGS003_Global_MissionBoardEliteBounty_RewardActual_02 => Construct(0x283d);
        public static FormLink<IGlobalGetter> SFBGS003_Bounties_Record_Threshold04 => Construct(0x4ca5);
        public static FormLink<IGlobalGetter> SFBGS003_Bounties_Record_Threshold01 => Construct(0x4ca7);
        public static FormLink<IGlobalGetter> SFBGS003_Bounties_Record_Threshold02 => Construct(0x4ca9);
        public static FormLink<IGlobalGetter> SFBGS003_Bounties_Record_Threshold03 => Construct(0x4caa);
        public static FormLink<IGlobalGetter> SFBGS003_Bounties_Record_Threshold05 => Construct(0x4cab);
        public static FormLink<IGlobalGetter> SFBGS003_Bounties_Total => Construct(0x4cae);
        public static FormLink<IGlobalGetter> SFBGS003_Bounty => Construct(0x577d);
        public static FormLink<IGlobalGetter> SFBGS003_Global_BountyBonusLimit => Construct(0x5789);
        public static FormLink<IGlobalGetter> SFTA00_JunkerShipRepairRateValue => Construct(0x7c21);
        public static FormLink<IGlobalGetter> SFBGS003_Global_BountySpawnChance => Construct(0xe090);
        public static FormLink<IGlobalGetter> SFBGS003_Global_MissionBountyBonus => Construct(0xe091);
        public static FormLink<IGlobalGetter> SFBGS003_Global_MissionBountyLimit => Construct(0xe092);
        public static FormLink<IGlobalGetter> SFBGS003_Astras_SmallAmount => Construct(0xe2f0);
        public static FormLink<IGlobalGetter> SFBGS003_Astras_MedAmount => Construct(0xe2f1);
        public static FormLink<IGlobalGetter> SFBGS003_Astras_LargeAmount => Construct(0xe2f2);
        public static FormLink<IGlobalGetter> MB_ParsecsStandardNearMax => Construct(0xe303);
        public static FormLink<IGlobalGetter> MB_ParsecsStandardNearMin => Construct(0xe304);
        public static FormLink<IGlobalGetter> SFBGS003_Warden_HelloCount => Construct(0xf364);
        public static FormLink<IGlobalGetter> SFBGS003_BountiesComplete_HighAmount => Construct(0xf5c0);
        public static FormLink<IGlobalGetter> SFBGS003_BountiesComplete_MediumAmount => Construct(0xf5c1);
        public static FormLink<IGlobalGetter> SFBGS003_Global_RareCrimeValue => Construct(0xf5c9);
        public static FormLink<IGlobalGetter> SFBGS003_Global_UncommonCrimeValue => Construct(0xf5ca);
        public static FormLink<IGlobalGetter> SFBGS003_Global_CommonCrimeValue => Construct(0xf5e8);
        public static FormLink<IGlobalGetter> SFBGS003_Global_BountyBonus => Construct(0xf5e9);
        public static FormLink<IGlobalGetter> SFBGS003_CreditsRewardBountyQuestMedium => Construct(0xf651);
        public static FormLink<IGlobalGetter> SFBGS003_CreditsRewardBountyQuestLarge => Construct(0xf652);
        public static FormLink<IGlobalGetter> SFBGS003_BountyCOPY0000 => Construct(0xf6b2);
        public static FormLink<IGlobalGetter> SFBGS003_NPCDemandMoney_MediumCOPY0000 => Construct(0xf6b4);
        public static FormLink<IGlobalGetter> SFBGS003_BountyCOPY0003 => Construct(0xf6ba);
        public static FormLink<IGlobalGetter> SFBGS003_NPCDemandMoney_MediumCOPY0003 => Construct(0xf6bc);
        public static FormLink<IGlobalGetter> SFBGS003_NPCDemandMoney_LargeCOPY0003 => Construct(0xf6bd);
        public static FormLink<IGlobalGetter> SFBGS003_NPCDemandMoney_SmallCOPY0003 => Construct(0xf6be);
        public static FormLink<IGlobalGetter> SFBGS003_BountyCOPY0002 => Construct(0xf6c2);
        public static FormLink<IGlobalGetter> SFBGS003_NPCDemandMoney_MediumCOPY0002 => Construct(0xf6c3);
        public static FormLink<IGlobalGetter> SFBGS003_NPCDemandMoney_LargeCOPY0002 => Construct(0xf6c4);
        public static FormLink<IGlobalGetter> SFBGS003_NPCDemandMoney_SmallCOPY0002 => Construct(0xf6c5);
        public static FormLink<IGlobalGetter> SFBGS003_BountyCOPY0001 => Construct(0xf6c9);
        public static FormLink<IGlobalGetter> SFBGS003_NPCDemandMoney_MediumCOPY0001 => Construct(0xf6ca);
        public static FormLink<IGlobalGetter> SFBGS003_NPCDemandMoney_LargeCOPY0001 => Construct(0xf6cb);
        public static FormLink<IGlobalGetter> SFBGS003_NPCDemandMoney_SmallCOPY0001 => Construct(0xf6cc);
        public static FormLink<IGlobalGetter> SFBGS003_BountyCOPY0004 => Construct(0xf70b);
        public static FormLink<IGlobalGetter> SFBGS003_NPCDemandMoney_MediumCOPY0004 => Construct(0xf70d);
        public static FormLink<IGlobalGetter> SFBGS003_NPCDemandMoney_LargeCOPY0000 => Construct(0xf70e);
        public static FormLink<IGlobalGetter> SFBGS003_NPCDemandMoney_SmallCOPY0000 => Construct(0xf70f);
        public static FormLink<IGlobalGetter> SFBGS003_BountyCOPY0005 => Construct(0xf712);
        public static FormLink<IGlobalGetter> SFBGS003_NPCDemandMoney_MediumCOPY0005 => Construct(0xf713);
        public static FormLink<IGlobalGetter> SFBGS003_NPCDemandMoney_LargeCOPY0004 => Construct(0xf714);
        public static FormLink<IGlobalGetter> SFBGS003_NPCDemandMoney_SmallCOPY0004 => Construct(0xf716);
        public static FormLink<IGlobalGetter> SFBGS003_BountyCOPY0006 => Construct(0xf719);
        public static FormLink<IGlobalGetter> SFBGS003_NPCDemandMoney_MediumCOPY0006 => Construct(0xf71a);
        public static FormLink<IGlobalGetter> SFBGS003_NPCDemandMoney_LargeCOPY0005 => Construct(0xf71b);
        public static FormLink<IGlobalGetter> SFBGS003_NPCDemandMoney_SmallCOPY0005 => Construct(0xf71c);
        public static FormLink<IGlobalGetter> SFBGS003_BountyCOPY0007 => Construct(0xf71f);
        public static FormLink<IGlobalGetter> SFBGS003_NPCDemandMoney_MediumCOPY0007 => Construct(0xf720);
        public static FormLink<IGlobalGetter> SFBGS003_NPCDemandMoney_LargeCOPY0006 => Construct(0xf721);
        public static FormLink<IGlobalGetter> SFBGS003_NPCDemandMoney_SmallCOPY0006 => Construct(0xf722);
        public static FormLink<IGlobalGetter> SFBGS003_CreditsRewardBountyQuestSmall => Construct(0xfd3b);
    }
}
