// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class SFBGS003
{
    public static partial class Key
    {
        private static FormLink<IKeyGetter> Construct(uint id) => new FormLink<IKeyGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IKeyGetter> SFBGS003_TAHQKey => Construct(0xa9);
        public static FormLink<IKeyGetter> SFBGS003_ChopShop_CommandTowerKey => Construct(0x584f);
        public static FormLink<IKeyGetter> SFTA00_LockedShipKey => Construct(0x5c12);
        public static FormLink<IKeyGetter> SFTA00_JunkerShipKey => Construct(0x5c26);
    }
}
