// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class SFBGS003
{
    public static partial class LayeredMaterialSwap
    {
        private static FormLink<ILayeredMaterialSwapGetter> Construct(uint id) => new FormLink<ILayeredMaterialSwapGetter>(ModKey.MakeFormKey(id));
        public static FormLink<ILayeredMaterialSwapGetter> sfbgs003_bountyboard_wantedposter01_To_sfbgs003_bountyboard_wantedposter02_Swap => Construct(0x52b);
        public static FormLink<ILayeredMaterialSwapGetter> sfbgs003_bountyboard_splashscreen01_To_sfbgs003_bountyboard_splashscreen01_completed_Swap => Construct(0x530);
        public static FormLink<ILayeredMaterialSwapGetter> sfbgs003_bountyboard_splashscreen01_To_sfbgs003_bountyboard_splashscreen01_sfta00_completed_Swap => Construct(0x531);
        public static FormLink<ILayeredMaterialSwapGetter> desktop_terminal01_plasticplainsmooth03_grey_To_sfbgs003_desktop_terminal01_plasticplainsmooth03_greydarker01_Swap => Construct(0x534);
        public static FormLink<ILayeredMaterialSwapGetter> paintedmetal_beige01_To_paintedmetalplain01_white01v1_Swap => Construct(0x3194);
        public static FormLink<ILayeredMaterialSwapGetter> paintedmetal_beige01_To_paintedmetalplain01_white01_Swap => Construct(0x3195);
        public static FormLink<ILayeredMaterialSwapGetter> pooltable_carpetred01_To_sfbgs003_pooltable_carpetblue01_Swap => Construct(0x5d1b);
        public static FormLink<ILayeredMaterialSwapGetter> akcarpetbeige_To_casino_tablecarpet_green01_Swap => Construct(0x5d7c);
        public static FormLink<ILayeredMaterialSwapGetter> aktextilepatterns01_To_casino_tablecarpet_green01_Swap => Construct(0x5d7d);
        public static FormLink<ILayeredMaterialSwapGetter> akcarpetbeige_To_textiletwill_colored02_Swap => Construct(0x5d7e);
        public static FormLink<ILayeredMaterialSwapGetter> aktextilepatterns01_To_textiletwill_colored02_Swap => Construct(0x5d7f);
        public static FormLink<ILayeredMaterialSwapGetter> akcarpetbeige_To_ucflag_textilecolor06_Swap => Construct(0x5d80);
        public static FormLink<ILayeredMaterialSwapGetter> aktextilepatterns01_To_ucflag_textilecolor06_Swap => Construct(0x5d81);
        public static FormLink<ILayeredMaterialSwapGetter> aktextilebannerlayered02_To_ucflag_textilecolor06_Swap => Construct(0x5d82);
        public static FormLink<ILayeredMaterialSwapGetter> aktextilepatterns01_To_ucflag_textilecolor03_Swap => Construct(0x5d83);
        public static FormLink<ILayeredMaterialSwapGetter> akcarpetbeige_To_ucflag_textilecolor05_Swap => Construct(0x5d84);
        public static FormLink<ILayeredMaterialSwapGetter> SFBGS003_LMS_Gloves_ETES => Construct(0x677b);
        public static FormLink<ILayeredMaterialSwapGetter> metalsteel01_To_paintedmetal02_swap_black01_Swap => Construct(0x6875);
        public static FormLink<ILayeredMaterialSwapGetter> LMS_SpaceSuit_Explorer_Celia => Construct(0x6b98);
        public static FormLink<ILayeredMaterialSwapGetter> LMS_SpaceSuit_Navigator_Booker => Construct(0x6bc4);
        public static FormLink<ILayeredMaterialSwapGetter> paintedmetalplain01_white01v1_To_paintedmetalplain01_lightgreen02_Swap => Construct(0x715b);
        public static FormLink<ILayeredMaterialSwapGetter> paintedmetalplain01_white03_To_paintedmetalplain01_reddark01_Swap => Construct(0x715c);
        public static FormLink<ILayeredMaterialSwapGetter> paintedmetalplain01_white01v1_To_paintedmetalplain01_reddark01_Swap => Construct(0x715d);
        public static FormLink<ILayeredMaterialSwapGetter> sciencemetalplain01_metal01_To_paintscuffed02_blue02_Swap => Construct(0x9b68);
        public static FormLink<ILayeredMaterialSwapGetter> sciencemetalplain01_metal01_To_paintmetalscratched01_orange01_Swap => Construct(0x9b69);
        public static FormLink<ILayeredMaterialSwapGetter> paintedmetalplain01_white03_To_paintscuffed02_blue02_Swap => Construct(0x9b6a);
        public static FormLink<ILayeredMaterialSwapGetter> sciencemetalplain01_metal01_To_paintscuffed01_blue02_Swap => Construct(0x9b6b);
        public static FormLink<ILayeredMaterialSwapGetter> aktextilebannerlayered01_To_textile_cotton_blue02_Swap => Construct(0xa3b0);
        public static FormLink<ILayeredMaterialSwapGetter> aktextilebannerlayered01_To_textileleather01_blue01_Swap => Construct(0xa3b1);
        public static FormLink<ILayeredMaterialSwapGetter> firstcavalryflagpinned_To_trackersallianceflagpinned01_Swap => Construct(0xa428);
        public static FormLink<ILayeredMaterialSwapGetter> firstcavalryflagpinned_To_trackersallianceflagpinned02_Swap => Construct(0xa429);
        public static FormLink<ILayeredMaterialSwapGetter> genglowopaque_white01_To_glowbright01red03_Swap => Construct(0xb841);
        public static FormLink<ILayeredMaterialSwapGetter> paintedmetalplain01_white03_To_plasticplainmatte01_yellow02_Swap => Construct(0xba74);
        public static FormLink<ILayeredMaterialSwapGetter> paintedmetalplain01_white03v1_To_genrugluxury05_Swap => Construct(0xba77);
        public static FormLink<ILayeredMaterialSwapGetter> paintedmetalplain01_white03v1_To_genrugluxury01_Swap => Construct(0xba78);
        public static FormLink<ILayeredMaterialSwapGetter> neon_gloworange01_To_glowoff01_Swap => Construct(0xbb6d);
        public static FormLink<ILayeredMaterialSwapGetter> decallabels01_faded01_To_indintlabels01_Swap => Construct(0xbb6e);
        public static FormLink<ILayeredMaterialSwapGetter> paintedmetalscratchedrusty01orange01_To_metalsteel01_Swap => Construct(0xbb6f);
        public static FormLink<ILayeredMaterialSwapGetter> decallabelsletters03fade_To_decallabelsletters03color01_Swap => Construct(0xbb70);
        public static FormLink<ILayeredMaterialSwapGetter> decalmetalboltstrimsdetails01_To_decalmetalboltstrimsdetails01_Swap => Construct(0xbb71);
        public static FormLink<ILayeredMaterialSwapGetter> paintedmetalplain01_white03_To_indintmetaltrimyellow03_Swap => Construct(0xbb72);
        public static FormLink<ILayeredMaterialSwapGetter> paintedmetalplain01_white03_To_indintmetaltileyellow03_Swap => Construct(0xbb73);
        public static FormLink<ILayeredMaterialSwapGetter> shpindintpaintedmetal01_black_To_paintedmetalplain01_white01_Swap => Construct(0xbbb8);
        public static FormLink<ILayeredMaterialSwapGetter> metalaluminumscuffed01_To_opiintpaneltile01d_Swap => Construct(0xbef5);
        public static FormLink<ILayeredMaterialSwapGetter> metalaluminumworn01_plain02_To_opiintpaneltile01_Swap => Construct(0xbef6);
        public static FormLink<ILayeredMaterialSwapGetter> indintmetaltrimgrey02_To_paintedmetalplain01_lightblue01_Swap => Construct(0xdfee);
        public static FormLink<ILayeredMaterialSwapGetter> indextrubberfloor01_To_paintmetalscratched01_white01_Swap => Construct(0xe016);
        public static FormLink<ILayeredMaterialSwapGetter> indintmetaltrimgrey02_To_paintmetalscratched01_white01_Swap => Construct(0xe017);
        public static FormLink<ILayeredMaterialSwapGetter> decalmetalboltstrimsdetails01_To_decalnull01_SwapDUPLICATE000 => Construct(0xe018);
        public static FormLink<ILayeredMaterialSwapGetter> decalmetalboltstrimsdetails01n_To_decalnull01_SwapDUPLICATE000 => Construct(0xe019);
        public static FormLink<ILayeredMaterialSwapGetter> indextrubberfloor01_To_metalaluminumworn03_Swap => Construct(0xe01a);
        public static FormLink<ILayeredMaterialSwapGetter> indintmetaltrimgrey02_To_metalaluminumworn03_Swap => Construct(0xe01b);
        public static FormLink<ILayeredMaterialSwapGetter> indintmetaltrimgrey02_To_paintedmetalplain01_reddark01_Swap => Construct(0xe08a);
        public static FormLink<ILayeredMaterialSwapGetter> indintmetaltrimgrey03_To_blanknorender00_Swap => Construct(0xe370);
        public static FormLink<ILayeredMaterialSwapGetter> paintedmetalplain01_white01_To_paintedmetalplain01_yellow01_Swap => Construct(0xe3ef);
        public static FormLink<ILayeredMaterialSwapGetter> indintmetaltilegrey02_To_paintmetalscratched01_white01_Swap => Construct(0xed29);
        public static FormLink<ILayeredMaterialSwapGetter> indintmetaltilegrey02_To_paintedmetal02_swap_white01_Swap => Construct(0xed2a);
        public static FormLink<ILayeredMaterialSwapGetter> splashscreen_trackeralliance_To_trackeralliance_logo_Swap => Construct(0xf4dd);
        public static FormLink<ILayeredMaterialSwapGetter> sfbgs003_bountyboard_splashscreen01_To_sfbgs003_bountyboard_splashscreen01_sfta00_Swap => Construct(0xf91b);
        public static FormLink<ILayeredMaterialSwapGetter> sfbgs003_bountyboard_splashscreen01_To_sfbgs003_bountyboard_splashscreen01_sfta01_Swap => Construct(0xf932);
        public static FormLink<ILayeredMaterialSwapGetter> sfbgs003_bountyboard_splashscreen01_To_sfbgs003_bountyboard_splashscreen01_sfta02_Swap => Construct(0xf937);
        public static FormLink<ILayeredMaterialSwapGetter> sfbgs003_bountyboard_splashscreen01_To_sfbgs003_bountyboard_splashscreen01_sfta03_Swap => Construct(0xf93f);
        public static FormLink<ILayeredMaterialSwapGetter> sfbgs003_bountyboard_splashscreen01_To_sfbgs003_bountyboard_splashscreen01_sfta04_Swap => Construct(0xf94d);
        public static FormLink<ILayeredMaterialSwapGetter> sfbgs003_bountyboard_splashscreen01_To_sfbgs003_bountyboard_splashscreen01_sfta05_Swap => Construct(0xf978);
        public static FormLink<ILayeredMaterialSwapGetter> sfbgs003_bountyboard_splashscreen01_To_sfbgs003_bountyboard_splashscreen01_sfta06_Swap => Construct(0xf989);
        public static FormLink<ILayeredMaterialSwapGetter> sfbgs003_bountyboard_splashscreen01_To_sfbgs003_bountyboard_splashscreen01_sfta07_Swap => Construct(0xf9a9);
    }
}
