// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class SFBGS003
{
    public static partial class LeveledItem
    {
        private static FormLink<ILeveledItemGetter> Construct(uint id) => new FormLink<ILeveledItemGetter>(ModKey.MakeFormKey(id));
        public static FormLink<ILeveledItemGetter> LL_MB_Elite_Reward_SFBGS003 => Construct(0x5d);
        public static FormLink<ILeveledItemGetter> SFBGS003_LLI_Roach_Unique => Construct(0x54b);
        public static FormLink<ILeveledItemGetter> SFBGS003_LL_Astras_Armor_MultiDrop => Construct(0x68d);
        public static FormLink<ILeveledItemGetter> SFBGS003_LL_Astras_Weapons_MultiDrop => Construct(0x68e);
        public static FormLink<ILeveledItemGetter> SFBGS003_LL_Astras_Weapons_And_Armor => Construct(0x68f);
        public static FormLink<ILeveledItemGetter> SFBGS003_LL_Astras_Both => Construct(0x69a);
        public static FormLink<ILeveledItemGetter> SFBGS003_AgentNo1_Spacesuit_Diver_01_Helmet_Quality_04 => Construct(0x66af);
        public static FormLink<ILeveledItemGetter> LLI_BountyTarget_AssaultDefaultRole => Construct(0x6b72);
        public static FormLink<ILeveledItemGetter> LLI_BountyTarget_Charger => Construct(0x6b73);
        public static FormLink<ILeveledItemGetter> LLI_BountyTarget_Heavy => Construct(0x6b74);
        public static FormLink<ILeveledItemGetter> LLI_BountyTarget_Sniper => Construct(0x6b75);
        public static FormLink<ILeveledItemGetter> SFBGS003_LLI_BountyScanner_Citizens => Construct(0xe08d);
        public static FormLink<ILeveledItemGetter> SFBGS003_LL_Astras_Weapons => Construct(0xe2f5);
        public static FormLink<ILeveledItemGetter> SFBGS003_LL_Astras_Armor => Construct(0xe2f6);
        public static FormLink<ILeveledItemGetter> SFBGS003_LLC_Vendor_TAHQ_TwoShotContainer => Construct(0xe301);
        public static FormLink<ILeveledItemGetter> LL_Spacesuit_ETES_Backpack_HighestQuality => Construct(0xff8e);
        public static FormLink<ILeveledItemGetter> LL_Spacesuit_ETES_Backpack_Quality_01 => Construct(0xff8f);
        public static FormLink<ILeveledItemGetter> LL_Spacesuit_ETES_Backpack_Quality_02 => Construct(0xff90);
        public static FormLink<ILeveledItemGetter> LL_Spacesuit_ETES_Backpack_Quality_03 => Construct(0xff91);
        public static FormLink<ILeveledItemGetter> LL_Spacesuit_ETES_Backpack_Quality_04 => Construct(0xff92);
        public static FormLink<ILeveledItemGetter> LL_Spacesuit_ETES_Body_HighestQuality => Construct(0xff93);
        public static FormLink<ILeveledItemGetter> LL_Spacesuit_ETES_Body_Quality_01 => Construct(0xff94);
        public static FormLink<ILeveledItemGetter> LL_Spacesuit_ETES_Body_Quality_02 => Construct(0xff95);
        public static FormLink<ILeveledItemGetter> LL_Spacesuit_ETES_Body_Quality_03 => Construct(0xff96);
        public static FormLink<ILeveledItemGetter> LL_Spacesuit_ETES_Body_Quality_04 => Construct(0xff97);
        public static FormLink<ILeveledItemGetter> LL_Spacesuit_ETES_Helmet_HighestQuality => Construct(0xff98);
        public static FormLink<ILeveledItemGetter> LL_Spacesuit_ETES_Helmet_Quality_01 => Construct(0xff99);
        public static FormLink<ILeveledItemGetter> LL_Spacesuit_ETES_Helmet_Quality_02 => Construct(0xff9a);
        public static FormLink<ILeveledItemGetter> LL_Spacesuit_ETES_Helmet_Quality_03 => Construct(0xff9b);
        public static FormLink<ILeveledItemGetter> LL_Spacesuit_ETES_Helmet_Quality_04 => Construct(0xff9c);
        public static FormLink<ILeveledItemGetter> LL_Weapon_PlasmaCutter => Construct(0xffd8);
        public static FormLink<ILeveledItemGetter> SFBGS003_LL_Astras_Aspirational_Armor => Construct(0xffda);
    }
}
