// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class SFBGS003
{
    public static partial class MusicTrack
    {
        private static FormLink<IMusicTrackGetter> Construct(uint id) => new FormLink<IMusicTrackGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IMusicTrackGetter> SFBGS003_MUSGenesisFactionTrackersAlliance01 => Construct(0x3c9);
        public static FormLink<IMusicTrackGetter> SFBGS003_MUSGenesisStingerTrackersAllianceGood01 => Construct(0x3ce);
        public static FormLink<IMusicTrackGetter> SFBGS003_MUSGenesisStingerTrackersAllianceBad01 => Construct(0x3cf);
    }
}
