// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class SFBGS003
{
    public static partial class MusicType
    {
        private static FormLink<IMusicTypeGetter> Construct(uint id) => new FormLink<IMusicTypeGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IMusicTypeGetter> SFBGS003_MUSGenesisFactionTrackersAlliance => Construct(0x3cc);
        public static FormLink<IMusicTypeGetter> SFBGS003_MUSGenesisStingerTrackersAllianceGood => Construct(0x3d4);
        public static FormLink<IMusicTypeGetter> SFBGS003_MUSGenesisStingerTrackersAllianceBad => Construct(0x3d5);
    }
}
