// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class SFBGS003
{
    public static partial class Npc
    {
        private static FormLink<INpcGetter> Construct(uint id) => new FormLink<INpcGetter>(ModKey.MakeFormKey(id));
        public static FormLink<INpcGetter> SFBGS003_Koios => Construct(0x7);
        public static FormLink<INpcGetter> SFTA00_Deke_Photomode => Construct(0x829);
        public static FormLink<INpcGetter> SFBGS003_Bloodhound => Construct(0xe90);
        public static FormLink<INpcGetter> SFBGS003_AgentNo1 => Construct(0xe93);
        public static FormLink<INpcGetter> SFBGS003_Inevitable => Construct(0xe94);
        public static FormLink<INpcGetter> SFBGS003_Roach => Construct(0xe97);
        public static FormLink<INpcGetter> SFBGS003_Tank => Construct(0xe99);
        public static FormLink<INpcGetter> SFBGS003_TwoShot => Construct(0xe9a);
        public static FormLink<INpcGetter> SFBGS003_Yama => Construct(0xe9c);
        public static FormLink<INpcGetter> SFBGS003ChopShopStation_AutopilotAI => Construct(0x2807);
        public static FormLink<INpcGetter> SFTA00_JunkerShip_AutopilotAI => Construct(0x47e6);
        public static FormLink<INpcGetter> SFBGS003_Stache => Construct(0x4cb0);
        public static FormLink<INpcGetter> SFBGS003_HannibalEutropio => Construct(0x505c);
        public static FormLink<INpcGetter> SFBGS003_Loot_Mannequin_Spacesuit_Male01 => Construct(0x541d);
        public static FormLink<INpcGetter> SFBGS003_Loot_Mannequin_Spacesuit_Female01 => Construct(0x541f);
        public static FormLink<INpcGetter> SFTA00_DecoyShip_AutopilotAI => Construct(0x551c);
        public static FormLink<INpcGetter> SFBGS003_BountyScannerTarget01 => Construct(0x577f);
        public static FormLink<INpcGetter> SFBGS003_BountyScannerTarget01Female => Construct(0x579c);
        public static FormLink<INpcGetter> EncShip_Generic_A_Transpo03_AutopilotAICOPY0000 => Construct(0x5bb2);
        public static FormLink<INpcGetter> SFTA00_Deke => Construct(0x5bb7);
        public static FormLink<INpcGetter> Enc_SFBGS003_BountyTargetNPC_NonCity01TEMPLATE => Construct(0x6b7a);
        public static FormLink<INpcGetter> Enc_SFBGS003_BountyTargetNPC_City02 => Construct(0x6b7b);
        public static FormLink<INpcGetter> Enc_SFBGS003_BountyTargetNPC_City03 => Construct(0x6b7c);
        public static FormLink<INpcGetter> Enc_SFBGS003_BountyTargetNPC_City04 => Construct(0x6b7d);
        public static FormLink<INpcGetter> Enc_SFBGS003_BountyTargetNPC_City01_TEMPLATE => Construct(0x6b7e);
        public static FormLink<INpcGetter> Enc_SFBGS003_BountyTargetNPC_City05 => Construct(0x6b7f);
        public static FormLink<INpcGetter> Enc_SFBGS003_BountyTargetNPC_City06 => Construct(0x6b80);
        public static FormLink<INpcGetter> Enc_SFBGS003_BountyTargetNPC_City07 => Construct(0x6b81);
        public static FormLink<INpcGetter> Enc_SFBGS003_BountyTargetNPC_City08 => Construct(0x6b82);
        public static FormLink<INpcGetter> Enc_SFBGS003_BountyTargetNPC_City09 => Construct(0x6b83);
        public static FormLink<INpcGetter> Enc_SFBGS003_BountyTargetNPC_City10 => Construct(0x6b84);
        public static FormLink<INpcGetter> Enc_SFBGS003_BountyTargetNPC_NonCity02 => Construct(0x6b85);
        public static FormLink<INpcGetter> Enc_SFBGS003_BountyTargetNPC_NonCity03 => Construct(0x6b86);
        public static FormLink<INpcGetter> Enc_SFBGS003_BountyTargetNPC_NonCity04 => Construct(0x6b87);
        public static FormLink<INpcGetter> Enc_SFBGS003_BountyTargetNPC_NonCity05 => Construct(0x6b88);
        public static FormLink<INpcGetter> Enc_SFBGS003_BountyTargetNPC_NonCity06 => Construct(0x6b89);
        public static FormLink<INpcGetter> Enc_SFBGS003_BountyTargetNPC_NonCity07 => Construct(0x6b8a);
        public static FormLink<INpcGetter> Enc_SFBGS003_BountyTargetNPC_NonCity08 => Construct(0x6b8b);
        public static FormLink<INpcGetter> Enc_SFBGS003_BountyTargetNPC_NonCity09 => Construct(0x6b8c);
        public static FormLink<INpcGetter> Enc_SFBGS003_BountyTargetNPC_NonCity10 => Construct(0x6b8d);
        public static FormLink<INpcGetter> Lvl_SFBGS003_BountyTargetNPC_City => Construct(0x6b8e);
        public static FormLink<INpcGetter> Lvl_SFBGS003_BountyTargetNPC_NonCity => Construct(0x6b8f);
        public static FormLink<INpcGetter> Lvl_SFBGS003_BountyTargetNPC_NonCity_Assualt => Construct(0x6b90);
        public static FormLink<INpcGetter> Lvl_SFBGS003_BountyTargetNPC_NonCity_Charger => Construct(0x6b91);
        public static FormLink<INpcGetter> Lvl_SFBGS003_BountyTargetNPC_NonCity_Heavy => Construct(0x6b92);
        public static FormLink<INpcGetter> Lvl_SFBGS003_BountyTargetNPC_NonCity_Sniper => Construct(0x6b93);
        public static FormLink<INpcGetter> Lvl_SFBGS003_BountyTargetNPC_City_Assault => Construct(0x6b94);
        public static FormLink<INpcGetter> Lvl_SFBGS003_BountyTargetNPC_City_Charger => Construct(0x6b95);
        public static FormLink<INpcGetter> Lvl_SFBGS003_BountyTargetNPC_City_Heavy => Construct(0x6b96);
        public static FormLink<INpcGetter> Lvl_SFBGS003_BountyTargetNPC_City_Sniper => Construct(0x6b97);
        public static FormLink<INpcGetter> SFTA00_EncReceptionSpacerFaceM => Construct(0x7a26);
        public static FormLink<INpcGetter> SFTA00_LvlSpacer_Receptioon_Aggro => Construct(0x7a28);
        public static FormLink<INpcGetter> SFTA00_LvlSpacerReception => Construct(0x7a29);
        public static FormLink<INpcGetter> SFBGS003_BountyTargetNPC_F01 => Construct(0xba40);
        public static FormLink<INpcGetter> SFBGS003_BountyTargetNPC_F02 => Construct(0xba41);
        public static FormLink<INpcGetter> SFBGS003_BountyTargetNPC_F03 => Construct(0xba42);
        public static FormLink<INpcGetter> SFBGS003_BountyTargetNPC_F04 => Construct(0xba44);
        public static FormLink<INpcGetter> SFBGS003_BountyTargetNPC_F05 => Construct(0xba45);
        public static FormLink<INpcGetter> SFBGS003_BountyTargetNPC_M01 => Construct(0xba46);
        public static FormLink<INpcGetter> SFBGS003_BountyTargetNPC_M02 => Construct(0xba47);
        public static FormLink<INpcGetter> SFBGS003_BountyTargetNPC_M03 => Construct(0xba48);
        public static FormLink<INpcGetter> SFBGS003_BountyTargetNPC_M04 => Construct(0xba49);
        public static FormLink<INpcGetter> SFBGS003_BountyTargetNPC_M05 => Construct(0xba4a);
        public static FormLink<INpcGetter> SFBGS003_BountyTargetNPC_M06 => Construct(0xba4b);
        public static FormLink<INpcGetter> SFBGS003_BountyTargetNPC_M07 => Construct(0xba4c);
        public static FormLink<INpcGetter> SFBGS003_BountyTargetNPC_NB01 => Construct(0xba4d);
        public static FormLink<INpcGetter> SFBGS003_BountyTargetNPC_M08 => Construct(0xba4e);
        public static FormLink<INpcGetter> SFBGS003_BountyTargetNPC_M09 => Construct(0xba4f);
        public static FormLink<INpcGetter> SFBGS003_BountyTargetNPC_NB02 => Construct(0xe08c);
        public static FormLink<INpcGetter> SFBGS003_Warden => Construct(0xf35f);
    }
}
