// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class SFBGS003
{
    public static partial class Outfit
    {
        private static FormLink<IOutfitGetter> Construct(uint id) => new FormLink<IOutfitGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IOutfitGetter> SFBGS003_Outfit_Spacesuit_Bloodhound => Construct(0x33be);
        public static FormLink<IOutfitGetter> SFBGS003_Outfit_Spacesuit_BountyHunter_AgentNo1 => Construct(0x4ca0);
        public static FormLink<IOutfitGetter> SFBGS003_Outfit_Spacesuit_Mannequin01 => Construct(0x5420);
        public static FormLink<IOutfitGetter> SFBGS003_Outfit_Spacesuit_Mannequin02 => Construct(0x5421);
        public static FormLink<IOutfitGetter> SFBGS003_Outfit_Inevitable_BountyHunter_02_Body => Construct(0x543f);
        public static FormLink<IOutfitGetter> SFBGS003_Outfit_Spacesuit_ETES => Construct(0x6774);
        public static FormLink<IOutfitGetter> Outfit_Spacesuit_BountyHunter_02_NoHelmet_NoBackpack => Construct(0x7cbc);
        public static FormLink<IOutfitGetter> SFBGS003_Outfit_Spacesuit_BountyHunter_Warden => Construct(0xf360);
    }
}
