// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class SFBGS003
{
    public static partial class Package
    {
        private static FormLink<IPackageGetter> Construct(uint id) => new FormLink<IPackageGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IPackageGetter> SFBGS003_MiscPointer_Inevitable_Sit_AttractPKG => Construct(0x34);
        public static FormLink<IPackageGetter> SFTA00_Roach_0700_DecoyShip_Sit_PKG => Construct(0xaa);
        public static FormLink<IPackageGetter> SFTA00_JunkerShipIgnoreCombat => Construct(0xac);
        public static FormLink<IPackageGetter> SFTA00_Hannibal_DecoyShipPrisoner_SitPKG => Construct(0x3fa);
        public static FormLink<IPackageGetter> SFTA00_Hannibal_DecoyShipReveal_PKG => Construct(0x3fc);
        public static FormLink<IPackageGetter> SFBGS003_BountyTarget_SandboxCrowd_Package => Construct(0x496);
        public static FormLink<IPackageGetter> SFBGS003_BountyTarget_FleeToGuard_Package => Construct(0x498);
        public static FormLink<IPackageGetter> SFBGS003_BountyTarget_Flee_Package => Construct(0x499);
        public static FormLink<IPackageGetter> SFBGS003_BountyTarget_Sandbox_Package => Construct(0x4d3);
        public static FormLink<IPackageGetter> BE_SandboxLinkedRefCOPY0000 => Construct(0x4d4);
        public static FormLink<IPackageGetter> SFBGS003_BountyTarget_Surrender_Package => Construct(0x4d5);
        public static FormLink<IPackageGetter> SFBGS003_BountyTarget_ForceGreet_Package => Construct(0x4df);
        public static FormLink<IPackageGetter> SFTA00_Hannibal_StayAtSelfScene => Construct(0x6a9);
        public static FormLink<IPackageGetter> SFBGS003_MiscPointer_Inevitable_Sit_PKG => Construct(0xf0c);
        public static FormLink<IPackageGetter> SFBGS003_Intro_Roach_Travel01PKG => Construct(0x1203);
        public static FormLink<IPackageGetter> SFBGS003_HQ_Roach_Sit_PKG => Construct(0x1204);
        public static FormLink<IPackageGetter> SFBGS003_BountyTarget_StartCombat_Package => Construct(0x3206);
        public static FormLink<IPackageGetter> SFBGS003_BountyScanner_GuardActivated_Package => Construct(0x3333);
        public static FormLink<IPackageGetter> SFTA00_Roach_1825_JunkerShip_Sit_PKG => Construct(0x3336);
        public static FormLink<IPackageGetter> SFBGS003_SandboxEditorLocationShortRadius => Construct(0x4cc9);
        public static FormLink<IPackageGetter> SFBGS003_YamaSandboxEditorLocation => Construct(0x4ccf);
        public static FormLink<IPackageGetter> SFTA00_HannibalSandboxEditorLocation => Construct(0x5c02);
        public static FormLink<IPackageGetter> SFTA00_Deke_1600_TravelPKG => Construct(0x5c1e);
        public static FormLink<IPackageGetter> SFTA00_Deke_1500_TravelPKG => Construct(0x5c23);
        public static FormLink<IPackageGetter> SFTA00_DecoyShipPKG => Construct(0x5c2f);
        public static FormLink<IPackageGetter> SFTA00_Hannibal_GroupFormation_FollowPlayer => Construct(0x5c32);
        public static FormLink<IPackageGetter> SFTA00_Roach_GroupFormation_FollowPlayer => Construct(0x5c33);
        public static FormLink<IPackageGetter> SFTA00_Deke_TravelPKG => Construct(0x676c);
        public static FormLink<IPackageGetter> SFTA00_Roach_End_TravelPKG => Construct(0x6877);
        public static FormLink<IPackageGetter> SFBGS003_BountyScanner_GuardApproaches_Package => Construct(0x6a8e);
        public static FormLink<IPackageGetter> SFBGS003_InevitableSandboxEditorLocationShortRadius => Construct(0x6b70);
        public static FormLink<IPackageGetter> SFBGS003_RoachSandboxEditorLocationShortRadius => Construct(0x6b71);
        public static FormLink<IPackageGetter> SFBGS003_SQ_Bounty_Arrest_Package => Construct(0xba69);
        public static FormLink<IPackageGetter> SFBGS003_SQ_Bounty_Arrest_ForceGreet_Package => Construct(0xba6b);
        public static FormLink<IPackageGetter> SFBGS003_Warden_Sit_PKG => Construct(0xf361);
        public static FormLink<IPackageGetter> SFBGS003_BountyTarget_StartCombat_PackageDUPLICATE008 => Construct(0xf672);
        public static FormLink<IPackageGetter> SFBGS003_BountyTarget_Surrender_PackageDUPLICATE008 => Construct(0xf673);
        public static FormLink<IPackageGetter> SFBGS003_BountyScanner_GuardApproaches_PackageDUPLICATE008 => Construct(0xf674);
        public static FormLink<IPackageGetter> SFBGS003_BountyScanner_GuardActivated_PackageDUPLICATE008 => Construct(0xf675);
        public static FormLink<IPackageGetter> SFBGS003_BountyTarget_StartCombat_PackageDUPLICATE000 => Construct(0xf723);
        public static FormLink<IPackageGetter> SFBGS003_BountyTarget_Surrender_PackageDUPLICATE000 => Construct(0xf724);
        public static FormLink<IPackageGetter> SFBGS003_BountyScanner_GuardApproaches_PackageDUPLICATE000 => Construct(0xf725);
        public static FormLink<IPackageGetter> SFBGS003_BountyScanner_GuardActivated_PackageDUPLICATE000 => Construct(0xf726);
        public static FormLink<IPackageGetter> SFBGS003_BountyTarget_StartCombat_PackageDUPLICATE001 => Construct(0xf727);
        public static FormLink<IPackageGetter> SFBGS003_BountyTarget_Surrender_PackageDUPLICATE001 => Construct(0xf728);
        public static FormLink<IPackageGetter> SFBGS003_BountyScanner_GuardApproaches_PackageDUPLICATE001 => Construct(0xf729);
        public static FormLink<IPackageGetter> SFBGS003_BountyScanner_GuardActivated_PackageDUPLICATE001 => Construct(0xf72a);
        public static FormLink<IPackageGetter> SFBGS003_BountyTarget_StartCombat_PackageDUPLICATE002 => Construct(0xf72b);
        public static FormLink<IPackageGetter> SFBGS003_BountyTarget_Surrender_PackageDUPLICATE002 => Construct(0xf72c);
        public static FormLink<IPackageGetter> SFBGS003_BountyScanner_GuardApproaches_PackageDUPLICATE002 => Construct(0xf72d);
        public static FormLink<IPackageGetter> SFBGS003_BountyScanner_GuardActivated_PackageDUPLICATE002 => Construct(0xf72e);
        public static FormLink<IPackageGetter> SFBGS003_BountyTarget_StartCombat_PackageDUPLICATE003 => Construct(0xf72f);
        public static FormLink<IPackageGetter> SFBGS003_BountyTarget_Surrender_PackageDUPLICATE003 => Construct(0xf730);
        public static FormLink<IPackageGetter> SFBGS003_BountyScanner_GuardApproaches_PackageDUPLICATE003 => Construct(0xf731);
        public static FormLink<IPackageGetter> SFBGS003_BountyScanner_GuardActivated_PackageDUPLICATE003 => Construct(0xf732);
        public static FormLink<IPackageGetter> SFTA00_DecoyShipInit_SitPKG => Construct(0xff9d);
        public static FormLink<IPackageGetter> SFBGS003_MB_BodyGuard_WantedAlive => Construct(0xffa2);
        public static FormLink<IPackageGetter> SFBGS003_MB_BodyGuard_WantedDead => Construct(0xffa3);
        public static FormLink<IPackageGetter> SFBGS003_MB_EliteBounty02_WantedAlive_FleeFromPlayer_Package => Construct(0xffa4);
    }
}
