// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class SFBGS003
{
    public static partial class ProjectedDecal
    {
        private static FormLink<IProjectedDecalGetter> Construct(uint id) => new FormLink<IProjectedDecalGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IProjectedDecalGetter> SFBGS003_proj_DecalLogo_Trackersalliance01 => Construct(0xa374);
        public static FormLink<IProjectedDecalGetter> SFBGS003_proj_DecalLogo_Trackersalliance01b => Construct(0xa37a);
        public static FormLink<IProjectedDecalGetter> SFBGS003_proj_DecalLogo_Trackersalliance02 => Construct(0xa37b);
    }
}
