// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class SFBGS003
{
    public static partial class Quest
    {
        private static FormLink<IQuestGetter> Construct(uint id) => new FormLink<IQuestGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IQuestGetter> SFBGS003_MB_EliteBounty01_WantedDead => Construct(0x4a);
        public static FormLink<IQuestGetter> SFBGS003_MB_EliteBountySpace01_TA => Construct(0x51);
        public static FormLink<IQuestGetter> SFBGS003_MB_EliteBountySpace02_TA => Construct(0x54);
        public static FormLink<IQuestGetter> SFBGS003_MiscPointer => Construct(0xcf2);
        public static FormLink<IQuestGetter> SFBGS003_DialogueTAHQ => Construct(0xcf4);
        public static FormLink<IQuestGetter> SFBGS003_TrackersAllianceSupportQuest => Construct(0xcf5);
        public static FormLink<IQuestGetter> SFBGS003LDMasterQuest => Construct(0x283a);
        public static FormLink<IQuestGetter> SFBGS003_MB_EliteBounty02_WantedAlive => Construct(0x283b);
        public static FormLink<IQuestGetter> SFBGS003_TAHQ_Convo_Bar02 => Construct(0x492a);
        public static FormLink<IQuestGetter> SFBGS003_TAHQ_Convo_Roach01 => Construct(0x492b);
        public static FormLink<IQuestGetter> SFBGS003_TAHQ_Convo_AgentNo101 => Construct(0x492c);
        public static FormLink<IQuestGetter> SFTA00 => Construct(0x492d);
        public static FormLink<IQuestGetter> SFBGS003_TAHQ_Convo_AgentNo102 => Construct(0x492e);
        public static FormLink<IQuestGetter> SFBGS003_TAHQ_Convo_Bar01 => Construct(0x492f);
        public static FormLink<IQuestGetter> SFBGS003_TAHQ_Convo_Yama01 => Construct(0x4930);
        public static FormLink<IQuestGetter> SFBGS003_BountyScannerQuest => Construct(0x556e);
        public static FormLink<IQuestGetter> SFBGS003_BountyScannerQuest03 => Construct(0x66b3);
        public static FormLink<IQuestGetter> SFBGS003_BountyScannerQuest02 => Construct(0x66b4);
        public static FormLink<IQuestGetter> SFBGS003_BountyScannerQuest01 => Construct(0x66b5);
        public static FormLink<IQuestGetter> SFBGS003_BountyScannerQuest00 => Construct(0x66b6);
        public static FormLink<IQuestGetter> SFBGS003_SQ_WantedPosters => Construct(0x7a0e);
        public static FormLink<IQuestGetter> SFBGS003_Bounty_SpeechChallenge => Construct(0xb919);
        public static FormLink<IQuestGetter> SFBGS003_TAHQ_Convo_TankInevitable01 => Construct(0xf57e);
        public static FormLink<IQuestGetter> Patch_Update05_Hotfix01 => Construct(0xffd9);
        public static FormLink<IQuestGetter> SQ_SFBGS003_Patch => Construct(0xffdb);
        public static FormLink<IQuestGetter> Patch_Update07_SFBGS003 => Construct(0xffde);
    }
}
