// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class SFBGS003
{
    public static partial class SnapTemplateNode
    {
        private static FormLink<ISnapTemplateNodeGetter> Construct(uint id) => new FormLink<ISnapTemplateNodeGetter>(ModKey.MakeFormKey(id));
        public static FormLink<ISnapTemplateNodeGetter> SFBGS003_BountyBoard01_Snapnode => Construct(0xf8ee);
    }
}
