// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class SFBGS003
{
    public static partial class SnapTemplate
    {
        private static FormLink<ISnapTemplateGetter> Construct(uint id) => new FormLink<ISnapTemplateGetter>(ModKey.MakeFormKey(id));
        public static FormLink<ISnapTemplateGetter> SFBGS003_BountyBoard01_DisplaySnap => Construct(0xf8f0);
    }
}
