// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class SFBGS003
{
    public static partial class SoundMarker
    {
        private static FormLink<ISoundMarkerGetter> Construct(uint id) => new FormLink<ISoundMarkerGetter>(ModKey.MakeFormKey(id));
        public static FormLink<ISoundMarkerGetter> SFBGS003_AMB_Roomtone_Marker_BasementTone => Construct(0x5901);
        public static FormLink<ISoundMarkerGetter> SFBGS003_AMB_ChopShop_Marker_OneShots_Vents1 => Construct(0xf375);
        public static FormLink<ISoundMarkerGetter> SFBGS003_AMB_ChopShop_Marker_OneShots_Vents2 => Construct(0xf376);
        public static FormLink<ISoundMarkerGetter> SFBGS003_AMB_ChopShop_Cooling_Loop => Construct(0xf3a8);
        public static FormLink<ISoundMarkerGetter> SFBGS003_AMB_ChopShop_WallFan_Fast => Construct(0xf49f);
        public static FormLink<ISoundMarkerGetter> SFBGS003_AMB_ChopShop_WallFan_Medium => Construct(0xf4a0);
        public static FormLink<ISoundMarkerGetter> SFBGS003_AMB_ChopShop_WallFan_Slow => Construct(0xf4a1);
        public static FormLink<ISoundMarkerGetter> SFBGS003_QST_SFTA00_Missile_ShipShake => Construct(0xf4d1);
        public static FormLink<ISoundMarkerGetter> SFBGS003_AMB_ChopShop_MovingPlatform => Construct(0xf4da);
    }
}
