// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class SFBGS003
{
    public static partial class Static
    {
        private static FormLink<IStaticGetter> Construct(uint id) => new FormLink<IStaticGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IStaticGetter> SFBGS003_BountyPoster_SFTA00 => Construct(0x525);
        public static FormLink<IStaticGetter> SFBGS003_BountyPoster_SFTA01 => Construct(0x528);
        public static FormLink<IStaticGetter> SFBGS003_BountyBoard01_Screen01 => Construct(0x6c0f);
        public static FormLink<IStaticGetter> SFBGS003_XMarker_SpawnMarker_BountyScanner => Construct(0xa853);
        public static FormLink<IStaticGetter> SFBGS003_TrackersAlliance_Sign01 => Construct(0xf4db);
    }
}
