// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class SFBGS003
{
    public static partial class Terminal
    {
        private static FormLink<ITerminalGetter> Construct(uint id) => new FormLink<ITerminalGetter>(ModKey.MakeFormKey(id));
        public static FormLink<ITerminalGetter> SFBGS003_ChopShop_ShipComputer => Construct(0x38d);
        public static FormLink<ITerminalGetter> SFBGS003_ChopShop_ControlRoomComputer => Construct(0x5855);
    }
}
