// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class SFBGS003
{
    public static partial class TerminalMenu
    {
        private static FormLink<ITerminalMenuGetter> Construct(uint id) => new FormLink<ITerminalMenuGetter>(ModKey.MakeFormKey(id));
        public static FormLink<ITerminalMenuGetter> SFBGS003_ChopShop_ControlRoomComputer_SubMenu_Memos => Construct(0x9a);
        public static FormLink<ITerminalMenuGetter> SFBGS003_ChopShop_ControlRoomComputer_SubMenu_Personal => Construct(0x193);
        public static FormLink<ITerminalMenuGetter> SFBGS003_ChopShop_ShipComputer_Menu => Construct(0x38e);
        public static FormLink<ITerminalMenuGetter> SFBGS003_ChopShop_ShipComputer_SubMenu_DebugMenu => Construct(0x38f);
        public static FormLink<ITerminalMenuGetter> SFBGS003_ChopShop_ShipComputer_SubMenu_OfflineSystems => Construct(0x396);
        public static FormLink<ITerminalMenuGetter> SFBGS003_ChopShop_ShipComputer_SubMenu_ShipLogs => Construct(0x397);
        public static FormLink<ITerminalMenuGetter> SFBGS003_ChopShop_ShipComputer_SubMenu_Weapons => Construct(0x398);
        public static FormLink<ITerminalMenuGetter> SFBGS003_ChopShop_ControlRoomComputer_SubMenu_Lockdown => Construct(0x8c2);
        public static FormLink<ITerminalMenuGetter> SFBGS003_ChopShop_ControlRoomComputer_Menu => Construct(0x5c13);
        public static FormLink<ITerminalMenuGetter> SFBGS003_ChopShop_ControlRoomComputer_SubMenu_Logs => Construct(0x5c14);
    }
}
