// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class SFBGS003
{
    public static partial class VoiceType
    {
        private static FormLink<IVoiceTypeGetter> Construct(uint id) => new FormLink<IVoiceTypeGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IVoiceTypeGetter> SFBGS003_NPCMTank => Construct(0xe8f);
        public static FormLink<IVoiceTypeGetter> SFBGS003_NPCMBloodhound => Construct(0xe91);
        public static FormLink<IVoiceTypeGetter> SFBGS003_NPCXAgentNo1 => Construct(0xe92);
        public static FormLink<IVoiceTypeGetter> SFBGS003_NPCFInevitable => Construct(0xe95);
        public static FormLink<IVoiceTypeGetter> SFBGS003_NPCMRoach => Construct(0xe96);
        public static FormLink<IVoiceTypeGetter> SFBGS003_NPCMYama => Construct(0xe98);
        public static FormLink<IVoiceTypeGetter> SFBGS003_NPCFTwoShot => Construct(0xe9b);
        public static FormLink<IVoiceTypeGetter> SFBGS003_NPCMStache => Construct(0x24a5);
        public static FormLink<IVoiceTypeGetter> SFBGS003_NPCMHannibalEutropio => Construct(0x505d);
        public static FormLink<IVoiceTypeGetter> SFBGS003_ScannerBountyMale01 => Construct(0x578b);
        public static FormLink<IVoiceTypeGetter> SFBGS003_ScannerBountyMale02 => Construct(0x578c);
        public static FormLink<IVoiceTypeGetter> SFBGS003_ScannerBountyMale03 => Construct(0x578d);
        public static FormLink<IVoiceTypeGetter> SFBGS003_ScannerBountyMale04 => Construct(0x578e);
        public static FormLink<IVoiceTypeGetter> SFBGS003_ScannerBountyMale05 => Construct(0x578f);
        public static FormLink<IVoiceTypeGetter> SFBGS003_ScannerBountyMale06 => Construct(0x5790);
        public static FormLink<IVoiceTypeGetter> SFBGS003_ScannerBountyMale07 => Construct(0x5791);
        public static FormLink<IVoiceTypeGetter> SFBGS003_ScannerBountyMale08 => Construct(0x5792);
        public static FormLink<IVoiceTypeGetter> SFBGS003_ScannerBountyMale09 => Construct(0x5793);
        public static FormLink<IVoiceTypeGetter> SFBGS003_ScannerBountyNB10 => Construct(0x5794);
        public static FormLink<IVoiceTypeGetter> SFBGS003_ScannerBountyFemale01 => Construct(0x5795);
        public static FormLink<IVoiceTypeGetter> SFBGS003_ScannerBountyFemale02 => Construct(0x5796);
        public static FormLink<IVoiceTypeGetter> SFBGS003_ScannerBountyFemale03 => Construct(0x5797);
        public static FormLink<IVoiceTypeGetter> SFBGS003_ScannerBountyFemale04 => Construct(0x5798);
        public static FormLink<IVoiceTypeGetter> SFBGS003_ScannerBountyFemale05 => Construct(0x5799);
        public static FormLink<IVoiceTypeGetter> SFTA00_NPCMDeke => Construct(0x5bb6);
    }
}
