// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class SFBGS003
{
    public static partial class WWiseEventData
    {
        private static FormLink<IWWiseEventDataGetter> Construct(uint id) => new FormLink<IWWiseEventDataGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IWWiseEventDataGetter> SFBGS003_WwiseEvent_AMB_TrackersAllianceHQ_Triggers_WoodFloorCreaks => Construct(0x58ff);
        public static FormLink<IWWiseEventDataGetter> SFBGS003_WwiseEvent_QST_SFTA00_Missile_MissileLaunchSequence => Construct(0xf4d0);
    }
}
