// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class SFBGS008
{
    public static partial class Layer
    {
        private static FormLink<ILayerGetter> Construct(uint id) => new FormLink<ILayerGetter>(ModKey.MakeFormKey(id));
        public static FormLink<ILayerGetter> NewAtlantis_CityMapmarkers => Construct(0x1);
        public static FormLink<ILayerGetter> Akila_CityMapMarkers => Construct(0x18);
        public static FormLink<ILayerGetter> Cydonia_CityMapMarkers => Construct(0x27);
        public static FormLink<ILayerGetter> CydoniaLeve02_CityMapMarkers => Construct(0x28);
        public static FormLink<ILayerGetter> NeonOrigin_CityMapMarkers => Construct(0x2f);
        public static FormLink<ILayerGetter> NeonCore_CityMapMarkers => Construct(0x30);
        public static FormLink<ILayerGetter> SFBGS008_NeonCore_CityMaps_Layout => Construct(0x43);
        public static FormLink<ILayerGetter> SFBGS008_NeonCore_CityMaps_TempLights => Construct(0x44);
        public static FormLink<ILayerGetter> TheWell_CityMapMarkers => Construct(0x65);
    }
}
