// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class SFBGS007
{
    public static partial class ActorValueInformation
    {
        private static FormLink<IActorValueInformationGetter> Construct(uint id) => new FormLink<IActorValueInformationGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IActorValueInformationGetter> PEO_MedicalItemHealing_DurationMult_AV => Construct(0x7);
        public static FormLink<IActorValueInformationGetter> PEO_MedicalItemHealing_MagnitudeMult_AV => Construct(0x8);
        public static FormLink<IActorValueInformationGetter> PEO_CombatLethality_EnemyDamage_AV => Construct(0x13);
        public static FormLink<IActorValueInformationGetter> PEO_CombatLethality_PlayerDamage_AV => Construct(0x14);
        public static FormLink<IActorValueInformationGetter> PEO_ShipDamageOutput_EnemyDMG_AV => Construct(0x1a);
        public static FormLink<IActorValueInformationGetter> PEO_ShipDamageOutput_PlayerDMG_AV => Construct(0x1b);
        public static FormLink<IActorValueInformationGetter> PEO_XP_Mult => Construct(0x35);
    }
}
