// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class SFBGS007
{
    public static partial class ConditionRecord
    {
        private static FormLink<IConditionRecordGetter> Construct(uint id) => new FormLink<IConditionRecordGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IConditionRecordGetter> PEO_SleepHeal_HardDifficultyLocations => Construct(0x24);
        public static FormLink<IConditionRecordGetter> PEO_CargoAccess_Distance => Construct(0x3a);
        public static FormLink<IConditionRecordGetter> PEO_CargoAccess_Easy => Construct(0x3c);
        public static FormLink<IConditionRecordGetter> PEO_CargoAccess_Medium => Construct(0x3d);
        public static FormLink<IConditionRecordGetter> PEO_CargoAccess_VHard => Construct(0x3e);
        public static FormLink<IConditionRecordGetter> PEO_CargoAccess_Hard => Construct(0x3f);
    }
}
