// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class SFBGS007
{
    public static partial class Global
    {
        private static FormLink<IGlobalGetter> Construct(uint id) => new FormLink<IGlobalGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IGlobalGetter> _SFBGS007 => Construct(0x893);
        public static FormLink<IGlobalGetter> PEO_FoodHealing_0_Small => Construct(0x9);
        public static FormLink<IGlobalGetter> PEO_FoodHealing_1_Medium => Construct(0xa);
        public static FormLink<IGlobalGetter> PEO_FoodHealing_2_Large => Construct(0xb);
    }
}
