// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Starfield;
using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.Starfield;

public static partial class SFBGS007
{
    public static partial class Perk
    {
        private static FormLink<IPerkGetter> Construct(uint id) => new FormLink<IPerkGetter>(ModKey.MakeFormKey(id));
        public static FormLink<IPerkGetter> PEO_MedicalItemHealing_Perk => Construct(0x4);
        public static FormLink<IPerkGetter> PEO_CarryCapacity_Perk => Construct(0xc);
        public static FormLink<IPerkGetter> PEO_AmmoWeight_Perk => Construct(0xd);
        public static FormLink<IPerkGetter> PEO_CombatLethality_Perk => Construct(0x15);
        public static FormLink<IPerkGetter> PEO_ShipDamageOutput_Player_Perk => Construct(0x1c);
        public static FormLink<IPerkGetter> PEO_XP_Mult_Perk => Construct(0x36);
    }
}
